import { MCQ_I, TFNG_I, abcd, gap, gapItem, lex, q, select, v } from '../kit';
import type { LexEntry, LibraryPassage } from '../types';

export const LEX: LexEntry[] = [
  lex('deposit', 'verb', 'advanced', 'to put or leave something somewhere', 'রেখে দেওয়া / জমা রাখা', 'The river deposits sand at its mouth every year.', 'নদীটা প্রতি বছর মোহনায় বালি জমা করে।', ['place', 'leave']),
  lex('hatchling', 'noun', 'advanced', 'a very young animal that has just come out of its egg', 'সদ্য ডিম ফুটে বের হওয়া বাচ্চা', 'The hatchlings stayed close to their mother for a week.', 'সদ্য ডিম ফোটা বাচ্চাগুলো এক সপ্তাহ মায়ের কাছাকাছি ছিল।'),
  lex('predator', 'noun', 'core', 'an animal that kills and eats other animals', 'শিকারি প্রাণী', 'Foxes are natural predators of rabbits.', 'শিয়াল খরগোশের প্রাকৃতিক শিকারি।', ['hunter']),
  lex('emerge', 'verb', 'core', 'to come out from somewhere and become visible', 'বেরিয়ে আসা', 'The sun emerged from behind the clouds.', 'মেঘের আড়াল থেকে সূর্য বেরিয়ে এল।', ['appear', 'come out']),
  lex('rely on', 'phrasal verb', 'core', 'to depend on someone or something', 'নির্ভর করা', 'Many farmers rely on rain to water their crops.', 'অনেক কৃষক ফসলে পানির জন্য বৃষ্টির ওপর নির্ভর করেন।', ['depend on', 'count on']),
  lex('horizon', 'noun', 'useful', 'the line far away where the sky seems to meet the land or sea', 'দিগন্ত', 'A ship appeared on the horizon.', 'দিগন্তে একটা জাহাজ দেখা গেল।'),
  lex('reflect', 'verb', 'useful', 'to send back light, heat or sound from a surface', 'প্রতিফলিত করা', 'White walls reflect sunlight and keep the room cool.', 'সাদা দেয়াল সূর্যের আলো প্রতিফলিত করে ঘর ঠান্ডা রাখে।', ['bounce back']),
  lex('vegetation', 'noun', 'useful', 'plants in general, especially those in a particular area', 'গাছপালা / উদ্ভিদ', 'The hills are covered in thick vegetation.', 'পাহাড়গুলো ঘন গাছপালায় ঢাকা।', ['plants', 'greenery']),
  lex('weakness', 'noun', 'core', 'a fault or a point that is not strong', 'দুর্বলতা', 'The plan has one major weakness: it is too expensive.', 'পরিকল্পনাটার একটা বড় দুর্বলতা আছে: এটা খুব ব্যয়বহুল।', ['flaw', 'drawback']),
  lex('artificial', 'adjective', 'core', 'made by people, not natural', 'কৃত্রিম', 'The room had no windows, only artificial light.', 'ঘরটায় কোনো জানালা ছিল না, শুধু কৃত্রিম আলো।', ['man-made', 'synthetic']),
  lex('coastal', 'adjective', 'core', 'on or near the coast', 'উপকূলীয়', 'Coastal towns are often busy in summer.', 'উপকূলীয় শহরগুলো গ্রীষ্মে প্রায়ই ব্যস্ত থাকে।'),
  lex('develop', 'verb', 'core', 'to grow or change into something bigger or more advanced', 'উন্নত করা / বিকশিত হওয়া', 'The company developed a new kind of battery.', 'কোম্পানিটা নতুন ধরনের একটা ব্যাটারি তৈরি করেছে।', ['grow', 'build']),
  lex('disoriented', 'adjective', 'advanced', 'confused about where you are or which way to go', 'দিশেহারা', 'After the long flight, she felt tired and disoriented.', 'লম্বা ফ্লাইটের পরে তিনি ক্লান্ত আর দিশেহারা বোধ করছিলেন।', ['confused', 'lost']),
  lex('inland', 'adverb / adjective', 'useful', 'towards or in the part of a country away from the coast', 'স্থলভাগের ভেতরের দিকে', 'The storm moved inland during the night.', 'রাতে ঝড়টা স্থলভাগের ভেতরের দিকে সরে যায়।'),
  lex('exposed to', 'phrase', 'useful', 'not protected from something harmful', '(ক্ষতিকর কিছুর) সম্মুখীন / অরক্ষিত', 'Workers on the roof are exposed to strong sun all day.', 'ছাদের কর্মীরা সারাদিন কড়া রোদের সম্মুখীন থাকেন।', ['open to', 'vulnerable to']),
  lex('exhaustion', 'noun', 'useful', 'the state of being extremely tired', 'চরম ক্লান্তি', 'The runners collapsed from exhaustion at the finish line.', 'দৌড়বিদরা শেষ রেখায় চরম ক্লান্তিতে লুটিয়ে পড়লেন।', ['fatigue', 'tiredness']),
  lex('dehydration', 'noun', 'useful', 'a harmful loss of water from the body', 'পানিশূন্যতা', 'Drink water often in hot weather to avoid dehydration.', 'গরমে পানিশূন্যতা এড়াতে বারবার পানি পান করুন।'),
  lex('eventually', 'adverb', 'core', 'in the end, after a long time or a lot of effort', 'শেষ পর্যন্ত', 'After many attempts, he eventually passed the test.', 'অনেক চেষ্টার পরে তিনি শেষ পর্যন্ত পরীক্ষায় পাস করলেন।', ['finally', 'in the end']),
  lex('pollution', 'noun', 'core', 'damage to air, water or land caused by harmful substances or waste', 'দূষণ', 'Air pollution is a serious problem in many large cities.', 'অনেক বড় শহরে বায়ুদূষণ একটা গুরুতর সমস্যা।', ['contamination']),
  lex('threat', 'noun', 'core', 'something that is likely to cause harm or danger', 'হুমকি', 'Climate change is a threat to many species.', 'জলবায়ু পরিবর্তন অনেক প্রজাতির জন্য হুমকি।', ['danger', 'risk']),
  lex('a combination of', 'phrase', 'useful', 'several different things together', 'কয়েকটা জিনিসের মিশ্রণ / সমন্বয়', 'Success usually comes from a combination of talent and hard work.', 'সাফল্য সাধারণত প্রতিভা আর পরিশ্রমের সমন্বয়ে আসে।', ['a mix of', 'a mixture of']),
  lex('nesting', 'adjective', 'useful', 'used by birds or animals to lay eggs and raise young', 'বাসা বাঁধার / ডিম পাড়ার', 'The island is an important nesting site for seabirds.', 'দ্বীপটা সামুদ্রিক পাখিদের বাসা বাঁধার একটা গুরুত্বপূর্ণ জায়গা।'),
  lex('determine', 'verb', 'core', 'to decide or control what happens', 'নির্ধারণ করা', 'Your answers determine your final score.', 'আপনার উত্তরই আপনার চূড়ান্ত score নির্ধারণ করে।', ['decide', 'control']),
  lex('population', 'noun', 'core', 'all the people living in a place', 'জনসংখ্যা', 'The population of the city has doubled in twenty years.', 'বিশ বছরে শহরের জনসংখ্যা দ্বিগুণ হয়েছে।'),
  lex('consist of', 'phrasal verb', 'useful', 'to be made of particular parts or members', 'নিয়ে গঠিত হওয়া', 'The team consists of five students and a teacher.', 'দলটা পাঁচজন শিক্ষার্থী আর একজন শিক্ষক নিয়ে গঠিত।', ['be made up of', 'comprise']),
  lex('entirely', 'adverb', 'useful', 'completely', 'সম্পূর্ণভাবে', 'The meal was made entirely from local food.', 'খাবারটা সম্পূর্ণভাবে স্থানীয় উপকরণে তৈরি।', ['completely', 'wholly']),
  lex('introduce', 'verb', 'core', 'to present one person to another so they meet', 'পরিচয় করিয়ে দেওয়া', 'Let me introduce you to my brother.', 'আমার ভাইয়ের সাথে আপনাকে পরিচয় করিয়ে দিই।'),
  lex('shield', 'verb', 'advanced', 'to cover something so that it is protected or hidden', 'আড়াল করা / রক্ষা করা', 'She shielded her eyes from the sun.', 'তিনি রোদ থেকে চোখ আড়াল করলেন।', ['cover', 'screen']),
  lex('wavelength', 'noun', 'advanced', 'the distance between two waves of light or sound, which gives light its colour', 'তরঙ্গদৈর্ঘ্য', 'Red light has a longer wavelength than blue light.', 'লাল আলোর তরঙ্গদৈর্ঘ্য নীল আলোর চেয়ে বেশি।'),
  lex('sensitive to', 'phrase', 'useful', 'easily affected by something', 'সংবেদনশীল', 'Some people are very sensitive to noise.', 'কিছু মানুষ শব্দের প্রতি খুব সংবেদনশীল।'),
  lex('patrol', 'verb', 'advanced', 'to go around an area regularly to watch or protect it', 'টহল দেওয়া', 'Guards patrol the building every night.', 'রক্ষীরা প্রতি রাতে ভবনটায় টহল দেন।'),
  lex('measure', 'noun', 'core', 'an action taken to deal with a problem', 'পদক্ষেপ / ব্যবস্থা', 'The government took new measures to reduce traffic.', 'যানজট কমাতে সরকার নতুন পদক্ষেপ নিয়েছে।', ['step', 'action']),
  lex('relatively', 'adverb', 'useful', 'when compared with other things', 'তুলনামূলকভাবে', 'The test was relatively easy.', 'পরীক্ষাটা তুলনামূলকভাবে সহজ ছিল।', ['comparatively', 'fairly']),
  lex('consistently', 'adverb', 'useful', 'always in the same way, without stopping or changing', 'ধারাবাহিকভাবে', 'She has consistently scored well in Reading.', 'তিনি Reading-এ ধারাবাহিকভাবে ভালো score করেছেন।', ['regularly', 'steadily']),
  lex('concerned', 'adjective', 'core', 'worried about something', 'চিন্তিত / উদ্বিগ্ন', 'Parents are concerned about the cost of education.', 'অভিভাবকরা শিক্ষার খরচ নিয়ে উদ্বিগ্ন।', ['worried', 'anxious']),
];

export const PASSAGE: LibraryPassage = {
  id: 'rl-01-turtles',
  title: 'Lights Out for Turtle Hatchlings',
  topic: 'Wildlife',
  level: 'foundation',
  minutes: 15,
  paragraphs: [
    'Every summer, on warm beaches in many parts of the world, female sea turtles crawl out of the ocean at night to lay their eggs. Each female digs a hole in the sand, deposits around a hundred eggs, covers them and returns to the sea. About two months later, the young turtles, known as hatchlings, break out of their shells and dig their way to the surface. Their next task is the most dangerous of their lives: they must reach the water before predators such as crabs and birds find them.',
    'For millions of years, hatchlings have relied on a simple rule to find the sea. They usually emerge at night and crawl towards the brightest part of the horizon. On a natural beach, that is almost always the direction of the ocean, where moonlight and starlight are reflected off the water, while the land behind the beach is darkened by dunes and vegetation. The rule works well in darkness, but it has one serious weakness: it can be fooled by artificial light.',
    'As coastal areas have been developed for tourism and housing, beaches that were once dark are now lit by hotels, street lamps and car parks. To a hatchling, a bright hotel window can look like the horizon over the sea. Disoriented hatchlings may crawl inland, towards roads and buildings, where they are exposed to heat, traffic and predators. Many die of exhaustion or dehydration before sunrise. Even those that eventually reach the water may have used up much of the energy they need for their first swim to deeper, safer water.',
    'Light pollution is not the only threat. Sea turtles face a combination of pressures, including plastic waste, fishing nets and the loss of nesting beaches. Rising temperatures present another, less obvious, problem. The temperature of the sand determines whether a hatchling becomes male or female: warmer nests produce more females. Scientists are concerned that as beaches become hotter, some populations could consist almost entirely of females.',
    'The good news is that light pollution is one of the easier problems to solve. In several countries, coastal towns have introduced rules that require lights near nesting beaches to be switched off, shielded or replaced during the nesting season. Turtle-friendly lights use long wavelengths, such as amber or red, which hatchlings are less sensitive to. Volunteers also patrol beaches at night, and residents are asked to close their curtains. These measures cost relatively little, and in places where they have been applied consistently, fewer hatchlings have been found heading the wrong way.',
  ],
  vocab: [
    v('deposit', 'deposits', 'the female turtle leaves her eggs in the hole', 'এখানে মা কচ্ছপ গর্তে ডিম রেখে দেয় — অর্থাৎ ডিম পাড়ে।'),
    v('hatchling', ['hatchlings', 'hatchling'], 'the baby turtles that have just come out of their eggs', 'এখানে সদ্য ডিম ফুটে বের হওয়া কচ্ছপের বাচ্চা বোঝানো হয়েছে।'),
    v('predator', 'predators', 'crabs and birds that catch and eat the hatchlings', 'এখানে কাঁকড়া আর পাখি — যারা বাচ্চা কচ্ছপ ধরে খায়।'),
    v('rely on', 'relied on', 'hatchlings have depended on one rule to find the sea', 'এখানে বাচ্চা কচ্ছপরা সমুদ্র খুঁজতে একটা নিয়মের ওপর নির্ভর করে এসেছে।'),
    v('emerge', 'emerge', 'the hatchlings come up out of the sand', 'এখানে বালির নিচ থেকে বেরিয়ে আসা বোঝানো হয়েছে।'),
    v('horizon', 'horizon', 'the far line where sky meets sea, usually the brightest part at night', 'এখানে দূরের দিগন্ত, যেখানে আকাশ সমুদ্রের সাথে মেশে।'),
    v('reflect', 'reflected', 'moonlight bounces off the water, making the sea look bright', 'এখানে চাঁদের আলো পানিতে পড়ে ফিরে আসে, তাই সমুদ্র উজ্জ্বল দেখায়।'),
    v('vegetation', 'vegetation', 'the plants behind the beach that make the land dark', 'এখানে সৈকতের পেছনের গাছপালা, যা স্থলভাগকে অন্ধকার রাখে।'),
    v('weakness', 'weakness', 'the one problem with the hatchlings’ simple rule', 'এখানে বাচ্চাদের নিয়মটার একটা দুর্বল দিক।'),
    v('artificial', 'artificial', 'light from lamps and buildings, not from the moon or stars', 'এখানে বাতি ও ভবনের আলো, চাঁদ-তারার নয়।'),
    v('coastal', 'coastal', 'areas near the sea', 'এখানে সমুদ্রের কাছের এলাকা।'),
    v('develop', 'developed', 'hotels and houses have been built there', 'এখানে এলাকায় হোটেল আর বাড়ি নির্মাণ করা বোঝানো হয়েছে।', { en: 'to build houses, hotels or roads on land', bn: '(জমিতে) নির্মাণ করা / উন্নয়ন করা' }),
    v('disoriented', 'disoriented', 'confused about which way the sea is', 'এখানে সমুদ্র কোন দিকে তা বুঝতে না পারা — দিশেহারা।'),
    v('inland', 'inland', 'away from the sea, towards the land', 'এখানে সমুদ্র থেকে দূরে, স্থলভাগের দিকে।'),
    v('exposed to', 'exposed to', 'the hatchlings are not protected from heat, traffic and predators', 'এখানে তারা গরম, যানবাহন আর শিকারির সামনে অরক্ষিত।'),
    v('exhaustion', 'exhaustion', 'extreme tiredness from crawling too far', 'এখানে অনেক দূর হামাগুড়ি দিয়ে চরম ক্লান্ত হয়ে পড়া।'),
    v('dehydration', 'dehydration', 'losing too much water from the body', 'এখানে শরীর থেকে অতিরিক্ত পানি হারানো।'),
    v('eventually', 'eventually', 'after a long, difficult journey', 'এখানে দীর্ঘ কষ্টের পথ পেরিয়ে শেষ পর্যন্ত।'),
    v('pollution', 'light pollution', 'too much artificial light at night', 'এখানে "light pollution" মানে রাতে অতিরিক্ত কৃত্রিম আলো — আলোক দূষণ।'),
    v('threat', 'threat', 'a danger to sea turtles', 'এখানে সামুদ্রিক কচ্ছপের জন্য বিপদ।'),
    v('a combination of', 'a combination of', 'several pressures acting together', 'এখানে একসাথে কয়েকটা চাপ।'),
    v('nesting', 'nesting', 'the beaches where turtles lay eggs', 'এখানে কচ্ছপ যেখানে ডিম পাড়ে সেই সৈকত।'),
    v('determine', 'determines', 'the sand temperature decides the sex of the hatchling', 'এখানে বালির তাপমাত্রাই বাচ্চাটা পুরুষ না স্ত্রী হবে তা ঠিক করে।'),
    v('concerned', 'concerned', 'scientists are worried', 'এখানে বিজ্ঞানীরা উদ্বিগ্ন।'),
    v('population', 'populations', 'groups of turtles living in one area', 'এখানে একটা এলাকার কচ্ছপের দল।', { en: 'all the animals of one kind living in an area', bn: '(কোনো এলাকার) একটা প্রজাতির প্রাণীর দল' }),
    v('consist of', 'consist', 'be made up of', 'এখানে "consist … of" মানে নিয়ে গঠিত হওয়া।'),
    v('entirely', 'entirely', 'completely', 'এখানে সম্পূর্ণভাবে।'),
    v('introduce', 'introduced', 'towns have started new rules', 'এখানে শহরগুলো নতুন নিয়ম চালু করেছে।', { en: 'to bring in a new rule or system', bn: '(নিয়ম বা ব্যবস্থা) চালু করা' }),
    v('shield', 'shielded', 'lights are covered so they do not shine on the beach', 'এখানে বাতি ঢেকে দেওয়া, যাতে আলো সৈকতে না পড়ে।'),
    v('wavelength', 'wavelengths', 'the property of light that gives its colour', 'এখানে আলোর তরঙ্গদৈর্ঘ্য, যা রং ঠিক করে।'),
    v('sensitive to', 'sensitive to', 'hatchlings notice red and amber light less', 'এখানে লাল ও amber আলো বাচ্চারা কম টের পায়।'),
    v('patrol', 'patrol', 'volunteers walk along the beach to check and protect hatchlings', 'এখানে স্বেচ্ছাসেবকরা সৈকতে টহল দেন।'),
    v('measure', 'measures', 'the actions taken to protect hatchlings', 'এখানে বাচ্চাদের রক্ষার জন্য নেওয়া পদক্ষেপ।'),
    v('relatively', 'relatively', 'not much, compared with other solutions', 'এখানে অন্য সমাধানের তুলনায় কম খরচ।'),
    v('consistently', 'consistently', 'every time, without gaps', 'এখানে নিয়মিত, ফাঁক ছাড়া প্রয়োগ।'),
  ],
  groups: [
    select('tfng', TFNG_I, [
      q('rl01-q1', 'Female sea turtles lay their eggs during the day.', 'FALSE', 'Paragraph A: they come out "at night to lay their eggs".', 'Paragraph A বলে তারা "at night" ডিম পাড়ে — তাই দিনের কথা বিপরীত, FALSE।', 'crawl out of the ocean at night to lay their eggs'),
      q('rl01-q2', 'Hatchlings have to dig upwards to get out of the nest.', 'TRUE', 'Paragraph A: they "dig their way to the surface".', 'Paragraph A: "dig their way to the surface" — ওপরে খুঁড়ে ওঠে, তাই TRUE।', 'dig their way to the surface'),
      q('rl01-q3', 'Most hatchlings are eaten by crabs.', 'NOT GIVEN', 'Crabs are named as predators, but the passage never says how many hatchlings they eat.', 'কাঁকড়াকে শিকারি বলা হয়েছে, কিন্তু "বেশিরভাগ" বাচ্চা খায় কি না তা বলা নেই — NOT GIVEN।'),
      q('rl01-q4', 'On a natural beach, the land behind the sand is usually darker than the sea.', 'TRUE', 'Paragraph B: the land "is darkened by dunes and vegetation" while the water reflects moonlight.', 'Paragraph B: স্থলভাগ "darkened by dunes and vegetation", আর পানি আলো প্রতিফলিত করে — TRUE।', 'the land behind the beach is darkened by dunes and vegetation'),
      q('rl01-q5', 'Turtle-friendly lights were first designed by volunteers.', 'NOT GIVEN', 'Volunteers patrol beaches, but the passage does not say who designed the lights.', 'স্বেচ্ছাসেবকরা টহল দেন, কিন্তু আলো কে তৈরি করেছে তা বলা নেই — NOT GIVEN।'),
    ]),
    gap('sentence', 1, [
      gapItem('rl01-q6', ['horizon'], 'Paragraph B: they crawl "towards the brightest part of the horizon".', 'Paragraph B: "the brightest part of the horizon" — উত্তর horizon।', 'the brightest part of the horizon', 'Hatchlings crawl towards the brightest part of the ___.'),
      gapItem('rl01-q7', ['dehydration'], 'Paragraph C: "Many die of exhaustion or dehydration before sunrise."', 'Paragraph C: "die of exhaustion or dehydration" — উত্তর dehydration।', 'exhaustion or dehydration', 'Hatchlings that go the wrong way may die of exhaustion or ___ before morning.'),
      gapItem('rl01-q8', ['females'], 'Paragraph D: "warmer nests produce more females".', 'Paragraph D: "warmer nests produce more females" — উত্তর females (plural)।', 'warmer nests produce more females', 'Nests in warmer sand produce more ___.'),
    ]),
    select('mcq', MCQ_I, [
      q('rl01-q9', 'What does paragraph C say about hatchlings that reach the sea after going the wrong way?', 'B', 'Paragraph C: they "may have used up much of the energy they need for their first swim".', 'Paragraph C: "used up much of the energy" — প্রথম সাঁতারের শক্তি কমে যায়, তাই B। অন্যগুলো passage-এ নেই।', 'may have used up much of the energy they need for their first swim', abcd('They are usually eaten by birds.', 'They may have less energy for their first swim.', 'They return to the beach the next night.', 'They grow more slowly than other turtles.')),
      q('rl01-q10', 'What is the writer’s view of light pollution in paragraph E?', 'C', 'Paragraph E: it is "one of the easier problems to solve".', 'Paragraph E: "one of the easier problems to solve" — অন্য হুমকির চেয়ে সহজে সমাধানযোগ্য, তাই C।', 'one of the easier problems to solve', abcd('It is the most serious threat to sea turtles.', 'It cannot be solved without new technology.', 'It is easier to deal with than some other threats.', 'It only affects a few countries.')),
    ]),
  ],
};
