import { HEAD_I, TFNG_I, gap, gapItem, headings, lex, q, select, v } from '../kit';
import type { LexEntry, LibraryPassage } from '../types';

export const LEX: LexEntry[] = [
  lex('low-lying', 'adjective', 'useful', '(of land) not much higher than the sea or rivers', 'নিচু (ভূমি)', 'Low-lying villages are often the first to flood.', 'নিচু গ্রামগুলো প্রায়ই প্রথমে প্লাবিত হয়।'),
  lex('wetland', 'noun', 'useful', 'an area of land that is often covered with water', 'জলাভূমি', 'Wetlands provide a home for many birds.', 'জলাভূমি অনেক পাখির আবাসস্থল।', ['marsh', 'swamp']),
  lex('monsoon', 'noun', 'useful', 'the season of heavy rain in South Asia', 'বর্ষাকাল / মৌসুমি বৃষ্টি', 'The monsoon usually arrives in June.', 'বর্ষা সাধারণত জুনে আসে।'),
  lex('recede', 'verb', 'advanced', '(of water) to move back from an area it covered', '(পানি) নেমে যাওয়া', 'Farmers waited for the floodwater to recede.', 'কৃষকরা বন্যার পানি নেমে যাওয়ার অপেক্ষা করলেন।', ['go down', 'retreat']),
  lex('for generations', 'phrase', 'useful', 'for a very long time, passed from parents to children', 'বংশপরম্পরায় / প্রজন্মের পর প্রজন্ম', 'The family has made pottery for generations.', 'পরিবারটা প্রজন্মের পর প্রজন্ম ধরে মাটির জিনিস তৈরি করছে।'),
  lex('aquatic', 'adjective', 'advanced', 'living or growing in water', 'জলজ', 'Lotus is an aquatic plant.', 'পদ্ম একটা জলজ উদ্ভিদ।'),
  lex('rapidly', 'adverb', 'core', 'very quickly', 'দ্রুত', 'The city’s population grew rapidly.', 'শহরের জনসংখ্যা দ্রুত বেড়েছে।', ['quickly', 'fast']),
  lex('regard as', 'phrasal verb', 'useful', 'to think of someone or something in a particular way', '…হিসেবে গণ্য করা', 'She is regarded as an excellent teacher.', 'তাঁকে একজন চমৎকার শিক্ষক হিসেবে গণ্য করা হয়।', ['consider', 'see as']),
  lex('nuisance', 'noun', 'advanced', 'something annoying that causes problems', 'উৎপাত / ঝামেলা', 'The noise from the road is a real nuisance.', 'রাস্তার শব্দটা সত্যিই একটা ঝামেলা।', ['annoyance', 'problem']),
  lex('platform', 'noun', 'useful', 'a flat raised surface', 'মঞ্চ / উঁচু সমতল ভিত', 'The speaker stood on a wooden platform.', 'বক্তা একটা কাঠের মঞ্চে দাঁড়ালেন।'),
  lex('layer', 'noun', 'useful', 'a flat piece of material lying over or under another', 'স্তর', 'Put a layer of cheese on the bread.', 'রুটির ওপর এক স্তর পনির দিন।'),
  lex('decompose', 'verb', 'useful', 'to be slowly destroyed by natural processes; to rot', 'পচে যাওয়া', 'Leaves decompose and feed the soil.', 'পাতা পচে মাটিকে পুষ্টি দেয়।', ['rot', 'break down']),
  lex('fertiliser', 'noun', 'useful', 'a substance added to soil to help plants grow', 'সার', 'Too much fertiliser can harm rivers.', 'অতিরিক্ত সার নদীর ক্ষতি করতে পারে।'),
  lex('germinate', 'verb', 'advanced', '(of a seed) to start to grow', 'অঙ্কুরিত হওয়া / করা', 'The seeds germinate after about a week.', 'প্রায় এক সপ্তাহ পরে বীজ অঙ্কুরিত হয়।', ['sprout']),
  lex('seedling', 'noun', 'useful', 'a very young plant grown from a seed', 'চারা', 'Water the seedlings every morning.', 'প্রতিদিন সকালে চারাগুলোতে পানি দিন।'),
  lex('transplant', 'verb', 'useful', 'to move a growing plant to another place', '(চারা) অন্য জায়গায় রোপণ করা', 'Rice seedlings are transplanted into the fields.', 'ধানের চারা মাঠে রোপণ করা হয়।'),
  lex('compost', 'noun', 'useful', 'rotted plant material used to improve soil', 'জৈব সার / কম্পোস্ট', 'She makes compost from kitchen waste.', 'তিনি রান্নাঘরের বর্জ্য থেকে কম্পোস্ট তৈরি করেন।'),
  lex('resource', 'noun', 'core', 'something useful that people can use, such as money, materials or skills', 'সম্পদ', 'Water is a precious resource.', 'পানি একটা মূল্যবান সম্পদ।', ['asset', 'supply']),
  lex('input', 'noun', 'useful', 'ideas, advice or effort given to help something', 'মতামত / অবদান', 'Thank you for your input on the project.', 'প্রকল্পে আপনার মতামতের জন্য ধন্যবাদ।'),
  lex('surplus', 'noun / adjective', 'useful', 'an amount that is more than is needed', 'উদ্বৃত্ত', 'The farm produced a surplus of rice this year.', 'এ বছর খামারে ধান উদ্বৃত্ত হয়েছে।', ['excess', 'extra']),
  lex('source of income', 'collocation', 'core', 'a way of earning money', 'আয়ের উৎস', 'Tourism is the island’s main source of income.', 'পর্যটন দ্বীপটার আয়ের প্রধান উৎস।'),
  lex('in recognition of', 'phrase', 'useful', 'as a way of showing respect for or thanks for something', 'স্বীকৃতিস্বরূপ', 'She received an award in recognition of her work.', 'কাজের স্বীকৃতিস্বরূপ তিনি একটা পুরস্কার পেয়েছেন।'),
  lex('heritage', 'noun', 'useful', 'traditions, buildings and skills passed down from the past', 'ঐতিহ্য', 'The old city is part of the nation’s heritage.', 'পুরনো শহরটা জাতির ঐতিহ্যের অংশ।', ['tradition', 'legacy']),
  lex('limitation', 'noun', 'core', 'a weakness or a limit on what something can do', 'সীমাবদ্ধতা', 'The study has some limitations.', 'গবেষণাটার কিছু সীমাবদ্ধতা আছে।', ['drawback', 'restriction']),
  lex('physically demanding', 'collocation', 'useful', 'needing a lot of physical strength and effort', 'শারীরিকভাবে পরিশ্রমসাধ্য', 'Farming is physically demanding work.', 'কৃষিকাজ শারীরিকভাবে পরিশ্রমসাধ্য।'),
  lex('scarce', 'adjective', 'useful', 'not available in large amounts', 'দুষ্প্রাপ্য / অপ্রতুল', 'Clean water is scarce in the dry season.', 'শুকনো মৌসুমে পরিষ্কার পানি অপ্রতুল।', ['rare', 'limited']),
  lex('obtain', 'verb', 'core', 'to get something, especially with effort', 'সংগ্রহ করা / পাওয়া', 'You must obtain a visa before you travel.', 'ভ্রমণের আগে আপনাকে ভিসা সংগ্রহ করতে হবে।', ['get', 'acquire']),
  lex('durable', 'adjective', 'useful', 'able to last a long time without breaking', 'টেকসই', 'These boots are cheap but durable.', 'এই জুতাগুলো সস্তা কিন্তু টেকসই।', ['long-lasting', 'strong']),
  lex('flood-prone', 'adjective', 'useful', 'likely to be affected by floods', 'বন্যাপ্রবণ', 'Houses in flood-prone areas are built on high ground.', 'বন্যাপ্রবণ এলাকায় বাড়ি উঁচু জায়গায় তৈরি হয়।'),
  lex('adapt', 'verb', 'core', 'to change so that you can deal with a new situation', 'খাপ খাওয়ানো', 'Students quickly adapt to online classes.', 'শিক্ষার্থীরা দ্রুত অনলাইন ক্লাসের সাথে খাপ খাইয়ে নেয়।', ['adjust']),
];

export const PASSAGE: LibraryPassage = {
  id: 'rl-02-floating-gardens',
  title: 'Gardens That Float',
  topic: 'Agriculture',
  level: 'foundation',
  minutes: 15,
  background: 'Floating-bed farming is a traditional practice in wetland areas of southern Bangladesh; the FAO has recognised Bangladesh’s floating garden practices as a Globally Important Agricultural Heritage System.',
  paragraphs: [
    'In the low-lying south of Bangladesh, large areas of farmland stay under water for several months every year. For farmers in these wetlands, the monsoon brings a difficult choice: leave their land unused until the water recedes, or find a way to farm on the water itself. For generations, many have chosen the second option by building gardens that float.',
    'A floating garden begins with water hyacinth, an aquatic plant that grows rapidly and is usually regarded as a nuisance because it blocks rivers and canals. Farmers collect the hyacinth, pile it into long beds and press it down until it forms a firm platform, often around a metre thick. Other plant material, such as straw and weeds, may be added in layers. Over a few weeks, the material begins to decompose, creating a rich growing medium that needs little or no chemical fertiliser.',
    'Seeds are often germinated first in small balls of soil and rotting plants and then placed on the platform. Vegetables such as okra, gourds and spinach grow well on the beds, as do seedlings that farmers later transplant to their fields when the water drops. Because the platform rises and falls with the water level, the crops are not destroyed by flooding. After the growing season, the old beds can be broken up and used as compost on dry land.',
    'Supporters point out several advantages. The system turns a problem weed into a resource, allows families to grow food during months when they would otherwise have none, and requires few purchased inputs. Surplus vegetables can be sold at local markets, providing an extra source of income. In recognition of its value, the Food and Agriculture Organization of the United Nations has listed the practice as an important example of agricultural heritage.',
    'However, floating gardens are not without limitations. Building a bed is physically demanding work, and most beds last only one season. Where water hyacinth is scarce, or where waterways have been drained for other uses, raw materials can be difficult to obtain. Researchers and development organisations are therefore exploring ways to make the beds more durable and to share the technique with farming communities in other flood-prone regions. Whether the tradition can adapt to a changing climate may depend as much on these communities as on scientists.',
  ],
  vocab: [
    v('low-lying', 'low-lying', 'land in the south that is only a little above water level', 'এখানে দক্ষিণের নিচু জমি, যা সহজে পানিতে ডোবে।'),
    v('wetland', 'wetlands', 'areas that are covered with water for long periods', 'এখানে যে এলাকা দীর্ঘ সময় পানিতে ঢাকা থাকে — জলাভূমি।'),
    v('monsoon', 'monsoon', 'the rainy season that floods the land', 'এখানে বর্ষাকাল, যখন জমি পানিতে ডুবে যায়।'),
    v('recede', 'recedes', 'the floodwater goes down', 'এখানে বন্যার পানি নেমে যাওয়া।'),
    v('for generations', 'for generations', 'for a very long time, from parents to children', 'এখানে বহু প্রজন্ম ধরে — বংশপরম্পরায়।'),
    v('aquatic', 'aquatic', 'water hyacinth grows in water', 'এখানে কচুরিপানা পানিতে জন্মায় — জলজ উদ্ভিদ।'),
    v('rapidly', 'rapidly', 'the plant spreads very fast', 'এখানে গাছটা খুব দ্রুত ছড়ায়।'),
    v('regard as', 'regarded as', 'people usually think of it as a problem', 'এখানে মানুষ সাধারণত এটাকে সমস্যা হিসেবে দেখে।'),
    v('nuisance', 'nuisance', 'an unwanted plant that causes trouble', 'এখানে ঝামেলা সৃষ্টিকারী অনাকাঙ্ক্ষিত গাছ।'),
    v('platform', 'platform', 'the firm floating base the crops grow on', 'এখানে যে শক্ত ভাসমান ভিতের ওপর ফসল হয়।'),
    v('layer', 'layers', 'material added one level on top of another', 'এখানে একটার ওপর আরেকটা স্তর করে উপকরণ দেওয়া।'),
    v('decompose', 'decompose', 'the plant material rots and becomes rich soil', 'এখানে গাছের অংশ পচে উর্বর মাটির মত হয়ে যায়।'),
    v('fertiliser', 'fertiliser', 'chemical products that help plants grow', 'এখানে রাসায়নিক সার।'),
    v('germinate', 'germinated', 'seeds start to grow before being put on the bed', 'এখানে বীজ আগে অঙ্কুরিত করে নেওয়া হয়।'),
    v('seedling', 'seedlings', 'young plants grown on the beds', 'এখানে বেডে জন্মানো ছোট চারা।'),
    v('transplant', 'transplant', 'farmers move the young plants to their fields', 'এখানে কৃষকরা চারা তুলে মাঠে রোপণ করেন।'),
    v('compost', 'compost', 'old beds are used to improve soil on dry land', 'এখানে পুরনো বেড শুকনো জমির সার হিসেবে ব্যবহার হয়।'),
    v('resource', 'resource', 'something useful', 'এখানে কাজে লাগার মত জিনিস — সম্পদ।'),
    v('input', 'inputs', 'things farmers must buy, such as seeds or fertiliser', 'এখানে কৃষকদের যা কিনতে হয় — বীজ, সার ইত্যাদি।', { en: 'things such as seeds, fertiliser or tools used in farming', bn: 'কৃষি উপকরণ (বীজ, সার ইত্যাদি)' }),
    v('surplus', 'surplus', 'vegetables the family does not need to eat', 'এখানে পরিবারের প্রয়োজনের চেয়ে বেশি সবজি।'),
    v('source of income', 'source of income', 'a way for families to earn money', 'এখানে পরিবারের টাকা আয়ের একটা উপায়।'),
    v('in recognition of', 'in recognition of', 'to show that the practice is valuable', 'এখানে পদ্ধতিটার মূল্য স্বীকার করে।'),
    v('heritage', 'heritage', 'a traditional practice worth keeping', 'এখানে সংরক্ষণযোগ্য ঐতিহ্যবাহী পদ্ধতি।'),
    v('limitation', 'limitations', 'weak points of the system', 'এখানে পদ্ধতিটার দুর্বল দিক।'),
    v('physically demanding', 'physically demanding', 'hard work for the body', 'এখানে শরীরের জন্য কঠিন পরিশ্রম।'),
    v('scarce', 'scarce', 'there is not much water hyacinth in some places', 'এখানে কিছু জায়গায় কচুরিপানা কম পাওয়া যায়।'),
    v('obtain', 'obtain', 'to get the raw materials', 'এখানে কাঁচামাল জোগাড় করা।'),
    v('durable', 'durable', 'lasting longer than one season', 'এখানে এক মৌসুমের বেশি টিকে থাকা।'),
    v('flood-prone', 'flood-prone', 'regions that often flood', 'এখানে যে অঞ্চলে প্রায়ই বন্যা হয়।'),
    v('adapt', 'adapt', 'the tradition changes to suit a new climate', 'এখানে পরিবর্তিত জলবায়ুর সাথে ঐতিহ্যটার খাপ খাওয়ানো।'),
    v('develop', 'development', 'organisations that help poorer communities improve their lives', 'এখানে "development organisations" মানে দরিদ্র এলাকার উন্নয়নে কাজ করা সংস্থা।', { en: 'the process of helping a place or people to improve', bn: 'উন্নয়ন' }),
  ],
  groups: [
    select('headings', HEAD_I, [
      q('rl02-q1', 'Paragraph A', 'iii', 'A describes farmland under water every year and the farmers’ choice.', 'Paragraph A-তে প্রতি বছর জমি পানিতে ডোবা আর কৃষকদের কঠিন সিদ্ধান্তের কথা — তাই iii।', 'farmland stay under water for several months every year'),
      q('rl02-q2', 'Paragraph B', 'v', 'B explains how a nuisance weed is pressed into a floating platform.', 'Paragraph B-তে ঝামেলার আগাছা থেকে ভাসমান ভিত তৈরির প্রক্রিয়া — তাই v। Hyacinth-এর ইতিহাস (ii) বলা নেই।', 'press it down until it forms a firm platform'),
      q('rl02-q3', 'Paragraph C', 'vi', 'C lists the crops and explains that the platform rises with the water.', 'Paragraph C-তে কোন ফসল হয় আর পানি বাড়লেও কেন নষ্ট হয় না — তাই vi।', 'the crops are not destroyed by flooding'),
      q('rl02-q4', 'Paragraph D', 'i', 'D lists advantages: food, few inputs, extra income.', 'Paragraph D-তে সুবিধার তালিকা: খাবার, কম উপকরণ, বাড়তি আয় — তাই i। বিদেশে বিক্রির (vii) কথা নেই, স্থানীয় বাজারের কথা আছে।', 'Supporters point out several advantages'),
      q('rl02-q5', 'Paragraph E', 'iv', 'E describes limitations and research to improve the beds.', 'Paragraph E-তে সীমাবদ্ধতা আর উন্নতির চেষ্টা — তাই iv।', 'floating gardens are not without limitations'),
    ], headings(
      'Benefits for families and farmers',
      'The origins of water hyacinth',
      'A seasonal problem for wetland farmers',
      'Challenges and future development',
      'From weed to growing platform',
      'Crops that survive rising water',
      'Selling floating gardens abroad',
    )),
    gap('note', 1, [
      gapItem('rl02-q6', ['hyacinth'], 'Paragraph B: the garden "begins with water hyacinth".', 'Paragraph B: "begins with water hyacinth" — note-এ "water" দেওয়া আছে, তাই শুধু hyacinth।', 'begins with water hyacinth'),
      gapItem('rl02-q7', ['weeds'], 'Paragraph B: "straw and weeds, may be added in layers".', 'Paragraph B: "straw and weeds" — উত্তর weeds (plural)।', 'straw and weeds'),
      gapItem('rl02-q8', ['decompose'], 'Paragraph B: "the material begins to decompose".', 'Paragraph B: "begins to decompose" — উত্তর decompose।', 'the material begins to decompose'),
      gapItem('rl02-q9', ['compost'], 'Paragraph C: old beds are "used as compost on dry land".', 'Paragraph C: "used as compost on dry land" — উত্তর compost।', 'used as compost on dry land'),
    ], {
      title: 'Making a floating garden',
      lines: [
        'Main material: water [[rl02-q6]], a fast-growing plant',
        'Extra layers: straw and [[rl02-q7]]',
        'After a few weeks the material starts to [[rl02-q8]], making a rich growing medium',
        'At the end of the season: old beds become [[rl02-q9]] for dry fields',
      ],
    }),
    select('tfng', TFNG_I, [
      q('rl02-q10', 'The height of the floating bed changes with the water level.', 'TRUE', 'Paragraph C: "the platform rises and falls with the water level".', 'Paragraph C: "rises and falls with the water level" — পানির সাথে ওঠে-নামে, TRUE।', 'the platform rises and falls with the water level'),
      q('rl02-q11', 'Floating gardens need large amounts of chemical fertiliser.', 'FALSE', 'Paragraph B: the medium "needs little or no chemical fertiliser".', 'Paragraph B: "little or no chemical fertiliser" — "large amounts"-এর বিপরীত, FALSE।', 'needs little or no chemical fertiliser'),
      q('rl02-q12', 'The FAO has paid for new floating gardens to be built.', 'NOT GIVEN', 'The FAO listed the practice as heritage; nothing is said about paying for gardens.', 'FAO পদ্ধতিটাকে ঐতিহ্য হিসেবে তালিকাভুক্ত করেছে; টাকা দেওয়ার কথা নেই — NOT GIVEN।'),
    ]),
  ],
};
