import { INFO_I, MCQ_I, YNNG_I, abcd, gap, gapItem, lex, q, select, v } from '../kit';
import type { LexEntry, LibraryPassage } from '../types';

export const LEX: LexEntry[] = [
  lex('assume', 'verb', 'core', 'to think something is true without proof', 'ধরে নেওয়া', 'Many people assume that expensive food is healthier.', 'অনেকে ধরে নেন দামি খাবার বেশি স্বাস্থ্যকর।', ['suppose', 'presume']),
  lex('material', 'noun', 'core', 'a substance that things are made from', 'উপাদান / কাঁচামাল', 'Bamboo is a strong building material.', 'বাঁশ একটা মজবুত নির্মাণ উপাদান।'),
  lex('report', 'verb', 'core', 'to give information about something that has happened', 'জানানো / প্রতিবেদন করা', 'Several newspapers reported the accident.', 'কয়েকটা পত্রিকা দুর্ঘটনাটার খবর দিয়েছে।', ['state', 'describe']),
  lex('research', 'noun', 'core', 'careful study to discover new facts', 'গবেষণা', 'Research shows that sleep improves memory.', 'গবেষণা দেখায় ঘুম স্মৃতিশক্তি বাড়ায়।', ['study', 'investigation']),
  lex('propose', 'verb', 'core', 'to suggest an idea or plan for people to consider', 'প্রস্তাব করা', 'The committee proposed a new timetable.', 'কমিটি একটা নতুন সময়সূচি প্রস্তাব করেছে।', ['suggest', 'put forward']),
  lex('tend to', 'phrase', 'core', 'to usually do something', 'প্রবণতা থাকা / সাধারণত করা', 'Young people tend to use their phones more.', 'তরুণরা সাধারণত ফোন বেশি ব্যবহার করে।'),
  lex('anticipate', 'verb', 'useful', 'to expect something and prepare for it', 'আগেভাগে আন্দাজ করা', 'Good teachers anticipate students’ questions.', 'ভালো শিক্ষকরা শিক্ষার্থীদের প্রশ্ন আগেভাগে আন্দাজ করেন।', ['expect', 'foresee']),
  lex('reveal', 'verb', 'core', 'to show something that was hidden or unknown', 'প্রকাশ করা / উন্মোচন করা', 'The survey revealed a surprising result.', 'জরিপে একটা বিস্ময়কর ফল প্রকাশ পেয়েছে।', ['show', 'uncover']),
  lex('gap', 'noun', 'core', 'an empty space between two things', 'ফাঁক', 'There is a gap between the door and the floor.', 'দরজা আর মেঝের মাঝে একটা ফাঁক আছে।'),
  lex('recite', 'verb', 'advanced', 'to say something aloud from memory', 'মুখস্থ বলা / আবৃত্তি করা', 'She can recite the whole poem.', 'তিনি পুরো কবিতাটা মুখস্থ বলতে পারেন।'),
  lex('definition', 'noun', 'core', 'a statement that explains the meaning of a word', 'সংজ্ঞা', 'Write a definition of "photosynthesis".', '"photosynthesis"-এর একটা সংজ্ঞা লিখুন।'),
  lex('encouraging', 'adjective', 'useful', 'giving hope that something will be successful', 'আশাব্যঞ্জক / উৎসাহজনক', 'The first test results are encouraging.', 'প্রথম পরীক্ষার ফলগুলো আশাব্যঞ্জক।', ['promising', 'positive']),
  lex('recall', 'noun / verb', 'useful', 'the ability to remember something; to remember', 'মনে করা / স্মরণ', 'Her recall of names is excellent.', 'নাম মনে রাখার ক্ষমতা তাঁর চমৎকার।', ['memory', 'remember']),
  lex('peer', 'noun', 'useful', 'a person of the same age or level as you', 'সমবয়সী / সমপর্যায়ের কেউ', 'Teenagers often care about what their peers think.', 'কিশোররা প্রায়ই সমবয়সীরা কী ভাবে তা নিয়ে চিন্তা করে।'),
  lex('tutor', 'noun / verb', 'useful', 'a teacher who helps one student or a small group', 'গৃহশিক্ষক / টিউটর; পড়ানো', 'He tutors younger students in maths.', 'তিনি ছোট শিক্ষার্থীদের অঙ্ক পড়ান।'),
  lex('be linked to', 'phrase', 'core', 'to be connected with something', 'যুক্ত থাকা / সম্পর্কিত হওয়া', 'Poor diet is linked to many health problems.', 'খারাপ খাদ্যাভ্যাস অনেক স্বাস্থ্য সমস্যার সাথে যুক্ত।', ['be connected to', 'be associated with']),
  lex('gain', 'noun', 'useful', 'an increase in amount or value', 'লাভ / বৃদ্ধি', 'The company reported a gain in profits.', 'কোম্পানিটা মুনাফা বৃদ্ধির খবর দিয়েছে।', ['increase', 'improvement']),
  lex('attempt', 'verb / noun', 'core', 'to try to do something', 'চেষ্টা করা', 'She attempted the hardest question first.', 'তিনি সবচেয়ে কঠিন প্রশ্নটা আগে চেষ্টা করলেন।', ['try']),
  lex('work out', 'phrasal verb', 'core', 'to find the answer to a problem by thinking', 'বের করা / সমাধান করা', 'I can’t work out how to open this box.', 'বাক্সটা কীভাবে খুলব বুঝে উঠতে পারছি না।', ['figure out', 'solve']),
  lex('formula', 'noun', 'useful', 'a fixed method for achieving something', 'সূত্র / নির্দিষ্ট পদ্ধতি', 'There is no simple formula for success.', 'সাফল্যের কোনো সহজ সূত্র নেই।'),
  lex('misunderstand', 'verb', 'useful', 'to understand something wrongly', 'ভুল বোঝা', 'I misunderstood the question and lost marks.', 'আমি প্রশ্নটা ভুল বুঝে নম্বর হারিয়েছি।'),
  lex('spread', 'verb', 'core', 'to move to more people or places', 'ছড়িয়ে পড়া / ছড়ানো', 'News spreads quickly on social media.', 'সামাজিক মাধ্যমে খবর দ্রুত ছড়ায়।'),
  lex('pressure', 'noun', 'core', 'a feeling of stress caused by having to do something', 'চাপ', 'Students feel a lot of pressure before exams.', 'পরীক্ষার আগে শিক্ষার্থীরা অনেক চাপ অনুভব করে।', ['stress', 'strain']),
  lex('abandon', 'verb', 'useful', 'to stop doing or using something completely', 'পরিত্যাগ করা / ছেড়ে দেওয়া', 'They abandoned the plan because of the cost.', 'খরচের কারণে তাঁরা পরিকল্পনাটা বাদ দিলেন।', ['give up', 'drop']),
  lex('capture', 'verb', 'useful', 'to catch a person or animal', 'ধরা / বন্দি করা', 'The police captured the thief.', 'পুলিশ চোরকে ধরেছে।', ['catch']),
  lex('benefit', 'noun', 'core', 'a good effect or advantage', 'সুবিধা / উপকার', 'Regular exercise has many benefits.', 'নিয়মিত ব্যায়ামের অনেক উপকার আছে।', ['advantage', 'gain']),
  lex('risk', 'noun', 'core', 'the possibility that something bad will happen', 'ঝুঁকি', 'Smoking increases the risk of heart disease.', 'ধূমপান হৃদরোগের ঝুঁকি বাড়ায়।', ['danger', 'threat']),
  lex('as if', 'phrase', 'useful', 'in a way that suggests something is true', 'যেন', 'Study each topic as if you had to teach it.', 'প্রতিটা বিষয় এমনভাবে পড়ুন যেন আপনাকে তা পড়াতে হবে।'),
];

export const PASSAGE: LibraryPassage = {
  id: 'rl-03-protege-effect',
  title: 'Learning by Teaching',
  topic: 'Education',
  level: 'foundation',
  minutes: 16,
  background: 'The "protégé effect" and the benefit of expecting to teach are discussed in educational psychology research; teachable computer agents have been used in learning software.',
  paragraphs: [
    'Most students assume that teachers are the people who learn the least in a classroom; after all, they already know the material. Yet many teachers report that they only truly understood their subject after they had to explain it to others. This common experience has a name in education research: the protégé effect, the idea that people learn more deeply when they study in order to teach.',
    'Several explanations have been proposed. When learners know they will have to teach, they tend to organise information more carefully, look for the main ideas and anticipate questions that others might ask. Explaining a topic also forces people to put knowledge into their own words, which reveals gaps in their understanding. A student who can recite a definition may discover, halfway through an explanation, that she cannot say why it matters.',
    'Classroom studies have produced encouraging results. In a number of experiments, students who were told they would later teach a passage to others remembered more of it, and organised their recall better, than students who expected only a test, even when, in the end, neither group actually taught. In other words, simply expecting to teach seemed to change the way they studied. Peer tutoring programmes, in which older or stronger students help younger ones, have also been linked to gains for both tutors and learners.',
    'Technology has opened up new versions of the idea. In some computer programs, children are asked to teach a cartoon character, which then attempts to answer questions using only what it has been taught. When the character makes mistakes, the children must work out what they explained badly. Designers of these programs have noticed that children often try harder for the character than they do for themselves.',
    'The protégé effect is not a magic formula. Teaching something you have misunderstood can spread errors, and shy students may find the pressure of explaining to classmates stressful rather than helpful. In my view, however, these problems are reasons to design teaching activities carefully, not to abandon them. Short, low-pressure tasks, such as explaining a single idea to a partner or recording a two-minute summary for an imaginary younger student, capture most of the benefits with few of the risks. For anyone preparing for an exam, the lesson is simple: if you want to learn something well, study it as if you had to teach it tomorrow.',
  ],
  vocab: [
    v('assume', 'assume', 'students believe it without checking', 'এখানে শিক্ষার্থীরা যাচাই না করেই ধরে নেয়।'),
    v('material', 'material', 'the content that is taught in a course', 'এখানে কোর্সে পড়ানো বিষয়বস্তু।', { en: 'the information or content studied in a course', bn: 'পাঠ্য বিষয়বস্তু' }),
    v('report', 'report', 'teachers say from their own experience', 'এখানে শিক্ষকরা নিজেদের অভিজ্ঞতা থেকে জানান।'),
    v('research', 'research', 'studies about how people learn', 'এখানে মানুষ কীভাবে শেখে তা নিয়ে গবেষণা।'),
    v('propose', 'proposed', 'researchers have suggested several explanations', 'এখানে গবেষকরা কয়েকটা ব্যাখ্যা প্রস্তাব করেছেন।'),
    v('tend to', 'tend to', 'learners usually do this', 'এখানে শিক্ষার্থীরা সাধারণত এমন করে।'),
    v('anticipate', 'anticipate', 'think ahead about what others will ask', 'এখানে অন্যরা কী জিজ্ঞেস করবে তা আগে থেকে ভাবা।'),
    v('reveal', 'reveals', 'explaining shows what the learner does not know', 'এখানে ব্যাখ্যা করতে গিয়ে কী জানা নেই তা বেরিয়ে আসে।'),
    v('gap', 'gaps', 'missing parts in what someone knows', 'এখানে জ্ঞানের ঘাটতি — যা জানা নেই।', { en: 'something missing from what someone knows', bn: '(জ্ঞানের) ঘাটতি / ফাঁক' }),
    v('recite', 'recite', 'say a definition from memory', 'এখানে সংজ্ঞা মুখস্থ বলে দেওয়া।'),
    v('definition', 'definition', 'the meaning of a term', 'এখানে কোনো পরিভাষার অর্থ — সংজ্ঞা।'),
    v('encouraging', 'encouraging', 'results that give hope', 'এখানে আশা জাগানো ফলাফল।'),
    v('recall', 'recall', 'what students remembered', 'এখানে শিক্ষার্থীরা যা মনে করতে পেরেছে।'),
    v('peer', 'peer', 'students of a similar age teaching each other', 'এখানে সমবয়সী শিক্ষার্থীরা একে অপরকে পড়ায়।'),
    v('tutor', ['tutoring', 'tutors'], 'students who help and teach other students', 'এখানে যে শিক্ষার্থীরা অন্যদের পড়ায়।'),
    v('be linked to', 'been linked to', 'connected with better results', 'এখানে ভালো ফলের সাথে যুক্ত।'),
    v('gain', 'gains', 'improvements in learning', 'এখানে শেখায় উন্নতি।', { en: 'an improvement', bn: 'উন্নতি' }),
    v('attempt', 'attempts', 'the character tries to answer', 'এখানে চরিত্রটা উত্তর দেওয়ার চেষ্টা করে।'),
    v('work out', 'work out', 'find what they explained badly', 'এখানে কোথায় খারাপ ব্যাখ্যা করেছে তা বের করা।'),
    v('formula', 'formula', 'a guaranteed method', 'এখানে নিশ্চিত সাফল্যের কোনো সূত্র নয়।'),
    v('misunderstand', 'misunderstood', 'understood wrongly', 'এখানে ভুলভাবে বোঝা।'),
    v('spread', 'spread', 'pass errors on to other students', 'এখানে ভুল অন্যদের মধ্যে ছড়ানো।'),
    v('pressure', 'pressure', 'stress from explaining in front of others', 'এখানে অন্যদের সামনে ব্যাখ্যা করার চাপ।'),
    v('abandon', 'abandon', 'stop using teaching activities', 'এখানে পড়ানোর কার্যক্রম বাদ দেওয়া।'),
    v('capture', 'capture', 'get most of the benefits', 'এখানে বেশিরভাগ সুবিধা পাওয়া।', { en: 'to get or keep something valuable', bn: 'অর্জন করা / ধরে রাখা' }),
    v('benefit', 'benefits', 'good effects on learning', 'এখানে শেখার উপকার।'),
    v('risk', 'risks', 'possible problems', 'এখানে সম্ভাব্য সমস্যা।'),
    v('as if', 'as if', 'study in the way you would if you had to teach', 'এখানে এমনভাবে পড়া যেন কাল পড়াতে হবে।'),
  ],
  groups: [
    select('info', INFO_I, [
      q('rl03-q1', 'a computer character that learns from children', 'D', 'Paragraph D: children "teach a cartoon character".', 'Paragraph D-তে শিশুরা একটা কার্টুন চরিত্রকে পড়ায় — উত্তর D।', 'children are asked to teach a cartoon character'),
      q('rl03-q2', 'a danger of teaching something incorrectly', 'E', 'Paragraph E: "Teaching something you have misunderstood can spread errors".', 'Paragraph E: ভুল বুঝে পড়ালে ভুল ছড়ায় — উত্তর E।', 'Teaching something you have misunderstood can spread errors'),
      q('rl03-q3', 'an example of knowing a definition without understanding its importance', 'B', 'Paragraph B: a student who can recite a definition but "cannot say why it matters".', 'Paragraph B: সংজ্ঞা মুখস্থ বলতে পারে কিন্তু "why it matters" বলতে পারে না — উত্তর B।', 'she cannot say why it matters'),
    ]),
    select('mcq', MCQ_I, [
      q('rl03-q4', 'In the experiments described in paragraph C, what helped students remember more?', 'B', 'Paragraph C: "simply expecting to teach seemed to change the way they studied" — neither group actually taught.', 'Paragraph C: কেউ আসলে পড়ায়নি, শুধু পড়াতে হবে এই প্রত্যাশাই পার্থক্য এনেছে — B। A ভুল কারণ "neither group actually taught"।', 'simply expecting to teach seemed to change the way they studied', abcd('actually teaching the passage to others', 'expecting to teach the passage later', 'taking a test straight after reading', 'working with an older tutor')),
      q('rl03-q5', 'What did the designers of the computer programs notice?', 'C', 'Paragraph D: "children often try harder for the character than they do for themselves".', 'Paragraph D: শিশুরা নিজের চেয়ে চরিত্রটার জন্য বেশি চেষ্টা করে — C।', 'children often try harder for the character than they do for themselves', abcd('The character answered most questions correctly.', 'Children preferred learning from teachers.', 'Children made more effort for the character than for themselves.', 'The programs were too difficult for young children.')),
    ]),
    select('ynng', YNNG_I, [
      q('rl03-q6', 'The problems with the protégé effect mean that schools should stop using teaching activities.', 'NO', 'Paragraph E: the problems are "reasons to design teaching activities carefully, not to abandon them".', 'Paragraph E: লেখক বলেন সমস্যাগুলো বাদ দেওয়ার কারণ নয়, সাবধানে ডিজাইনের কারণ — তাই NO।', 'not to abandon them'),
      q('rl03-q7', 'Short, low-pressure teaching tasks can give most of the benefits.', 'YES', 'Paragraph E: such tasks "capture most of the benefits with few of the risks".', 'Paragraph E: "capture most of the benefits" — লেখকের মতের সাথে মেলে, YES।', 'capture most of the benefits with few of the risks'),
      q('rl03-q8', 'The protégé effect is stronger for science subjects than for languages.', 'NOT GIVEN', 'The writer never compares subjects.', 'লেখক বিষয়ভিত্তিক কোনো তুলনা করেননি — NOT GIVEN।'),
    ]),
    gap('sentence', 2, [
      gapItem('rl03-q9', ['own words'], 'Paragraph B: explaining forces people to "put knowledge into their own words".', 'Paragraph B: "put knowledge into their own words" — উত্তর own words।', 'put knowledge into their own words', 'Explaining a topic makes people express knowledge in their ___.'),
      gapItem('rl03-q10', ['peer tutoring'], 'Paragraph C: "Peer tutoring programmes, in which older or stronger students help younger ones".', 'Paragraph C: "Peer tutoring programmes" — উত্তর peer tutoring।', 'Peer tutoring programmes', 'In ___ programmes, older or stronger students help younger ones.'),
      gapItem('rl03-q11', ['stressful'], 'Paragraph E: shy students may find it "stressful rather than helpful".', 'Paragraph E: "stressful rather than helpful" — উত্তর stressful।', 'stressful rather than helpful', 'Shy students may find explaining to classmates ___ rather than helpful.'),
    ]),
  ],
};
