import { MCQ_I, TFNG_I, abcd, gap, gapItem, lex, q, select, v } from '../kit';
import type { LexEntry, LibraryPassage } from '../types';

export const LEX: LexEntry[] = [
  lex('accessible', 'adjective', 'useful', 'easy to reach, use or take part in', 'সহজলভ্য / সবার নাগালে', 'The library is accessible to everyone in the town.', 'লাইব্রেরিটা শহরের সবার জন্য সহজলভ্য।', ['available', 'reachable']),
  lex('equipment', 'noun', 'core', 'the tools or machines needed for an activity', 'সরঞ্জাম', 'The lab has modern equipment.', 'ল্যাবে আধুনিক সরঞ্জাম আছে।', ['gear', 'tools']),
  lex('routine', 'noun', 'core', 'the usual order in which you do things', 'দৈনন্দিন রুটিন / নিয়মিত কাজ', 'Exercise is part of her morning routine.', 'ব্যায়াম তাঁর সকালের রুটিনের অংশ।', ['habit', 'schedule']),
  lex('overlook', 'verb', 'useful', 'to fail to notice or consider something', 'উপেক্ষা করা / নজর এড়িয়ে যাওয়া', 'Small details are easy to overlook.', 'ছোট খুঁটিনাটি সহজেই নজর এড়িয়ে যায়।', ['ignore', 'miss']),
  lex('associate with', 'phrasal verb', 'useful', 'to connect one thing with another in your mind', 'কোনো কিছুর সাথে যুক্ত করে ভাবা', 'Many people associate summer with holidays.', 'অনেকে গ্রীষ্মকে ছুটির সাথে যুক্ত করে ভাবেন।', ['connect with', 'link with']),
  lex('a body of research', 'collocation', 'advanced', 'a large amount of research on one topic', 'গবেষণার একটা বড় ভাণ্ডার', 'A growing body of research links sleep and memory.', 'ক্রমবর্ধমান গবেষণা ঘুম আর স্মৃতিকে যুক্ত করছে।'),
  lex('substantial', 'adjective', 'core', 'large in amount, size or importance', 'উল্লেখযোগ্য / বড়', 'The new road brought a substantial increase in traffic.', 'নতুন রাস্তা যানবাহন উল্লেখযোগ্যভাবে বাড়িয়েছে।', ['considerable', 'significant']),
  lex('well established', 'collocation', 'useful', 'known and accepted for a long time', 'সুপ্রতিষ্ঠিত', 'The link between smoking and cancer is well established.', 'ধূমপান আর ক্যান্সারের সম্পর্ক সুপ্রতিষ্ঠিত।'),
  lex('brisk', 'adjective', 'advanced', 'quick and energetic', 'দ্রুত ও চটপটে', 'We went for a brisk walk before breakfast.', 'নাস্তার আগে আমরা দ্রুত পায়ে হাঁটতে গেলাম।', ['quick', 'fast']),
  lex('heart rate', 'noun', 'useful', 'the number of times the heart beats in a minute', 'হৃৎস্পন্দনের হার', 'Running raises your heart rate.', 'দৌড়ালে হৃৎস্পন্দনের হার বাড়ে।'),
  lex('strengthen', 'verb', 'core', 'to make something stronger', 'শক্তিশালী করা', 'Swimming strengthens the muscles.', 'সাঁতার পেশি শক্তিশালী করে।', ['reinforce']),
  lex('blood pressure', 'noun', 'useful', 'the force of blood moving through the body', 'রক্তচাপ', 'Salt can raise blood pressure.', 'লবণ রক্তচাপ বাড়াতে পারে।'),
  lex('manage', 'verb', 'core', 'to control or deal with something successfully', 'নিয়ন্ত্রণ করা / সামলানো', 'She manages her time very well.', 'তিনি সময় খুব ভালোভাবে সামলান।', ['control', 'handle']),
  lex('load', 'noun', 'useful', 'something heavy that is carried', 'বোঝা', 'The truck was carrying a heavy load.', 'ট্রাকটা ভারী বোঝা বহন করছিল।'),
  lex('maintain', 'verb', 'core', 'to keep something at the same level or in good condition', 'বজায় রাখা', 'It is hard to maintain high grades all year.', 'সারা বছর ভালো নম্বর বজায় রাখা কঠিন।', ['keep', 'preserve']),
  lex('inactive', 'adjective', 'useful', 'not physically active; not moving much', 'নিষ্ক্রিয় / অলস', 'Office workers are often inactive for hours.', 'অফিসকর্মীরা প্রায়ই ঘণ্টার পর ঘণ্টা নিষ্ক্রিয় থাকেন।'),
  lex('mental health', 'noun', 'core', 'the health of your mind and emotions', 'মানসিক স্বাস্থ্য', 'Sleep is important for mental health.', 'ঘুম মানসিক স্বাস্থ্যের জন্য গুরুত্বপূর্ণ।'),
  lex('appear to', 'phrase', 'core', 'to seem to', 'মনে হওয়া', 'The medicine appears to work.', 'ওষুধটা কাজ করছে বলে মনে হচ্ছে।', ['seem to']),
  lex('mood', 'noun', 'core', 'the way you feel at a particular time', 'মেজাজ / মনের অবস্থা', 'Music can change your mood.', 'গান আপনার মেজাজ বদলে দিতে পারে।'),
  lex('evidence', 'noun', 'core', 'facts or signs that show something is true', 'প্রমাণ', 'There is no evidence that the drug works.', 'ওষুধটা কাজ করে এমন কোনো প্রমাণ নেই।', ['proof']),
  lex('creatively', 'adverb', 'useful', 'in a way that uses new and original ideas', 'সৃজনশীলভাবে', 'The children used the old boxes creatively.', 'শিশুরা পুরনো বাক্সগুলো সৃজনশীলভাবে ব্যবহার করেছে।'),
  lex('participant', 'noun', 'core', 'a person who takes part in something', 'অংশগ্রহণকারী', 'Each participant answered twenty questions.', 'প্রত্যেক অংশগ্রহণকারী বিশটা প্রশ্নের উত্তর দিয়েছেন।'),
  lex('original', 'adjective', 'core', 'existing at the beginning; first', 'মূল / আদি', 'The original building was made of wood.', 'মূল ভবনটা কাঠের তৈরি ছিল।'),
  lex('target', 'noun', 'core', 'a result that you try to achieve', 'লক্ষ্যমাত্রা', 'My target is Band 7 in Reading.', 'আমার লক্ষ্য Reading-এ Band 7।', ['goal', 'aim']),
  lex('market', 'verb', 'useful', 'to advertise and sell a product', 'বাজারজাত করা', 'The phone was marketed to young people.', 'ফোনটা তরুণদের কাছে বাজারজাত করা হয়েছিল।', ['advertise', 'promote']),
  lex('appeal', 'noun', 'useful', 'the quality that makes something attractive or interesting', 'আকর্ষণ', 'The city’s appeal lies in its old streets.', 'শহরটার আকর্ষণ এর পুরনো রাস্তায়।', ['attraction', 'charm']),
  lex('identify', 'verb', 'core', 'to recognise or find something', 'শনাক্ত করা / চিহ্নিত করা', 'Doctors identified the cause of the illness.', 'ডাক্তাররা অসুখের কারণ শনাক্ত করেছেন।', ['recognise', 'find']),
  lex('steadily', 'adverb', 'useful', 'gradually and regularly', 'ধীরে ধীরে নিয়মিতভাবে', 'Prices have risen steadily this year.', 'এ বছর দাম ধীরে ধীরে বেড়েছে।', ['gradually']),
  lex('meaningful', 'adjective', 'useful', 'important or large enough to matter', 'অর্থবহ / উল্লেখযোগ্য', 'The new rule made no meaningful difference.', 'নতুন নিয়মে উল্লেখযোগ্য কোনো পার্থক্য হয়নি।', ['significant']),
  lex('gradually', 'adverb', 'core', 'slowly, over a period of time', 'ধীরে ধীরে', 'The weather gradually improved.', 'আবহাওয়া ধীরে ধীরে ভালো হলো।', ['slowly', 'step by step']),
  lex('pace', 'noun', 'useful', 'the speed at which someone moves or something happens', 'গতি', 'She walked at a steady pace.', 'তিনি স্থির গতিতে হাঁটলেন।', ['speed', 'rate']),
  lex('moderate', 'adjective', 'useful', 'neither very large nor very small; medium', 'মাঝারি / পরিমিত', 'Moderate exercise is good for most people.', 'মাঝারি ব্যায়াম বেশিরভাগ মানুষের জন্য ভালো।', ['medium', 'reasonable']),
  lex('effective', 'adjective', 'core', 'producing the result that is wanted', 'কার্যকর', 'This is an effective way to learn new words.', 'নতুন word শেখার এটা একটা কার্যকর উপায়।', ['successful', 'useful']),
  lex('point out', 'phrasal verb', 'core', 'to tell someone a fact they should know', 'উল্লেখ করা / দেখিয়ে দেওয়া', 'The teacher pointed out a mistake in my essay.', 'শিক্ষক আমার essay-র একটা ভুল দেখিয়ে দিলেন।', ['mention', 'note']),
];

export const PASSAGE: LibraryPassage = {
  id: 'rl-04-walking',
  title: 'Walking Back to Health',
  topic: 'Health',
  level: 'foundation',
  minutes: 16,
  background: 'The 10,000-steps figure is widely traced to a pedometer marketed in Japan in the 1960s; research on walking, health and creative thinking is summarised in general terms.',
  paragraphs: [
    'Few forms of exercise are as accessible as walking. It requires no special equipment, costs nothing and can be fitted into daily routines, from walking to the shops to taking the stairs instead of a lift. Perhaps because it seems so ordinary, walking is often overlooked by people who associate fitness with gyms and running tracks. Yet a large body of research suggests that regular walking brings substantial benefits for both body and mind.',
    'The physical advantages are well established. Brisk walking raises the heart rate, strengthens the heart and helps to control blood pressure. It burns energy, which makes it useful for managing body weight, and because each step places a small load on the bones, it can help to maintain bone strength as people age. Studies that have followed large groups of adults over many years have found that those who walk regularly have a lower risk of heart disease and type 2 diabetes than those who are mostly inactive.',
    'Walking also appears to benefit mental health. People who take regular walks often report lower levels of stress and better sleep, and some studies suggest that walking in green spaces, such as parks, may improve mood more than walking along busy roads. There is also evidence that a short walk can help people think more creatively: participants in some experiments produced more original ideas while walking, or shortly afterwards, than while sitting at a desk.',
    'Many people now measure their walking with a step count, and the most famous target is 10,000 steps a day. Surprisingly, this number did not come from medical research. It became popular in Japan in the 1960s, when a company marketed a pedometer whose name meant "10,000-step meter". The figure was easy to remember, but it was chosen partly for its appeal rather than because scientists had identified it as ideal. Later research has suggested that health benefits increase steadily with the number of steps, and that meaningful gains may begin well below 10,000 for many people.',
    'For people who have been inactive, the best advice is to start gradually. Adding a ten-minute walk after meals, getting off the bus one stop early or walking during phone calls can all increase daily activity without requiring major changes. Pace matters too: walking fast enough to breathe more heavily while still being able to talk counts as moderate exercise. The most effective walking plan, experts point out, is simply the one that a person can keep doing.',
  ],
  vocab: [
    v('accessible', 'accessible', 'almost anyone can do it easily', 'এখানে প্রায় সবাই সহজে করতে পারে — সহজলভ্য।'),
    v('equipment', 'equipment', 'special tools or machines for exercise', 'এখানে ব্যায়ামের বিশেষ সরঞ্জাম।'),
    v('routine', 'routines', 'the things people do every day', 'এখানে মানুষের প্রতিদিনের নিয়মিত কাজ।'),
    v('overlook', 'overlooked', 'people do not think of walking as exercise', 'এখানে মানুষ হাঁটাকে ব্যায়াম হিসেবে গুরুত্ব দেয় না।'),
    v('associate with', 'associate fitness with', 'people connect fitness with gyms in their minds', 'এখানে মানুষ ফিটনেস বলতে জিম-কে বোঝে।'),
    v('a body of research', 'body of research', 'many studies on the topic', 'এখানে বিষয়টা নিয়ে অনেক গবেষণা।'),
    v('research', 'research', 'scientific studies', 'এখানে বৈজ্ঞানিক গবেষণা।'),
    v('substantial', 'substantial', 'large and important benefits', 'এখানে বড় ও গুরুত্বপূর্ণ উপকার।'),
    v('benefit', ['benefits', 'benefit'], 'good effects on health', 'এখানে স্বাস্থ্যের উপকার; "benefit mental health" মানে মানসিক স্বাস্থ্যের উপকার করা।'),
    v('well established', 'well established', 'known and accepted by scientists for a long time', 'এখানে বিজ্ঞানীরা বহুদিন ধরে জানেন ও মানেন।'),
    v('brisk', 'Brisk', 'walking quickly', 'এখানে দ্রুত পায়ে হাঁটা।'),
    v('heart rate', 'heart rate', 'how fast the heart beats', 'এখানে হৃৎস্পন্দন কত দ্রুত।'),
    v('strengthen', 'strengthens', 'makes the heart stronger', 'এখানে হৃৎপিণ্ড শক্তিশালী করে।'),
    v('blood pressure', 'blood pressure', 'the force of blood in the body', 'এখানে রক্তচাপ।'),
    v('manage', 'managing', 'keeping body weight under control', 'এখানে শরীরের ওজন নিয়ন্ত্রণে রাখা।'),
    v('load', 'load', 'the small weight each step puts on the bones', 'এখানে প্রতিটা পদক্ষেপে হাড়ের ওপর পড়া ছোট চাপ।', { en: 'the weight or force that something has to support', bn: 'চাপ / ভার' }),
    v('maintain', 'maintain', 'keep bones strong', 'এখানে হাড়ের শক্তি বজায় রাখা।'),
    v('risk', 'risk', 'the chance of getting a disease', 'এখানে রোগ হওয়ার সম্ভাবনা।'),
    v('inactive', 'inactive', 'people who hardly exercise', 'এখানে যারা প্রায় ব্যায়াম করেন না।'),
    v('mental health', 'mental health', 'the health of the mind', 'এখানে মানসিক স্বাস্থ্য।'),
    v('appear to', 'appears to', 'the evidence suggests, but is not certain', 'এখানে প্রমাণ ইঙ্গিত দেয়, তবে নিশ্চিত নয়।'),
    v('report', 'report', 'people say how they feel', 'এখানে মানুষ নিজেদের অনুভূতি জানান।'),
    v('mood', 'mood', 'how people feel', 'এখানে মানুষের মনের অবস্থা।'),
    v('evidence', 'evidence', 'results that support the idea', 'এখানে ধারণাটার পক্ষে প্রমাণ।'),
    v('creatively', 'creatively', 'with new ideas', 'এখানে নতুন ধারণা নিয়ে ভাবা।'),
    v('participant', 'participants', 'people who took part in the experiments', 'এখানে পরীক্ষায় অংশ নেওয়া মানুষ।'),
    v('original', 'original', 'new and different ideas', 'এখানে নতুন ও ভিন্ন ধরনের ধারণা।', { en: 'new and different; not copied', bn: 'মৌলিক / নতুন' }),
    v('measure', 'measure', 'count how much people walk', 'এখানে কতটা হাঁটা হলো তা মাপা।', { en: 'to find the size or amount of something', bn: 'মাপা / পরিমাপ করা' }),
    v('target', 'target', 'the number of steps people aim for', 'এখানে যত পদক্ষেপ হাঁটার লক্ষ্য।'),
    v('market', 'marketed', 'a company advertised and sold the pedometer', 'এখানে একটা কোম্পানি pedometer-টা বাজারজাত করেছিল।'),
    v('appeal', 'appeal', 'the number was attractive and easy to remember', 'এখানে সংখ্যাটা আকর্ষণীয় ও মনে রাখা সহজ।'),
    v('identify', 'identified', 'scientists had not found it to be ideal', 'এখানে বিজ্ঞানীরা এটাকে আদর্শ হিসেবে চিহ্নিত করেননি।'),
    v('steadily', 'steadily', 'benefits grow bit by bit with more steps', 'এখানে পদক্ষেপ বাড়ার সাথে সাথে উপকার ধীরে ধীরে বাড়ে।'),
    v('meaningful', 'meaningful', 'large enough to make a real difference', 'এখানে সত্যিকার পার্থক্য আনার মত যথেষ্ট।'),
    v('gain', 'gains', 'improvements in health', 'এখানে স্বাস্থ্যের উন্নতি।', { en: 'an improvement', bn: 'উন্নতি' }),
    v('gradually', 'gradually', 'little by little', 'এখানে অল্প অল্প করে।'),
    v('pace', 'Pace', 'how fast you walk', 'এখানে কত দ্রুত হাঁটছেন।'),
    v('moderate', 'moderate', 'medium-intensity exercise', 'এখানে মাঝারি মাত্রার ব্যায়াম।'),
    v('effective', 'effective', 'the plan that works best', 'এখানে যে পরিকল্পনা সবচেয়ে ভালো কাজ করে।'),
    v('point out', 'point out', 'experts say this', 'এখানে বিশেষজ্ঞরা বিষয়টা উল্লেখ করেন।'),
  ],
  groups: [
    select('tfng', TFNG_I, [
      q('rl04-q1', 'Some people connect fitness mainly with gyms and running.', 'TRUE', 'Paragraph A: people "associate fitness with gyms and running tracks".', 'Paragraph A: "associate fitness with gyms and running tracks" — মিলে যায়, TRUE।', 'associate fitness with gyms and running tracks'),
      q('rl04-q2', 'Walking can help people keep their bones strong as they grow older.', 'TRUE', 'Paragraph B: it "can help to maintain bone strength as people age".', 'Paragraph B: "maintain bone strength as people age" — বয়স বাড়লেও হাড় শক্ত রাখতে সাহায্য করে, TRUE।', 'it can help to maintain bone strength as people age'),
      q('rl04-q3', 'The 10,000-step target was first recommended by doctors.', 'FALSE', 'Paragraph D: "this number did not come from medical research"; it came from a company’s product.', 'Paragraph D: সংখ্যাটা চিকিৎসা গবেষণা থেকে আসেনি, একটা কোম্পানির পণ্য থেকে — FALSE।', 'this number did not come from medical research'),
      q('rl04-q4', 'The company that sold the pedometer was based in Tokyo.', 'NOT GIVEN', 'Only "Japan" is mentioned; no city is named.', 'শুধু "Japan" বলা আছে; কোনো শহরের নাম নেই — NOT GIVEN।'),
      q('rl04-q5', 'Health benefits may begin at fewer than 10,000 steps a day.', 'TRUE', 'Paragraph D: "meaningful gains may begin well below 10,000 for many people".', 'Paragraph D: "well below 10,000" — কম পদক্ষেপেও উপকার শুরু হতে পারে, TRUE।', 'meaningful gains may begin well below 10,000'),
    ]),
    gap('summary', 1, [
      gapItem('rl04-q6', ['pressure'], 'Paragraph B: brisk walking "helps to control blood pressure".', 'Paragraph B: "control blood pressure" — summary-তে blood দেওয়া আছে, তাই pressure।', 'helps to control blood pressure'),
      gapItem('rl04-q7', ['diabetes'], 'Paragraph B: "a lower risk of heart disease and type 2 diabetes".', 'Paragraph B: "type 2 diabetes" — উত্তর diabetes।', 'heart disease and type 2 diabetes'),
      gapItem('rl04-q8', ['stress'], 'Paragraph C: walkers "report lower levels of stress and better sleep".', 'Paragraph C: "lower levels of stress" — উত্তর stress।', 'lower levels of stress'),
    ], {
      title: 'The benefits of walking',
      lines: [
        'Brisk walking strengthens the heart and helps to control blood [[rl04-q6]]. Over many years, people who walk regularly have a lower risk of heart disease and type 2 [[rl04-q7]]. Walking may also reduce [[rl04-q8]] and help people sleep better.',
      ],
    }),
    gap('short', 2, [
      gapItem('rl04-q9', ['step count'], 'Paragraph D: people "measure their walking with a step count".', 'Paragraph D: "measure their walking with a step count" — উত্তর step count।', 'measure their walking with a step count', 'What do many people now use to measure their walking?'),
      gapItem('rl04-q10', ['phone calls'], 'Paragraph E: people can walk "during phone calls".', 'Paragraph E: "walking during phone calls" — উত্তর phone calls।', 'walking during phone calls', 'During which everyday activity does the writer suggest people could walk?'),
    ]),
    select('mcq', MCQ_I, [
      q('rl04-q11', 'According to paragraph E, the most effective walking plan is', 'C', 'Paragraph E: it is "simply the one that a person can keep doing".', 'Paragraph E: "the one that a person can keep doing" — যেটা চালিয়ে যাওয়া যায়, তাই C।', 'the one that a person can keep doing', abcd('one that reaches 10,000 steps every day.', 'one that includes running as well as walking.', 'one that a person is able to continue.', 'one designed by a doctor.')),
    ]),
  ],
};
