import { MCQ_I, NAMES_I, TFNG_I, abcd, gap, gapItem, lex, named, q, select, v } from '../kit';
import type { LexEntry, LibraryPassage } from '../types';

export const LEX: LexEntry[] = [
  lex('packaged', 'adjective', 'useful', 'wrapped or put in a box or container for selling', 'মোড়কজাত', 'Packaged food often contains a lot of salt.', 'মোড়কজাত খাবারে প্রায়ই অনেক লবণ থাকে।'),
  lex('familiar', 'adjective', 'core', 'well known because you have seen it many times', 'পরিচিত', 'The song sounded familiar.', 'গানটা পরিচিত মনে হলো।', ['well known', 'common']),
  lex('invisible', 'adjective', 'useful', 'impossible to see; not noticed', 'অদৃশ্য / চোখে না পড়া', 'Some dangers in the home are almost invisible.', 'বাড়ির কিছু বিপদ প্রায় চোখেই পড়ে না।', ['unseen']),
  lex('goods', 'noun', 'core', 'things that are made to be sold', 'পণ্য / মালামাল', 'The shop sells household goods.', 'দোকানটা গৃহস্থালির পণ্য বিক্রি করে।', ['products', 'merchandise']),
  lex('transport', 'verb / noun', 'core', 'to move people or goods from one place to another', 'পরিবহন করা', 'The fruit is transported by lorry.', 'ফলগুলো লরিতে পরিবহন করা হয়।', ['carry', 'move']),
  lex('practical', 'adjective', 'core', 'likely to work well in real situations', 'বাস্তবসম্মত / কাজের উপযোগী', 'We need a practical solution, not just an idea.', 'আমাদের শুধু ধারণা নয়, বাস্তবসম্মত সমাধান দরকার।', ['workable', 'realistic']),
  lex('trace to', 'phrasal verb', 'useful', 'to find where something began', 'উৎস খুঁজে পাওয়া', 'The tradition can be traced to the 18th century.', 'ঐতিহ্যটার উৎস অষ্টাদশ শতাব্দীতে খুঁজে পাওয়া যায়।'),
  lex('overhear', 'verb', 'useful', 'to hear what other people are saying without them knowing', 'আড়ি পেতে বা হঠাৎ শুনে ফেলা', 'I overheard two students talking about the exam.', 'আমি দুজন শিক্ষার্থীকে পরীক্ষা নিয়ে কথা বলতে শুনে ফেললাম।'),
  lex('record', 'verb', 'core', 'to write down or store information so it can be used later', 'লিপিবদ্ধ করা / রেকর্ড করা', 'The nurse recorded the patient’s temperature.', 'নার্স রোগীর তাপমাত্রা লিখে রাখলেন।', ['note', 'register']),
  lex('automatically', 'adverb', 'useful', 'by itself, without a person having to do it', 'স্বয়ংক্রিয়ভাবে', 'The lights switch off automatically at midnight.', 'মধ্যরাতে বাতিগুলো স্বয়ংক্রিয়ভাবে বন্ধ হয়।'),
  lex('determined', 'adjective', 'core', 'having decided firmly to do something', 'দৃঢ়প্রতিজ্ঞ', 'She was determined to pass the test.', 'তিনি পরীক্ষায় পাস করতে দৃঢ়প্রতিজ্ঞ ছিলেন।', ['resolved', 'committed']),
  lex('account', 'noun', 'core', 'an arrangement with a bank to keep your money', 'হিসাব / অ্যাকাউন্ট', 'I opened a bank account last week.', 'গত সপ্তাহে আমি একটা ব্যাংক অ্যাকাউন্ট খুলেছি।'),
  lex('patent', 'noun', 'useful', 'an official right to be the only one who makes or sells an invention', 'পেটেন্ট / উদ্ভাবনস্বত্ব', 'The company holds a patent on the new engine.', 'নতুন ইঞ্জিনের পেটেন্ট কোম্পানিটার কাছে।'),
  lex('reliably', 'adverb', 'useful', 'in a way that can be trusted to work well every time', 'নির্ভরযোগ্যভাবে', 'The old car still runs reliably.', 'পুরনো গাড়িটা এখনো নির্ভরযোগ্যভাবে চলে।'),
  lex('commercial', 'adjective', 'core', 'related to buying and selling things to make money', 'বাণিজ্যিক', 'The film was a commercial success.', 'ছবিটা বাণিজ্যিকভাবে সফল হয়েছিল।', ['business']),
  lex('affordable', 'adjective', 'core', 'cheap enough for people to buy', 'সাশ্রয়ী / কেনার সামর্থ্যের মধ্যে', 'The city needs more affordable housing.', 'শহরে আরও সাশ্রয়ী আবাসন দরকার।', ['cheap', 'inexpensive']),
  lex('retailer', 'noun', 'useful', 'a business that sells goods to the public', 'খুচরা বিক্রেতা', 'Large retailers sell products online and in shops.', 'বড় খুচরা বিক্রেতারা অনলাইন আর দোকানে পণ্য বিক্রি করে।', ['shop', 'seller']),
  lex('adopt', 'verb', 'core', 'to start to use a new method or system', 'গ্রহণ করা', 'Many schools have adopted online testing.', 'অনেক স্কুল অনলাইন পরীক্ষা গ্রহণ করেছে।', ['take up', 'accept']),
  lex('standard', 'noun', 'core', 'an agreed rule or model that others follow', 'মানদণ্ড / মান', 'All plugs must meet the safety standard.', 'সব প্লাগকে নিরাপত্তা মানদণ্ড মানতে হবে।', ['norm', 'benchmark']),
  lex('scan', 'verb', 'useful', 'to pass a machine over something to read information from it', 'স্ক্যান করা', 'The officer scanned my passport.', 'কর্মকর্তা আমার পাসপোর্ট স্ক্যান করলেন।'),
  lex('adoption', 'noun', 'useful', 'the act of starting to use something new', 'গ্রহণ / প্রচলন', 'The adoption of electric buses has been slow.', 'বৈদ্যুতিক বাসের প্রচলন ধীর গতিতে হয়েছে।'),
  lex('manufacturer', 'noun', 'core', 'a company that makes goods in large numbers', 'প্রস্তুতকারক', 'The manufacturer recalled the faulty phones.', 'প্রস্তুতকারক ত্রুটিপূর্ণ ফোনগুলো ফেরত নিয়েছে।', ['maker', 'producer']),
  lex('packaging', 'noun', 'useful', 'the box, bag or paper that a product is sold in', 'মোড়ক / প্যাকেজিং', 'Too much plastic packaging ends up in the sea.', 'অতিরিক্ত প্লাস্টিক মোড়ক শেষ পর্যন্ত সমুদ্রে যায়।'),
  lex('obvious', 'adjective', 'core', 'easy to see or understand', 'স্পষ্ট', 'The answer seemed obvious.', 'উত্তরটা স্পষ্ট মনে হলো।', ['clear', 'evident']),
  lex('accurate', 'adjective', 'core', 'correct and exact', 'নির্ভুল', 'The map is not very accurate.', 'মানচিত্রটা খুব নির্ভুল নয়।', ['correct', 'precise']),
  lex('track', 'verb', 'core', 'to follow the movement or progress of something', 'অনুসরণ করা / নজর রাখা', 'The app tracks your daily steps.', 'অ্যাপটা আপনার প্রতিদিনের পদক্ষেপের হিসাব রাখে।', ['follow', 'monitor']),
  lex('stock', 'noun', 'useful', 'a supply of something kept for use', 'মজুত', 'We have a good stock of rice for the winter.', 'শীতের জন্য আমাদের ভালো পরিমাণ চাল মজুত আছে।', ['supply', 'store']),
  lex('warehouse', 'noun', 'useful', 'a large building for storing goods', 'গুদাম', 'The goods are kept in a warehouse near the port.', 'পণ্যগুলো বন্দরের কাছের একটা গুদামে রাখা হয়।'),
  lex('relative', 'noun', 'core', 'a member of your family', 'আত্মীয়', 'We visited our relatives during Eid.', 'ঈদে আমরা আত্মীয়দের বাড়ি গিয়েছিলাম।'),
  lex('originally', 'adverb', 'useful', 'at first; in the beginning', 'মূলত / শুরুতে', 'The building was originally a school.', 'ভবনটা শুরুতে একটা স্কুল ছিল।', ['initially', 'at first']),
  lex('principle', 'noun', 'useful', 'a basic idea or rule that explains how something works', 'মূলনীতি', 'The principle behind the machine is simple.', 'যন্ত্রটার পেছনের মূলনীতি সহজ।', ['rule', 'basis']),
  lex('in an instant', 'phrase', 'useful', 'immediately; extremely quickly', 'মুহূর্তের মধ্যে', 'The news spread in an instant.', 'খবরটা মুহূর্তের মধ্যে ছড়িয়ে পড়ল।', ['instantly']),
];

export const PASSAGE: LibraryPassage = {
  id: 'rl-05-barcode',
  title: 'The Story of the Barcode',
  topic: 'Technology',
  level: 'foundation',
  minutes: 17,
  background: 'Well-documented history: Woodland and Silver’s 1952 barcode patent, George Laurer’s work on the Universal Product Code at IBM, the first UPC scan in Troy, Ohio (1974), and Denso Wave’s QR code (1994).',
  paragraphs: [
    'Almost every packaged product in a modern shop carries a small pattern of black and white stripes. The barcode is so familiar that it is almost invisible, yet it has changed the way goods are sold, stored and transported. Its history shows how an idea can wait decades for the technology that makes it practical.',
    'The story is usually traced to Philadelphia in the late 1940s. Bernard Silver, a graduate student, overheard the head of a food company asking a university dean for a system that could record product information automatically at the checkout. Silver mentioned the problem to a friend, Norman Joseph Woodland, who became determined to solve it. According to Woodland’s own account, the key idea came to him on a beach, where he drew the dots and dashes of Morse code in the sand and then pulled them downwards with his fingers, turning them into thin and thick lines.',
    'Woodland and Silver received a patent for their design in 1952. Their version used circles rather than straight lines, so that it could be read from any direction. However, the equipment needed to read the code reliably and cheaply did not yet exist, and the invention attracted little commercial interest. It was only in the late 1960s and early 1970s, with the arrival of affordable lasers and computers, that retailers began to take the idea seriously.',
    'In the early 1970s, American grocery companies agreed to adopt a single standard so that one code could be read in any shop. The design they chose, the Universal Product Code, was developed largely by George Laurer, an engineer at IBM, and used straight bars instead of circles. On 26 June 1974, in a supermarket in Troy, Ohio, a packet of chewing gum became the first product to be scanned at a checkout using the new code.',
    'Adoption was slow at first, because shops had to buy expensive scanners and manufacturers had to print codes on their packaging. Once enough products carried codes, however, the benefits became obvious. Checkouts became faster and more accurate, and shops could track exactly what had been sold and when, which made it far easier to reorder stock. Barcodes soon spread from supermarkets to warehouses, libraries, hospitals and airports.',
    'The barcode also has a younger relative. In 1994, the Japanese company Denso Wave introduced the QR code, a square pattern that can hold far more information than a traditional barcode. It was originally designed to track car parts during manufacturing, but decades later it found a second life on mobile phones, where it is used for everything from payments to restaurant menus. More than seventy years after a drawing in the sand, the principle remains the same: a pattern that a machine can read in an instant.',
  ],
  vocab: [
    v('packaged', 'packaged', 'products sold in boxes or wrappers', 'এখানে বাক্স বা মোড়কে বিক্রি হওয়া পণ্য।'),
    v('familiar', 'familiar', 'people see barcodes all the time', 'এখানে মানুষ সবসময় barcode দেখে — খুব পরিচিত।'),
    v('invisible', 'invisible', 'so common that people no longer notice it', 'এখানে এত সাধারণ যে আর চোখেই পড়ে না।'),
    v('goods', 'goods', 'products in shops', 'এখানে দোকানের পণ্য।'),
    v('transport', 'transported', 'moved from place to place', 'এখানে এক জায়গা থেকে আরেক জায়গায় নেওয়া।'),
    v('practical', 'practical', 'able to be used in real life', 'এখানে বাস্তবে ব্যবহারযোগ্য।'),
    v('trace to', 'traced to', 'the beginning of the story is found there', 'এখানে গল্পটার শুরু সেখানে খুঁজে পাওয়া যায়।'),
    v('overhear', 'overheard', 'Silver heard a conversation he was not part of', 'এখানে Silver এমন একটা কথা শুনে ফেলেন যেখানে তিনি অংশ ছিলেন না।'),
    v('record', 'record', 'store information about each product', 'এখানে প্রতিটা পণ্যের তথ্য সংরক্ষণ করা।'),
    v('automatically', 'automatically', 'without a person typing it', 'এখানে কেউ টাইপ না করেই।'),
    v('determined', 'determined', 'Woodland firmly decided to solve the problem', 'এখানে Woodland সমস্যাটা সমাধানে দৃঢ়প্রতিজ্ঞ হন।'),
    v('account', 'account', 'Woodland’s own description of what happened', 'এখানে কী ঘটেছিল তা নিয়ে Woodland-এর নিজের বর্ণনা।', { en: 'a description of events', bn: 'বিবরণ / বর্ণনা' }),
    v('patent', 'patent', 'the legal right to their invention', 'এখানে তাঁদের উদ্ভাবনের আইনি স্বত্ব।'),
    v('equipment', 'equipment', 'machines that read the code', 'এখানে কোড পড়ার যন্ত্র।'),
    v('reliably', 'reliably', 'correctly every time', 'এখানে প্রতিবার নির্ভুলভাবে।'),
    v('commercial', 'commercial', 'interest from businesses', 'এখানে ব্যবসায়ীদের আগ্রহ।'),
    v('affordable', 'affordable', 'cheap enough for shops to buy', 'এখানে দোকান কিনতে পারে এমন সস্তা।'),
    v('retailer', 'retailers', 'shops and supermarkets', 'এখানে দোকান ও সুপারমার্কেট।'),
    v('adopt', 'adopt', 'agree to start using', 'এখানে ব্যবহার শুরু করতে রাজি হওয়া।'),
    v('standard', 'standard', 'one agreed system for all shops', 'এখানে সব দোকানের জন্য একটাই সম্মত ব্যবস্থা।'),
    v('develop', 'developed', 'designed and created', 'এখানে নকশা করে তৈরি করা।'),
    v('scan', 'scanned', 'read by a machine at the checkout', 'এখানে checkout-এ যন্ত্র দিয়ে পড়া।'),
    v('adoption', 'Adoption', 'shops starting to use barcodes', 'এখানে দোকানগুলোর barcode ব্যবহার শুরু।'),
    v('manufacturer', 'manufacturers', 'companies that make products', 'এখানে যে কোম্পানি পণ্য তৈরি করে।'),
    v('packaging', 'packaging', 'the boxes and wrappers of products', 'এখানে পণ্যের বাক্স ও মোড়ক।'),
    v('benefit', 'benefits', 'advantages', 'এখানে সুবিধা।'),
    v('obvious', 'obvious', 'clear to everyone', 'এখানে সবার কাছে স্পষ্ট।'),
    v('accurate', 'accurate', 'fewer mistakes at checkouts', 'এখানে checkout-এ ভুল কম।'),
    v('track', 'track', 'follow exactly what was sold', 'এখানে কী বিক্রি হলো তার সঠিক হিসাব রাখা।'),
    v('stock', 'stock', 'goods the shop keeps to sell', 'এখানে দোকানে বিক্রির জন্য রাখা পণ্য।'),
    v('spread', 'spread', 'barcodes began to be used in other places', 'এখানে অন্য জায়গায়ও barcode ব্যবহার শুরু হয়।'),
    v('warehouse', 'warehouses', 'large buildings for storing goods', 'এখানে পণ্য রাখার বড় গুদাম।'),
    v('relative', 'relative', 'the QR code is related to the barcode', 'এখানে QR code হলো barcode-এর "আত্মীয়" — একই ধরনের প্রযুক্তি।', { en: 'something related to another thing', bn: 'সম্পর্কিত কিছু / সগোত্র' }),
    v('introduce', 'introduced', 'Denso Wave brought out the QR code', 'এখানে Denso Wave QR code বাজারে আনে।', { en: 'to bring a new product into use for the first time', bn: 'বাজারে আনা / চালু করা' }),
    v('originally', 'originally', 'at first, before phones used it', 'এখানে শুরুতে, ফোনে ব্যবহারের আগে।'),
    v('principle', 'principle', 'the basic idea behind barcodes', 'এখানে barcode-এর পেছনের মূল ধারণা।'),
    v('in an instant', 'in an instant', 'immediately', 'এখানে মুহূর্তের মধ্যে।'),
  ],
  groups: [
    select('names', NAMES_I, [
      q('rl05-q1', 'heard about a need to record product information at the checkout', 'A', 'Paragraph B: Silver "overheard the head of a food company asking … for a system".', 'Paragraph B: Silver একজন কোম্পানি-প্রধানের কথা শুনে ফেলেন — উত্তর A।', 'Bernard Silver, a graduate student, overheard'),
      q('rl05-q2', 'turned the symbols of Morse code into lines', 'B', 'Paragraph B: Woodland "drew the dots and dashes of Morse code in the sand".', 'Paragraph B: Woodland বালিতে Morse code এঁকে রেখায় বদলান — উত্তর B।', 'drew the dots and dashes of Morse code in the sand'),
      q('rl05-q3', 'designed a code made of straight bars', 'C', 'Paragraph D: the UPC "was developed largely by George Laurer … and used straight bars".', 'Paragraph D: Laurer-এর UPC-তে সোজা bar — উত্তর C। Woodland-দের নকশায় বৃত্ত ছিল।', 'used straight bars instead of circles'),
      q('rl05-q4', 'created a code first used for car parts', 'D', 'Paragraph F: the QR code "was originally designed to track car parts".', 'Paragraph F: QR code শুরুতে গাড়ির যন্ত্রাংশ ট্র্যাক করতে — উত্তর D।', 'originally designed to track car parts'),
    ], named('Bernard Silver', 'Norman Joseph Woodland', 'George Laurer', 'Denso Wave')),
    select('tfng', TFNG_I, [
      q('rl05-q5', 'The 1952 design could be read from any direction.', 'TRUE', 'Paragraph C: circles were used "so that it could be read from any direction".', 'Paragraph C: বৃত্ত ব্যবহার করা হয়েছিল যাতে যেকোনো দিক থেকে পড়া যায় — TRUE।', 'so that it could be read from any direction'),
      q('rl05-q6', 'Businesses were keen to use the barcode as soon as it was patented.', 'FALSE', 'Paragraph C: "the invention attracted little commercial interest".', 'Paragraph C: "little commercial interest" — ব্যবসায়ীরা আগ্রহী ছিল না, তাই FALSE।', 'the invention attracted little commercial interest'),
      q('rl05-q7', 'The first product scanned cost less than a dollar.', 'NOT GIVEN', 'The passage names the product (chewing gum) but not its price.', 'পণ্যটা chewing gum বলা আছে, কিন্তু দাম বলা নেই — NOT GIVEN।'),
      q('rl05-q8', 'Shops had to buy costly equipment before they could use barcodes.', 'TRUE', 'Paragraph E: "shops had to buy expensive scanners".', 'Paragraph E: "buy expensive scanners" — costly মানে expensive (দামি), তাই TRUE।', 'shops had to buy expensive scanners'),
    ]),
    gap('table', 1, [
      gapItem('rl05-q9', ['patent'], 'Paragraph C: they "received a patent for their design in 1952".', 'Paragraph C: "received a patent … in 1952" — উত্তর patent।', 'received a patent for their design in 1952'),
      gapItem('rl05-q10', ['1974'], 'Paragraph D: "On 26 June 1974 … the first product to be scanned".', 'Paragraph D: "26 June 1974" — table-এ শুধু বছর, উত্তর 1974।', 'On 26 June 1974'),
      gapItem('rl05-q11', ['QR'], 'Paragraph F: in 1994 Denso Wave "introduced the QR code".', 'Paragraph F: "introduced the QR code" — table-এ "code" দেওয়া আছে, তাই QR।', 'introduced the QR code'),
    ], {
      numbers: true,
      title: 'Key dates in barcode history',
      table: {
        head: ['Year', 'Event'],
        rows: [
          ['1952', 'Woodland and Silver receive a [[rl05-q9]]'],
          ['[[rl05-q10]]', 'The first product is scanned in Troy, Ohio'],
          ['1994', 'The [[rl05-q11]] code is introduced'],
        ],
      },
    }),
    select('mcq', MCQ_I, [
      q('rl05-q12', 'Why did the barcode take so long to become popular?', 'B', 'Paragraph C: "the equipment needed to read the code reliably and cheaply did not yet exist".', 'Paragraph C: কম খরচে নির্ভরযোগ্যভাবে পড়ার যন্ত্র তখনো ছিল না — B।', 'the equipment needed to read the code reliably and cheaply did not yet exist', abcd('The patent did not allow other companies to use it.', 'Cheap and reliable reading equipment was not yet available.', 'Shoppers did not trust the new system.', 'The design was too difficult to print.')),
    ]),
  ],
};
