import { INFO_I, TFNG_I, gap, gapItem, lex, q, select, v } from '../kit';
import type { LexEntry, LibraryPassage } from '../types';

export const LEX: LexEntry[] = [
  lex('linguist', 'noun', 'useful', 'a person who studies languages', 'ভাষাবিজ্ঞানী', 'Linguists study how languages change over time.', 'ভাষাবিজ্ঞানীরা সময়ের সাথে ভাষা কীভাবে বদলায় তা নিয়ে গবেষণা করেন।'),
  lex('estimate', 'verb / noun', 'core', 'to guess a number or amount using the information you have', 'আনুমানিক হিসাব করা', 'Experts estimate that the bridge will cost two million dollars.', 'বিশেষজ্ঞদের হিসাবে সেতুটার খরচ হবে প্রায় বিশ লাখ ডলার।', ['calculate', 'judge']),
  lex('distribution', 'noun', 'useful', 'the way something is shared out or spread over an area or group', 'বণ্টন / বিন্যাস', 'The distribution of wealth in the country is unequal.', 'দেশটায় সম্পদের বণ্টন অসম।', ['spread', 'allocation']),
  lex('uneven', 'adjective', 'useful', 'not equal or the same in all parts', 'অসম', 'Rainfall is uneven across the region.', 'অঞ্চলজুড়ে বৃষ্টিপাত অসম।', ['unequal']),
  lex('endangered', 'adjective', 'core', 'at risk of disappearing completely', 'বিপন্ন', 'The tiger is an endangered species.', 'বাঘ একটা বিপন্ন প্রজাতি।', ['threatened', 'at risk']),
  lex('survive', 'verb', 'core', 'to continue to live or exist', 'টিকে থাকা', 'Only a few old houses survived the flood.', 'বন্যায় মাত্র কয়েকটা পুরনো বাড়ি টিকে ছিল।', ['last', 'remain']),
  lex('shift', 'noun', 'useful', 'a change in position or direction', 'পরিবর্তন / স্থানান্তর', 'There has been a shift towards online shopping.', 'অনলাইন কেনাকাটার দিকে একটা পরিবর্তন এসেছে।', ['change', 'move']),
  lex('generation', 'noun', 'core', 'all the people born at about the same time', 'প্রজন্ম', 'My parents’ generation grew up without the internet.', 'আমার বাবা-মায়ের প্রজন্ম ইন্টারনেট ছাড়াই বড় হয়েছে।'),
  lex('minority', 'noun / adjective', 'useful', 'a smaller group within a larger one', 'সংখ্যালঘু', 'A minority of students chose to study at night.', 'অল্প কিছু শিক্ষার্থী রাতে পড়া বেছে নিয়েছে।'),
  lex('opportunity', 'noun', 'core', 'a chance to do something good', 'সুযোগ', 'Studying abroad is a great opportunity.', 'বিদেশে পড়াশোনা একটা বড় সুযোগ।', ['chance']),
  lex('dominant', 'adjective', 'useful', 'more powerful, common or important than others', 'প্রভাবশালী / প্রধান', 'English is the dominant language of international business.', 'আন্তর্জাতিক ব্যবসায় English প্রধান ভাষা।', ['main', 'leading']),
  lex('pass on', 'phrasal verb', 'core', 'to give something to someone else, often to a younger person', 'হস্তান্তর করা / পরের প্রজন্মে দেওয়া', 'She passed on her cooking skills to her daughter.', 'তিনি তাঁর রান্নার দক্ষতা মেয়েকে শিখিয়ে দিয়েছেন।', ['hand down', 'transmit']),
  lex('fluently', 'adverb', 'useful', 'easily and well, especially when speaking a language', 'সাবলীলভাবে', 'He speaks three languages fluently.', 'তিনি তিনটা ভাষা সাবলীলভাবে বলেন।'),
  lex('argument', 'noun', 'core', 'a reason given to support an idea', 'যুক্তি', 'There is a strong argument for free school meals.', 'স্কুলে বিনামূল্যে খাবারের পক্ষে জোরালো যুক্তি আছে।', ['reason', 'case']),
  lex('landscape', 'noun', 'useful', 'everything you can see in a large area of land', 'প্রাকৃতিক দৃশ্য / ভূদৃশ্য', 'The landscape changes as you travel north.', 'উত্তরে গেলে ভূদৃশ্য বদলে যায়।', ['scenery']),
  lex('be tied to', 'phrase', 'useful', 'to be closely connected to something', 'গভীরভাবে যুক্ত থাকা', 'Their traditions are tied to the river.', 'তাঁদের ঐতিহ্য নদীর সাথে গভীরভাবে যুক্ত।', ['be linked to']),
  lex('identity', 'noun', 'core', 'who someone is; the feeling of belonging to a group', 'পরিচয়', 'Language is an important part of cultural identity.', 'ভাষা সাংস্কৃতিক পরিচয়ের একটা গুরুত্বপূর্ণ অংশ।'),
  lex('translate', 'verb', 'core', 'to change words from one language into another', 'অনুবাদ করা', 'The book has been translated into Bangla.', 'বইটা বাংলায় অনুবাদ করা হয়েছে।'),
  lex('effort', 'noun', 'core', 'an attempt to do something difficult', 'প্রচেষ্টা', 'The school made an effort to reduce waste.', 'স্কুলটা বর্জ্য কমানোর প্রচেষ্টা নিয়েছে।', ['attempt', 'work']),
  lex('document', 'verb', 'useful', 'to record details of something in writing, film or sound', 'লিপিবদ্ধ করা / নথিভুক্ত করা', 'The team documented every step of the project.', 'দলটা প্রকল্পের প্রতিটা ধাপ লিপিবদ্ধ করেছে।', ['record']),
  lex('remaining', 'adjective', 'useful', 'still left when others have gone', 'অবশিষ্ট', 'The remaining students waited outside.', 'অবশিষ্ট শিক্ষার্থীরা বাইরে অপেক্ষা করল।', ['left']),
  lex('grammar', 'noun', 'core', 'the rules of a language; also a book describing them', 'ব্যাকরণ', 'This grammar explains every tense clearly.', 'এই ব্যাকরণ বইটা প্রতিটা tense পরিষ্কারভাবে ব্যাখ্যা করে।'),
  lex('decline', 'noun / verb', 'core', 'a fall in amount, quality or importance; to become less', 'হ্রাস / কমে যাওয়া', 'There has been a decline in the number of wild animals.', 'বন্য প্রাণীর সংখ্যা কমে গেছে।', ['decrease', 'reduction']),
  lex('reverse', 'verb', 'useful', 'to change something to its opposite', 'উল্টে দেওয়া / বিপরীত দিকে ফেরানো', 'The new policy reversed the fall in sales.', 'নতুন নীতি বিক্রির পতন উল্টে দিয়েছে।', ['undo', 'turn around']),
  lex('set up', 'phrasal verb', 'core', 'to start a business, organisation or system', 'প্রতিষ্ঠা করা / চালু করা', 'They set up a small school in the village.', 'তাঁরা গ্রামে একটা ছোট স্কুল প্রতিষ্ঠা করেছেন।', ['establish', 'found']),
  lex('striking', 'adjective', 'useful', 'very noticeable or unusual', 'উল্লেখযোগ্য / চোখে পড়ার মত', 'There is a striking difference between the two results.', 'দুটো ফলের মধ্যে চোখে পড়ার মত পার্থক্য আছে।', ['remarkable', 'notable']),
  lex('purpose', 'noun', 'core', 'the reason for which something is done or used', 'উদ্দেশ্য', 'The purpose of the test is to measure progress.', 'পরীক্ষাটার উদ্দেশ্য অগ্রগতি মাপা।', ['aim', 'reason']),
  lex('possibility', 'noun', 'core', 'something that might happen or be done', 'সম্ভাবনা', 'The internet opened up new possibilities for learning.', 'ইন্টারনেট শেখার নতুন সম্ভাবনা খুলে দিয়েছে।', ['chance', 'option']),
  lex('audience', 'noun', 'core', 'the people who watch, listen to or read something', 'দর্শক / শ্রোতা / পাঠক', 'The programme has a young audience.', 'অনুষ্ঠানটার দর্শক তরুণরা।'),
  lex('caution', 'verb', 'advanced', 'to warn someone to be careful', 'সতর্ক করা', 'Doctors caution against eating too much sugar.', 'ডাক্তাররা অতিরিক্ত চিনি খাওয়ার বিরুদ্ধে সতর্ক করেন।', ['warn']),
  lex('replace', 'verb', 'core', 'to take the place of something', 'প্রতিস্থাপন করা / জায়গা নেওয়া', 'Machines have replaced many factory workers.', 'যন্ত্র অনেক কারখানা-শ্রমিকের জায়গা নিয়েছে।', ['substitute']),
  lex('factor', 'noun', 'core', 'one of the things that causes or influences a result', 'কারণ / উপাদান', 'Cost is an important factor in choosing a university.', 'বিশ্ববিদ্যালয় বাছাইয়ে খরচ একটা গুরুত্বপূর্ণ বিষয়।', ['element', 'cause']),
];

export const PASSAGE: LibraryPassage = {
  id: 'rl-06-languages',
  title: 'When Languages Fall Silent',
  topic: 'Culture',
  level: 'foundation',
  minutes: 17,
  background: 'Widely cited estimates: about 7,000 living languages, a large share endangered. Revitalisation examples (Māori language nests, Welsh-medium schools, the revival of spoken Hebrew) are well documented.',
  paragraphs: [
    'Linguists estimate that around 7,000 languages are spoken in the world today. The distribution of speakers, however, is extremely uneven. More than half of the world’s population speaks one of just a few dozen major languages, while thousands of smaller languages are spoken by communities of a few thousand people or fewer. According to some estimates, around forty per cent of all languages are endangered, meaning that they may not survive into the next century.',
    'Languages rarely disappear suddenly. The usual pattern is a gradual shift over several generations. Parents who speak a minority language may decide that their children will have better opportunities at school and at work if they speak the dominant language of the region. The children may understand the old language but reply in the new one, and their own children may not learn it at all. Once a language is no longer passed on to young children, it is considered seriously at risk, even if many older people still speak it fluently.',
    'Why should this matter? One argument is that each language is a record of how a community has understood the world. Many small languages contain detailed vocabulary for local plants, animals, weather and landscapes, reflecting knowledge built up over centuries. When a language stops being spoken, some of this knowledge may be lost with it, particularly if it has never been written down. Languages are also closely tied to identity: songs, stories and jokes often lose something important when they are translated.',
    'Efforts to protect endangered languages take several forms. Linguists work with the remaining speakers to document their language by recording conversations, stories and word lists, and by producing dictionaries and grammars. Recording alone, however, does not keep a language alive; for that, people must continue to use it in daily life.',
    'Some communities have shown that decline can be reversed. In New Zealand, Māori "language nests" were set up in the 1980s so that young children could spend their days with fluent older speakers. In Wales, schools that teach mainly in Welsh have helped to increase the number of young speakers. The most striking case is Hebrew, which for centuries was used mainly for religious and written purposes but became the everyday spoken language of millions of people in the twentieth century.',
    'Technology offers new possibilities too. Online courses, mobile apps and social media allow speakers of small languages to connect with each other across long distances and to create content for younger audiences. Yet experts caution that no app can replace the most important factor of all: families choosing to speak the language at home.',
  ],
  vocab: [
    v('linguist', 'Linguists', 'experts who study languages', 'এখানে যারা ভাষা নিয়ে গবেষণা করেন — ভাষাবিজ্ঞানী।'),
    v('estimate', ['estimate', 'estimates'], 'calculate approximately; an approximate figure', 'এখানে আনুমানিক হিসাব — সঠিক সংখ্যা নয়।'),
    v('distribution', 'distribution', 'how speakers are spread across languages', 'এখানে কোন ভাষায় কত বক্তা — সেই বণ্টন।'),
    v('uneven', 'uneven', 'some languages have many speakers, most have few', 'এখানে কিছু ভাষার বক্তা অনেক, বেশিরভাগের কম — অসম।'),
    v('endangered', 'endangered', 'languages that might disappear', 'এখানে যে ভাষা হারিয়ে যেতে পারে — বিপন্ন।'),
    v('survive', 'survive', 'continue to be spoken', 'এখানে ভাষাটা চালু থাকা।'),
    v('shift', 'shift', 'a slow change from one language to another', 'এখানে এক ভাষা থেকে আরেক ভাষায় ধীর পরিবর্তন।'),
    v('generation', 'generations', 'parents, children and grandchildren', 'এখানে বাবা-মা, সন্তান, নাতি-নাতনি — প্রজন্ম।'),
    v('minority', 'minority', 'a language spoken by a smaller group', 'এখানে ছোট একটা গোষ্ঠীর ভাষা।'),
    v('opportunity', 'opportunities', 'chances for a better education and job', 'এখানে ভালো শিক্ষা ও কাজের সুযোগ।'),
    v('dominant', 'dominant', 'the main, most powerful language of the area', 'এখানে এলাকার প্রধান, প্রভাবশালী ভাষা।'),
    v('pass on', 'passed on', 'taught to the next generation', 'এখানে পরের প্রজন্মকে শেখানো।'),
    v('risk', 'at risk', 'in danger of disappearing', 'এখানে "at risk" মানে হারিয়ে যাওয়ার ঝুঁকিতে।'),
    v('fluently', 'fluently', 'speaking easily and well', 'এখানে সাবলীলভাবে বলা।'),
    v('argument', 'argument', 'a reason why language loss matters', 'এখানে ভাষা হারানো কেন গুরুত্বপূর্ণ তার একটা যুক্তি।'),
    v('record', 'record', 'a store of a community’s knowledge', 'এখানে একটা সম্প্রদায়ের জ্ঞানের সংরক্ষিত রূপ।', { en: 'something that keeps information about the past', bn: 'দলিল / সংরক্ষিত বিবরণ' }),
    v('landscape', 'landscapes', 'the local land, hills and rivers', 'এখানে এলাকার ভূমি, পাহাড়, নদী।'),
    v('reflect', 'reflecting', 'the words show what people knew', 'এখানে word-গুলো মানুষের জ্ঞান প্রকাশ করে।', { en: 'to show or be a sign of something', bn: 'প্রতিফলিত করা / প্রকাশ করা' }),
    v('be tied to', 'tied to', 'closely connected with who people are', 'এখানে মানুষের পরিচয়ের সাথে গভীরভাবে যুক্ত।'),
    v('identity', 'identity', 'the sense of who a community is', 'এখানে একটা সম্প্রদায়ের পরিচয়বোধ।'),
    v('translate', 'translated', 'put into another language', 'এখানে অন্য ভাষায় রূপান্তর।'),
    v('effort', 'Efforts', 'attempts to protect languages', 'এখানে ভাষা রক্ষার প্রচেষ্টা।'),
    v('document', 'document', 'record a language in detail', 'এখানে একটা ভাষা বিস্তারিতভাবে লিপিবদ্ধ করা।'),
    v('remaining', 'remaining', 'the last people who still speak it', 'এখানে যারা এখনো ভাষাটা বলেন, শেষ কয়েকজন।'),
    v('grammar', 'grammars', 'books that describe how a language works', 'এখানে ভাষার নিয়ম বর্ণনা করা বই।'),
    v('decline', 'decline', 'the fall in the number of speakers', 'এখানে বক্তার সংখ্যা কমে যাওয়া।'),
    v('reverse', 'reversed', 'turned around so the language grows again', 'এখানে পরিস্থিতি উল্টে ভাষাটা আবার বাড়ানো।'),
    v('set up', 'set up', 'started or created', 'এখানে চালু করা হয়েছিল।'),
    v('striking', 'striking', 'the most remarkable example', 'এখানে সবচেয়ে উল্লেখযোগ্য উদাহরণ।'),
    v('purpose', 'purposes', 'the uses Hebrew had', 'এখানে Hebrew কোন কাজে ব্যবহৃত হতো।'),
    v('possibility', 'possibilities', 'new ways to help languages', 'এখানে ভাষাকে সাহায্যের নতুন উপায়।'),
    v('audience', 'audiences', 'young people who watch or read the content', 'এখানে যে তরুণরা content দেখে বা পড়ে।'),
    v('caution', 'caution', 'experts warn', 'এখানে বিশেষজ্ঞরা সতর্ক করেন।'),
    v('replace', 'replace', 'take the place of', 'এখানে কোনো app পরিবারের জায়গা নিতে পারে না।'),
    v('factor', 'factor', 'the thing that matters most', 'এখানে সবচেয়ে গুরুত্বপূর্ণ বিষয়।'),
  ],
  groups: [
    select('info', INFO_I, [
      q('rl06-q1', 'an example of a language that became widely spoken again', 'E', 'Paragraph E: Hebrew "became the everyday spoken language of millions".', 'Paragraph E: Hebrew আবার লাখো মানুষের দৈনন্দিন ভাষা হয় — উত্তর E।', 'became the everyday spoken language of millions of people'),
      q('rl06-q2', 'the point at which a language is seen as seriously threatened', 'B', 'Paragraph B: "Once a language is no longer passed on to young children, it is considered seriously at risk".', 'Paragraph B: শিশুদের আর শেখানো না হলে ভাষাটা গুরুতর ঝুঁকিতে — উত্তর B।', 'it is considered seriously at risk'),
      q('rl06-q3', 'a reason why translation cannot always keep the full meaning', 'C', 'Paragraph C: songs and stories "often lose something important when they are translated".', 'Paragraph C: অনুবাদে গান-গল্প গুরুত্বপূর্ণ কিছু হারায় — উত্তর C।', 'often lose something important when they are translated'),
    ]),
    select('tfng', TFNG_I, [
      q('rl06-q4', 'Most of the world’s languages have millions of speakers.', 'FALSE', 'Paragraph A: "thousands of smaller languages are spoken by communities of a few thousand people or fewer".', 'Paragraph A: হাজার হাজার ভাষার বক্তা মাত্র কয়েক হাজার বা তারও কম — "লাখো বক্তা"-র বিপরীত, FALSE।', 'thousands of smaller languages are spoken by communities of a few thousand people or fewer'),
      q('rl06-q5', 'Languages usually disappear within a single generation.', 'FALSE', 'Paragraph B: "The usual pattern is a gradual shift over several generations."', 'Paragraph B: সাধারণত কয়েক প্রজন্ম ধরে ধীরে ধীরে — এক প্রজন্মে নয়, FALSE।', 'a gradual shift over several generations'),
      q('rl06-q6', 'Linguists produce dictionaries of endangered languages.', 'TRUE', 'Paragraph D: linguists document languages "by producing dictionaries and grammars".', 'Paragraph D: "producing dictionaries and grammars" — ভাষাবিজ্ঞানীরা অভিধান তৈরি করেন, TRUE।', 'producing dictionaries and grammars'),
      q('rl06-q7', 'Welsh-language schools receive more government money than other schools.', 'NOT GIVEN', 'Welsh schools are mentioned, but not their funding.', 'Welsh স্কুলের কথা আছে, কিন্তু সরকারি অর্থের কথা নেই — NOT GIVEN।'),
    ]),
    gap('summary', 1, [
      gapItem('rl06-q8', ['dominant'], 'Paragraph B: parents may prefer "the dominant language of the region".', 'Paragraph B: "the dominant language of the region" — উত্তর dominant।', 'the dominant language of the region'),
      gapItem('rl06-q9', ['nests'], 'Paragraph E: Māori "language nests" were set up in the 1980s.', 'Paragraph E: "language nests" — summary-তে language আছে, তাই nests।', 'language nests'),
      gapItem('rl06-q10', ['home'], 'Paragraph F: "families choosing to speak the language at home".', 'Paragraph F: "speak the language at home" — উত্তর home।', 'speak the language at home'),
    ], {
      title: 'Losing and saving languages',
      lines: [
        'Parents may want their children to use the [[rl06-q8]] language of their region. However, some decline can be reversed: in New Zealand, language [[rl06-q9]] allow young children to spend time with fluent speakers. According to experts, the most important factor is families using the language at [[rl06-q10]].',
      ],
    }),
  ],
};
