import { HEAD_I, NAMES_I, TFNG_I, gap, gapItem, headings, lex, named, q, select, v } from '../kit';
import type { LexEntry, LibraryPassage } from '../types';

export const LEX: LexEntry[] = [
  lex('essentially', 'adverb', 'useful', 'in the most basic or important way', 'মূলত', 'The two plans are essentially the same.', 'দুটো পরিকল্পনা মূলত একই।', ['basically', 'fundamentally']),
  lex('overturn', 'verb', 'advanced', 'to change a decision or belief completely', 'বাতিল করা / সম্পূর্ণ উল্টে দেওয়া', 'New evidence overturned the old theory.', 'নতুন প্রমাণ পুরনো তত্ত্বটা সম্পূর্ণ উল্টে দিয়েছে।', ['reverse', 'overthrow']),
  lex('retrieval', 'noun', 'advanced', 'the process of getting information back from memory or storage', 'পুনরুদ্ধার / স্মৃতি থেকে তুলে আনা', 'Sleep helps the retrieval of new words.', 'ঘুম নতুন word মনে করে তুলে আনতে সাহায্য করে।'),
  lex('reconstruction', 'noun', 'advanced', 'the act of building something again from parts', 'পুনর্গঠন', 'The reconstruction of the bridge took two years.', 'সেতুটার পুনর্গঠনে দুই বছর লেগেছে।'),
  lex('fragment', 'noun', 'useful', 'a small piece of something larger', 'টুকরো / খণ্ডাংশ', 'Only fragments of the ancient letter survived.', 'প্রাচীন চিঠিটার মাত্র কয়েকটা টুকরো টিকে আছে।', ['piece', 'part']),
  lex('expectation', 'noun', 'core', 'a belief about what will happen', 'প্রত্যাশা', 'The results were better than our expectations.', 'ফলাফল আমাদের প্রত্যাশার চেয়ে ভালো ছিল।'),
  lex('remarkably', 'adverb', 'useful', 'in a way that is unusual and surprising', 'আশ্চর্যজনকভাবে', 'The old machine still works remarkably well.', 'পুরনো যন্ত্রটা এখনো আশ্চর্যজনকভাবে ভালো কাজ করে।', ['surprisingly', 'extraordinarily']),
  lex('interval', 'noun', 'useful', 'a period of time between two events', 'বিরতি / ব্যবধান', 'Review new words at regular intervals.', 'নির্দিষ্ট ব্যবধানে নতুন word review করুন।', ['gap', 'period']),
  lex('deliberately', 'adverb', 'useful', 'on purpose, not by accident', 'ইচ্ছাকৃতভাবে', 'The question was deliberately difficult.', 'প্রশ্নটা ইচ্ছাকৃতভাবে কঠিন করা হয়েছিল।', ['intentionally', 'on purpose']),
  lex('be influenced by', 'phrase', 'core', 'to be affected or changed by something', 'প্রভাবিত হওয়া', 'Children are influenced by their friends.', 'শিশুরা বন্ধুদের দ্বারা প্রভাবিত হয়।', ['be affected by']),
  lex('precisely', 'adverb', 'useful', 'exactly and accurately', 'নিখুঁতভাবে', 'The train arrived precisely on time.', 'ট্রেনটা নিখুঁতভাবে সময়মতো পৌঁছেছে।', ['exactly', 'accurately']),
  lex('quantity', 'noun', 'core', 'an amount or number of something', 'পরিমাণ', 'Quality matters more than quantity.', 'পরিমাণের চেয়ে মান বেশি গুরুত্বপূর্ণ।', ['amount']),
  lex('conventional', 'adjective', 'useful', 'usual and traditional; not unusual', 'প্রচলিত / গতানুগতিক', 'She chose a conventional career in banking.', 'তিনি ব্যাংকিংয়ে একটা প্রচলিত পেশা বেছে নিলেন।', ['traditional', 'ordinary']),
  lex('conclude', 'verb', 'core', 'to decide something is true after thinking about the facts', 'সিদ্ধান্তে পৌঁছানো', 'The report concluded that the plan was too costly.', 'প্রতিবেদনটা এই সিদ্ধান্তে পৌঁছেছে যে পরিকল্পনাটা খুব ব্যয়বহুল।', ['decide', 'deduce']),
  lex('framework', 'noun', 'useful', 'a set of ideas or a structure that supports something', 'কাঠামো', 'The course gives students a framework for essay writing.', 'কোর্সটা শিক্ষার্থীদের essay লেখার একটা কাঠামো দেয়।', ['structure', 'system']),
  lex('demonstrate', 'verb', 'core', 'to show clearly that something is true', 'প্রমাণ করে দেখানো', 'The study demonstrated a link between diet and mood.', 'গবেষণাটা খাদ্য আর মেজাজের সম্পর্ক প্রমাণ করে দেখিয়েছে।', ['show', 'prove']),
  lex('steer', 'verb', 'advanced', 'to guide or direct something in a particular direction', 'নির্দিষ্ট দিকে চালিত করা', 'The teacher steered the discussion back to the topic.', 'শিক্ষক আলোচনাটা আবার বিষয়ে ফিরিয়ে আনলেন।', ['guide', 'direct']),
  lex('finding', 'noun', 'core', 'information discovered as a result of research', 'গবেষণালব্ধ ফল', 'The main finding was that sleep improves memory.', 'মূল ফল হলো, ঘুম স্মৃতিশক্তি বাড়ায়।', ['result', 'conclusion']),
  lex('consequence', 'noun', 'core', 'a result of an action or situation, often a bad one', 'পরিণতি / ফলাফল', 'Pollution has serious consequences for health.', 'দূষণের স্বাস্থ্যগত পরিণতি গুরুতর।', ['result', 'effect']),
  lex('laboratory', 'noun', 'core', 'a room or building used for scientific experiments', 'গবেষণাগার', 'The samples were tested in a laboratory.', 'নমুনাগুলো গবেষণাগারে পরীক্ষা করা হয়েছে।'),
  lex('testimony', 'noun', 'advanced', 'a formal statement, especially in a court of law', 'সাক্ষ্য', 'The witness gave testimony for two hours.', 'সাক্ষী দুই ঘণ্টা সাক্ষ্য দিলেন।', ['statement', 'evidence']),
  lex('eyewitness', 'noun', 'useful', 'a person who saw something happen', 'প্রত্যক্ষদর্শী', 'An eyewitness described the car to the police.', 'একজন প্রত্যক্ষদর্শী পুলিশকে গাড়িটার বর্ণনা দিলেন।', ['witness', 'observer']),
  lex('confident', 'adjective', 'core', 'feeling sure about something', 'আত্মবিশ্বাসী / নিশ্চিত', 'I am confident that my answer is right.', 'আমি নিশ্চিত যে আমার উত্তর ঠিক।', ['sure', 'certain']),
  lex('wrongful conviction', 'collocation', 'advanced', 'a decision by a court that an innocent person is guilty', 'অন্যায়ভাবে দোষী সাব্যস্ত করা', 'He spent ten years in prison after a wrongful conviction.', 'অন্যায়ভাবে দোষী সাব্যস্ত হয়ে তিনি দশ বছর কারাগারে ছিলেন।'),
  lex('identification', 'noun', 'useful', 'the act of recognising who someone is', 'শনাক্তকরণ', 'The police asked for identification of the suspect.', 'পুলিশ সন্দেহভাজনকে শনাক্ত করতে বলল।'),
  lex('proportion', 'noun', 'core', 'a part of a whole, compared with the whole', 'অনুপাত / অংশ', 'A large proportion of students live at home.', 'শিক্ষার্থীদের একটা বড় অংশ বাড়িতে থাকে।', ['share', 'percentage']),
  lex('conduct', 'verb', 'useful', 'to organise and carry out an activity', 'পরিচালনা করা', 'The university conducted a survey of its students.', 'বিশ্ববিদ্যালয়টা শিক্ষার্থীদের ওপর একটা জরিপ পরিচালনা করেছে।', ['carry out', 'run']),
  lex('leading question', 'collocation', 'advanced', 'a question asked in a way that suggests the answer', 'উত্তরের ইঙ্গিত দেওয়া প্রশ্ন', 'Lawyers must not ask a witness leading questions.', 'আইনজীবীরা সাক্ষীকে উত্তরের ইঙ্গিত দেওয়া প্রশ্ন করতে পারেন না।'),
  lex('faulty', 'adjective', 'useful', 'not working correctly; having a fault', 'ত্রুটিপূর্ণ', 'The fire was caused by faulty wiring.', 'ত্রুটিপূর্ণ বৈদ্যুতিক তারের কারণে আগুন লেগেছিল।', ['defective', 'flawed']),
  lex('inflexible', 'adjective', 'useful', 'unable to change or adapt', 'অনমনীয়', 'The timetable is too inflexible for working students.', 'কর্মজীবী শিক্ষার্থীদের জন্য সময়সূচিটা খুব অনমনীয়।', ['rigid', 'fixed']),
  lex('unreliable', 'adjective', 'useful', 'not able to be trusted', 'অনির্ভরযোগ্য', 'The bus service is slow and unreliable.', 'বাস সার্ভিসটা ধীর আর অনির্ভরযোগ্য।', ['untrustworthy']),
  lex('appropriate', 'adjective', 'core', 'suitable for a particular situation', 'উপযুক্ত', 'Formal language is appropriate for an essay.', 'Essay-র জন্য formal ভাষা উপযুক্ত।', ['suitable', 'proper']),
  lex('humility', 'noun', 'advanced', 'the quality of not thinking you are better or more certain than you are', 'বিনয় / নম্রতা', 'Good scientists approach their results with humility.', 'ভালো বিজ্ঞানীরা নিজেদের ফল বিনয়ের সাথে দেখেন।', ['modesty']),
  lex('vivid', 'adjective', 'useful', 'very clear and detailed in the mind', 'স্পষ্ট / জীবন্ত', 'I have vivid memories of my first day at school.', 'স্কুলের প্রথম দিনের স্মৃতি আমার কাছে খুব স্পষ্ট।', ['clear', 'intense']),
  lex('owe to', 'phrase', 'advanced', 'to exist or succeed because of something', 'কোনো কিছুর কারণে হওয়া / কাছে ঋণী', 'The city owes its wealth to the river trade.', 'শহরটার সম্পদ নদীবাণিজ্যের কারণে।'),
];

export const PASSAGE: LibraryPassage = {
  id: 'rl-07-memory',
  title: 'How Memory Rebuilds the Past',
  topic: 'Psychology',
  level: 'intermediate',
  minutes: 20,
  background: 'Well-known studies summarised in original words: Ebbinghaus’s forgetting curve (1880s), Bartlett’s "War of the Ghosts" studies (1932) and Loftus and Palmer’s car-crash experiment (1974).',
  paragraphs: [
    'For much of history, memory was imagined as a kind of storehouse. Experiences were thought to be placed inside it, like documents in a cabinet, and taken out again when needed, perhaps a little faded but essentially unchanged. A century of research has overturned this picture. Psychologists now describe remembering not as retrieval but as reconstruction: each time we recall an event, we rebuild it from fragments, filling the gaps with knowledge, expectation and, sometimes, pure invention.',
    'The scientific study of memory began with a remarkably patient experiment. In the 1880s the German psychologist Hermann Ebbinghaus spent years memorising lists of meaningless syllables and testing himself at different intervals. He used nonsense material deliberately, so that his results would not be influenced by what he already knew. His measurements produced the first "forgetting curve", which showed that most forgetting happens soon after learning and that the rate of loss then slows down. Ebbinghaus’s work suggested that memory could be studied as precisely as any other natural process.',
    'It was a British psychologist, Frederic Bartlett, who showed that the meaning of material mattered as much as its quantity. In studies published in 1932, Bartlett asked participants to read a Native American folk tale, "The War of the Ghosts", and to retell it after various delays. With each retelling the story became shorter and more conventional. Unfamiliar details were dropped or replaced with ones that made sense within the participants’ own culture: in some versions, for instance, a canoe turned into a boat. Bartlett concluded that people remember by fitting information into existing mental frameworks, which he called schemas.',
    'Four decades later, the American researchers Elizabeth Loftus and John Palmer demonstrated how easily such reconstruction could be steered by other people. Participants watched short films of traffic accidents and were then asked how fast the cars had been travelling when they "hit" each other. For some participants, however, the verb was changed to "smashed" or "collided". This single word affected the answers: those who heard "smashed" gave the highest estimates of speed. When some participants were questioned a week later, those in the "smashed" group were also more likely to report having seen broken glass, although none had appeared in the film.',
    'Such findings have serious consequences outside the laboratory. Courts have traditionally placed great weight on the testimony of eyewitnesses, who often feel entirely confident about what they saw. Yet confidence and accuracy are not the same thing. Reviews of wrongful convictions, particularly those later overturned by DNA evidence, have found that mistaken eyewitness identification played a part in a large proportion of cases. As a result, many police forces have changed the way they conduct interviews and identity parades, for example by avoiding leading questions and recording how certain a witness is at the moment of first identification.',
    'It would be wrong, however, to conclude that human memory is simply faulty. Reconstruction has important advantages. A system that stored every detail of every experience would be slow and inflexible; by keeping the general meaning of events and rebuilding the details when needed, the brain can use past experience to understand new situations and to imagine the future. Indeed, some researchers argue that the same processes that make memory unreliable also make creativity possible.',
    'The practical lesson is not that we should distrust all our memories, but that we should treat them with appropriate humility. A vivid, detailed memory can still be wrong, and a memory that has been retold many times may owe as much to the retelling as to the original event. Where accuracy truly matters, as in a court or a scientific study, it is wiser to rely on written notes, photographs or other independent records than on the confident voice of memory alone.',
  ],
  vocab: [
    v('essentially', 'essentially', 'in its basic form', 'এখানে মূল রূপে — প্রায় অপরিবর্তিত।'),
    v('research', 'research', 'a century of scientific studies', 'এখানে এক শতাব্দীর বৈজ্ঞানিক গবেষণা।'),
    v('overturn', ['overturned'], 'proved the old idea wrong; (courts) cancelled a decision', 'এখানে পুরনো ধারণা ভুল প্রমাণিত হয়েছে; আদালতের ক্ষেত্রে রায় বাতিল হয়েছে।'),
    v('retrieval', 'retrieval', 'simply taking a stored memory out unchanged', 'এখানে সংরক্ষিত স্মৃতি অপরিবর্তিত অবস্থায় বের করে আনা।'),
    v('reconstruction', 'reconstruction', 'rebuilding a memory each time from pieces', 'এখানে প্রতিবার টুকরো থেকে স্মৃতি আবার গড়ে তোলা।'),
    v('recall', 'recall', 'remember an event', 'এখানে কোনো ঘটনা মনে করা।'),
    v('fragment', 'fragments', 'small pieces of the original experience', 'এখানে মূল অভিজ্ঞতার ছোট ছোট টুকরো।'),
    v('gap', 'gaps', 'missing parts of a memory', 'এখানে স্মৃতির হারানো অংশ।'),
    v('expectation', 'expectation', 'what we think probably happened', 'এখানে আমাদের ধারণা, কী ঘটে থাকতে পারে।'),
    v('remarkably', 'remarkably', 'unusually patient', 'এখানে আশ্চর্যজনক রকমের ধৈর্যশীল।'),
    v('interval', 'intervals', 'different amounts of time after learning', 'এখানে শেখার পরে ভিন্ন ভিন্ন সময়ের ব্যবধান।'),
    v('deliberately', 'deliberately', 'on purpose', 'এখানে ইচ্ছাকৃতভাবে।'),
    v('be influenced by', 'be influenced by', 'affected by his existing knowledge', 'এখানে তাঁর আগের জ্ঞানের প্রভাব।'),
    v('precisely', 'precisely', 'as exactly as other sciences', 'এখানে অন্য বিজ্ঞানের মত নিখুঁতভাবে।'),
    v('quantity', 'quantity', 'how much is remembered', 'এখানে কতটা মনে থাকে।'),
    v('participant', 'participants', 'people taking part in the studies', 'এখানে গবেষণায় অংশ নেওয়া মানুষ।'),
    v('conventional', 'conventional', 'more ordinary and familiar to the readers', 'এখানে পাঠকদের কাছে বেশি সাধারণ ও পরিচিত।'),
    v('replace', 'replaced', 'swapped for familiar details', 'এখানে পরিচিত খুঁটিনাটি দিয়ে বদলানো।'),
    v('conclude', ['concluded', 'conclude'], 'decided from the evidence', 'এখানে প্রমাণ থেকে সিদ্ধান্তে পৌঁছানো।'),
    v('framework', 'frameworks', 'mental structures of knowledge', 'এখানে মনের ভেতরের জ্ঞানের কাঠামো।'),
    v('demonstrate', 'demonstrated', 'showed clearly in an experiment', 'এখানে পরীক্ষার মাধ্যমে স্পষ্টভাবে দেখানো।'),
    v('steer', 'steered', 'guided in a particular direction by others', 'এখানে অন্যদের দ্বারা নির্দিষ্ট দিকে চালিত।'),
    v('estimate', 'estimates', 'guesses of speed', 'এখানে গতির আনুমানিক হিসাব।'),
    v('report', 'report', 'say they had seen', 'এখানে দেখেছে বলে জানানো।'),
    v('finding', 'findings', 'results of the research', 'এখানে গবেষণার ফলাফল।'),
    v('consequence', 'consequences', 'serious effects in real life', 'এখানে বাস্তব জীবনে গুরুতর প্রভাব।'),
    v('laboratory', 'laboratory', 'the place where experiments are done', 'এখানে যেখানে পরীক্ষা হয়।'),
    v('testimony', 'testimony', 'what eyewitnesses say in court', 'এখানে আদালতে প্রত্যক্ষদর্শীর বক্তব্য।'),
    v('eyewitness', ['eyewitnesses', 'eyewitness'], 'people who saw a crime', 'এখানে যারা অপরাধ ঘটতে দেখেছেন।'),
    v('confident', 'confident', 'feeling sure', 'এখানে নিশ্চিত বোধ করা।'),
    v('accurate', 'accuracy', 'being correct', 'এখানে "accuracy" মানে নির্ভুলতা।'),
    v('wrongful conviction', 'wrongful convictions', 'cases where innocent people were found guilty', 'এখানে যে মামলায় নির্দোষ মানুষ দোষী সাব্যস্ত হয়েছেন।'),
    v('evidence', 'evidence', 'DNA proof', 'এখানে DNA প্রমাণ।'),
    v('identification', 'identification', 'a witness saying "that is the person"', 'এখানে সাক্ষীর "এই সেই লোক" বলে শনাক্ত করা।'),
    v('proportion', 'proportion', 'a large part of all the cases', 'এখানে সব মামলার বড় একটা অংশ।'),
    v('conduct', 'conduct', 'carry out interviews', 'এখানে জিজ্ঞাসাবাদ পরিচালনা করা।'),
    v('leading question', 'leading questions', 'questions that suggest the answer', 'এখানে উত্তরের ইঙ্গিত দেয় এমন প্রশ্ন।'),
    v('faulty', 'faulty', 'broken or badly designed', 'এখানে ত্রুটিপূর্ণ।'),
    v('inflexible', 'inflexible', 'unable to adapt to new situations', 'এখানে নতুন পরিস্থিতিতে খাপ খাওয়াতে অক্ষম।'),
    v('unreliable', 'unreliable', 'not always correct', 'এখানে সবসময় সঠিক নয়।'),
    v('appropriate', 'appropriate', 'the right amount of', 'এখানে যতটা দরকার ততটা।'),
    v('humility', 'humility', 'accepting we might be wrong', 'এখানে আমরা ভুল হতে পারি তা মেনে নেওয়া।'),
    v('vivid', 'vivid', 'very clear and detailed', 'এখানে খুব স্পষ্ট ও বিস্তারিত।'),
    v('owe to', 'owe as much to', 'be caused by', 'এখানে "owe … to" মানে কোনো কিছুর কারণে হওয়া।'),
  ],
  groups: [
    select('headings', HEAD_I, [
      q('rl07-q1', 'Paragraph B', 'ii', 'B describes Ebbinghaus measuring how memory is lost over time.', 'Paragraph B-তে Ebbinghaus-এর forgetting curve — কত দ্রুত ভুলি তা মাপা, তাই ii।', 'the first "forgetting curve"'),
      q('rl07-q2', 'Paragraph C', 'v', 'C shows readers changing a story to fit their own culture.', 'Paragraph C-তে পাঠকরা নিজের সংস্কৃতি অনুযায়ী গল্প বদলে ফেলে — তাই v।', 'replaced with ones that made sense within the participants’ own culture'),
      q('rl07-q3', 'Paragraph D', 'i', 'D shows that changing one verb changed what people remembered.', 'Paragraph D-তে একটা verb বদলে স্মৃতি বদলে যায় — "a single word", তাই i।', 'This single word affected the answers'),
      q('rl07-q4', 'Paragraph E', 'vii', 'E is about eyewitness errors in courts and police changes.', 'Paragraph E-তে আদালতে প্রত্যক্ষদর্শীর ভুল আর পুলিশের পরিবর্তন — তাই vii।', 'placed great weight on the testimony of eyewitnesses'),
      q('rl07-q5', 'Paragraph F', 'iv', 'F explains the advantages of a reconstructive memory.', 'Paragraph F-এ reconstruction-এর সুবিধা — অসম্পূর্ণ স্মৃতিও কেন কাজের, তাই iv। "Techniques for improving memory" (iii) বলা নেই।', 'Reconstruction has important advantages'),
    ], headings(
      'The power of a single word',
      'Measuring how quickly we forget',
      'Techniques for improving memory',
      'Why an imperfect memory can still be useful',
      'How culture reshapes a story',
      'The chemistry of the brain',
      'When memory errors reach the courtroom',
      'A decline in public trust of science',
    )),
    select('names', NAMES_I, [
      q('rl07-q6', 'showed that the wording of a question can change what people remember', 'C', 'Paragraph D: Loftus and Palmer changed "hit" to "smashed" and answers changed.', 'Paragraph D: Loftus ও Palmer প্রশ্নের একটা word বদলে উত্তর বদলে যেতে দেখেন — C।', 'This single word affected the answers'),
      q('rl07-q7', 'used learning material that was chosen to have no meaning', 'A', 'Paragraph B: Ebbinghaus used "nonsense material deliberately".', 'Paragraph B: Ebbinghaus ইচ্ছাকৃতভাবে অর্থহীন syllable ব্যবহার করেন — A।', 'He used nonsense material deliberately'),
      q('rl07-q8', 'found that a story became shorter each time it was retold', 'B', 'Paragraph C: "With each retelling the story became shorter".', 'Paragraph C: প্রতিবার বলায় গল্প ছোট হয়েছে — Bartlett, B।', 'With each retelling the story became shorter'),
      q('rl07-q9', 'gave a name to the mental structures that organise memory', 'B', 'Paragraph C: Bartlett called the frameworks "schemas".', 'Paragraph C: Bartlett এই কাঠামোর নাম দেন "schemas" — B।', 'which he called schemas'),
    ], named('Hermann Ebbinghaus', 'Frederic Bartlett', 'Elizabeth Loftus and John Palmer')),
    select('tfng', TFNG_I, [
      q('rl07-q10', 'Ebbinghaus asked a large group of volunteers to learn his lists.', 'NOT GIVEN', 'Paragraph B only says he tested himself; it says nothing about volunteers.', 'Paragraph B শুধু বলে তিনি নিজেকে পরীক্ষা করেছেন; স্বেচ্ছাসেবকদের কথা নেই — NOT GIVEN।'),
      q('rl07-q11', 'The films in Loftus and Palmer’s study showed broken glass.', 'FALSE', 'Paragraph D: participants reported glass "although none had appeared in the film".', 'Paragraph D: "none had appeared in the film" — ভাঙা কাচ ছবিতে ছিল না, তাই FALSE।', 'although none had appeared in the film'),
      q('rl07-q12', 'Some police forces now record how sure a witness is when they first identify someone.', 'TRUE', 'Paragraph E: they record "how certain a witness is at the moment of first identification".', 'Paragraph E: "recording how certain a witness is" — sure = certain, তাই TRUE।', 'recording how certain a witness is at the moment of first identification'),
    ]),
    gap('summary', 1, [
      gapItem('rl07-q13', ['inflexible'], 'Paragraph F: storing every detail "would be slow and inflexible".', 'Paragraph F: "slow and inflexible" — উত্তর inflexible।', 'would be slow and inflexible'),
      gapItem('rl07-q14', ['humility'], 'Paragraph G: treat memories "with appropriate humility".', 'Paragraph G: "with appropriate humility" — উত্তর humility।', 'treat them with appropriate humility'),
    ], {
      title: 'Is reconstruction a weakness?',
      lines: [
        'A memory that stored every detail would be slow and [[rl07-q13]]. Keeping the general meaning helps the brain understand new situations. The writer advises treating our memories with appropriate [[rl07-q14]], because even vivid memories can be wrong.',
      ],
    }),
  ],
};
