import { NAMES_I, TFNG_I, TWO_I, abcd, gap, gapItem, lex, multi, named, q, select, v } from '../kit';
import type { LexEntry, LibraryPassage } from '../types';

export const LEX: LexEntry[] = [
  lex('latitude', 'noun', 'useful', 'the distance of a place north or south of the equator', 'অক্ষাংশ', 'Dhaka lies at a latitude of about 24 degrees north.', 'ঢাকা প্রায় ২৪ ডিগ্রি উত্তর অক্ষাংশে অবস্থিত।'),
  lex('longitude', 'noun', 'useful', 'the distance of a place east or west of a fixed line on the Earth', 'দ্রাঘিমাংশ', 'Sailors once found it very hard to measure longitude.', 'একসময় নাবিকদের জন্য দ্রাঘিমাংশ মাপা খুব কঠিন ছিল।'),
  lex('equator', 'noun', 'useful', 'the imaginary line around the middle of the Earth', 'বিষুবরেখা', 'Countries near the equator are hot all year.', 'বিষুবরেখার কাছের দেশগুলো সারা বছর গরম।'),
  lex('navigator', 'noun', 'useful', 'a person who plans the route of a ship or plane', 'নৌ-চালক / দিকনির্ণায়ক', 'The navigator checked the map every hour.', 'দিকনির্ণায়ক প্রতি ঘণ্টায় মানচিত্র দেখছিলেন।'),
  lex('supplies', 'noun', 'core', 'food, water and other things that people need', 'রসদ / প্রয়োজনীয় সামগ্রী', 'The hikers ran out of supplies after three days.', 'তিন দিন পরে পর্বতারোহীদের রসদ ফুরিয়ে গেল।', ['provisions', 'stores']),
  lex('wreck', 'verb', 'useful', 'to destroy a ship completely in an accident', '(জাহাজ) ধ্বংস হওয়া / ডুবে যাওয়া', 'The ship was wrecked in a storm.', 'ঝড়ে জাহাজটা ধ্বংস হয়ে যায়।', ['destroy', 'sink']),
  lex('in principle', 'phrase', 'useful', 'in theory, even if not yet in practice', 'তত্ত্বগতভাবে', 'In principle, the plan is simple, but it will be hard to do.', 'তত্ত্বগতভাবে পরিকল্পনাটা সহজ, কিন্তু বাস্তবায়ন কঠিন হবে।', ['in theory']),
  lex('correspond to', 'phrasal verb', 'useful', 'to be equal to or match something', 'সমান হওয়া / মিলে যাওয়া', 'Each colour on the map corresponds to a type of soil.', 'মানচিত্রের প্রতিটা রং এক ধরনের মাটির সাথে মেলে।', ['match', 'be equal to']),
  lex('reference point', 'noun', 'advanced', 'a fixed thing used to measure or compare other things', 'তুলনার ভিত্তিবিন্দু', 'The old clock tower is a useful reference point in the city.', 'পুরনো ঘড়িঘরটা শহরে একটা কাজের ভিত্তিবিন্দু।'),
  lex('observe', 'verb', 'core', 'to watch something carefully', 'পর্যবেক্ষণ করা', 'Scientists observed the birds for a year.', 'বিজ্ঞানীরা এক বছর পাখিগুলো পর্যবেক্ষণ করেছেন।', ['watch', 'study']),
  lex('despite', 'preposition', 'core', 'without being affected by something', 'সত্ত্বেও', 'Despite the rain, the match continued.', 'বৃষ্টি সত্ত্বেও খেলা চলতে থাকল।', ['in spite of']),
  lex('timekeeper', 'noun', 'advanced', 'a clock or watch that measures time', 'সময়রক্ষক যন্ত্র / ঘড়ি', 'The old timekeeper still runs perfectly.', 'পুরনো ঘড়িটা এখনো নিখুঁতভাবে চলে।'),
  lex('triumph', 'noun', 'useful', 'a great success', 'বিজয় / বড় সাফল্য', 'The new bridge was a triumph of engineering.', 'নতুন সেতুটা প্রকৌশলের এক বড় সাফল্য।', ['success', 'achievement']),
  lex('motion', 'noun', 'useful', 'the act of moving', 'গতি / নড়াচড়া', 'The motion of the bus made him sleepy.', 'বাসের দোলায় তাঁর ঘুম পেল।', ['movement']),
  lex('mechanics', 'noun', 'advanced', 'the science of how machines and moving parts work', 'বলবিদ্যা / যন্ত্রকৌশল', 'She studied the mechanics of old clocks.', 'তিনি পুরনো ঘড়ির যন্ত্রকৌশল নিয়ে পড়েছেন।'),
  lex('demand', 'verb', 'core', 'to need something such as time, skill or effort', 'দাবি করা / প্রয়োজন হওয়া', 'This job demands a lot of patience.', 'এই কাজে অনেক ধৈর্য লাগে।', ['require', 'need']),
  lex('urgency', 'noun', 'useful', 'the need to deal with something quickly', 'জরুরি অবস্থা / তাড়া', 'The flood added urgency to the plan.', 'বন্যা পরিকল্পনাটার জরুরি প্রয়োজন বাড়িয়ে দিয়েছে।'),
  lex('illustrate', 'verb', 'useful', 'to show or explain something by giving an example', 'উদাহরণ দিয়ে দেখানো', 'The accident illustrates the need for better roads.', 'দুর্ঘটনাটা ভালো রাস্তার প্রয়োজনীয়তা দেখিয়ে দেয়।', ['show', 'demonstrate']),
  lex('enormous', 'adjective', 'core', 'extremely large', 'বিশাল', 'The project cost an enormous amount of money.', 'প্রকল্পটায় বিশাল অঙ্কের টাকা খরচ হয়েছে।', ['huge', 'vast']),
  lex('establish', 'verb', 'core', 'to start an organisation or system that will last', 'প্রতিষ্ঠা করা', 'The university was established in 1921.', 'বিশ্ববিদ্যালয়টা ১৯২১ সালে প্রতিষ্ঠিত।', ['set up', 'found']),
  lex('unlikely', 'adjective', 'core', 'not expected; probably not true or not going to happen', 'অপ্রত্যাশিত / অসম্ভাব্য', 'Help came from an unlikely source.', 'সাহায্য এল এক অপ্রত্যাশিত জায়গা থেকে।', ['improbable', 'unexpected']),
  lex('self-taught', 'adjective', 'useful', 'having learned a skill without a teacher', 'স্বশিক্ষিত', 'He is a self-taught programmer.', 'তিনি একজন স্বশিক্ষিত প্রোগ্রামার।'),
  lex('refined', 'adjective', 'advanced', 'improved by small, careful changes', 'পরিমার্জিত', 'Each new model was more refined than the last.', 'প্রতিটা নতুন মডেল আগেরটার চেয়ে বেশি পরিমার্জিত।', ['improved', 'polished']),
  lex('ingenious', 'adjective', 'advanced', 'very clever and original', 'উদ্ভাবনী / বুদ্ধিদীপ্ত', 'She found an ingenious way to save water.', 'তিনি পানি বাঁচানোর একটা বুদ্ধিদীপ্ত উপায় বের করেছেন।', ['clever', 'inventive']),
  lex('friction', 'noun', 'useful', 'the force that slows down things rubbing against each other', 'ঘর্ষণ', 'Oil reduces friction between moving parts.', 'তেল চলমান অংশগুলোর ঘর্ষণ কমায়।'),
  lex('compensate for', 'phrasal verb', 'advanced', 'to balance or reduce the bad effect of something', 'পুষিয়ে দেওয়া / ক্ষতিপূরণ করা', 'Hard work can compensate for a lack of experience.', 'কঠোর পরিশ্রম অভিজ্ঞতার অভাব পুষিয়ে দিতে পারে।', ['make up for', 'offset']),
  lex('voyage', 'noun', 'useful', 'a long journey, especially by sea', 'সমুদ্রযাত্রা', 'The voyage to India took six months.', 'ভারতে সমুদ্রযাত্রায় ছয় মাস লেগেছিল।', ['journey', 'sea trip']),
  lex('favour', 'verb', 'useful', 'to prefer or support one idea or person', 'পছন্দ করা / সমর্থন করা', 'Most teachers favour the new timetable.', 'বেশিরভাগ শিক্ষক নতুন সময়সূচি সমর্থন করেন।', ['prefer', 'support']),
  lex('insist on', 'phrasal verb', 'useful', 'to demand firmly that something must happen', 'জোর দেওয়া / জেদ ধরা', 'The doctor insisted on more tests.', 'ডাক্তার আরও পরীক্ষার ওপর জোর দিলেন।'),
  lex('trial', 'noun', 'useful', 'a test of how well something works', 'পরীক্ষামূলক প্রয়োগ', 'The new medicine is still in trials.', 'নতুন ওষুধটা এখনো পরীক্ষামূলক পর্যায়ে।', ['test', 'experiment']),
  lex('reproduce', 'verb', 'useful', 'to make a copy of something', 'পুনরায় তৈরি করা / নকল করা', 'Other labs could not reproduce the results.', 'অন্য ল্যাবগুলো ফলটা পুনরায় পেতে পারেনি।', ['copy', 'duplicate']),
  lex('elderly', 'adjective', 'useful', 'old (a polite word)', 'বয়স্ক', 'The bus has seats for elderly passengers.', 'বাসে বয়স্ক যাত্রীদের জন্য আসন আছে।', ['old', 'aged']),
  lex('grant', 'verb', 'useful', 'to give something officially, such as money or permission', 'প্রদান করা / মঞ্জুর করা', 'The university granted her a scholarship.', 'বিশ্ববিদ্যালয় তাঁকে একটা বৃত্তি প্রদান করেছে।', ['give', 'award']),
  lex('formally', 'adverb', 'useful', 'officially', 'আনুষ্ঠানিকভাবে', 'The results will be formally announced tomorrow.', 'ফলাফল কাল আনুষ্ঠানিকভাবে ঘোষণা করা হবে।', ['officially']),
  lex('confidence', 'noun', 'core', 'trust in someone or something', 'আস্থা / আত্মবিশ্বাস', 'Customers lost confidence in the bank.', 'গ্রাহকরা ব্যাংকটার ওপর আস্থা হারালেন।', ['trust', 'faith']),
];

export const PASSAGE: LibraryPassage = {
  id: 'rl-08-longitude',
  title: 'The Race to Measure Longitude',
  topic: 'History',
  level: 'intermediate',
  minutes: 20,
  background: 'Well-documented history: the 1707 Scilly naval disaster, the Longitude Act of 1714, John Harrison’s sea clocks (H4, 1759), Nevil Maskelyne and the lunar-distance method, and Captain Cook’s use of a copy of H4.',
  paragraphs: [
    'By the seventeenth century, European sailors could cross oceans with growing confidence, but they could not be sure exactly where they were. Latitude, a ship’s position north or south of the equator, could be calculated fairly easily by measuring the height of the sun at midday or of certain stars at night. Longitude, the position east or west, was a different matter. Without it, navigators relied on estimates of speed and direction, and errors of many kilometres were common. Ships ran out of supplies while searching for islands, and others were wrecked on coasts they believed to be far away.',
    'In principle, the solution was simple. Because the Earth turns through 360 degrees in 24 hours, every hour of difference between local time and the time at a fixed reference point corresponds to fifteen degrees of longitude. Local time could be found by observing the sun. The difficulty lay in knowing the time at the reference point, such as the ship’s home port, after weeks at sea. That required a clock that kept accurate time despite the rolling of the ship, changes in temperature and the damp, salty air.',
    'The best timekeepers of the age could not meet this challenge. The pendulum clock, invented by the Dutch scientist Christiaan Huygens in the 1650s, was a triumph on land, but its pendulum was thrown off by the motion of the waves. Many scientists therefore believed that the answer lay not in mechanics but in the sky. They proposed that sailors could use the position of the moon against the background of the stars as a kind of natural clock, although the method demanded careful observation, accurate tables and long calculations.',
    'The urgency of the problem was dramatically illustrated in 1707, when several British warships struck rocks off the Isles of Scilly and more than a thousand sailors lost their lives. Seven years later, the British Parliament passed the Longitude Act, offering a reward of up to £20,000, an enormous sum at the time, for a practical method of determining longitude at sea. A committee, later known as the Board of Longitude, was established to judge the proposals.',
    'The most famous response came from an unlikely source. John Harrison was a self-taught carpenter and clockmaker from the north of England with no university education. Over several decades he built a series of increasingly refined sea clocks, using ingenious designs to reduce friction and to compensate for changes in temperature. His fourth timekeeper, completed in 1759, looked like a large pocket watch. On a voyage to Jamaica in 1761 and 1762, it kept time with remarkable accuracy, well within the terms of the Act.',
    'Harrison’s reward, however, was slow to arrive. Members of the Board, several of whom favoured the astronomical method, insisted on further trials and demanded that others should be able to reproduce his design. Among that method’s leading supporters was Nevil Maskelyne, who became Astronomer Royal in 1765 and began publishing tables that made the lunar calculations far quicker. Harrison, by then elderly, came to believe that the Board was treating him unfairly. In 1773, after King George III took a personal interest in his case, Parliament granted him a substantial payment, although he never formally received the prize itself.',
    'In the end, both approaches proved valuable. Lunar tables remained in use for decades because early marine clocks were expensive, while copies of Harrison’s design gradually won the confidence of navigators. Captain James Cook carried one on his second voyage to the Pacific and praised it highly. By the nineteenth century, as manufacturing improved and prices fell, the marine chronometer had become standard equipment on ocean-going ships.',
  ],
  vocab: [
    v('confidence', 'confidence', 'trust in their ability or in a device', 'এখানে নাবিকদের সামর্থ্য বা যন্ত্রের ওপর আস্থা।'),
    v('latitude', 'Latitude', 'position north or south', 'এখানে উত্তর-দক্ষিণ অবস্থান — অক্ষাংশ।'),
    v('equator', 'equator', 'the line around the middle of the Earth', 'এখানে পৃথিবীর মাঝখানের কাল্পনিক রেখা।'),
    v('longitude', 'Longitude', 'position east or west', 'এখানে পূর্ব-পশ্চিম অবস্থান — দ্রাঘিমাংশ।'),
    v('navigator', 'navigators', 'people who work out a ship’s route', 'এখানে যারা জাহাজের পথ নির্ধারণ করেন।'),
    v('rely on', 'relied on', 'had to depend on', 'এখানে নির্ভর করতে হতো।'),
    v('estimate', 'estimates', 'rough calculations', 'এখানে মোটামুটি হিসাব।'),
    v('supplies', 'supplies', 'food and water on board', 'এখানে জাহাজের খাবার ও পানি — রসদ।'),
    v('wreck', 'wrecked', 'destroyed on the rocks', 'এখানে পাথরে ধাক্কা লেগে ধ্বংস।'),
    v('in principle', 'In principle', 'in theory', 'এখানে তত্ত্বগতভাবে — বাস্তবে কঠিন হলেও।'),
    v('correspond to', 'corresponds to', 'is equal to', 'এখানে সমান।'),
    v('reference point', 'reference point', 'the fixed place whose time is known, such as the home port', 'এখানে যে নির্দিষ্ট জায়গার সময় জানা, যেমন নিজের বন্দর।'),
    v('observe', 'observing', 'watching the sun', 'এখানে সূর্য পর্যবেক্ষণ।'),
    v('accurate', 'accurate', 'correct', 'এখানে সঠিক সময়।'),
    v('despite', 'despite', 'even with the rolling and damp', 'এখানে দোলা আর আর্দ্রতা সত্ত্বেও।'),
    v('timekeeper', ['timekeepers', 'timekeeper'], 'clocks', 'এখানে ঘড়ি।'),
    v('triumph', 'triumph', 'a great success', 'এখানে বড় সাফল্য।'),
    v('motion', 'motion', 'the movement of the waves', 'এখানে ঢেউয়ের নড়াচড়া।'),
    v('mechanics', 'mechanics', 'machines such as clocks', 'এখানে ঘড়ির মত যন্ত্রকৌশল।'),
    v('propose', 'proposed', 'suggested', 'এখানে প্রস্তাব দিলেন।'),
    v('demand', ['demanded'], 'needed; (the Board) insisted on', 'এখানে পদ্ধতিটার জন্য দরকার ছিল; Board-এর ক্ষেত্রে দাবি করল।'),
    v('urgency', 'urgency', 'how serious and pressing the problem was', 'এখানে সমস্যাটা কতটা জরুরি।'),
    v('illustrate', 'illustrated', 'shown by an example', 'এখানে একটা ঘটনা দিয়ে স্পষ্ট হলো।'),
    v('enormous', 'enormous', 'extremely large', 'এখানে তখনকার দিনে বিশাল অঙ্ক।'),
    v('practical', 'practical', 'usable at sea', 'এখানে সমুদ্রে ব্যবহারযোগ্য।'),
    v('determine', 'determining', 'finding out', 'এখানে বের করা / নির্ণয় করা।', { en: 'to find out something exactly', bn: 'নির্ণয় করা' }),
    v('establish', 'established', 'set up', 'এখানে গঠন করা হলো।'),
    v('unlikely', 'unlikely', 'unexpected', 'এখানে অপ্রত্যাশিত জায়গা থেকে।'),
    v('self-taught', 'self-taught', 'he learned without formal teaching', 'এখানে তিনি নিজে নিজে শিখেছিলেন।'),
    v('refined', 'refined', 'each clock better than the last', 'এখানে প্রতিটা ঘড়ি আগেরটার চেয়ে উন্নত।'),
    v('ingenious', 'ingenious', 'very clever', 'এখানে খুব বুদ্ধিদীপ্ত নকশা।'),
    v('friction', 'friction', 'rubbing that slows moving parts', 'এখানে চলমান অংশের ঘর্ষণ।'),
    v('compensate for', 'compensate for', 'cancel out the effect of', 'এখানে প্রভাবটা পুষিয়ে দেওয়া।'),
    v('voyage', 'voyage', 'a long sea journey', 'এখানে দীর্ঘ সমুদ্রযাত্রা।'),
    v('favour', 'favoured', 'preferred', 'এখানে পছন্দ করতেন।'),
    v('insist on', 'insisted on', 'firmly demanded', 'এখানে জোর দিয়ে দাবি করলেন।'),
    v('trial', 'trials', 'tests at sea', 'এখানে সমুদ্রে পরীক্ষা।'),
    v('reproduce', 'reproduce', 'make copies of', 'এখানে নকশাটা অন্যরাও তৈরি করতে পারা।'),
    v('elderly', 'elderly', 'old', 'এখানে বৃদ্ধ।'),
    v('grant', 'granted', 'officially gave', 'এখানে আনুষ্ঠানিকভাবে দিল।'),
    v('substantial', 'substantial', 'large', 'এখানে বড় অঙ্কের।'),
    v('formally', 'formally', 'officially', 'এখানে আনুষ্ঠানিকভাবে।'),
    v('gradually', 'gradually', 'slowly, over time', 'এখানে ধীরে ধীরে।'),
    v('standard', 'standard', 'normal, expected on every ship', 'এখানে প্রতিটা জাহাজে স্বাভাবিকভাবে থাকা।', { en: 'normal and usual', bn: 'প্রচলিত / আদর্শ' }),
    v('equipment', 'equipment', 'instruments carried on ships', 'এখানে জাহাজের যন্ত্রপাতি।'),
  ],
  groups: [
    select('names', NAMES_I, [
      q('rl08-q1', 'had no university education', 'B', 'Paragraph E: Harrison was "self-taught … with no university education".', 'Paragraph E: Harrison স্বশিক্ষিত, বিশ্ববিদ্যালয়ে পড়েননি — B।', 'with no university education'),
      q('rl08-q2', 'published tables that made calculations much faster', 'C', 'Paragraph F: Maskelyne "began publishing tables that made the lunar calculations far quicker".', 'Paragraph F: Maskelyne-এর table হিসাব অনেক দ্রুত করে — C।', 'began publishing tables that made the lunar calculations far quicker'),
      q('rl08-q3', 'spoke very positively about a copy of Harrison’s design', 'D', 'Paragraph G: Cook "carried one on his second voyage … and praised it highly".', 'Paragraph G: Cook একটা কপি নিয়ে গিয়ে উচ্চ প্রশংসা করেন — D।', 'praised it highly'),
      q('rl08-q4', 'invented a clock that did not work well at sea', 'A', 'Paragraph C: Huygens’s pendulum clock "was thrown off by the motion of the waves".', 'Paragraph C: Huygens-এর pendulum ঘড়ি ঢেউয়ে ঠিক চলত না — A।', 'its pendulum was thrown off by the motion of the waves'),
    ], named('Christiaan Huygens', 'John Harrison', 'Nevil Maskelyne', 'James Cook')),
    select('tfng', TFNG_I, [
      q('rl08-q5', 'Finding latitude at sea was easier than finding longitude.', 'TRUE', 'Paragraph A: latitude "could be calculated fairly easily"; longitude "was a different matter".', 'Paragraph A: অক্ষাংশ তুলনামূলক সহজে হিসাব করা যেত, দ্রাঘিমাংশ নয় — TRUE।', 'could be calculated fairly easily'),
      q('rl08-q6', 'The ships lost in 1707 were carrying no maps.', 'NOT GIVEN', 'Paragraph D describes the disaster but not what the ships carried.', 'Paragraph D দুর্ঘটনার কথা বলে, কিন্তু জাহাজে মানচিত্র ছিল কি না বলে না — NOT GIVEN।'),
      q('rl08-q7', 'The reward offered by the Longitude Act was a modest amount of money.', 'FALSE', 'Paragraph D: £20,000 was "an enormous sum at the time".', 'Paragraph D: "an enormous sum" — modest (সামান্য)-এর বিপরীত, FALSE।', 'an enormous sum at the time'),
      q('rl08-q8', 'Some members of the Board preferred the method based on the moon and stars.', 'TRUE', 'Paragraph F: "several of whom favoured the astronomical method".', 'Paragraph F: কয়েকজন সদস্য astronomical পদ্ধতি পছন্দ করতেন — preferred = favoured, TRUE।', 'several of whom favoured the astronomical method'),
    ]),
    gap('sentence', 2, [
      gapItem('rl08-q9', ['fifteen degrees', '15 degrees'], 'Paragraph B: every hour of difference "corresponds to fifteen degrees of longitude".', 'Paragraph B: "corresponds to fifteen degrees" — উত্তর fifteen degrees।', 'corresponds to fifteen degrees of longitude', 'One hour of difference in time is equal to ___ of longitude.'),
      gapItem('rl08-q10', ['friction'], 'Paragraph E: designs "to reduce friction and to compensate for changes in temperature".', 'Paragraph E: "to reduce friction" — উত্তর friction।', 'to reduce friction', 'Harrison’s clever designs helped to reduce ___ and to balance the effects of temperature.'),
      gapItem('rl08-q11', ['standard equipment'], 'Paragraph G: the marine chronometer "had become standard equipment on ocean-going ships".', 'Paragraph G: "had become standard equipment" — উত্তর standard equipment।', 'had become standard equipment', 'By the nineteenth century, the marine chronometer was ___ on ocean-going ships.'),
    ]),
    multi('rl08-q12', TWO_I, 'Which TWO problems did a clock at sea have to overcome, according to paragraph B?', abcd('the rolling of the ship', 'long, dark nights', 'changes in temperature', 'the weight of the cargo', 'a lack of trained sailors'), ['A', 'C'], 'Paragraph B: the clock had to keep time "despite the rolling of the ship, changes in temperature and the damp, salty air".', 'Paragraph B: জাহাজের দোলা (A) আর তাপমাত্রার পরিবর্তন (C) — অন্য option-গুলোর কথা নেই।', 'despite the rolling of the ship, changes in temperature'),
  ],
};
