import { HEAD_I, MCQ_I, TFNG_I, abcd, gap, gapItem, headings, lex, q, select, v } from '../kit';
import type { LexEntry, LibraryPassage } from '../types';

export const LEX: LexEntry[] = [
  lex('coastline', 'noun', 'useful', 'the land along the edge of the sea', 'উপকূলরেখা', 'Bangladesh has a long coastline on the Bay of Bengal.', 'বঙ্গোপসাগরে বাংলাদেশের দীর্ঘ উপকূলরেখা আছে।', ['coast', 'shore']),
  lex('species', 'noun', 'core', 'a group of animals or plants of the same type', 'প্রজাতি', 'Many species of birds live in the forest.', 'বনে অনেক প্রজাতির পাখি বাস করে।'),
  lex('shrub', 'noun', 'useful', 'a small, low plant with woody stems; a bush', 'গুল্ম / ঝোপ', 'Small shrubs grow along the path.', 'পথের ধারে ছোট ছোট ঝোপ জন্মায়।', ['bush']),
  lex('intertidal', 'adjective', 'advanced', 'between the high and low levels of the sea', 'জোয়ার-ভাটার মধ্যবর্তী', 'Crabs live in the intertidal zone.', 'কাঁকড়া জোয়ার-ভাটার মধ্যবর্তী এলাকায় বাস করে।'),
  lex('tide', 'noun', 'useful', 'the regular rise and fall of the sea', 'জোয়ার-ভাটা', 'At high tide the beach disappears.', 'জোয়ারের সময় সৈকতটা ডুবে যায়।'),
  lex('tolerate', 'verb', 'useful', 'to be able to survive difficult conditions', 'সহ্য করা', 'Some plants can tolerate very dry soil.', 'কিছু গাছ খুব শুকনো মাটি সহ্য করতে পারে।', ['withstand', 'bear']),
  lex('let alone', 'phrase', 'advanced', 'used to show that something is even less likely than the first thing', 'তো দূরের কথা', 'He can’t cook rice, let alone a full meal.', 'তিনি ভাতই রাঁধতে পারেন না, পুরো খাবার তো দূরের কথা।'),
  lex('adaptation', 'noun', 'useful', 'a feature that helps a living thing survive in its environment', 'অভিযোজন', 'Thick fur is an adaptation to the cold.', 'ঘন লোম ঠান্ডার সাথে অভিযোজন।'),
  lex('waterlogged', 'adjective', 'advanced', 'so full of water that no more can be absorbed', 'জলাবদ্ধ / পানিতে ভেজা', 'The football pitch was waterlogged after the rain.', 'বৃষ্টির পরে ফুটবল মাঠটা জলাবদ্ধ ছিল।'),
  lex('specialised', 'adjective', 'useful', 'designed or developed for one particular purpose', 'বিশেষায়িত', 'Divers need specialised equipment.', 'ডুবুরিদের বিশেষায়িত সরঞ্জাম দরকার।', ['specific']),
  lex('stable', 'adjective', 'core', 'firmly fixed; not likely to move or change', 'স্থিতিশীল / মজবুত', 'Make sure the ladder is stable before you climb.', 'ওঠার আগে নিশ্চিত হোন মইটা মজবুতভাবে বসানো।', ['steady', 'secure']),
  lex('cope with', 'phrasal verb', 'core', 'to deal successfully with a difficult situation', 'সামলানো / মোকাবিলা করা', 'Students must cope with a lot of pressure.', 'শিক্ষার্থীদের অনেক চাপ সামলাতে হয়।', ['deal with', 'manage']),
  lex('filter', 'verb', 'useful', 'to remove unwanted substances from a liquid or gas', 'ছেঁকে নেওয়া / পরিশোধন করা', 'The machine filters the water before we drink it.', 'যন্ত্রটা পান করার আগে পানি পরিশোধন করে।'),
  lex('excess', 'adjective / noun', 'useful', 'more than is needed or allowed', 'অতিরিক্ত', 'Excess sugar is stored as fat.', 'অতিরিক্ত চিনি চর্বি হিসেবে জমা হয়।', ['extra', 'surplus']),
  lex('dense', 'adjective', 'useful', 'closely packed together; thick', 'ঘন', 'The village is surrounded by dense forest.', 'গ্রামটা ঘন বনে ঘেরা।', ['thick', 'compact']),
  lex('network', 'noun', 'core', 'a large system of connected lines or parts', 'জাল / নেটওয়ার্ক', 'The city has a good network of roads.', 'শহরটায় রাস্তার ভালো নেটওয়ার্ক আছে।', ['system', 'web']),
  lex('trap', 'verb', 'useful', 'to catch and hold something so it cannot escape', 'আটকে রাখা', 'The walls trap heat inside the house.', 'দেয়ালগুলো ঘরের ভেতরে তাপ আটকে রাখে।', ['catch', 'hold']),
  lex('sediment', 'noun', 'advanced', 'sand, mud and small stones carried and dropped by water', 'পলি', 'The river carries sediment down to the sea.', 'নদী পলি বয়ে সমুদ্রে নিয়ে যায়।', ['silt']),
  lex('overwhelm', 'verb', 'useful', 'to be too strong or too great for something', 'অভিভূত করা / ছাপিয়ে যাওয়া', 'The flood overwhelmed the town’s defences.', 'বন্যা শহরের সুরক্ষাব্যবস্থা ছাপিয়ে গেল।', ['overpower', 'swamp']),
  lex('defence', 'noun', 'core', 'protection against attack or harm', 'প্রতিরক্ষা / সুরক্ষা', 'Trees are a natural defence against wind.', 'গাছ বাতাসের বিরুদ্ধে প্রাকৃতিক সুরক্ষা।', ['protection']),
  lex('boundary', 'noun', 'useful', 'the edge or limit of an area', 'সীমানা', 'The river forms the boundary between the two districts.', 'নদীটা দুই জেলার মধ্যে সীমানা তৈরি করেছে।', ['border', 'edge']),
  lex('sheltered', 'adjective', 'useful', 'protected from wind, rain or waves', 'সুরক্ষিত / আড়ালে থাকা', 'Boats wait in a sheltered bay during storms.', 'ঝড়ের সময় নৌকাগুলো সুরক্ষিত উপসাগরে অপেক্ষা করে।', ['protected']),
  lex('nursery', 'noun', 'useful', 'a place where young children are looked after', 'শিশুসদন / নার্সারি', 'Her son goes to a nursery near the office.', 'তাঁর ছেলে অফিসের কাছের একটা শিশুসদনে যায়।'),
  lex('stretch across', 'phrasal verb', 'useful', 'to cover a large area from one side to another', 'বিস্তৃত থাকা', 'The desert stretches across three countries.', 'মরুভূমিটা তিনটা দেশজুড়ে বিস্তৃত।', ['extend across', 'span']),
  lex('draw attention to', 'phrase', 'useful', 'to make people notice something', 'দৃষ্টি আকর্ষণ করা', 'The report draws attention to air pollution.', 'প্রতিবেদনটা বায়ুদূষণের দিকে দৃষ্টি আকর্ষণ করে।', ['highlight']),
  lex('visible', 'adjective', 'core', 'able to be seen', 'দৃশ্যমান', 'The mountain is visible from the city.', 'শহর থেকে পাহাড়টা দেখা যায়।', ['noticeable']),
  lex('bury', 'verb', 'useful', 'to put or keep something under the ground', 'মাটিচাপা দেওয়া / পুঁতে রাখা', 'The old coins were buried under the house.', 'পুরনো মুদ্রাগুলো বাড়ির নিচে পুঁতে রাখা ছিল।'),
  lex('store', 'verb', 'core', 'to keep something to use later', 'সংরক্ষণ করা / জমা রাখা', 'We store rice in large tins.', 'আমরা বড় টিনে চাল জমা রাখি।', ['keep', 'hold']),
  lex('clear', 'verb', 'core', 'to remove things from a place', 'পরিষ্কার করা / সরিয়ে ফেলা', 'Please clear the table after dinner.', 'রাতের খাবারের পরে টেবিলটা পরিষ্কার করে দিন।'),
  lex('release', 'verb', 'core', 'to let something go or come out', 'ছেড়ে দেওয়া / নির্গত করা', 'Cars release harmful gases into the air.', 'গাড়ি বাতাসে ক্ষতিকর গ্যাস নির্গত করে।', ['emit', 'let out']),
  lex('atmosphere', 'noun', 'core', 'the layer of gases around the Earth', 'বায়ুমণ্ডল', 'Carbon dioxide traps heat in the atmosphere.', 'কার্বন ডাই-অক্সাইড বায়ুমণ্ডলে তাপ আটকে রাখে।'),
  lex('conservation', 'noun', 'core', 'the protection of nature and wildlife', 'সংরক্ষণ', 'The group works on forest conservation.', 'দলটা বন সংরক্ষণে কাজ করে।', ['protection', 'preservation']),
  lex('respond', 'verb', 'core', 'to react to something by doing something', 'প্রতিক্রিয়া দেখানো / সাড়া দেওয়া', 'The city responded to the flood by building new walls.', 'বন্যার প্রতিক্রিয়ায় শহরটা নতুন বাঁধ তৈরি করেছে।', ['react', 'answer']),
  lex('mixed', 'adjective', 'useful', 'partly good and partly bad', 'মিশ্র', 'The film received mixed reviews.', 'ছবিটা মিশ্র প্রতিক্রিয়া পেয়েছে।'),
  lex('restoration', 'noun', 'useful', 'the act of returning something to its earlier good condition', 'পুনরুদ্ধার', 'The restoration of the old mosque took years.', 'পুরনো মসজিদটার পুনরুদ্ধারে কয়েক বছর লেগেছে।', ['repair', 'renewal']),
  lex('restore', 'verb', 'useful', 'to bring something back to its earlier condition', 'পুনরুদ্ধার করা / আগের অবস্থায় ফেরানো', 'Engineers restored the power after the storm.', 'ঝড়ের পরে প্রকৌশলীরা বিদ্যুৎ পুনরুদ্ধার করেছেন।', ['repair', 'bring back']),
  lex('infrastructure', 'noun', 'useful', 'the basic systems a society needs, such as roads, bridges and power supplies', 'অবকাঠামো', 'The country is investing in new infrastructure.', 'দেশটা নতুন অবকাঠামোয় বিনিয়োগ করছে।'),
  lex('willing', 'adjective', 'core', 'happy or ready to do something', 'ইচ্ছুক', 'Are you willing to work at weekends?', 'আপনি কি সপ্তাহান্তে কাজ করতে ইচ্ছুক?', ['ready', 'prepared']),
];

export const PASSAGE: LibraryPassage = {
  id: 'rl-09-mangroves',
  title: 'Forests with Their Feet in the Sea',
  topic: 'Environment',
  level: 'intermediate',
  minutes: 20,
  background: 'General, well-established ecology of mangroves: adaptations, coastal protection, fish nurseries and "blue carbon" storage; the Sundarbans is the largest mangrove forest, shared by Bangladesh and India.',
  paragraphs: [
    'Along many tropical coastlines, where rivers meet the sea, there are forests that stand with their roots in salt water. Mangroves are not a single species but a group of trees and shrubs that share an unusual ability: they can survive in the salty, oxygen-poor mud of the intertidal zone, the strip of shore that is covered by the sea at high tide and exposed at low tide. Few other trees could tolerate such conditions for a single season, let alone for centuries.',
    'Their survival depends on a range of remarkable adaptations. Because waterlogged mud contains little oxygen, many mangroves produce specialised roots that grow upwards out of the mud like pencils, allowing the tree to take in air at low tide. Others are supported by curved "prop" roots that arch down from the trunk, keeping the tree stable in soft ground. Mangroves also cope with salt in different ways: some filter most of it out at the roots, while others remove excess salt through their leaves, which can sometimes be seen glittering with tiny crystals.',
    'For people living on the coast, the most obvious value of mangroves is protection. The dense network of roots and trunks slows the movement of water, reducing the energy of waves and trapping sediment that would otherwise be washed away. During storms, a wide belt of healthy mangroves can lower the height of incoming water and reduce damage to the villages behind it. This protection is not unlimited, however: extremely powerful storms can overwhelm even large forests, and a narrow strip of trees offers far less defence than a wide one.',
    'Mangroves also support life far beyond their own boundaries. The sheltered water among their roots acts as a nursery for young fish, crabs and shrimp, many of which later move to open water, where they are caught by fishing communities. Birds nest in the branches, and larger animals use the forests as hunting grounds. The Sundarbans, which stretches across the border between Bangladesh and India and is the largest mangrove forest in the world, is famous as a home of the Bengal tiger.',
    'In recent years, scientists have drawn attention to a less visible benefit. Mangrove soils are waterlogged, so dead leaves and roots decompose very slowly, and the carbon they contain can remain buried for centuries. Measured per hectare, some mangrove forests store more carbon than many tropical forests on land, most of it in the soil rather than in the trees. When mangroves are cleared, much of this carbon can be released into the atmosphere, adding to the problem of climate change.',
    'Despite these benefits, a large share of the world’s mangroves has been lost in recent decades, cleared for shrimp farms, agriculture, timber and coastal construction. Governments and conservation groups have responded with large planting programmes, but the results have been mixed. In some projects, millions of seedlings were planted on mudflats where the water was too deep for too long, and most of them died. Researchers have found that restoration is more likely to succeed when it begins with the conditions rather than the trees: if the natural flow of tides and fresh water is restored, mangroves often return on their own, and local communities that depend on the forests are more willing to protect them.',
    'The value of mangroves is increasingly recognised in economic terms as well. Studies that estimate the cost of building sea walls, replacing lost fisheries or reducing carbon emissions by other means often conclude that keeping existing forests is far cheaper than repairing the damage caused by their loss. For this reason, some coastal planners now describe mangroves not as empty land waiting to be developed but as natural infrastructure, as valuable in its own way as a road or a harbour.',
  ],
  vocab: [
    v('coastline', 'coastlines', 'the edges of the land beside the sea', 'এখানে সমুদ্রের পাশের ভূমির প্রান্ত — উপকূলরেখা।'),
    v('species', 'species', 'one type of tree', 'এখানে এক প্রজাতির গাছ।'),
    v('shrub', 'shrubs', 'bushes', 'এখানে ঝোপ জাতীয় গাছ।'),
    v('survive', 'survive', 'stay alive', 'এখানে বেঁচে থাকা।'),
    v('intertidal', 'intertidal', 'between high and low tide', 'এখানে জোয়ার আর ভাটার মাঝের এলাকা।'),
    v('tide', 'tide', 'the level of the sea as it rises and falls', 'এখানে সমুদ্রের ওঠানামা — জোয়ার-ভাটা।'),
    v('tolerate', 'tolerate', 'survive in', 'এখানে এমন কঠিন অবস্থায় টিকে থাকা।'),
    v('let alone', 'let alone', 'and certainly not', 'এখানে এক মৌসুমই পারে না, শতাব্দী তো দূরের কথা।'),
    v('adaptation', 'adaptations', 'special features for this environment', 'এখানে এই পরিবেশে টিকে থাকার বিশেষ বৈশিষ্ট্য।'),
    v('waterlogged', 'waterlogged', 'full of water', 'এখানে পানিতে ভরা মাটি।'),
    v('specialised', 'specialised', 'developed for one job', 'এখানে নির্দিষ্ট কাজের জন্য তৈরি শিকড়।'),
    v('stable', 'stable', 'steady, not falling over', 'এখানে না পড়ে মজবুতভাবে দাঁড়িয়ে থাকা।'),
    v('cope with', 'cope with', 'deal with', 'এখানে লবণ সামলানো।'),
    v('filter', 'filter', 'remove salt as water enters the roots', 'এখানে শিকড় দিয়ে ঢোকার সময় লবণ ছেঁকে ফেলা।'),
    v('excess', 'excess', 'extra salt the tree does not need', 'এখানে গাছের দরকারের চেয়ে বেশি লবণ।'),
    v('obvious', 'obvious', 'easy to see', 'এখানে সহজে চোখে পড়ে এমন।'),
    v('dense', 'dense', 'thick, closely packed', 'এখানে ঘন করে জড়ানো।'),
    v('network', 'network', 'many connected roots', 'এখানে পরস্পর জড়ানো অনেক শিকড়।'),
    v('trap', 'trapping', 'catching and holding', 'এখানে পলি ধরে রাখা।'),
    v('sediment', 'sediment', 'mud and sand carried by water', 'এখানে পানিতে বয়ে আসা কাদা-বালি — পলি।'),
    v('overwhelm', 'overwhelm', 'be too strong for', 'এখানে বনের সহ্যক্ষমতা ছাপিয়ে যাওয়া।'),
    v('defence', 'defence', 'protection', 'এখানে সুরক্ষা।'),
    v('boundary', 'boundaries', 'the edges of the forest', 'এখানে বনের সীমানা।'),
    v('sheltered', 'sheltered', 'protected from waves', 'এখানে ঢেউ থেকে সুরক্ষিত।'),
    v('nursery', 'nursery', 'a safe place where young fish grow', 'এখানে ছোট মাছ বড় হওয়ার নিরাপদ জায়গা।', { en: 'a place where young animals or plants grow before they move elsewhere', bn: 'ছোট প্রাণী বা চারা বেড়ে ওঠার জায়গা' }),
    v('stretch across', 'stretches across', 'covers land on both sides of the border', 'এখানে সীমান্তের দুই পাশজুড়ে বিস্তৃত।'),
    v('draw attention to', 'drawn attention to', 'made people notice', 'এখানে মানুষের দৃষ্টি আকর্ষণ করেছেন।'),
    v('visible', 'visible', 'easy to see', 'এখানে চোখে পড়ে এমন — এই উপকার চোখে কম পড়ে।'),
    v('benefit', ['benefit', 'benefits'], 'advantage', 'এখানে উপকার।'),
    v('decompose', 'decompose', 'rot', 'এখানে পচে যাওয়া।'),
    v('bury', 'buried', 'kept under the ground', 'এখানে মাটির নিচে জমা থাকা।'),
    v('store', 'store', 'hold and keep', 'এখানে কার্বন জমিয়ে রাখা।'),
    v('clear', 'cleared', 'cut down and removed', 'এখানে গাছ কেটে ফেলা।', { en: 'to remove trees or plants from an area of land', bn: '(বন) কেটে সাফ করা' }),
    v('release', 'released', 'let out', 'এখানে বাতাসে ছেড়ে দেওয়া।'),
    v('atmosphere', 'atmosphere', 'the air around the Earth', 'এখানে পৃথিবীর বায়ুমণ্ডল।'),
    v('despite', 'Despite', 'even though there are these benefits', 'এখানে এত উপকার সত্ত্বেও।'),
    v('conservation', 'conservation', 'protecting nature', 'এখানে প্রকৃতি রক্ষা।'),
    v('respond', 'responded', 'reacted', 'এখানে প্রতিক্রিয়া হিসেবে পদক্ষেপ নিয়েছে।'),
    v('mixed', 'mixed', 'some good, some bad', 'এখানে কিছু ভালো, কিছু খারাপ।'),
    v('seedling', 'seedlings', 'young trees', 'এখানে ছোট চারা গাছ।'),
    v('restoration', 'restoration', 'bringing the forest back', 'এখানে বন আগের অবস্থায় ফেরানো।'),
    v('restore', 'restored', 'brought back', 'এখানে স্বাভাবিক পানিপ্রবাহ ফিরিয়ে আনা।'),
    v('willing', 'willing', 'ready to', 'এখানে রক্ষা করতে ইচ্ছুক।'),
    v('estimate', 'estimate', 'calculate roughly', 'এখানে খরচের আনুমানিক হিসাব করা।'),
    v('conclude', 'conclude', 'decide from the evidence', 'এখানে প্রমাণ থেকে সিদ্ধান্তে পৌঁছানো।'),
    v('infrastructure', 'infrastructure', 'something as useful to society as roads or ports', 'এখানে রাস্তা বা বন্দরের মত সমাজের জন্য প্রয়োজনীয় ব্যবস্থা — প্রাকৃতিক অবকাঠামো।'),
    v('develop', 'developed', 'built on', 'এখানে জমিতে স্থাপনা নির্মাণ করা।', { en: 'to build houses, hotels or roads on land', bn: '(জমিতে) নির্মাণ করা / উন্নয়ন করা' }),
  ],
  groups: [
    select('headings', HEAD_I, [
      q('rl09-q1', 'Paragraph B', 'i', 'B explains how mangroves deal with low oxygen and salt.', 'Paragraph B-তে অক্সিজেনের অভাব আর লবণ সামলানোর অভিযোজন — তাই i।', 'Because waterlogged mud contains little oxygen'),
      q('rl09-q2', 'Paragraph C', 'ii', 'C is about protecting coasts from waves and storms.', 'Paragraph C-তে ঢেউ ও ঝড় থেকে উপকূল রক্ষা — তাই ii।', 'the most obvious value of mangroves is protection'),
      q('rl09-q3', 'Paragraph D', 'iii', 'D describes fish, birds and tigers that rely on mangroves.', 'Paragraph D-তে মাছ, পাখি, বাঘ — যারা mangrove-এর ওপর নির্ভরশীল, তাই iii। Sundarbans-এর ইতিহাস (vi) নেই।', 'support life far beyond their own boundaries'),
      q('rl09-q4', 'Paragraph E', 'iv', 'E explains carbon buried in the soil.', 'Paragraph E-তে মাটির নিচে জমা কার্বন — চোখে না পড়া ভাণ্ডার, তাই iv।', 'most of it in the soil rather than in the trees'),
      q('rl09-q5', 'Paragraph F', 'v', 'F explains why many planting projects failed.', 'Paragraph F-এ অনেক চারা রোপণ প্রকল্প কেন ব্যর্থ — তাই v।', 'the results have been mixed'),
    ], headings(
      'Coping with salt and a lack of oxygen',
      'A shield against the sea',
      'Life that depends on the forests',
      'Hidden storage beneath the trees',
      'Why planting trees is not always enough',
      'The history of the Sundarbans',
      'New uses for mangrove timber',
      'How tides are created',
    )),
    select('tfng', TFNG_I, [
      q('rl09-q6', 'All mangroves belong to one species.', 'FALSE', 'Paragraph A: "Mangroves are not a single species but a group of trees and shrubs".', 'Paragraph A: "not a single species" — একটা প্রজাতি নয়, তাই FALSE।', 'Mangroves are not a single species'),
      q('rl09-q7', 'The Sundarbans is protected by law in both Bangladesh and India.', 'NOT GIVEN', 'Paragraph D describes the Sundarbans but says nothing about laws.', 'Paragraph D-তে Sundarbans-এর বর্ণনা আছে, কিন্তু আইনের কথা নেই — NOT GIVEN।'),
      q('rl09-q8', 'In some mangrove forests, most of the carbon is stored in the ground.', 'TRUE', 'Paragraph E: "most of it in the soil rather than in the trees".', 'Paragraph E: বেশিরভাগ কার্বন মাটিতে — ground = soil, TRUE।', 'most of it in the soil rather than in the trees'),
      q('rl09-q9', 'Young fish that grow among mangrove roots stay there for their whole lives.', 'FALSE', 'Paragraph D: "many of which later move to open water".', 'Paragraph D: অনেকে পরে খোলা পানিতে চলে যায় — সারাজীবন থাকে না, FALSE।', 'many of which later move to open water'),
    ]),
    gap('note', 1, [
      gapItem('rl09-q10', ['air'], 'Paragraph B: upward roots allow the tree "to take in air at low tide".', 'Paragraph B: "to take in air at low tide" — উত্তর air।', 'to take in air at low tide'),
      gapItem('rl09-q11', ['stable'], 'Paragraph B: prop roots keep "the tree stable in soft ground".', 'Paragraph B: "keeping the tree stable" — উত্তর stable।', 'keeping the tree stable in soft ground'),
      gapItem('rl09-q12', ['leaves'], 'Paragraph B: some "remove excess salt through their leaves".', 'Paragraph B: "through their leaves" — উত্তর leaves।', 'remove excess salt through their leaves'),
    ], {
      title: 'How mangroves survive',
      lines: [
        'Upward-growing roots: let the tree take in [[rl09-q10]] when the tide is low',
        'Curved "prop" roots: keep the tree [[rl09-q11]] in soft mud',
        'Salt: filtered out at the roots, or removed through the [[rl09-q12]]',
      ],
    }),
    select('mcq', MCQ_I, [
      q('rl09-q13', 'According to paragraph F, mangrove restoration is most likely to succeed when', 'C', 'Paragraph F: "if the natural flow of tides and fresh water is restored, mangroves often return on their own".', 'Paragraph F: স্বাভাবিক পানিপ্রবাহ ফিরিয়ে আনলে mangrove নিজেই ফেরে — C। বেশি চারা লাগানো (A) অনেক প্রকল্পে ব্যর্থ হয়েছে।', 'if the natural flow of tides and fresh water is restored', abcd('as many seedlings as possible are planted.', 'trees are planted on deep mudflats.', 'the natural movement of water is brought back first.', 'local people are kept away from the forest.')),
    ]),
  ],
};
