import { INFO_I, MCQ_I, YNNG_I, abcd, gap, gapItem, lex, q, select, v } from '../kit';
import type { LexEntry, LibraryPassage } from '../types';

export const LEX: LexEntry[] = [
  lex('widespread', 'adjective', 'core', 'existing or happening in many places or among many people', 'ব্যাপক / বহুল প্রচলিত', 'Mobile banking is now widespread in Bangladesh.', 'বাংলাদেশে মোবাইল ব্যাংকিং এখন বহুল প্রচলিত।', ['common', 'extensive']),
  lex('barely', 'adverb', 'useful', 'almost not; only just', 'প্রায় না / কোনোমতে', 'I could barely hear the teacher.', 'আমি শিক্ষকের কথা প্রায় শুনতেই পাচ্ছিলাম না।', ['hardly', 'scarcely']),
  lex('persistence', 'noun', 'advanced', 'the fact of continuing to exist for a long time', 'টিকে থাকা / দীর্ঘস্থায়িত্ব', 'The persistence of the problem worries experts.', 'সমস্যাটা টিকে থাকায় বিশেষজ্ঞরা চিন্তিত।', ['continuation', 'survival']),
  lex('go to the trouble of', 'phrase', 'advanced', 'to make a special effort to do something', 'কষ্ট করে কিছু করা', 'She went to the trouble of cooking for everyone.', 'তিনি কষ্ট করে সবার জন্য রান্না করেছেন।'),
  lex('plausible', 'adjective', 'useful', 'seeming reasonable and possibly true', 'বিশ্বাসযোগ্য মনে হয় এমন', 'His excuse sounded plausible.', 'তাঁর অজুহাতটা বিশ্বাসযোগ্য শোনাল।', ['believable', 'reasonable']),
  lex('solid', 'adjective', 'useful', 'hard and firm, not liquid or gas', 'কঠিন / শক্ত', 'Water becomes solid when it freezes.', 'জমে গেলে পানি কঠিন হয়ে যায়।'),
  lex('convincing', 'adjective', 'useful', 'making you believe that something is true', 'বিশ্বাসযোগ্য / জোরালো', 'She gave a convincing argument for change.', 'তিনি পরিবর্তনের পক্ষে একটা জোরালো যুক্তি দিলেন।', ['persuasive', 'compelling']),
  lex('judge', 'verb', 'core', 'to form an opinion about something', 'বিচার করা / মূল্যায়ন করা', 'Don’t judge a book by its cover.', 'মলাট দেখে বইয়ের বিচার করবেন না।', ['assess', 'estimate']),
  lex('disproportionate', 'adjective', 'advanced', 'too large or too small compared with something else', 'অসামঞ্জস্যপূর্ণ / মাত্রাতিরিক্ত', 'Small shops pay a disproportionate share of the tax.', 'ছোট দোকানগুলো করের মাত্রাতিরিক্ত অংশ দেয়।', ['excessive', 'unequal']),
  lex('register', 'verb', 'useful', 'to put a name on an official list', 'নিবন্ধন করা', 'You must register for the exam by Friday.', 'শুক্রবারের মধ্যে পরীক্ষার জন্য নিবন্ধন করতে হবে।', ['enrol', 'sign up']),
  lex('refer to as', 'phrasal verb', 'useful', 'to call something by a particular name', '…নামে উল্লেখ করা', 'The area is often referred to as the city’s heart.', 'এলাকাটাকে প্রায়ই শহরের হৃদয় বলা হয়।', ['call', 'describe as']),
  lex('justify', 'verb', 'useful', 'to be a good reason for something', 'যৌক্তিকতা প্রমাণ করা / ন্যায্য করা', 'Nothing can justify such a high price.', 'এত বেশি দামের কোনো যৌক্তিকতা নেই।', ['warrant', 'explain']),
  lex('analyse', 'verb', 'core', 'to examine something in detail to understand it', 'বিশ্লেষণ করা', 'The team analysed data from ten hospitals.', 'দলটা দশটা হাসপাতালের তথ্য বিশ্লেষণ করেছে।', ['examine', 'study']),
  lex('sharply', 'adverb', 'useful', 'suddenly and by a large amount', 'তীব্রভাবে / হঠাৎ অনেকটা', 'Prices rose sharply last month.', 'গত মাসে দাম হঠাৎ অনেক বেড়েছে।', ['steeply', 'dramatically']),
  lex('mileage', 'noun', 'advanced', 'the total number of miles a vehicle has travelled', 'গাড়ির অতিক্রান্ত মাইল', 'The car is old but has low mileage.', 'গাড়িটা পুরনো কিন্তু কম মাইল চলেছে।'),
  lex('considerably', 'adverb', 'useful', 'much; a lot', 'উল্লেখযোগ্যভাবে', 'The new model is considerably faster.', 'নতুন মডেলটা উল্লেখযোগ্যভাবে দ্রুত।', ['significantly', 'much']),
  lex('identical', 'adjective', 'useful', 'exactly the same', 'হুবহু একই', 'The two answers are identical.', 'দুটো উত্তর হুবহু একই।', ['the same', 'matching']),
  lex('universal', 'adjective', 'useful', 'true or done everywhere or by everyone', 'সর্বজনীন', 'There is no universal rule for success.', 'সাফল্যের কোনো সর্বজনীন নিয়ম নেই।', ['general', 'worldwide']),
  lex('bargain', 'noun', 'useful', 'something bought for less than its usual price', 'সস্তায় পাওয়া জিনিস / দারুণ দরদাম', 'At that price, the laptop is a real bargain.', 'ওই দামে ল্যাপটপটা সত্যিই সস্তা।', ['good deal']),
  lex('luxurious', 'adjective', 'useful', 'very comfortable and expensive', 'বিলাসবহুল', 'They stayed in a luxurious hotel.', 'তাঁরা একটা বিলাসবহুল হোটেলে ছিলেন।', ['expensive', 'grand']),
  lex('damaging', 'adjective', 'useful', 'causing harm', 'ক্ষতিকর', 'The scandal was damaging to the company.', 'কেলেঙ্কারিটা কোম্পানির জন্য ক্ষতিকর ছিল।', ['harmful']),
  lex('figure', 'noun', 'core', 'the shape of a person’s body', 'দেহের গঠন / অবয়ব', 'A tall figure appeared at the door.', 'দরজায় একটা লম্বা অবয়ব দেখা গেল।'),
  lex('process', 'verb', 'core', 'to deal with information, often using the mind or a computer', 'প্রক্রিয়াকরণ করা / বুঝে নেওয়া', 'Children process new words very quickly.', 'শিশুরা নতুন word খুব দ্রুত বুঝে নেয়।', ['handle', 'deal with']),
  lex('purchase', 'noun / verb', 'core', 'something that you buy; to buy', 'ক্রয় / কেনা', 'A house is the biggest purchase most people make.', 'বেশিরভাগ মানুষের জীবনে সবচেয়ে বড় কেনাকাটা একটা বাড়ি।', ['buy']),
  lex('driven by', 'phrase', 'useful', 'caused or strongly influenced by', 'চালিত / প্রভাবিত', 'The growth was driven by exports.', 'প্রবৃদ্ধিটা রপ্তানির কারণে হয়েছে।', ['caused by']),
  lex('consumer', 'noun', 'core', 'a person who buys goods or services', 'ভোক্তা', 'Consumers want cheaper and cleaner energy.', 'ভোক্তারা সস্তা ও পরিচ্ছন্ন জ্বালানি চান।', ['customer', 'buyer']),
  lex('impact', 'noun', 'core', 'a strong effect', 'প্রভাব', 'The new road had a big impact on local shops.', 'নতুন রাস্তা স্থানীয় দোকানগুলোর ওপর বড় প্রভাব ফেলেছে।', ['effect', 'influence']),
  lex('influence', 'verb', 'core', 'to affect the way someone thinks or behaves', 'প্রভাবিত করা', 'Advertising influences what children want.', 'বিজ্ঞাপন শিশুদের চাওয়াকে প্রভাবিত করে।', ['affect', 'shape']),
  lex('perception', 'noun', 'useful', 'the way you notice or understand something', 'উপলব্ধি / ধারণা', 'Public perception of the police has changed.', 'পুলিশ সম্পর্কে জনগণের ধারণা বদলেছে।', ['view', 'impression']),
  lex('cumulative', 'adjective', 'advanced', 'increasing gradually as more is added', 'ক্রমপুঞ্জিত / জমতে জমতে বাড়া', 'The cumulative effect of small savings can be large.', 'ছোট ছোট সঞ্চয়ের সম্মিলিত প্রভাব বড় হতে পারে।', ['growing', 'accumulated']),
  lex('underestimate', 'verb', 'useful', 'to think that something is smaller or less important than it is', 'কম করে ধরা / অবমূল্যায়ন করা', 'Never underestimate the time you need for Writing.', 'Writing-এর জন্য দরকারি সময় কখনো কম করে ধরবেন না।'),
  lex('bias', 'noun', 'useful', 'a tendency to think or act unfairly or in one particular way', 'পক্ষপাত / ঝোঁক', 'The survey had a bias towards young people.', 'জরিপটায় তরুণদের দিকে ঝোঁক ছিল।', ['prejudice', 'tendency']),
  lex('mild', 'adjective', 'useful', 'not strong or serious', 'মৃদু / হালকা', 'She had a mild fever.', 'তাঁর হালকা জ্বর ছিল।', ['slight', 'gentle']),
  lex('revealing', 'adjective', 'useful', 'showing something interesting that was not known', 'তাৎপর্যপূর্ণ / অনেক কিছু প্রকাশ করে এমন', 'The interview was very revealing.', 'সাক্ষাৎকারটা থেকে অনেক কিছু জানা গেল।'),
  lex('predictable', 'adjective', 'useful', 'happening in a way that can be expected', 'পূর্বানুমানযোগ্য', 'The ending of the film was predictable.', 'ছবিটার শেষটা আগে থেকেই আন্দাজ করা যাচ্ছিল।', ['expected', 'foreseeable']),
  lex('deceptive', 'adjective', 'advanced', 'making people believe something that is not true', 'প্রতারণামূলক / বিভ্রান্তিকর', 'The advertisement was deceptive.', 'বিজ্ঞাপনটা বিভ্রান্তিকর ছিল।', ['misleading']),
  lex('unrealistic', 'adjective', 'useful', 'not sensible or likely to happen', 'অবাস্তব', 'It is unrealistic to learn a language in a week.', 'এক সপ্তাহে একটা ভাষা শেখা অবাস্তব।'),
  lex('awareness', 'noun', 'core', 'knowledge or understanding of something', 'সচেতনতা', 'The campaign raised awareness of road safety.', 'প্রচারণাটা সড়ক নিরাপত্তা নিয়ে সচেতনতা বাড়িয়েছে।', ['knowledge', 'understanding']),
  lex('on their own terms', 'phrase', 'advanced', 'in the way that they choose, not the way others want', 'নিজেদের শর্তে / নিজেদের মত করে', 'The students wanted to learn on their own terms.', 'শিক্ষার্থীরা নিজেদের মত করে শিখতে চেয়েছিল।'),
];

export const PASSAGE: LibraryPassage = {
  id: 'rl-10-prices',
  title: 'The Magic of Ninety-Nine',
  topic: 'Economics',
  level: 'intermediate',
  minutes: 20,
  background: 'Summarises well-known consumer research in original words: the left-digit effect in price perception, used-car prices falling at round mileage thresholds, and research on round prices for feeling-based purchases.',
  paragraphs: [
    'Walk into almost any supermarket and you will find prices that end in 99: a bottle of shampoo at 2.99, a jacket at 49.99. The pattern is so widespread that most shoppers barely notice it. Economists call it "charm pricing", and its persistence raises an obvious question. If a price of 3.00 is only one cent higher than 2.99, why do so many sellers go to the trouble of avoiding round numbers? In some countries the favoured ending is 95 or 90 rather than 99, but the principle is the same.',
    'One popular explanation has little to do with psychology. According to a story that is often repeated, shopkeepers in the late nineteenth century began using odd prices so that cashiers would have to open the till to give change, making it harder for them to pocket money from customers who paid the exact amount. The story is plausible, but there is little solid evidence for it, and it cannot explain why the practice has survived in an age of card payments and self-service checkouts.',
    'A more convincing explanation concerns the way people read numbers. We read from left to right, and when we judge a price quickly, the first digit seems to carry disproportionate weight. A price of 2.99 is therefore registered as "two and something" rather than as almost three. Psychologists refer to this as the left-digit effect. In laboratory experiments, participants have consistently judged prices just below a round number to be noticeably cheaper than the difference justifies, particularly when they were asked to decide quickly.',
    'The effect does not appear only in shops. One striking example comes from the market for second-hand cars. Researchers who analysed millions of sales found that prices fell sharply each time a car’s mileage crossed a round number of thousands, so that a car that had travelled 79,900 miles sold for considerably more than an almost identical car with 80,100 miles. Buyers seemed to be paying close attention to the first digits and much less attention to the rest.',
    'Yet charm pricing is not a universal rule, and some sellers deliberately avoid it. Prices ending in 99 have become associated with discounts and bargains, and for products that are meant to feel luxurious, that association can be damaging. Expensive restaurants, jewellers and fashion brands often prefer round figures, such as 200 rather than 199.99, which suggest quality and confidence rather than value. Some research also suggests that round numbers are easier to process, which may make them more suitable for purchases driven by feelings rather than careful calculation.',
    'For consumers, the practical impact of any single price is small. Paying one cent more or less makes no real difference, and the left-digit effect influences perception rather than the actual amount paid. The concern is cumulative. Shoppers who repeatedly underestimate what they are spending may find, at the end of a month, that their bill is higher than they expected, and the same bias can affect larger decisions, such as choosing between two cars or two holidays. Shops also combine the effect with other techniques, such as showing a crossed-out higher price next to the new one, which makes the saving seem larger still.',
    'In my view, charm pricing is best understood as a mild but revealing example of how businesses use predictable features of human judgement. It is not deceptive in the legal sense, since the price is displayed openly, and it would be unrealistic to expect shops to abandon a practice that works. The more useful response is awareness. Once shoppers know that 9.99 is simply ten, they are in a better position to compare prices on their own terms, and the small trick loses much of its power.',
  ],
  vocab: [
    v('widespread', 'widespread', 'found almost everywhere', 'এখানে প্রায় সব জায়গায় দেখা যায়।'),
    v('barely', 'barely', 'almost do not', 'এখানে প্রায় খেয়ালই করে না।'),
    v('persistence', 'persistence', 'the fact that it continues', 'এখানে প্রথাটা যে টিকে আছে সেটা।'),
    v('obvious', 'obvious', 'natural to ask', 'এখানে স্বাভাবিকভাবেই মনে আসে এমন প্রশ্ন।'),
    v('go to the trouble of', 'go to the trouble of', 'make the effort of', 'এখানে কষ্ট করে এড়িয়ে চলা।'),
    v('plausible', 'plausible', 'it sounds possible', 'এখানে শুনতে সম্ভব মনে হয়।'),
    v('solid', 'solid', 'strong, reliable', 'এখানে জোরালো, নির্ভরযোগ্য প্রমাণ।', { en: 'strong and reliable', bn: 'জোরালো / নির্ভরযোগ্য' }),
    v('evidence', 'evidence', 'proof', 'এখানে প্রমাণ।'),
    v('survive', 'survived', 'continued to exist', 'এখানে প্রথাটা টিকে আছে।'),
    v('convincing', 'convincing', 'more believable', 'এখানে বেশি বিশ্বাসযোগ্য ব্যাখ্যা।'),
    v('judge', ['judge', 'judged'], 'decide how cheap or expensive a price is', 'এখানে দাম কতটা সস্তা বা দামি তা বিচার করা।'),
    v('disproportionate', 'disproportionate', 'more importance than it deserves', 'এখানে প্রাপ্যের চেয়ে বেশি গুরুত্ব।'),
    v('register', 'registered', 'noticed and understood by the mind', 'এখানে মনে যেভাবে ধরা পড়ে।', { en: 'to notice something and keep it in your mind', bn: '(মনে) ধরা পড়া / খেয়াল হওয়া' }),
    v('refer to as', 'refer to this as', 'call it', 'এখানে এই নামে ডাকেন।'),
    v('laboratory', 'laboratory', 'controlled experiments', 'এখানে নিয়ন্ত্রিত পরিবেশে পরীক্ষা।'),
    v('participant', 'participants', 'people in the experiments', 'এখানে পরীক্ষায় অংশ নেওয়া মানুষ।'),
    v('consistently', 'consistently', 'again and again', 'এখানে বারবার একই ফল।'),
    v('justify', 'justifies', 'the real difference is not big enough to explain it', 'এখানে প্রকৃত পার্থক্য এতটা নয় যে সেটার যৌক্তিকতা থাকে।'),
    v('striking', 'striking', 'very noticeable', 'এখানে খুব চোখে পড়ার মত উদাহরণ।'),
    v('market', 'market', 'the buying and selling of used cars', 'এখানে পুরনো গাড়ির কেনাবেচার বাজার।', { en: 'the business of buying and selling a particular product', bn: '(নির্দিষ্ট পণ্যের) বাজার' }),
    v('analyse', 'analysed', 'studied the sales data in detail', 'এখানে বিক্রির তথ্য বিস্তারিতভাবে বিশ্লেষণ করা।'),
    v('sharply', 'sharply', 'suddenly and by a lot', 'এখানে হঠাৎ অনেকটা।'),
    v('mileage', 'mileage', 'how far the car had been driven', 'এখানে গাড়িটা কত মাইল চলেছে।'),
    v('considerably', 'considerably', 'much more', 'এখানে অনেক বেশি দামে।'),
    v('identical', 'identical', 'almost exactly the same', 'এখানে প্রায় হুবহু একই।'),
    v('universal', 'universal', 'followed by everyone', 'এখানে সবাই মানে এমন নিয়ম।'),
    v('deliberately', 'deliberately', 'on purpose', 'এখানে ইচ্ছাকৃতভাবে।'),
    v('associate with', 'associated with', 'linked in people’s minds with', 'এখানে মানুষের মনে ছাড়ের সাথে যুক্ত।'),
    v('bargain', 'bargains', 'cheap deals', 'এখানে সস্তায় পাওয়া জিনিস।'),
    v('luxurious', 'luxurious', 'expensive and high-quality', 'এখানে দামি ও উঁচু মানের অনুভূতি।'),
    v('damaging', 'damaging', 'harmful to the product’s image', 'এখানে পণ্যের ভাবমূর্তির জন্য ক্ষতিকর।'),
    v('figure', 'figures', 'numbers', 'এখানে সংখ্যা।', { en: 'a number, especially an amount of money', bn: 'সংখ্যা / অঙ্ক' }),
    v('process', 'process', 'understand quickly', 'এখানে দ্রুত বুঝে নেওয়া।'),
    v('purchase', 'purchases', 'things people buy', 'এখানে কেনাকাটা।'),
    v('driven by', 'driven by', 'caused mainly by', 'এখানে মূলত অনুভূতির কারণে।'),
    v('consumer', 'consumers', 'shoppers', 'এখানে ক্রেতা।'),
    v('impact', 'impact', 'effect', 'এখানে প্রভাব।'),
    v('influence', 'influences', 'affects', 'এখানে প্রভাব ফেলে।'),
    v('perception', 'perception', 'how cheap the price seems', 'এখানে দামটা কতটা সস্তা মনে হয়।'),
    v('cumulative', 'cumulative', 'growing as small effects add up', 'এখানে ছোট প্রভাবগুলো জমে বড় হওয়া।'),
    v('underestimate', 'underestimate', 'think they are spending less than they are', 'এখানে যা খরচ হচ্ছে তার চেয়ে কম মনে করা।'),
    v('bias', 'bias', 'a tendency in thinking', 'এখানে চিন্তার একটা ঝোঁক।'),
    v('mild', 'mild', 'small, not serious', 'এখানে হালকা, গুরুতর নয়।'),
    v('revealing', 'revealing', 'showing something important', 'এখানে গুরুত্বপূর্ণ কিছু প্রকাশ করে।'),
    v('predictable', 'predictable', 'expected, always the same', 'এখানে আগে থেকে আন্দাজ করা যায়।'),
    v('deceptive', 'deceptive', 'meant to trick people', 'এখানে প্রতারণামূলক।'),
    v('unrealistic', 'unrealistic', 'not reasonable to expect', 'এখানে আশা করা অবাস্তব।'),
    v('abandon', 'abandon', 'stop using', 'এখানে ছেড়ে দেওয়া।'),
    v('awareness', 'awareness', 'knowing about the effect', 'এখানে প্রভাবটা সম্পর্কে জানা।'),
    v('on their own terms', 'on their own terms', 'in their own way, not the shop’s', 'এখানে দোকানের নয়, নিজেদের মত করে।'),
  ],
  groups: [
    select('info', INFO_I, [
      q('rl10-q1', 'an explanation from history that lacks strong evidence', 'B', 'Paragraph B: the till story is "plausible, but there is little solid evidence for it".', 'Paragraph B: গল্পটা বিশ্বাসযোগ্য, কিন্তু জোরালো প্রমাণ নেই — উত্তর B।', 'there is little solid evidence for it'),
      q('rl10-q2', 'an example of the effect outside ordinary shopping', 'D', 'Paragraph D: "The effect does not appear only in shops" — second-hand cars.', 'Paragraph D: পুরনো গাড়ির বাজারের উদাহরণ — উত্তর D।', 'The effect does not appear only in shops'),
      q('rl10-q3', 'a reason why some businesses prefer whole-number prices', 'E', 'Paragraph E: round figures "suggest quality and confidence rather than value".', 'Paragraph E: রাউন্ড সংখ্যা মান আর আস্থার ইঙ্গিত দেয় — উত্তর E।', 'which suggest quality and confidence rather than value'),
      q('rl10-q4', 'why a small effect could become a larger problem over time', 'F', 'Paragraph F: "The concern is cumulative."', 'Paragraph F: "cumulative" — ছোট প্রভাব জমে বড় হয়, উত্তর F।', 'The concern is cumulative'),
    ]),
    select('ynng', YNNG_I, [
      q('rl10-q5', 'The story about cashiers explains why prices still end in 99 today.', 'NO', 'Paragraph B: it "cannot explain why the practice has survived".', 'Paragraph B: লেখক বলেন গল্পটা আজকের প্রথা ব্যাখ্যা করতে পারে না — NO।', 'it cannot explain why the practice has survived'),
      q('rl10-q6', 'Shops should be made to stop using prices that end in 99.', 'NO', 'Paragraph G: "it would be unrealistic to expect shops to abandon a practice that works".', 'Paragraph G: লেখক বলেন দোকানগুলোর এটা ছেড়ে দেওয়ার আশা অবাস্তব; তিনি awareness চান — NO।', 'it would be unrealistic to expect shops to abandon a practice that works'),
      q('rl10-q7', 'Understanding the left-digit effect can make it less powerful.', 'YES', 'Paragraph G: once shoppers know, "the small trick loses much of its power".', 'Paragraph G: জানলে কৌশলটা শক্তি হারায় — লেখকের মত, YES।', 'the small trick loses much of its power'),
      q('rl10-q8', 'Most shoppers calculate prices accurately when they have enough time.', 'NOT GIVEN', 'The writer says the effect is stronger when people decide quickly, but does not say shoppers are accurate with more time.', 'লেখক বলেন দ্রুত সিদ্ধান্তে প্রভাব বেশি, কিন্তু সময় পেলে মানুষ নির্ভুল হিসাব করে কি না বলেননি — NOT GIVEN।'),
      q('rl10-q9', 'Charm pricing is not dishonest in a legal sense.', 'YES', 'Paragraph G: "It is not deceptive in the legal sense, since the price is displayed openly".', 'Paragraph G: আইনগতভাবে প্রতারণা নয় — dishonest ≈ deceptive, YES।', 'It is not deceptive in the legal sense'),
    ]),
    gap('summary', 2, [
      gapItem('rl10-q10', ['digit'], 'Paragraph C: "the first digit seems to carry disproportionate weight".', 'Paragraph C: "the first digit" — summary-তে first দেওয়া আছে, তাই digit।', 'the first digit seems to carry disproportionate weight'),
      gapItem('rl10-q11', ['left-digit effect'], 'Paragraph C: "Psychologists refer to this as the left-digit effect."', 'Paragraph C: "the left-digit effect" — hyphen-যুক্ত word একটা ধরা হয়, তাই দুটো word।', 'refer to this as the left-digit effect'),
      gapItem('rl10-q12', ['quickly'], 'Paragraph C: "particularly when they were asked to decide quickly".', 'Paragraph C: "decide quickly" — উত্তর quickly।', 'particularly when they were asked to decide quickly'),
    ], {
      title: 'Why 2.99 feels cheaper',
      lines: [
        'When people judge a price quickly, the first [[rl10-q10]] seems especially important, so 2.99 feels like "two and something". Psychologists call this the [[rl10-q11]]. In experiments, people judged such prices to be much cheaper, particularly when they had to decide [[rl10-q12]].',
      ],
    }),
    select('mcq', MCQ_I, [
      q('rl10-q13', 'Why do expensive restaurants often use round prices?', 'B', 'Paragraph E: round figures "suggest quality and confidence rather than value".', 'Paragraph E: রাউন্ড দাম মান আর আস্থা বোঝায় — B। "value" বা ছাড় (A) বোঝায় 99-এ শেষ দাম।', 'which suggest quality and confidence rather than value', abcd('to make customers think they are getting a bargain', 'because round numbers suggest quality', 'because the law requires it', 'to make bills easier to calculate')),
    ]),
  ],
};
