import { INFO_I, TFNG_I, TWO_I, abcd, gap, gapItem, lex, multi, q, select, v } from '../kit';
import type { LexEntry, LibraryPassage } from '../types';

export const LEX: LexEntry[] = [
  lex('launch', 'verb', 'core', 'to send a rocket or satellite into space; to start something new', 'উৎক্ষেপণ করা / চালু করা', 'The country launched its first satellite in 2018.', 'দেশটা ২০১৮ সালে প্রথম স্যাটেলাইট উৎক্ষেপণ করে।'),
  lex('crowded', 'adjective', 'core', 'full of people or things', 'ভিড়ে ঠাসা', 'The market is always crowded on Fridays.', 'শুক্রবারে বাজারটা সবসময় ভিড়ে ঠাসা থাকে।', ['packed', 'busy']),
  lex('forecasting', 'noun', 'useful', 'saying what will probably happen in the future, especially the weather', 'পূর্বাভাস', 'Weather forecasting has become more accurate.', 'আবহাওয়ার পূর্বাভাস আরও নির্ভুল হয়েছে।', ['prediction']),
  lex('navigation', 'noun', 'useful', 'finding the way from one place to another', 'দিকনির্ণয় / পথনির্দেশ', 'Phones use satellites for navigation.', 'ফোন পথনির্দেশের জন্য স্যাটেলাইট ব্যবহার করে।'),
  lex('alongside', 'preposition', 'useful', 'next to; together with', 'পাশাপাশি', 'Volunteers worked alongside the doctors.', 'স্বেচ্ছাসেবকরা ডাক্তারদের পাশাপাশি কাজ করেছেন।', ['beside', 'together with']),
  lex('debris', 'noun', 'useful', 'broken pieces left after something has been destroyed', 'ধ্বংসাবশেষ', 'Workers cleared the debris after the storm.', 'ঝড়ের পরে কর্মীরা ধ্বংসাবশেষ সরিয়েছেন।', ['remains', 'rubble']),
  lex('orbit', 'noun / verb', 'useful', 'the curved path of an object around a planet or star', 'কক্ষপথ', 'The satellite is in orbit around the Earth.', 'স্যাটেলাইটটা পৃথিবীর চারপাশে কক্ষপথে আছে।'),
  lex('collide', 'verb', 'useful', 'to hit something violently while moving', 'সংঘর্ষ হওয়া', 'Two buses collided on the highway.', 'মহাসড়কে দুটো বাসের সংঘর্ষ হয়েছে।', ['crash', 'hit']),
  lex('flake', 'noun', 'advanced', 'a small, thin piece of something', 'পাতলা টুকরো', 'Flakes of paint fell from the old wall.', 'পুরনো দেয়াল থেকে রঙের পাতলা টুকরো খসে পড়ল।', ['chip', 'fleck']),
  lex('agency', 'noun', 'core', 'a government organisation with a particular job', 'সংস্থা', 'The space agency announced a new mission.', 'মহাকাশ সংস্থাটা একটা নতুন মিশন ঘোষণা করেছে।', ['organisation', 'body']),
  lex('particle', 'noun', 'useful', 'a very small piece of something', 'কণা', 'Dust particles can harm the lungs.', 'ধুলিকণা ফুসফুসের ক্ষতি করতে পারে।', ['bit', 'speck']),
  lex('individually', 'adverb', 'useful', 'separately, one at a time', 'আলাদাভাবে', 'The teacher spoke to each student individually.', 'শিক্ষক প্রত্যেক শিক্ষার্থীর সাথে আলাদাভাবে কথা বললেন।', ['separately', 'one by one']),
  lex('velocity', 'noun', 'advanced', 'speed in a particular direction', 'বেগ', 'The bullet left the gun at high velocity.', 'গুলিটা উচ্চ বেগে বন্দুক থেকে বের হলো।', ['speed']),
  lex('crater', 'noun', 'advanced', 'a round hole in a surface made by something hitting it', 'গর্ত / খাদ', 'The moon is covered in craters.', 'চাঁদের গায়ে অসংখ্য গর্ত।'),
  lex('disable', 'verb', 'useful', 'to stop a machine or system from working', 'অকেজো করা', 'The storm disabled the power station.', 'ঝড় বিদ্যুৎকেন্দ্রটা অকেজো করে দিয়েছে।', ['put out of action']),
  lex('predicted', 'adjective', 'useful', 'expected to happen', 'পূর্বাভাসিত / প্রত্যাশিত', 'The predicted rain did not arrive.', 'পূর্বাভাসিত বৃষ্টি আসেনি।', ['expected', 'forecast']),
  lex('scale', 'noun', 'core', 'the size or level of something', 'মাত্রা / ব্যাপকতা', 'Nobody expected the scale of the damage.', 'ক্ষতির মাত্রা কেউ আশা করেনি।', ['size', 'extent']),
  lex('scatter', 'verb', 'useful', 'to throw or spread things over a wide area', 'ছড়িয়ে ছিটিয়ে দেওয়া', 'The wind scattered the papers across the floor.', 'বাতাস কাগজগুলো মেঝেজুড়ে ছড়িয়ে দিল।', ['spread', 'throw about']),
  lex('disused', 'adjective', 'useful', 'no longer used', 'অব্যবহৃত / পরিত্যক্ত', 'The disused factory was turned into a museum.', 'পরিত্যক্ত কারখানাটাকে জাদুঘরে রূপান্তর করা হয়েছে।', ['abandoned', 'unused']),
  lex('intact', 'adjective', 'advanced', 'complete and not damaged', 'অক্ষত', 'The ancient pot was found intact.', 'প্রাচীন হাঁড়িটা অক্ষত অবস্থায় পাওয়া গেছে।', ['whole', 'undamaged']),
  lex('scenario', 'noun', 'useful', 'a description of a possible situation in the future', 'সম্ভাব্য পরিস্থিতি / দৃশ্যকল্প', 'In the worst scenario, the river will flood the town.', 'সবচেয়ে খারাপ পরিস্থিতিতে নদী শহর প্লাবিত করবে।', ['situation', 'case']),
  lex('density', 'noun', 'advanced', 'how crowded something is in a given space', 'ঘনত্ব', 'Dhaka has a very high population density.', 'ঢাকার জনসংখ্যার ঘনত্ব খুব বেশি।'),
  lex('chain reaction', 'noun', 'useful', 'a series of events where each one causes the next', 'শৃঙ্খল বিক্রিয়া / ধারাবাহিক প্রতিক্রিয়া', 'One accident started a chain reaction on the road.', 'একটা দুর্ঘটনা রাস্তায় ধারাবাহিক দুর্ঘটনার সূত্রপাত করল।'),
  lex('constellation', 'noun', 'advanced', 'a group of stars; also a group of satellites working together', 'নক্ষত্রপুঞ্জ / স্যাটেলাইটের বহর', 'You can see the constellation from the village at night.', 'রাতে গ্রাম থেকে নক্ষত্রপুঞ্জটা দেখা যায়।'),
  lex('coverage', 'noun', 'useful', 'the area or number of people that a service reaches', 'বিস্তার / আওতা', 'Mobile coverage is poor in the hills.', 'পাহাড়ি এলাকায় মোবাইল নেটওয়ার্কের আওতা দুর্বল।', ['reach', 'range']),
  lex('intensify', 'verb', 'useful', 'to become or make something stronger', 'তীব্র হওয়া / জোরদার করা', 'The storm intensified overnight.', 'রাতারাতি ঝড়টা তীব্র হয়েছে।', ['increase', 'strengthen']),
  lex('sheer', 'adjective', 'advanced', 'used to emphasise how large or great something is', 'নিছক / বিপুল', 'The sheer size of the city surprised us.', 'শহরটার বিপুল আয়তন আমাদের অবাক করল।', ['pure', 'absolute']),
  lex('monitor', 'verb', 'core', 'to watch and check something over a period of time', 'নজরদারি করা / পর্যবেক্ষণ করা', 'Nurses monitor patients through the night.', 'নার্সরা সারা রাত রোগীদের পর্যবেক্ষণ করেন।', ['observe', 'track']),
  lex('interfere with', 'phrasal verb', 'useful', 'to stop something from working or happening properly', 'বাধা দেওয়া / ব্যাঘাত ঘটানো', 'Noise interferes with sleep.', 'শব্দ ঘুমে ব্যাঘাত ঘটায়।', ['disrupt', 'hinder']),
  lex('prevention', 'noun', 'core', 'stopping something bad from happening', 'প্রতিরোধ', 'Prevention is better than cure.', 'প্রতিকারের চেয়ে প্রতিরোধ ভালো।'),
  lex('guideline', 'noun', 'useful', 'a piece of official advice about how to do something', 'নির্দেশিকা', 'Follow the safety guidelines in the lab.', 'ল্যাবে নিরাপত্তা নির্দেশিকা মেনে চলুন।', ['rule', 'recommendation']),
  lex('regulator', 'noun', 'useful', 'an official organisation that controls an industry', 'নিয়ন্ত্রক সংস্থা', 'The telecom regulator set new prices.', 'টেলিকম নিয়ন্ত্রক সংস্থা নতুন দাম নির্ধারণ করেছে।'),
  lex('ultimately', 'adverb', 'useful', 'in the end; most importantly', 'শেষ পর্যন্ত / মূলত', 'Ultimately, the decision is yours.', 'শেষ পর্যন্ত সিদ্ধান্তটা আপনারই।', ['finally', 'in the end']),
  lex('responsibility', 'noun', 'core', 'a duty to deal with or take care of something', 'দায়িত্ব', 'Keeping the city clean is everyone’s responsibility.', 'শহর পরিষ্কার রাখা সবার দায়িত্ব।', ['duty']),
  lex('vulnerable', 'adjective', 'core', 'easily harmed or damaged', 'ঝুঁকিপূর্ণ / অরক্ষিত', 'Old people are more vulnerable to heat.', 'বয়স্করা গরমে বেশি ঝুঁকিতে থাকেন।', ['at risk', 'exposed']),
  lex('overuse', 'noun', 'advanced', 'using something too much', 'অতিব্যবহার', 'Overuse of antibiotics is a serious problem.', 'অ্যান্টিবায়োটিকের অতিব্যবহার একটা গুরুতর সমস্যা।'),
  lex('generate', 'verb', 'core', 'to produce or create something', 'উৎপন্ন করা / তৈরি করা', 'Solar panels generate electricity.', 'সৌর প্যানেল বিদ্যুৎ উৎপন্ন করে।', ['produce', 'create']),
];

export const PASSAGE: LibraryPassage = {
  id: 'rl-11-space-debris',
  title: 'The Crowded Sky',
  topic: 'Space',
  level: 'intermediate',
  minutes: 22,
  background: 'Well-documented events and ideas: Sputnik 1 (1957), the 2007 anti-satellite test, the 2009 collision of two intact satellites, Donald Kessler’s 1978 collision-cascade scenario and international debris-mitigation guidelines.',
  paragraphs: [
    'When the Soviet Union launched Sputnik 1 in 1957, the region of space around the Earth was empty of anything made by humans. Today it is crowded. Many thousands of working satellites provide services that modern life depends on, from weather forecasting and navigation to television and internet connections. Alongside them, however, circles a far larger population of objects that serve no purpose at all: the debris left behind by more than six decades of spaceflight.',
    'This debris takes many forms. It includes satellites that have reached the end of their working lives, the upper stages of rockets that carried them into orbit, and fragments produced when objects explode or collide. Some pieces are as large as a bus; others are flakes of paint. Space agencies track tens of thousands of objects larger than about ten centimetres, but models suggest that there are hundreds of thousands of pieces between one and ten centimetres across, and many millions of smaller particles, too small to be followed individually.',
    'Size is a poor guide to danger, because of the speeds involved. In low Earth orbit, objects travel at around 28,000 kilometres per hour, several times faster than a bullet. At such velocities, even a tiny fragment carries enormous energy. Flecks of paint have left small craters in the windows of spacecraft, and a fragment the size of a marble could disable a working satellite. For this reason, the International Space Station is fitted with shielding, and on a number of occasions it has changed its orbit to avoid a predicted close approach.',
    'Two events in particular made the scale of the problem clear. In 2007, a missile test deliberately destroyed an old weather satellite, scattering thousands of trackable fragments across a busy region of orbit. Two years later, an American communications satellite and a disused Russian satellite collided at high speed above Siberia, the first accidental collision between two intact satellites. Both events added large quantities of debris that will remain in orbit for many years.',
    'Such collisions worry scientists because debris can generate more debris. In 1978, the NASA scientist Donald Kessler described a scenario in which the density of objects in certain orbits becomes so high that each collision produces fragments that cause further collisions. In the worst case, this chain reaction could make some orbits too dangerous to use for generations. Experts disagree about how close we are to that point, but most accept that the risk rises as more satellites are launched.',
    'The rapid growth of so-called mega-constellations, groups of thousands of small satellites designed to provide global internet coverage, has intensified the debate. Supporters argue that these satellites fly low enough to fall back to Earth within a few years if they fail, and that they can be steered to avoid collisions. Critics reply that the sheer number of spacecraft increases the chance of accidents and makes the sky harder to monitor, and some astronomers complain that sunlight reflected from the satellites interferes with their observations.',
    'Responses to the problem fall into two broad categories. The first is prevention. International guidelines recommend that satellites in low orbits should be removed within 25 years of the end of their missions, either by lowering them so that they burn up in the atmosphere or by moving them to little-used graveyard orbits, and some national regulators have recently shortened this period. The second is active removal: several companies and space agencies have tested spacecraft that could capture a dead satellite and drag it down. These technologies remain expensive, and no country has yet agreed to pay for clearing debris that others created.',
    'Ultimately, the challenge is one of shared responsibility. Orbit is a resource that belongs to no single nation, and like many shared resources it is vulnerable to overuse. Keeping it usable for future generations will depend less on any one technology than on whether countries and companies are willing to follow common rules.',
  ],
  vocab: [
    v('launch', ['launched'], 'sent into space', 'এখানে মহাকাশে পাঠানো — উৎক্ষেপণ।'),
    v('crowded', 'crowded', 'full of objects', 'এখানে বস্তুতে ঠাসা।'),
    v('forecasting', 'forecasting', 'predicting the weather', 'এখানে আবহাওয়ার পূর্বাভাস।'),
    v('navigation', 'navigation', 'finding routes, for example with GPS', 'এখানে পথ খোঁজা, যেমন GPS দিয়ে।'),
    v('alongside', 'Alongside', 'next to the working satellites', 'এখানে সচল স্যাটেলাইটগুলোর পাশাপাশি।'),
    v('population', 'population', 'the total number of objects', 'এখানে বস্তুর মোট সংখ্যা।', { en: 'the total number of things of one kind in a place', bn: '(কোনো জায়গায়) একই ধরনের জিনিসের মোট সংখ্যা' }),
    v('purpose', 'purpose', 'use', 'এখানে কোনো কাজে লাগে না।'),
    v('debris', 'debris', 'pieces of old spacecraft', 'এখানে পুরনো মহাকাশযানের ধ্বংসাবশেষ।'),
    v('orbit', ['orbit', 'orbits'], 'the path around the Earth', 'এখানে পৃথিবীর চারপাশের কক্ষপথ।'),
    v('fragment', ['fragments', 'fragment'], 'broken pieces', 'এখানে ভাঙা টুকরো।'),
    v('collide', ['collide', 'collided'], 'crash into each other', 'এখানে একে অপরের সাথে ধাক্কা লাগা।'),
    v('flake', 'flakes', 'thin pieces of paint', 'এখানে রঙের পাতলা টুকরো।'),
    v('agency', 'agencies', 'organisations such as NASA', 'এখানে NASA-র মত সংস্থা।'),
    v('track', 'track', 'follow the position of', 'এখানে অবস্থান অনুসরণ করা।'),
    v('particle', 'particles', 'tiny pieces', 'এখানে অতি ক্ষুদ্র কণা।'),
    v('individually', 'individually', 'one by one', 'এখানে একটা একটা করে।'),
    v('velocity', 'velocities', 'very high speeds', 'এখানে অতি উচ্চ বেগ।'),
    v('enormous', 'enormous', 'huge', 'এখানে বিপুল শক্তি।'),
    v('crater', 'craters', 'small holes caused by impacts', 'এখানে আঘাতে তৈরি ছোট গর্ত।'),
    v('disable', 'disable', 'stop from working', 'এখানে অকেজো করে দেওয়া।'),
    v('predicted', 'predicted', 'expected from calculations', 'এখানে হিসাব থেকে প্রত্যাশিত।'),
    v('scale', 'scale', 'how big the problem is', 'এখানে সমস্যাটা কতটা বড়।'),
    v('deliberately', 'deliberately', 'on purpose', 'এখানে ইচ্ছাকৃতভাবে।'),
    v('scatter', 'scattering', 'spreading widely', 'এখানে চারদিকে ছড়িয়ে দেওয়া।'),
    v('disused', 'disused', 'no longer working', 'এখানে আর কাজ করছিল না।'),
    v('intact', 'intact', 'whole, not already broken', 'এখানে আগে ভাঙা নয়, অক্ষত।'),
    v('quantity', 'quantities', 'amounts', 'এখানে পরিমাণ।'),
    v('generate', 'generate', 'create', 'এখানে তৈরি করা।'),
    v('scenario', 'scenario', 'a possible future situation', 'এখানে ভবিষ্যতের সম্ভাব্য পরিস্থিতি।'),
    v('density', 'density', 'how crowded an orbit is', 'এখানে কক্ষপথ কতটা ঠাসা।'),
    v('chain reaction', 'chain reaction', 'collisions causing more collisions', 'এখানে এক সংঘর্ষ থেকে আরও সংঘর্ষ।'),
    v('generation', 'generations', 'a very long time', 'এখানে প্রজন্মের পর প্রজন্ম — দীর্ঘ সময়।'),
    v('risk', 'risk', 'the danger', 'এখানে বিপদের সম্ভাবনা।'),
    v('constellation', 'mega-constellations', 'huge groups of satellites', 'এখানে হাজার হাজার স্যাটেলাইটের বহর।', { en: 'a large group of satellites working together', bn: 'একসাথে কাজ করা স্যাটেলাইটের বহর' }),
    v('coverage', 'coverage', 'internet available everywhere', 'এখানে সব জায়গায় ইন্টারনেট পৌঁছানো।'),
    v('intensify', 'intensified', 'made stronger', 'এখানে বিতর্ক আরও জোরদার হয়েছে।'),
    v('steer', 'steered', 'moved in a chosen direction', 'এখানে পথ বদলানো যায়।'),
    v('sheer', 'sheer', 'the very large number', 'এখানে বিপুল সংখ্যা।'),
    v('monitor', 'monitor', 'watch and check', 'এখানে নজর রাখা।'),
    v('interfere with', 'interferes with', 'disturbs', 'এখানে পর্যবেক্ষণে ব্যাঘাত ঘটায়।'),
    v('prevention', 'prevention', 'stopping new debris', 'এখানে নতুন ধ্বংসাবশেষ তৈরি ঠেকানো।'),
    v('guideline', 'guidelines', 'official advice', 'এখানে আন্তর্জাতিক নির্দেশিকা।'),
    v('atmosphere', 'atmosphere', 'the air around the Earth', 'এখানে পৃথিবীর বায়ুমণ্ডল।'),
    v('regulator', 'regulators', 'official bodies that make rules', 'এখানে নিয়ম তৈরি করা সরকারি সংস্থা।'),
    v('capture', 'capture', 'catch and hold', 'এখানে মৃত স্যাটেলাইট ধরে ফেলা।'),
    v('clear', 'clearing', 'removing', 'এখানে ধ্বংসাবশেষ সরানো।'),
    v('ultimately', 'Ultimately', 'in the end, most importantly', 'এখানে শেষ বিচারে।'),
    v('responsibility', 'responsibility', 'a duty for everyone', 'এখানে সবার দায়িত্ব।'),
    v('resource', ['resource', 'resources'], 'something valuable that can be used up', 'এখানে মূল্যবান সম্পদ যা নষ্ট হতে পারে।'),
    v('vulnerable', 'vulnerable', 'easily harmed', 'এখানে সহজে ক্ষতিগ্রস্ত হতে পারে।'),
    v('overuse', 'overuse', 'being used too much', 'এখানে অতিরিক্ত ব্যবহার।'),
    v('willing', 'willing', 'ready', 'এখানে রাজি।'),
  ],
  groups: [
    select('tfng', TFNG_I, [
      q('rl11-q1', 'There were already human-made objects in orbit before Sputnik 1 was launched.', 'FALSE', 'Paragraph A: space "was empty of anything made by humans".', 'Paragraph A: তখন মানুষের তৈরি কিছুই ছিল না — FALSE।', 'was empty of anything made by humans'),
      q('rl11-q2', 'The International Space Station has moved to avoid debris.', 'TRUE', 'Paragraph C: "it has changed its orbit to avoid a predicted close approach".', 'Paragraph C: কক্ষপথ বদলেছে — moved = changed its orbit, TRUE।', 'it has changed its orbit to avoid a predicted close approach'),
      q('rl11-q3', 'Both satellites in the 2009 collision were still in use.', 'FALSE', 'Paragraph D: one was "a disused Russian satellite".', 'Paragraph D: একটা ছিল "disused" — অব্যবহৃত, তাই FALSE।', 'a disused Russian satellite'),
      q('rl11-q4', 'Most mega-constellation satellites are launched by government agencies.', 'NOT GIVEN', 'Paragraph F does not say who launches them.', 'Paragraph F-এ কারা উৎক্ষেপণ করে তা বলা নেই — NOT GIVEN।'),
    ]),
    select('info', INFO_I, [
      q('rl11-q5', 'a description of how one collision could lead to many more', 'E', 'Paragraph E: "each collision produces fragments that cause further collisions".', 'Paragraph E: এক সংঘর্ষ থেকে আরও সংঘর্ষ — উত্তর E।', 'each collision produces fragments that cause further collisions'),
      q('rl11-q6', 'a reason why very small objects can still be dangerous', 'C', 'Paragraph C: "even a tiny fragment carries enormous energy" because of speed.', 'Paragraph C: গতির কারণে ছোট টুকরোতেও বিপুল শক্তি — উত্তর C।', 'even a tiny fragment carries enormous energy'),
      q('rl11-q7', 'opposing views about a particular kind of satellite project', 'F', 'Paragraph F: supporters and critics of mega-constellations.', 'Paragraph F: mega-constellation নিয়ে সমর্থক আর সমালোচকদের মত — উত্তর F।', 'has intensified the debate'),
    ]),
    gap('short', 2, [
      gapItem('rl11-q8', ['graveyard orbits'], 'Paragraph G: satellites can be moved "to little-used graveyard orbits".', 'Paragraph G: "graveyard orbits" — উত্তর দুটো word।', 'little-used graveyard orbits', 'Instead of burning up, where can old satellites be moved?'),
      gapItem('rl11-q9', ['shielding'], 'Paragraph C: the ISS "is fitted with shielding".', 'Paragraph C: "fitted with shielding" — উত্তর shielding।', 'is fitted with shielding', 'What protection is the International Space Station fitted with?'),
      gapItem('rl11-q10', ['Donald Kessler', 'Kessler'], 'Paragraph E: "the NASA scientist Donald Kessler described a scenario".', 'Paragraph E: Donald Kessler — উত্তর তাঁর নাম।', 'the NASA scientist Donald Kessler', 'Which scientist first described the chain-reaction scenario?'),
    ]),
    multi('rl11-q11', TWO_I, 'Which TWO arguments do supporters of mega-constellations make?', abcd('Failed satellites fall back to Earth within a few years.', 'The satellites help astronomers.', 'The satellites can be steered away from collisions.', 'The satellites are cheaper than older ones.', 'The satellites remove existing debris.'), ['A', 'C'], 'Paragraph F: supporters say they "fall back to Earth within a few years if they fail" and "can be steered to avoid collisions".', 'Paragraph F: সমর্থকরা বলেন ব্যর্থ হলে কয়েক বছরে পৃথিবীতে ফেরে (A) আর সংঘর্ষ এড়াতে পথ বদলানো যায় (C)। জ্যোতির্বিদরা বরং অভিযোগ করেন (B ভুল)।', 'fall back to Earth within a few years if they fail'),
  ],
};
