import { HEAD_I, MCQ_I, TFNG_I, abcd, gap, gapItem, headings, lex, q, select, v } from '../kit';
import type { LexEntry, LibraryPassage } from '../types';

export const LEX: LexEntry[] = [
  lex('quarter', 'noun', 'core', 'one of four equal parts of something', 'চার ভাগের এক ভাগ', 'A quarter of the students are from Sylhet.', 'শিক্ষার্থীদের চার ভাগের এক ভাগ সিলেটের।'),
  lex('skyline', 'noun', 'useful', 'the outline of buildings seen against the sky', 'আকাশরেখা / দূর থেকে দেখা ভবনের সারি', 'The city’s skyline has changed in ten years.', 'দশ বছরে শহরটার আকাশরেখা বদলে গেছে।'),
  lex('dominate', 'verb', 'useful', 'to be the most important or noticeable part of something', 'প্রধান হয়ে থাকা / আধিপত্য করা', 'A large mosque dominates the town centre.', 'একটা বড় মসজিদ শহরের কেন্দ্রে প্রধান হয়ে আছে।', ['control', 'overshadow']),
  lex('inhabited', 'adjective', 'useful', 'having people living there', 'জনবসতিপূর্ণ', 'The island has been inhabited for thousands of years.', 'দ্বীপটায় হাজার হাজার বছর ধরে মানুষ বাস করছে।', ['populated', 'occupied']),
  lex('mechanical', 'adjective', 'useful', 'operated by a machine', 'যান্ত্রিক', 'The factory uses mechanical tools.', 'কারখানাটা যান্ত্রিক সরঞ্জাম ব্যবহার করে।'),
  lex('structure', 'noun', 'core', 'something that has been built; the way parts are arranged', 'কাঠামো / স্থাপনা', 'The bridge is the tallest structure in the country.', 'সেতুটা দেশের সবচেয়ে উঁচু স্থাপনা।', ['building', 'construction']),
  lex('shaft', 'noun', 'advanced', 'a long, narrow vertical passage in a building or the ground', 'খাড়া নালি / সুড়ঙ্গপথ', 'Air enters the mine through a shaft.', 'একটা খাড়া নালি দিয়ে খনিতে বাতাস ঢোকে।'),
  lex('still', 'adverb', 'core', 'continuing until now; even now', 'এখনো', 'She still lives in her village.', 'তিনি এখনো গ্রামে থাকেন।'),
  lex('vary', 'verb', 'core', 'to be different in different situations', 'ভিন্ন হওয়া / তারতম্য হওয়া', 'Prices vary from shop to shop.', 'দোকানভেদে দামের তারতম্য হয়।', ['differ', 'change']),
  lex('internal', 'adjective', 'useful', 'inside something', 'অভ্যন্তরীণ', 'The building has thick internal walls.', 'ভবনটার ভেতরের দেয়াল পুরু।', ['inner', 'inside']),
  lex('divide', 'verb', 'core', 'to separate something into parts', 'ভাগ করা', 'The teacher divided the class into groups.', 'শিক্ষক ক্লাসকে কয়েকটা দলে ভাগ করলেন।', ['split', 'separate']),
  lex('channel', 'noun', 'useful', 'a passage that water or air flows along', 'নালি / প্রণালী', 'Farmers dug channels to water their fields.', 'কৃষকরা মাঠে পানি দিতে নালি কেটেছেন।', ['passage', 'duct']),
  lex('neighbouring', 'adjective', 'useful', 'next to or near another place', 'প্রতিবেশী / পাশের', 'The fire spread to neighbouring houses.', 'আগুন পাশের বাড়িগুলোতে ছড়িয়ে পড়ল।', ['nearby', 'adjacent']),
  lex('evaporation', 'noun', 'useful', 'the process of a liquid changing into gas', 'বাষ্পীভবন', 'Evaporation cools the skin when we sweat.', 'ঘাম হলে বাষ্পীভবন ত্বক ঠান্ডা করে।'),
  lex('basin', 'noun', 'useful', 'a bowl or shallow container for water', 'জলাধার / গামলা', 'Water fell into a stone basin in the courtyard.', 'উঠানের পাথরের জলাধারে পানি পড়ছিল।'),
  lex('distant', 'adjective', 'core', 'far away', 'দূরবর্তী', 'We could hear distant thunder.', 'আমরা দূরের বজ্রপাতের শব্দ শুনতে পাচ্ছিলাম।', ['far', 'remote']),
  lex('tunnel', 'noun', 'useful', 'a passage under the ground', 'সুড়ঙ্গ', 'The train goes through a long tunnel.', 'ট্রেনটা একটা লম্বা সুড়ঙ্গের ভেতর দিয়ে যায়।'),
  lex('install', 'verb', 'useful', 'to put a machine or system in place so it can be used', 'স্থাপন করা', 'They installed solar panels on the roof.', 'তাঁরা ছাদে সৌর প্যানেল স্থাপন করেছেন।', ['fit', 'set up']),
  lex('regardless of', 'phrase', 'useful', 'without being affected by something', 'যাই হোক না কেন / নির্বিশেষে', 'The match will be played regardless of the weather.', 'আবহাওয়া যাই হোক, খেলা হবে।', ['despite', 'irrespective of']),
  lex('alternative', 'noun', 'core', 'another possible choice', 'বিকল্প', 'Cycling is a healthy alternative to driving.', 'গাড়ি চালানোর স্বাস্থ্যকর বিকল্প সাইকেল চালানো।', ['option', 'substitute']),
  lex('ventilation', 'noun', 'useful', 'the movement of fresh air into a room or building', 'বায়ু চলাচল', 'Good ventilation keeps the kitchen cool.', 'ভালো বায়ু চলাচল রান্নাঘর ঠান্ডা রাখে।', ['air flow']),
  lex('inspired by', 'phrase', 'useful', 'having new ideas because of something', 'অনুপ্রাণিত', 'The design was inspired by traditional houses.', 'নকশাটা ঐতিহ্যবাহী বাড়ি থেকে অনুপ্রাণিত।', ['influenced by']),
  lex('sensor', 'noun', 'useful', 'a device that notices and measures changes such as heat or light', 'সেন্সর / সংবেদক যন্ত্র', 'A sensor turns the lights on when someone enters.', 'কেউ ঢুকলে একটা সেন্সর বাতি জ্বালিয়ে দেয়।', ['detector']),
  lex('adjustable', 'adjective', 'useful', 'able to be changed to suit different needs', 'সামঞ্জস্যযোগ্য', 'The chair has an adjustable height.', 'চেয়ারটার উচ্চতা সামঞ্জস্য করা যায়।'),
  lex('humid', 'adjective', 'useful', '(of air) warm and wet', 'আর্দ্র / ভ্যাপসা', 'Dhaka is hot and humid in summer.', 'গ্রীষ্মে ঢাকা গরম আর ভ্যাপসা।', ['damp', 'muggy']),
  lex('moisture', 'noun', 'useful', 'a small amount of water in the air or in something', 'আর্দ্রতা', 'The plants need moisture in the soil.', 'গাছগুলোর মাটিতে আর্দ্রতা দরকার।', ['dampness', 'humidity']),
  lex('admit', 'verb', 'core', 'to agree that something is true, often unwillingly', 'স্বীকার করা', 'He admitted that he had made a mistake.', 'তিনি স্বীকার করলেন যে ভুল করেছেন।', ['confess', 'accept']),
];

export const PASSAGE: LibraryPassage = {
  id: 'rl-12-windcatchers',
  title: 'Catching the Wind',
  topic: 'Architecture',
  level: 'intermediate',
  minutes: 20,
  background: 'Traditional windcatchers (badgir) of Yazd, Iran, and similar towers across the Middle East, including their use with qanats and pools for evaporative cooling, are well documented.',
  paragraphs: [
    'In the old quarter of Yazd, a desert city in central Iran, the skyline is dominated not by domes or minarets but by rectangular towers rising above the roofs of houses. These are windcatchers, known in Persian as badgir, and for centuries they allowed families to live in comfort in one of the hottest inhabited regions on Earth without any mechanical cooling at all. Like the houses beneath them, most are built of mud brick, a material that heats up only slowly during the day. Similar structures can be found across the Middle East, from the coast of the Persian Gulf to Egypt, where they are called by different names but work on the same principles.',
    'A windcatcher is essentially a tall chimney with openings near the top. When the wind blows, the openings that face it capture moving air and direct it down a shaft into the rooms below. At the same time, the air pressure on the sheltered side of the tower is lower, so warm air inside the building is drawn upwards and out. Even on still days the tower continues to work, although less powerfully, because hot air naturally rises and escapes through the top, pulling cooler air in through doors and windows at ground level.',
    'The designs vary with local conditions. Where the wind blows mainly from one direction, a tower may have openings on only one side. In places where winds are less predictable, towers have openings on four or even eight sides, with internal walls that divide the shaft into separate channels so that air enters on one side and leaves on another. The height of the tower matters too: taller towers reach stronger and cleaner winds above the level of dust and neighbouring roofs.',
    'The most effective systems combined wind with water. In some houses, air from the windcatcher passed over a pool or a basin before entering the living rooms, and the evaporation of water lowered its temperature. Others were connected to underground channels, called qanats, which brought water from distant hills; air drawn through these cool tunnels could arrive in the house several degrees colder than the air outside. In such buildings, families often spent the hottest part of the day in basement rooms beneath the towers.',
    'With the arrival of electricity and air conditioning in the twentieth century, many windcatchers fell out of use. Installing an air conditioner was often cheaper than maintaining a traditional tower, and it worked regardless of the weather. In many cities, older houses were abandoned for modern apartment blocks, and the skills needed to build and repair windcatchers began to disappear.',
    'Today, however, interest in these structures is growing again. Air conditioning uses a large and growing share of electricity in hot countries, and on the hottest days it can place heavy demands on power networks, while also releasing heat into the streets outside. Architects searching for low-energy alternatives have begun to study traditional windcatchers, and some modern buildings in the Middle East and Europe now include ventilation towers inspired by them, often combined with sensors and adjustable vents. Researchers have also used computer models and wind tunnels to test how changes to the shape and height of a tower affect the amount of air it delivers.',
    'Windcatchers are not a complete solution. They depend on wind and on a large difference between day and night temperatures, and they work best in dry climates: in humid regions, evaporative cooling is far less effective, because the air already contains a great deal of moisture. Open towers can also admit dust, insects and noise. Their real value may lie less in replacing air conditioning than in reducing the need for it, allowing machines to be smaller and to run for fewer hours.',
  ],
  vocab: [
    v('quarter', 'quarter', 'an old part of the city', 'এখানে শহরের পুরনো এলাকা বা মহল্লা।', { en: 'a part of a town or city', bn: 'মহল্লা / এলাকা' }),
    v('skyline', 'skyline', 'the view of rooftops against the sky', 'এখানে আকাশের পটভূমিতে ছাদের সারি।'),
    v('dominate', 'dominated', 'the towers are the most noticeable feature', 'এখানে টাওয়ারগুলোই সবচেয়ে চোখে পড়ে।'),
    v('inhabited', 'inhabited', 'where people live', 'এখানে যেখানে মানুষ বাস করে।'),
    v('mechanical', 'mechanical', 'using machines', 'এখানে যন্ত্রের সাহায্যে।'),
    v('structure', ['structures'], 'buildings of this kind', 'এখানে এ ধরনের স্থাপনা।'),
    v('principle', 'principles', 'basic scientific ideas', 'এখানে মূল বৈজ্ঞানিক ধারণা।'),
    v('essentially', 'essentially', 'basically', 'এখানে মূলত।'),
    v('capture', 'capture', 'catch', 'এখানে বাতাস ধরে ফেলা।'),
    v('shaft', 'shaft', 'a vertical passage down into the building', 'এখানে ভবনের ভেতরে নেমে যাওয়া খাড়া নালি।'),
    v('pressure', 'pressure', 'the force of the air', 'এখানে বাতাসের চাপ।', { en: 'the force of air or liquid pushing on something', bn: '(বাতাসের) চাপ' }),
    v('sheltered', 'sheltered', 'the side away from the wind', 'এখানে টাওয়ারের যে দিকে বাতাস লাগে না।'),
    v('still', 'still', 'without wind', 'এখানে "still days" মানে বাতাসহীন দিন।', { en: '(of air or weather) without wind; calm', bn: 'স্থির / বাতাসহীন' }),
    v('vary', 'vary', 'are different in different places', 'এখানে জায়গাভেদে নকশা আলাদা।'),
    v('predictable', 'predictable', 'easy to know in advance', 'এখানে আগে থেকে জানা যায় এমন।'),
    v('internal', 'internal', 'inside the tower', 'এখানে টাওয়ারের ভেতরের।'),
    v('divide', 'divide', 'split into parts', 'এখানে কয়েক ভাগে ভাগ করা।'),
    v('channel', 'channels', 'separate passages for air or water', 'এখানে বাতাস বা পানির আলাদা পথ।'),
    v('neighbouring', 'neighbouring', 'nearby', 'এখানে আশপাশের ছাদ।'),
    v('effective', 'effective', 'working best', 'এখানে সবচেয়ে ভালো কাজ করা।'),
    v('evaporation', 'evaporation', 'water turning into vapour', 'এখানে পানি বাষ্প হয়ে যাওয়া।'),
    v('basin', 'basin', 'a small pool', 'এখানে ছোট জলাধার।'),
    v('distant', 'distant', 'far away', 'এখানে দূরের পাহাড়।'),
    v('tunnel', 'tunnels', 'underground passages', 'এখানে মাটির নিচের সুড়ঙ্গ।'),
    v('install', 'Installing', 'putting in place', 'এখানে এয়ার কন্ডিশনার বসানো।'),
    v('maintain', 'maintaining', 'keeping in good repair', 'এখানে ভালো অবস্থায় রাখা।', { en: 'to keep something in good condition by repairing it', bn: 'রক্ষণাবেক্ষণ করা' }),
    v('regardless of', 'regardless of', 'whatever the weather', 'এখানে আবহাওয়া যাই হোক।'),
    v('abandon', 'abandoned', 'left empty', 'এখানে পুরনো বাড়ি ছেড়ে যাওয়া।'),
    v('demand', 'demands', 'heavy use of electricity', 'এখানে বিদ্যুতের ওপর বড় চাপ।', { en: 'a need that something must supply', bn: 'চাহিদা / চাপ' }),
    v('network', 'networks', 'electricity supply systems', 'এখানে বিদ্যুৎ সরবরাহ ব্যবস্থা।'),
    v('release', 'releasing', 'giving out', 'এখানে তাপ বাইরে ছাড়া।'),
    v('alternative', 'alternatives', 'other options', 'এখানে কম শক্তির বিকল্প।'),
    v('ventilation', 'ventilation', 'air flow', 'এখানে বাতাস চলাচলের টাওয়ার।'),
    v('inspired by', 'inspired by', 'based on the idea of', 'এখানে ঐতিহ্যবাহী টাওয়ার থেকে অনুপ্রাণিত।'),
    v('sensor', 'sensors', 'devices that measure conditions', 'এখানে তাপমাত্রা ইত্যাদি মাপার যন্ত্র।'),
    v('adjustable', 'adjustable', 'can be opened or closed as needed', 'এখানে দরকারমতো খোলা-বন্ধ করা যায়।'),
    v('humid', 'humid', 'wet air', 'এখানে আর্দ্র বাতাস।'),
    v('moisture', 'moisture', 'water in the air', 'এখানে বাতাসে থাকা জলীয় বাষ্প।'),
    v('admit', 'admit', 'let in', 'এখানে ধুলা-পোকা ঢুকতে দেওয়া।', { en: 'to allow something to enter', bn: 'ঢুকতে দেওয়া' }),
  ],
  groups: [
    select('headings', HEAD_I, [
      q('rl12-q1', 'Paragraph B', 'iii', 'B explains how air is pulled in and pushed out.', 'Paragraph B-তে বাতাস কীভাবে ঢোকে আর বের হয় — তাই iii।', 'direct it down a shaft into the rooms below'),
      q('rl12-q2', 'Paragraph C', 'vi', 'C explains how designs change with local winds.', 'Paragraph C-তে স্থানীয় বাতাস অনুযায়ী নকশার পার্থক্য — তাই vi।', 'The designs vary with local conditions'),
      q('rl12-q3', 'Paragraph D', 'i', 'D describes cooling air with pools and qanats.', 'Paragraph D-তে পুকুর আর qanat দিয়ে পানির সাহায্যে বাতাস ঠান্ডা করা — তাই i।', 'The most effective systems combined wind with water'),
      q('rl12-q4', 'Paragraph E', 'viii', 'E explains why windcatchers fell out of use.', 'Paragraph E-তে বিদ্যুৎ আর AC আসার পরে windcatcher-এর ব্যবহার কমে যাওয়া — তাই viii। খরচের কথা (ii) আজকের নয়, AC-র তুলনায়।', 'many windcatchers fell out of use'),
      q('rl12-q5', 'Paragraph F', 'iv', 'F describes new interest from architects.', 'Paragraph F-এ স্থপতিদের নতুন আগ্রহ — তাই iv।', 'interest in these structures is growing again'),
    ], headings(
      'Cooling air with water',
      'Why windcatchers cost so much today',
      'How the tower moves air in and out',
      'Renewed interest from modern designers',
      'The religious meaning of desert towers',
      'Adapting the design to local winds',
      'Building materials used in Yazd',
      'A tradition in decline',
    )),
    gap('sentence', 1, [
      gapItem('rl12-q6', ['rises'], 'Paragraph B: on still days it works "because hot air naturally rises".', 'Paragraph B: "hot air naturally rises" — উত্তর rises।', 'because hot air naturally rises', 'Even without wind, the tower works because hot air naturally ___.'),
      gapItem('rl12-q7', ['cleaner'], 'Paragraph C: "taller towers reach stronger and cleaner winds".', 'Paragraph C: "stronger and cleaner winds" — উত্তর cleaner।', 'reach stronger and cleaner winds', 'Taller towers reach winds that are stronger and ___.'),
      gapItem('rl12-q8', ['basement'], 'Paragraph D: families spent the hottest hours "in basement rooms beneath the towers".', 'Paragraph D: "in basement rooms" — উত্তর basement।', 'in basement rooms beneath the towers', 'Families often spent the hottest part of the day in ___ rooms.'),
    ]),
    select('tfng', TFNG_I, [
      q('rl12-q9', 'Windcatchers are found only in Iran.', 'FALSE', 'Paragraph A: "Similar structures can be found across the Middle East".', 'Paragraph A: মধ্যপ্রাচ্যজুড়ে একই রকম স্থাপনা আছে — শুধু ইরানে নয়, FALSE।', 'Similar structures can be found across the Middle East'),
      q('rl12-q10', 'Air conditioning was often a cheaper option than keeping a windcatcher in good repair.', 'TRUE', 'Paragraph E: "Installing an air conditioner was often cheaper than maintaining a traditional tower".', 'Paragraph E: AC বসানো প্রায়ই টাওয়ার রক্ষণাবেক্ষণের চেয়ে সস্তা ছিল — TRUE।', 'Installing an air conditioner was often cheaper than maintaining a traditional tower'),
      q('rl12-q11', 'Yazd has more windcatchers than any other city in the world.', 'NOT GIVEN', 'Yazd’s windcatchers are described, but no comparison with other cities is made.', 'Yazd-এর কথা আছে, কিন্তু অন্য শহরের সাথে সংখ্যার তুলনা নেই — NOT GIVEN।'),
    ]),
    select('mcq', MCQ_I, [
      q('rl12-q12', 'According to paragraph G, windcatchers are most effective in', 'D', 'Paragraph G: "they work best in dry climates".', 'Paragraph G: শুকনো জলবায়ুতে সবচেয়ে ভালো কাজ করে — D। আর্দ্র এলাকায় (A) কম কার্যকর।', 'they work best in dry climates', abcd('humid coastal cities.', 'places with little difference between day and night temperatures.', 'areas without regular wind.', 'dry climates.')),
      q('rl12-q13', 'What does the writer suggest is the main value of windcatchers today?', 'B', 'Paragraph G: their value lies "less in replacing air conditioning than in reducing the need for it".', 'Paragraph G: AC পুরোপুরি বাদ দেওয়া নয়, বরং এর প্রয়োজন কমানো — B।', 'less in replacing air conditioning than in reducing the need for it', abcd('They can completely replace air conditioning.', 'They can reduce how much air conditioning is needed.', 'They are cheaper to build than apartment blocks.', 'They keep dust and insects out of buildings.')),
    ]),
  ],
};
