import { INFO_I, MCQ_I, TFNG_I, abcd, gap, gapItem, lex, q, select, v } from '../kit';
import type { LexEntry, LibraryPassage } from '../types';

export const LEX: LexEntry[] = [
  lex('cite', 'verb', 'useful', 'to mention something as an example or as proof', 'উদ্ধৃত করা / উল্লেখ করা', 'The report cites three recent studies.', 'প্রতিবেদনটা সাম্প্রতিক তিনটা গবেষণা উল্লেখ করেছে।', ['quote', 'mention']),
  lex('indifference', 'noun', 'advanced', 'a lack of interest or concern', 'উদাসীনতা', 'The public’s indifference to the problem surprised him.', 'সমস্যাটা নিয়ে মানুষের উদাসীনতা তাঁকে অবাক করেছে।', ['unconcern', 'apathy']),
  lex('emergency', 'noun', 'core', 'a sudden, dangerous situation that needs action at once', 'জরুরি অবস্থা', 'In an emergency, call 999.', 'জরুরি অবস্থায় ৯৯৯-এ কল করুন।', ['crisis']),
  lex('influential', 'adjective', 'useful', 'having a lot of influence', 'প্রভাবশালী', 'She wrote an influential book on education.', 'তিনি শিক্ষা নিয়ে একটা প্রভাবশালী বই লিখেছেন।', ['powerful', 'important']),
  lex('blame', 'verb', 'core', 'to say that someone is responsible for something bad', 'দোষ দেওয়া', 'Don’t blame others for your mistakes.', 'নিজের ভুলের জন্য অন্যদের দোষ দেবেন না।', ['hold responsible']),
  lex('suspect', 'verb', 'useful', 'to think something is probably true', 'সন্দেহ করা / ধারণা করা', 'Doctors suspect that the water was polluted.', 'ডাক্তারদের ধারণা পানি দূষিত ছিল।', ['believe', 'guess']),
  lex('presence', 'noun', 'useful', 'the fact of being in a place', 'উপস্থিতি', 'The presence of a teacher kept the class quiet.', 'শিক্ষকের উপস্থিতিতে ক্লাস শান্ত ছিল।'),
  lex('seizure', 'noun', 'advanced', 'a sudden attack of illness, especially one that causes shaking', 'খিঁচুনি', 'The patient had a seizure in the waiting room.', 'রোগী অপেক্ষাকক্ষে খিঁচুনিতে আক্রান্ত হলেন।', ['fit']),
  lex('witness', 'verb / noun', 'core', 'to see something happen; a person who sees it', 'প্রত্যক্ষ করা / সাক্ষী', 'Several people witnessed the accident.', 'কয়েকজন দুর্ঘটনাটা প্রত্যক্ষ করেছেন।', ['see', 'observe']),
  lex('diffusion', 'noun', 'advanced', 'the spreading of something over a wide area or among many people', 'বিস্তার / ছড়িয়ে পড়া', 'The diffusion of new ideas takes time.', 'নতুন ধারণার বিস্তারে সময় লাগে।', ['spread']),
  lex('individual', 'noun / adjective', 'core', 'a single person, considered separately', 'ব্যক্তি / একক', 'Each individual has different needs.', 'প্রত্যেক ব্যক্তির চাহিদা আলাদা।', ['person']),
  lex('interpretation', 'noun', 'useful', 'the way someone understands the meaning of something', 'ব্যাখ্যা / অর্থ করা', 'Her interpretation of the poem was unusual.', 'কবিতাটার তাঁর ব্যাখ্যা ছিল অসাধারণ।', ['understanding', 'reading']),
  lex('ambiguous', 'adjective', 'useful', 'having more than one possible meaning; unclear', 'দ্ব্যর্থক / অস্পষ্ট', 'The question was ambiguous, so students answered differently.', 'প্রশ্নটা অস্পষ্ট ছিল, তাই শিক্ষার্থীরা ভিন্নভাবে উত্তর দিয়েছে।', ['unclear', 'vague']),
  lex('clue', 'noun', 'useful', 'a piece of information that helps you understand something', 'সূত্র / ইঙ্গিত', 'The title gives a clue about the main idea.', 'শিরোনামটা মূল ধারণার একটা ইঙ্গিত দেয়।', ['hint', 'sign']),
  lex('privately', 'adverb', 'useful', 'without other people knowing', 'গোপনে / মনে মনে', 'She was privately worried about the result.', 'তিনি মনে মনে ফলাফল নিয়ে চিন্তিত ছিলেন।', ['secretly', 'personally']),
  lex('uncertain', 'adjective', 'core', 'not sure', 'অনিশ্চিত', 'I am uncertain about my plans for next year.', 'আগামী বছরের পরিকল্পনা নিয়ে আমি অনিশ্চিত।', ['unsure', 'doubtful']),
  lex('embarrassment', 'noun', 'useful', 'the feeling of being ashamed or uncomfortable in front of others', 'লজ্জা / বিব্রতবোধ', 'He hid his embarrassment with a laugh.', 'তিনি হেসে বিব্রতবোধ লুকালেন।', ['shame', 'awkwardness']),
  lex('intervene', 'verb', 'useful', 'to become involved in a situation to change or stop it', 'হস্তক্ষেপ করা', 'A passer-by intervened to stop the fight.', 'একজন পথচারী মারামারি থামাতে হস্তক্ষেপ করলেন।', ['step in', 'get involved']),
  lex('misjudge', 'verb', 'useful', 'to form a wrong opinion about something', 'ভুল বিচার করা', 'I misjudged the distance and missed the bus.', 'আমি দূরত্ব ভুল আন্দাজ করে বাস মিস করেছি।'),
  lex('reject', 'verb', 'core', 'to refuse to accept someone or something', 'প্রত্যাখ্যান করা', 'The university rejected her application.', 'বিশ্ববিদ্যালয় তাঁর আবেদন প্রত্যাখ্যান করেছে।', ['refuse', 'turn down']),
  lex('outweigh', 'verb', 'useful', 'to be greater or more important than something else', 'চেয়ে বেশি গুরুত্বপূর্ণ হওয়া / ছাপিয়ে যাওয়া', 'The benefits of the plan outweigh the costs.', 'পরিকল্পনাটার সুবিধা খরচকে ছাপিয়ে যায়।', ['exceed']),
  lex('investigation', 'noun', 'core', 'a careful study to discover the truth about something', 'তদন্ত', 'The police began an investigation into the fire.', 'পুলিশ আগুনের ঘটনায় তদন্ত শুরু করেছে।', ['inquiry', 'examination']),
  lex('exaggerate', 'verb', 'useful', 'to make something seem larger or worse than it really is', 'অতিরঞ্জিত করা', 'Newspapers sometimes exaggerate the danger.', 'পত্রিকাগুলো কখনো কখনো বিপদ অতিরঞ্জিত করে।', ['overstate']),
  lex('complicate', 'verb', 'useful', 'to make something more difficult to understand or deal with', 'জটিল করা', 'Heavy rain complicated the rescue.', 'ভারী বৃষ্টি উদ্ধারকাজ জটিল করে তুলল।'),
  lex('contrary to', 'phrase', 'useful', 'opposite to what is believed or expected', 'বিপরীতে / উল্টো', 'Contrary to popular belief, camels do not store water in their humps.', 'প্রচলিত ধারণার বিপরীতে, উট কুঁজে পানি জমা রাখে না।', ['unlike']),
  lex('incident', 'noun', 'core', 'an event, especially an unusual or unpleasant one', 'ঘটনা', 'The incident was reported to the police.', 'ঘটনাটা পুলিশকে জানানো হয়েছে।', ['event', 'occurrence']),
  lex('potential', 'adjective', 'core', 'possible but not yet real', 'সম্ভাব্য', 'We discussed the potential problems of the plan.', 'আমরা পরিকল্পনাটার সম্ভাব্য সমস্যা নিয়ে আলোচনা করলাম।', ['possible', 'likely']),
  lex('single out', 'phrasal verb', 'useful', 'to choose one person from a group for special attention', 'আলাদা করে বেছে নেওয়া', 'The teacher singled out two students for praise.', 'শিক্ষক প্রশংসার জন্য দুজন শিক্ষার্থীকে আলাদা করে বেছে নিলেন।', ['pick out']),
  lex('specific', 'adjective', 'core', 'exact and clear; particular', 'সুনির্দিষ্ট', 'Give a specific example in your answer.', 'উত্তরে একটা সুনির্দিষ্ট উদাহরণ দিন।', ['particular', 'precise']),
  lex('uncertainty', 'noun', 'useful', 'a state of not being sure', 'অনিশ্চয়তা', 'There is still uncertainty about the exam date.', 'পরীক্ষার তারিখ নিয়ে এখনো অনিশ্চয়তা আছে।', ['doubt']),
];

export const PASSAGE: LibraryPassage = {
  id: 'rl-13-bystanders',
  title: 'Why Crowds Hesitate',
  topic: 'Human behaviour',
  level: 'intermediate',
  minutes: 22,
  background: 'Summarises well-known research in original words: the 1964 Kitty Genovese case and later re-examination of the original reporting, Darley and Latané’s bystander experiments (1968), and a later analysis of CCTV footage of real public conflicts in three countries.',
  paragraphs: [
    'In March 1964, a young woman named Kitty Genovese was attacked and killed outside her apartment in New York. Two weeks later, a newspaper report claimed that thirty-eight neighbours had watched the attack from their windows and that none of them had called the police. The story shocked the country and became one of the most widely cited examples of human indifference. It also inspired a question that psychologists have studied ever since: why do people sometimes fail to help others in an emergency, even when many of them are present?',
    'The most influential answer came from two young social psychologists, John Darley and Bibb Latané. Rather than blaming the neighbours’ character, they suspected that the presence of other people might itself make helping less likely. In one experiment, students took part in a discussion through an intercom system, believing that they were talking to one, two or five other participants in separate rooms. During the conversation, one voice appeared to have a seizure and call for help. Students who believed that they were the only listener almost always left their room to report the emergency, and did so quickly; those who believed that several others could also hear were much slower to act, and many never acted at all.',
    'Darley and Latané called this pattern the bystander effect, and they proposed several explanations. The first is diffusion of responsibility: when many people witness an emergency, each individual feels less personally responsible for acting, assuming that someone else will. The second concerns the interpretation of the situation. Emergencies are often ambiguous, and people look to others for clues about what is happening. If everyone else appears calm, each person may conclude that nothing serious is wrong, even though all of them are privately uncertain. A related study, in which a room gradually filled with smoke, found that participants were far less likely to report it when they were sitting with others who ignored it.',
    'A third factor is the fear of embarrassment. Intervening in public means risking the possibility of misjudging the situation, being rejected or doing something foolish in front of strangers. For many people, the social cost of making a mistake appears to outweigh the uncertain benefit of acting.',
    'The story that first inspired this research has itself been re-examined. Later investigations by journalists and researchers concluded that the original newspaper report had been exaggerated. Far fewer than thirty-eight people had actually seen the attack; many had heard only shouts, which they could not identify, and at least one neighbour did call the police, while another went out to help. The image of dozens of silent witnesses, in other words, was more powerful than it was accurate.',
    'More recent evidence has also complicated the picture. In one study, researchers analysed video recordings of real public arguments and fights captured by security cameras in three cities on different continents. Contrary to what the bystander effect might predict, at least one bystander intervened in the great majority of incidents, and the chance that someone would help actually increased with the number of people present. The researchers suggested that while each individual may be less likely to act in a crowd, larger groups simply contain more potential helpers.',
    'These findings do not mean that the original experiments were wrong. Rather, they suggest that the bystander effect is strongest in situations that are ambiguous, where no one is sure that help is needed, and weaker in obvious, dangerous conflicts. They also offer practical advice. Anyone who needs help in a public place is often advised not to call out to a crowd in general, but to single out one person, making eye contact and giving a specific instruction, such as "You in the blue shirt, call an ambulance." Removing uncertainty about who should act, and what they should do, may be the simplest way to turn bystanders into helpers.',
  ],
  vocab: [
    v('cite', 'cited', 'mentioned as an example', 'এখানে উদাহরণ হিসেবে উল্লেখ করা।'),
    v('indifference', 'indifference', 'not caring about others', 'এখানে অন্যদের প্রতি উদাসীনতা।'),
    v('emergency', ['emergency', 'Emergencies', 'emergencies'], 'a sudden dangerous situation', 'এখানে হঠাৎ বিপজ্জনক পরিস্থিতি।'),
    v('influential', 'influential', 'with great influence on later research', 'এখানে পরবর্তী গবেষণায় বড় প্রভাব ফেলেছে।'),
    v('blame', 'blaming', 'saying the neighbours were bad people', 'এখানে প্রতিবেশীদের দোষ দেওয়া।'),
    v('suspect', 'suspected', 'thought it was probably true', 'এখানে সম্ভবত সত্য বলে মনে করলেন।'),
    v('presence', 'presence', 'being there', 'এখানে অন্যদের উপস্থিত থাকা।'),
    v('participant', 'participants', 'people in the experiment', 'এখানে পরীক্ষায় অংশ নেওয়া মানুষ।'),
    v('seizure', 'seizure', 'a sudden medical attack', 'এখানে হঠাৎ খিঁচুনি।'),
    v('report', 'report', 'tell someone in charge', 'এখানে দায়িত্বপ্রাপ্ত কাউকে জানানো।'),
    v('propose', 'proposed', 'suggested', 'এখানে প্রস্তাব করলেন।'),
    v('diffusion', 'diffusion', 'spreading among many people', 'এখানে দায়িত্ব অনেকের মধ্যে ছড়িয়ে যাওয়া।'),
    v('responsibility', 'responsibility', 'the duty to act', 'এখানে কিছু করার দায়িত্ব।'),
    v('witness', ['witness', 'witnesses'], 'see; people who see', 'এখানে ঘটনা দেখা / প্রত্যক্ষদর্শী।'),
    v('individual', 'individual', 'each single person', 'এখানে প্রত্যেক ব্যক্তি।'),
    v('assume', 'assuming', 'believing without checking', 'এখানে যাচাই না করে ধরে নেওয়া।'),
    v('interpretation', 'interpretation', 'how people understand what is happening', 'এখানে কী ঘটছে তা মানুষ কীভাবে বোঝে।'),
    v('ambiguous', 'ambiguous', 'not clear', 'এখানে পরিস্থিতি স্পষ্ট নয়।'),
    v('clue', 'clues', 'signs about what is happening', 'এখানে কী ঘটছে তার ইঙ্গিত।'),
    v('conclude', 'conclude', 'decide', 'এখানে সিদ্ধান্তে আসা।'),
    v('privately', 'privately', 'inside their own minds', 'এখানে মনে মনে।'),
    v('uncertain', 'uncertain', 'not sure', 'এখানে নিশ্চিত নয়।'),
    v('gradually', 'gradually', 'slowly', 'এখানে ধীরে ধীরে।'),
    v('factor', 'factor', 'cause', 'এখানে একটা কারণ।'),
    v('embarrassment', 'embarrassment', 'feeling foolish in front of others', 'এখানে অন্যদের সামনে বোকা বনে যাওয়ার ভয়।'),
    v('intervene', ['Intervening', 'intervened'], 'step in to help', 'এখানে সাহায্যে এগিয়ে আসা।'),
    v('misjudge', 'misjudging', 'understanding the situation wrongly', 'এখানে পরিস্থিতি ভুল বোঝা।'),
    v('reject', 'rejected', 'refused by the person you try to help', 'এখানে যাকে সাহায্য করতে যাচ্ছেন তিনি ফিরিয়ে দেওয়া।'),
    v('outweigh', 'outweigh', 'be more important than', 'এখানে সুবিধার চেয়ে বেশি ভারী মনে হওয়া।'),
    v('benefit', 'benefit', 'good result', 'এখানে উপকার।'),
    v('investigation', 'investigations', 'careful research into what happened', 'এখানে কী ঘটেছিল তার অনুসন্ধান।'),
    v('exaggerate', 'exaggerated', 'made to seem worse than it was', 'এখানে প্রকৃত ঘটনার চেয়ে বাড়িয়ে বলা।'),
    v('identify', 'identify', 'recognise', 'এখানে কী শব্দ তা চিনতে পারা।'),
    v('accurate', 'accurate', 'true to the facts', 'এখানে সত্য ঘটনার সাথে মেলে।'),
    v('complicate', 'complicated', 'made less simple', 'এখানে বিষয়টা জটিল করেছে।'),
    v('analyse', 'analysed', 'studied in detail', 'এখানে বিস্তারিতভাবে বিশ্লেষণ।'),
    v('capture', 'captured', 'recorded on camera', 'এখানে ক্যামেরায় ধরা পড়া।', { en: 'to record something on camera or in words', bn: '(ক্যামেরায়) ধারণ করা' }),
    v('contrary to', 'Contrary to', 'the opposite of', 'এখানে প্রত্যাশার বিপরীতে।'),
    v('incident', 'incidents', 'events such as fights', 'এখানে মারামারির মত ঘটনা।'),
    v('potential', 'potential', 'possible', 'এখানে সম্ভাব্য সাহায্যকারী।'),
    v('finding', 'findings', 'results', 'এখানে গবেষণার ফল।'),
    v('obvious', 'obvious', 'clear to everyone', 'এখানে স্পষ্ট বিপদ।'),
    v('single out', 'single out', 'choose one particular person', 'এখানে একজনকে আলাদা করে বেছে নেওয়া।'),
    v('specific', 'specific', 'clear and exact', 'এখানে পরিষ্কার নির্দেশ।'),
    v('uncertainty', 'uncertainty', 'not knowing', 'এখানে কে কী করবে তা না জানা।'),
  ],
  groups: [
    select('tfng', TFNG_I, [
      q('rl13-q1', 'The newspaper report was published the day after the attack.', 'FALSE', 'Paragraph A: the report appeared "Two weeks later".', 'Paragraph A: প্রতিবেদন এসেছে দুই সপ্তাহ পরে — পরের দিন নয়, FALSE।', 'Two weeks later, a newspaper report claimed'),
      q('rl13-q2', 'Darley and Latané had worked together before the Genovese case.', 'NOT GIVEN', 'The passage does not say when they began working together.', 'তাঁরা কবে একসাথে কাজ শুরু করেন তা বলা নেই — NOT GIVEN।'),
      q('rl13-q3', 'Later investigations found that some neighbours had tried to help.', 'TRUE', 'Paragraph E: "at least one neighbour did call the police, while another went out to help".', 'Paragraph E: একজন পুলিশ ডেকেছিলেন, আরেকজন সাহায্যে গিয়েছিলেন — TRUE।', 'at least one neighbour did call the police'),
      q('rl13-q4', 'In the video study, the more people were present, the more likely it was that someone helped.', 'TRUE', 'Paragraph F: "the chance that someone would help actually increased with the number of people present".', 'Paragraph F: মানুষ বেশি থাকলে কেউ সাহায্য করার সম্ভাবনা বেড়েছে — TRUE।', 'the chance that someone would help actually increased with the number of people present'),
    ]),
    select('info', INFO_I, [
      q('rl13-q5', 'an explanation linked to how people understand an unclear situation', 'C', 'Paragraph C: "The second concerns the interpretation of the situation. Emergencies are often ambiguous".', 'Paragraph C: অস্পষ্ট পরিস্থিতিতে অন্যদের দেখে অর্থ বোঝা — উত্তর C।', 'The second concerns the interpretation of the situation'),
      q('rl13-q6', 'a claim that a famous story was not accurate', 'E', 'Paragraph E: "the original newspaper report had been exaggerated".', 'Paragraph E: মূল প্রতিবেদন অতিরঞ্জিত ছিল — উত্তর E।', 'the original newspaper report had been exaggerated'),
      q('rl13-q7', 'advice for a person who needs help from strangers', 'G', 'Paragraph G: "single out one person, making eye contact and giving a specific instruction".', 'Paragraph G: একজনকে বেছে নিয়ে সুনির্দিষ্ট নির্দেশ দেওয়া — উত্তর G।', 'single out one person'),
    ]),
    gap('summary', 3, [
      gapItem('rl13-q8', ['diffusion of responsibility'], 'Paragraph C: "The first is diffusion of responsibility".', 'Paragraph C: "diffusion of responsibility" — তিনটা word, সীমার মধ্যে।', 'The first is diffusion of responsibility'),
      gapItem('rl13-q9', ['embarrassment'], 'Paragraph D: "A third factor is the fear of embarrassment."', 'Paragraph D: "the fear of embarrassment" — উত্তর embarrassment।', 'A third factor is the fear of embarrassment'),
      gapItem('rl13-q10', ['ambiguous'], 'Paragraph G: the effect "is strongest in situations that are ambiguous".', 'Paragraph G: "strongest in situations that are ambiguous" — উত্তর ambiguous।', 'strongest in situations that are ambiguous'),
    ], {
      title: 'Why bystanders fail to act',
      lines: [
        'When many people see an emergency, each person feels less responsible, a process known as [[rl13-q8]]. People may also hold back because of the fear of [[rl13-q9]] in front of strangers. Recent research suggests that the effect is strongest when situations are [[rl13-q10]].',
      ],
    }),
    select('mcq', MCQ_I, [
      q('rl13-q11', 'What did Darley and Latané suspect at the start of their research?', 'A', 'Paragraph B: they suspected "that the presence of other people might itself make helping less likely".', 'Paragraph B: তাঁদের ধারণা ছিল অন্যদের উপস্থিতিই সাহায্যের সম্ভাবনা কমায় — A। প্রতিবেশীদের চরিত্রকে (B) তাঁরা দায়ী করেননি।', 'the presence of other people might itself make helping less likely', abcd('The presence of others could make people less likely to help.', 'The neighbours were unusually selfish people.', 'People in cities care less than people in villages.', 'The newspaper report was exaggerated.')),
      q('rl13-q12', 'What does the writer conclude in paragraph G about the original experiments?', 'C', 'Paragraph G: "These findings do not mean that the original experiments were wrong"; the effect is strongest in ambiguous situations.', 'Paragraph G: মূল পরীক্ষাগুলো ভুল নয়; প্রভাব অস্পষ্ট পরিস্থিতিতে বেশি — C।', 'These findings do not mean that the original experiments were wrong', abcd('They should no longer be taught.', 'They proved that crowds never help.', 'They are still valid, but apply most to unclear situations.', 'They were based on exaggerated reports.')),
    ]),
  ],
};
