import { MCQ_I, TFNG_I, abcd, gap, gapItem, lex, q, select, v } from '../kit';
import type { LexEntry, LibraryPassage } from '../types';

export const LEX: LexEntry[] = [
  lex('ice sheet', 'noun', 'useful', 'a very large, thick layer of ice covering land', 'বরফের চাদর / হিমস্তর', 'The Greenland ice sheet is losing ice every year.', 'গ্রিনল্যান্ডের বরফের চাদর প্রতি বছর বরফ হারাচ্ছে।'),
  lex('compress', 'verb', 'useful', 'to press something so that it takes up less space', 'চাপ দিয়ে সংকুচিত করা', 'The machine compresses waste into small blocks.', 'যন্ত্রটা বর্জ্যকে চাপ দিয়ে ছোট ব্লকে পরিণত করে।', ['squeeze', 'press']),
  lex('seal off', 'phrasal verb', 'useful', 'to close something completely so nothing can get in or out', 'পুরোপুরি বন্ধ করে দেওয়া', 'Police sealed off the street after the accident.', 'দুর্ঘটনার পরে পুলিশ রাস্তাটা বন্ধ করে দিল।', ['close off', 'shut']),
  lex('vertical', 'adjective', 'useful', 'standing or pointing straight up', 'উল্লম্ব / খাড়া', 'Draw a vertical line down the page.', 'পাতার ওপর থেকে নিচে একটা খাড়া রেখা আঁকুন।', ['upright']),
  lex('archive', 'noun', 'advanced', 'a collection of historical records', 'সংরক্ষণাগার / মহাফেজখানা', 'The library keeps an archive of old newspapers.', 'লাইব্রেরিটা পুরনো পত্রিকার একটা সংরক্ষণাগার রাখে।', ['record', 'collection']),
  lex('sample', 'noun', 'core', 'a small amount of something used to test or show what the rest is like', 'নমুনা', 'The doctor took a blood sample.', 'ডাক্তার রক্তের নমুনা নিলেন।', ['specimen']),
  lex('drill', 'verb', 'useful', 'to make a hole using a special tool', 'ছিদ্র করা / খনন করা', 'Engineers drilled deep into the rock.', 'প্রকৌশলীরা পাথরের গভীরে ছিদ্র করলেন।', ['bore']),
  lex('extract', 'verb', 'useful', 'to take something out, often with effort', 'বের করে আনা / নিষ্কাশন করা', 'Oil is extracted from under the sea.', 'সমুদ্রের নিচ থেকে তেল নিষ্কাশন করা হয়।', ['remove', 'take out']),
  lex('cylinder', 'noun', 'advanced', 'a shape with circular ends and long straight sides, like a tube', 'বেলন / সিলিন্ডার', 'Gas is stored in metal cylinders.', 'গ্যাস ধাতব সিলিন্ডারে রাখা হয়।'),
  lex('remote', 'adjective', 'core', 'far away from towns and cities', 'প্রত্যন্ত / দূরবর্তী', 'The school is in a remote village.', 'স্কুলটা একটা প্রত্যন্ত গ্রামে।', ['isolated', 'distant']),
  lex('section', 'noun', 'core', 'one of the parts that something is divided into', 'অংশ / খণ্ড', 'The book is divided into three sections.', 'বইটা তিনটা অংশে বিভক্ত।', ['part', 'piece']),
  lex('continuous', 'adjective', 'useful', 'without a break or interruption', 'অবিচ্ছিন্ন / একটানা', 'The machine needs a continuous supply of power.', 'যন্ত্রটার একটানা বিদ্যুৎ সরবরাহ দরকার।', ['unbroken', 'constant']),
  lex('concentration', 'noun', 'useful', 'the amount of a substance in a mixture or in the air', 'ঘনত্ব / পরিমাণ', 'The concentration of salt in seawater is high.', 'সমুদ্রের পানিতে লবণের ঘনত্ব বেশি।'),
  lex('indirectly', 'adverb', 'useful', 'not in a direct way; through something else', 'পরোক্ষভাবে', 'The drought indirectly raised food prices.', 'খরা পরোক্ষভাবে খাদ্যের দাম বাড়িয়েছে।'),
  lex('molecule', 'noun', 'advanced', 'the smallest unit of a substance, made of atoms', 'অণু', 'A water molecule has two hydrogen atoms and one oxygen atom.', 'পানির একটা অণুতে দুটো হাইড্রোজেন আর একটা অক্সিজেন পরমাণু থাকে।'),
  lex('readily', 'adverb', 'useful', 'quickly and easily', 'সহজে / অনায়াসে', 'The information is readily available online.', 'তথ্যটা অনলাইনে সহজেই পাওয়া যায়।', ['easily']),
  lex('meanwhile', 'adverb', 'useful', 'at the same time; while something else is happening', 'ইতিমধ্যে / একই সময়ে', 'Meanwhile, prices continued to rise.', 'একই সময়ে দাম বাড়তেই থাকল।', ['at the same time']),
  lex('eruption', 'noun', 'useful', 'the sudden explosion of a volcano', 'অগ্ন্যুৎপাত', 'The eruption covered the town in ash.', 'অগ্ন্যুৎপাতে শহরটা ছাইয়ে ঢেকে গেল।'),
  lex('annual', 'adjective', 'core', 'happening once every year', 'বার্ষিক', 'The school holds an annual science fair.', 'স্কুলটা একটা বার্ষিক বিজ্ঞান মেলা করে।', ['yearly']),
  lex('date', 'verb', 'useful', 'to find out how old something is', 'বয়স নির্ধারণ করা', 'Scientists dated the bones to 3,000 years ago.', 'বিজ্ঞানীরা হাড়গুলোর বয়স ৩,০০০ বছর বলে নির্ধারণ করেছেন।'),
  lex('transform', 'verb', 'core', 'to change something completely', 'আমূল পরিবর্তন করা', 'The internet transformed the way we shop.', 'ইন্টারনেট আমাদের কেনাকাটার ধরন আমূল বদলে দিয়েছে।', ['change', 'revolutionise']),
  lex('cycle', 'noun', 'useful', 'a series of events that repeat in the same order', 'চক্র', 'The water cycle moves water between sea, air and land.', 'পানিচক্র সমুদ্র, বাতাস আর ভূমির মধ্যে পানি চলাচল করায়।'),
  lex('by contrast', 'phrase', 'useful', 'used to show a clear difference', 'বিপরীতে / তুলনায়', 'The north is dry; the south, by contrast, is wet.', 'উত্তরাঞ্চল শুষ্ক; বিপরীতে দক্ষিণাঞ্চল আর্দ্র।', ['in contrast']),
  lex('abrupt', 'adjective', 'useful', 'sudden and unexpected', 'আকস্মিক', 'The meeting came to an abrupt end.', 'সভাটা আকস্মিকভাবে শেষ হলো।', ['sudden']),
  lex('cautious', 'adjective', 'useful', 'careful to avoid risks', 'সতর্ক', 'Be cautious when driving in the rain.', 'বৃষ্টিতে গাড়ি চালাতে সতর্ক থাকুন।', ['careful', 'wary']),
  lex('ironically', 'adverb', 'advanced', 'in a way that is the opposite of what you would expect', 'পরিহাসের বিষয় হলো', 'Ironically, the fire station burned down.', 'পরিহাসের বিষয় হলো, দমকল স্টেশনটাই পুড়ে গেল।'),
  lex('glacier', 'noun', 'useful', 'a large mass of ice that moves slowly down a mountain', 'হিমবাহ', 'Many Himalayan glaciers are shrinking.', 'হিমালয়ের অনেক হিমবাহ সংকুচিত হচ্ছে।'),
  lex('percolate', 'verb', 'advanced', '(of a liquid) to pass slowly through something', 'চুঁইয়ে ঢোকা', 'Rainwater percolates through the soil.', 'বৃষ্টির পানি মাটির ভেতর দিয়ে চুঁইয়ে যায়।', ['seep', 'filter']),
  lex('blur', 'verb', 'useful', 'to make something less clear', 'ঝাপসা করা', 'Tears blurred her vision.', 'কান্নায় তাঁর দৃষ্টি ঝাপসা হয়ে গেল।', ['obscure']),
  lex('preserve', 'verb', 'core', 'to keep something safe and in its original state', 'সংরক্ষণ করা', 'The museum preserves old manuscripts.', 'জাদুঘরটা পুরনো পাণ্ডুলিপি সংরক্ষণ করে।', ['protect', 'conserve']),
  lex('instrument', 'noun', 'useful', 'a tool used for scientific measurement', 'যন্ত্র', 'The instrument measures wind speed.', 'যন্ত্রটা বাতাসের গতি মাপে।', ['device', 'tool']),
];

export const PASSAGE: LibraryPassage = {
  id: 'rl-14-ice-cores',
  title: 'Reading the Ice',
  topic: 'Climate',
  level: 'intermediate',
  minutes: 22,
  background: 'Well-established ice-core science: annual layers in Greenland, isotope temperature records, the roughly 800,000-year Antarctic record of carbon dioxide (never far above 300 ppm before the industrial era), abrupt Greenland warming events, and efforts to preserve cores from melting mountain glaciers in Antarctica.',
  paragraphs: [
    'The ice sheets that cover Antarctica and Greenland are more than frozen water. Every year, a fresh layer of snow falls on their surface and is gradually buried by the snow of later years. Under the weight of the layers above, the snow is compressed into solid ice, and tiny pockets of air between the snowflakes are sealed off as bubbles. Over hundreds of thousands of years, this process has created a vertical archive in which the deepest ice is also the oldest, and each bubble contains a sample of the atmosphere as it was when the ice formed.',
    'To read this archive, scientists drill into the ice sheets and extract long cylinders of ice, known as cores. Drilling is slow and technically difficult. Teams work for several summers at remote camps where temperatures rarely rise above freezing, lifting the core to the surface in sections a few metres long. Each section is then cut, labelled and packed in insulated boxes so that it stays frozen during the long journey to a laboratory. The deepest cores are more than three kilometres in length, and the oldest continuous record, from a site in Antarctica, covers roughly 800,000 years.',
    'Once a core reaches the laboratory, it can be analysed in several ways. The air trapped in the bubbles can be released and measured directly, revealing past concentrations of gases such as carbon dioxide and methane. The ice itself records temperature indirectly. Water molecules containing heavier forms of oxygen and hydrogen fall as snow less readily in colder conditions, so the proportion of these heavier forms in each layer acts as a kind of thermometer. Layers of volcanic ash and chemicals, meanwhile, mark major eruptions and can be used to match cores from different parts of the world.',
    'In places where snowfall is heavy, such as central Greenland, the seasons leave visible differences between summer and winter snow. Scientists can count these annual layers, rather like the rings of a tree, to date the ice precisely for tens of thousands of years. In Antarctica, where snowfall is much lighter, the layers are too thin to count, so dates are calculated using models of how the ice has flowed and compressed.',
    'The results have transformed our understanding of the climate. Ice cores show that over the last 800,000 years the Earth has swung repeatedly between long ice ages and shorter warm periods, and that carbon dioxide and temperature have risen and fallen together throughout these cycles. They also show that during this long period, the concentration of carbon dioxide never rose far above about 300 parts per million. Measurements of the modern atmosphere, by contrast, show levels well above 400 parts per million.',
    'Greenland cores revealed another surprise. The climate of the past has not always changed slowly. During the last ice age, temperatures in Greenland repeatedly rose by several degrees within a few decades before falling back more gradually. Many scientists think these jumps were linked to sudden changes in the currents of the North Atlantic Ocean. Such abrupt shifts were once thought impossible, and their discovery has made scientists more cautious about assuming that future change will be smooth and predictable.',
    'Ironically, the archive itself is now under threat. Mountain glaciers in the Alps, the Andes and the Himalayas are melting, and in some of them water from the surface is already percolating downwards and blurring the chemical signals in the ice. To preserve this record before it is lost, one international project has begun collecting cores from threatened glaciers and storing them in a cave dug into the snow in Antarctica, where they can be kept frozen for future scientists with instruments that do not yet exist.',
  ],
  vocab: [
    v('ice sheet', 'ice sheets', 'the huge areas of ice on Antarctica and Greenland', 'এখানে অ্যান্টার্কটিকা ও গ্রিনল্যান্ডের বিশাল বরফের চাদর।'),
    v('layer', ['layer', 'layers'], 'one year’s snow on top of another', 'এখানে প্রতি বছরের তুষারের একটা স্তর।'),
    v('gradually', 'gradually', 'slowly over time', 'এখানে সময়ের সাথে ধীরে ধীরে।'),
    v('bury', 'buried', 'covered by later snow', 'এখানে পরের বছরের তুষারে চাপা পড়া।'),
    v('compress', ['compressed'], 'pressed tightly', 'এখানে চাপে সংকুচিত।'),
    v('seal off', 'sealed off', 'closed completely', 'এখানে বাতাস পুরোপুরি আটকে যাওয়া।'),
    v('vertical', 'vertical', 'going straight down', 'এখানে ওপর থেকে নিচ পর্যন্ত খাড়া।'),
    v('archive', 'archive', 'a record of the past', 'এখানে অতীতের সংরক্ষিত রেকর্ড।'),
    v('sample', 'sample', 'a small amount of ancient air', 'এখানে প্রাচীন বাতাসের একটু নমুনা।'),
    v('atmosphere', 'atmosphere', 'the air of the past', 'এখানে অতীতের বায়ুমণ্ডল।'),
    v('drill', 'drill', 'make deep holes', 'এখানে বরফে গভীর ছিদ্র করা।'),
    v('extract', 'extract', 'take out', 'এখানে বের করে আনা।'),
    v('cylinder', 'cylinders', 'long round pieces', 'এখানে লম্বা গোল বরফখণ্ড।'),
    v('remote', 'remote', 'far from anywhere', 'এখানে লোকালয় থেকে অনেক দূরে।'),
    v('section', 'sections', 'pieces', 'এখানে খণ্ড।'),
    v('continuous', 'continuous', 'without gaps', 'এখানে ফাঁক ছাড়া একটানা রেকর্ড।'),
    v('laboratory', 'laboratory', 'the scientists’ workplace', 'এখানে গবেষণাগার।'),
    v('analyse', 'analysed', 'studied', 'এখানে বিশ্লেষণ করা।'),
    v('trap', 'trapped', 'held inside', 'এখানে বুদবুদে আটকে থাকা।'),
    v('release', 'released', 'let out', 'এখানে বাতাস বের করে আনা।'),
    v('reveal', 'revealing', 'showing', 'এখানে প্রকাশ করা।'),
    v('concentration', 'concentrations', 'amounts in the air', 'এখানে বাতাসে গ্যাসের পরিমাণ।'),
    v('indirectly', 'indirectly', 'through another measurement', 'এখানে সরাসরি নয়, অন্য মাপের মাধ্যমে।'),
    v('molecule', 'molecules', 'tiny units of water', 'এখানে পানির অণু।'),
    v('readily', 'readily', 'easily', 'এখানে সহজে।'),
    v('proportion', 'proportion', 'the share of heavier forms', 'এখানে ভারী রূপের অনুপাত।'),
    v('meanwhile', 'meanwhile', 'also, at the same time', 'এখানে "এদিকে" — আরেকটা বিষয় যোগ করা।'),
    v('eruption', 'eruptions', 'volcanic explosions', 'এখানে আগ্নেয়গিরির অগ্ন্যুৎপাত।'),
    v('visible', 'visible', 'can be seen', 'এখানে চোখে দেখা যায়।'),
    v('annual', 'annual', 'one per year', 'এখানে প্রতি বছরে একটা।'),
    v('date', 'date', 'find the age of', 'এখানে বরফের বয়স নির্ধারণ করা।'),
    v('precisely', 'precisely', 'exactly', 'এখানে নিখুঁতভাবে।'),
    v('transform', 'transformed', 'changed completely', 'এখানে ধারণা আমূল বদলে দিয়েছে।'),
    v('cycle', 'cycles', 'repeated periods of cold and warm', 'এখানে বারবার ফিরে আসা শীতল-উষ্ণ পর্ব।'),
    v('by contrast', 'by contrast', 'showing a big difference', 'এখানে তুলনায় বড় পার্থক্য।'),
    v('abrupt', 'abrupt', 'sudden', 'এখানে আকস্মিক।'),
    v('shift', 'shifts', 'changes', 'এখানে পরিবর্তন।'),
    v('cautious', 'cautious', 'careful', 'এখানে সতর্ক।'),
    v('assume', 'assuming', 'believing without proof', 'এখানে প্রমাণ ছাড়া ধরে নেওয়া।'),
    v('predictable', 'predictable', 'possible to know in advance', 'এখানে আগে থেকে জানা যায় এমন।'),
    v('ironically', 'Ironically', 'strangely, the opposite of what we would want', 'এখানে পরিহাসের বিষয় — যে রেকর্ড জলবায়ু বোঝায়, সেটাই জলবায়ুর কারণে হুমকিতে।'),
    v('threat', 'threat', 'danger', 'এখানে বিপদ।'),
    v('glacier', 'glaciers', 'rivers of ice in mountains', 'এখানে পাহাড়ের হিমবাহ।'),
    v('percolate', 'percolating', 'moving slowly down through the ice', 'এখানে পানি চুঁইয়ে নিচে নামা।'),
    v('blur', 'blurring', 'making unclear', 'এখানে রাসায়নিক সংকেত ঝাপসা করা।'),
    v('preserve', 'preserve', 'keep safe', 'এখানে নিরাপদে সংরক্ষণ করা।'),
    v('store', 'storing', 'keeping', 'এখানে জমা রাখা।'),
    v('instrument', 'instruments', 'scientific tools', 'এখানে বৈজ্ঞানিক যন্ত্র।'),
  ],
  groups: [
    select('tfng', TFNG_I, [
      q('rl14-q1', 'The oldest ice in an ice sheet is found closest to the surface.', 'FALSE', 'Paragraph A: "the deepest ice is also the oldest".', 'Paragraph A: সবচেয়ে গভীর বরফই সবচেয়ে পুরনো — ওপরে নয়, FALSE।', 'the deepest ice is also the oldest'),
      q('rl14-q2', 'Most ice cores are stored in Greenland after drilling.', 'NOT GIVEN', 'The passage does not say where most cores are stored.', 'বেশিরভাগ core কোথায় রাখা হয় তা বলা নেই — NOT GIVEN।'),
      q('rl14-q3', 'Annual layers can be counted as easily in Antarctic ice as in Greenland ice.', 'FALSE', 'Paragraph D: in Antarctica "the layers are too thin to count".', 'Paragraph D: অ্যান্টার্কটিকায় স্তর গোনার পক্ষে খুব পাতলা — FALSE।', 'the layers are too thin to count'),
      q('rl14-q4', 'Carbon dioxide in today’s atmosphere is higher than at any point in the 800,000-year ice record.', 'TRUE', 'Paragraph E: in the record CO₂ "never rose far above about 300 parts per million"; today it is "well above 400".', 'Paragraph E: রেকর্ডে কখনো প্রায় ৩০০-র বেশি হয়নি, আজ ৪০০-র অনেক ওপরে — TRUE।', 'show levels well above 400 parts per million'),
    ]),
    gap('table', 1, [
      gapItem('rl14-q5', ['bubbles'], 'Paragraph C: "The air trapped in the bubbles can be released and measured".', 'Paragraph C: "trapped in the bubbles" — উত্তর bubbles।', 'The air trapped in the bubbles'),
      gapItem('rl14-q6', ['temperature'], 'Paragraph C: "The ice itself records temperature indirectly."', 'Paragraph C: ভারী অক্সিজেন-হাইড্রোজেনের অনুপাত তাপমাত্রা দেখায় — উত্তর temperature।', 'The ice itself records temperature indirectly'),
      gapItem('rl14-q7', ['eruptions'], 'Paragraph C: ash layers "mark major eruptions".', 'Paragraph C: "mark major eruptions" — উত্তর eruptions।', 'mark major eruptions'),
      gapItem('rl14-q8', ['rings'], 'Paragraph D: annual layers are counted "rather like the rings of a tree".', 'Paragraph D: "like the rings of a tree" — উত্তর rings।', 'rather like the rings of a tree'),
    ], {
      title: 'What ice cores record',
      table: {
        head: ['Evidence', 'What it shows'],
        rows: [
          ['Air in the [[rl14-q5]]', 'past levels of gases such as carbon dioxide'],
          ['Heavier forms of oxygen and hydrogen', 'past [[rl14-q6]]'],
          ['Layers of ash and chemicals', 'major volcanic [[rl14-q7]]'],
          ['Annual layers in Greenland', 'years counted like the [[rl14-q8]] of a tree'],
        ],
      },
    }),
    gap('sentence', 2, [
      gapItem('rl14-q9', ['three kilometres', '3 kilometres'], 'Paragraph B: "The deepest cores are more than three kilometres in length".', 'Paragraph B: "more than three kilometres" — উত্তর three kilometres।', 'more than three kilometres in length', 'The deepest ice cores are more than ___ long.'),
      gapItem('rl14-q10', ['degrees'], 'Paragraph F: temperatures "rose by several degrees within a few decades".', 'Paragraph F: "rose by several degrees" — উত্তর degrees।', 'rose by several degrees within a few decades', 'During the last ice age, Greenland temperatures sometimes rose by several ___ within a few decades.'),
    ]),
    select('mcq', MCQ_I, [
      q('rl14-q11', 'How are dates worked out for Antarctic ice?', 'C', 'Paragraph D: "dates are calculated using models of how the ice has flowed and compressed".', 'Paragraph D: বরফ কীভাবে প্রবাহিত ও সংকুচিত হয়েছে তার মডেল দিয়ে — C। স্তর গোনা (A) সেখানে সম্ভব নয়।', 'dates are calculated using models of how the ice has flowed and compressed', abcd('by counting the annual layers', 'by measuring the size of the air bubbles', 'by using models of how the ice has moved and been pressed', 'by comparing them with tree rings')),
      q('rl14-q12', 'Why are some glacier cores being taken to Antarctica?', 'B', 'Paragraph G: "To preserve this record before it is lost".', 'Paragraph G: হিমবাহ গলার আগে রেকর্ড রক্ষা করতে — B।', 'To preserve this record before it is lost', abcd('because Antarctic laboratories have the best instruments', 'to keep the record safe before melting destroys it', 'to compare them with Antarctic ice', 'because mountain glaciers are too difficult to drill')),
    ]),
  ],
};
