import { HEAD_I, TFNG_I, TWO_I, abcd, gap, gapItem, headings, lex, multi, q, select, v } from '../kit';
import type { LexEntry, LibraryPassage } from '../types';

export const LEX: LexEntry[] = [
  lex('reliable', 'adjective', 'core', 'able to be trusted to work well or be correct', 'নির্ভরযোগ্য', 'We need reliable data before we decide.', 'সিদ্ধান্ত নেওয়ার আগে আমাদের নির্ভরযোগ্য তথ্য দরকার।', ['dependable', 'trustworthy']),
  lex('by reference to', 'phrase', 'advanced', 'by using something as a basis for comparison', 'কোনো কিছুর ভিত্তিতে / তুলনা করে', 'The date was fixed by reference to church records.', 'গির্জার নথির ভিত্তিতে তারিখটা নির্ধারণ করা হয়েছিল।'),
  lex('presume', 'verb', 'advanced', 'to believe something is true without proof', 'ধরে নেওয়া / অনুমান করা', 'I presume you have read the instructions.', 'আমি ধরে নিচ্ছি আপনি নির্দেশনাগুলো পড়েছেন।', ['assume', 'suppose']),
  lex('sequence', 'noun', 'useful', 'a series of things in a particular order', 'ক্রম / ধারাবাহিকতা', 'Put the pictures in the correct sequence.', 'ছবিগুলো সঠিক ক্রমে সাজান।', ['order', 'series']),
  lex('possess', 'verb', 'useful', 'to have or own something', 'অধিকারী হওয়া / থাকা', 'The museum possesses many rare coins.', 'জাদুঘরটার কাছে অনেক দুর্লভ মুদ্রা আছে।', ['have', 'own']),
  lex('rest on', 'phrasal verb', 'advanced', 'to depend on or be based on something', 'কোনো কিছুর ওপর নির্ভর করা / ভিত্তি করে থাকা', 'The whole argument rests on one study.', 'পুরো যুক্তিটা একটা গবেষণার ওপর নির্ভর করে।', ['depend on', 'be based on']),
  lex('convert', 'verb', 'core', 'to change something into a different form', 'রূপান্তর করা', 'Solar panels convert sunlight into electricity.', 'সৌর প্যানেল সূর্যের আলোকে বিদ্যুতে রূপান্তর করে।', ['change', 'transform']),
  lex('radioactive', 'adjective', 'advanced', 'giving off energy as a result of atoms breaking apart', 'তেজস্ক্রিয়', 'Radioactive waste must be stored safely.', 'তেজস্ক্রিয় বর্জ্য নিরাপদে সংরক্ষণ করতে হয়।'),
  lex('absorb', 'verb', 'core', 'to take in a liquid, gas, heat or information', 'শোষণ করা / শুষে নেওয়া', 'Dark clothes absorb more heat.', 'গাঢ় রঙের কাপড় বেশি তাপ শোষণ করে।', ['take in', 'soak up']),
  lex('photosynthesis', 'noun', 'useful', 'the process by which plants use sunlight to make food', 'সালোকসংশ্লেষণ', 'Leaves need light for photosynthesis.', 'সালোকসংশ্লেষণের জন্য পাতার আলো দরকার।'),
  lex('tissue', 'noun', 'advanced', 'the material that plants and animals are made of', 'কলা / টিস্যু', 'The doctor examined a sample of skin tissue.', 'ডাক্তার ত্বকের কলার একটা নমুনা পরীক্ষা করলেন।'),
  lex('decay', 'verb / noun', 'useful', 'to break down slowly; (of radioactive atoms) to change into another form', 'ক্ষয় হওয়া', 'Sugar makes teeth decay.', 'চিনি দাঁতের ক্ষয় ঘটায়।', ['break down', 'rot']),
  lex('indicate', 'verb', 'core', 'to show or suggest that something is true', 'নির্দেশ করা / ইঙ্গিত দেওয়া', 'The results indicate a rise in temperature.', 'ফলাফল তাপমাত্রা বৃদ্ধির ইঙ্গিত দেয়।', ['show', 'suggest']),
  lex('colleague', 'noun', 'core', 'a person you work with', 'সহকর্মী', 'She discussed the idea with her colleagues.', 'তিনি সহকর্মীদের সাথে ধারণাটা নিয়ে আলোচনা করলেন।', ['co-worker']),
  lex('built-in', 'adjective', 'useful', 'forming a basic part of something that cannot be separated from it', 'অন্তর্নিহিত / সহজাত', 'The plan has a built-in weakness.', 'পরিকল্পনাটায় একটা অন্তর্নিহিত দুর্বলতা আছে।', ['inherent']),
  lex('precious', 'adjective', 'useful', 'rare and very valuable', 'মূল্যবান', 'Water is precious in the desert.', 'মরুভূমিতে পানি অত্যন্ত মূল্যবান।', ['valuable', 'treasured']),
  lex('assumption', 'noun', 'core', 'something that you believe is true without proof', 'অনুমান / ধারণা', 'The plan is based on the assumption that prices will fall.', 'পরিকল্পনাটা দাম কমবে এই অনুমানের ওপর তৈরি।', ['belief', 'presumption']),
  lex('constant', 'adjective', 'core', 'staying the same; not changing', 'স্থির / অপরিবর্তিত', 'Keep the oven at a constant temperature.', 'চুলাটা একটা স্থির তাপমাত্রায় রাখুন।', ['fixed', 'steady']),
  lex('alter', 'verb', 'useful', 'to change something', 'পরিবর্তন করা', 'The new road altered the shape of the village.', 'নতুন রাস্তা গ্রামটার চেহারা বদলে দিয়েছে।', ['change', 'modify']),
  lex('discrepancy', 'noun', 'advanced', 'a difference between two things that should be the same', 'অসঙ্গতি / গরমিল', 'There is a discrepancy between the two reports.', 'দুটো প্রতিবেদনের মধ্যে গরমিল আছে।', ['difference', 'mismatch']),
  lex('calibration', 'noun', 'advanced', 'the process of checking and adjusting a measuring instrument or method', 'মাপাঙ্কন / সংশোধন', 'The scale needs regular calibration.', 'নিক্তিটার নিয়মিত মাপাঙ্কন দরকার।'),
  lex('periodically', 'adverb', 'useful', 'regularly, at intervals', 'নির্দিষ্ট সময় পরপর', 'The rules are reviewed periodically.', 'নিয়মগুলো নির্দিষ্ট সময় পরপর পর্যালোচনা করা হয়।', ['regularly', 'from time to time']),
  lex('revise', 'verb', 'useful', 'to change something to make it more accurate or up to date', 'সংশোধন করা', 'The government revised its growth forecast.', 'সরকার প্রবৃদ্ধির পূর্বাভাস সংশোধন করেছে।', ['update', 'amend']),
  lex('dramatic', 'adjective', 'useful', 'sudden and very noticeable', 'নাটকীয় / উল্লেখযোগ্য', 'There has been a dramatic rise in prices.', 'দামে নাটকীয় বৃদ্ধি ঘটেছে।', ['striking', 'remarkable']),
  lex('innovation', 'noun', 'core', 'a new idea, method or invention', 'উদ্ভাবন', 'Mobile banking was an important innovation.', 'মোবাইল ব্যাংকিং একটা গুরুত্বপূর্ণ উদ্ভাবন ছিল।', ['invention', 'new idea']),
  lex('monumental', 'adjective', 'advanced', 'very large and built to last; like a monument', 'বিশাল / স্মারকসদৃশ', 'The pyramids are monumental structures.', 'পিরামিডগুলো বিশাল স্থাপনা।'),
  lex('undermine', 'verb', 'useful', 'to make something weaker or less likely to succeed', 'দুর্বল করে দেওয়া', 'The new evidence undermines his argument.', 'নতুন প্রমাণ তাঁর যুক্তিকে দুর্বল করে দেয়।', ['weaken']),
  lex('prompt', 'verb', 'useful', 'to cause someone to do something', 'প্ররোচিত করা / কারণ হওয়া', 'The accident prompted a review of safety rules.', 'দুর্ঘটনাটা নিরাপত্তা নিয়ম পর্যালোচনার কারণ হয়েছে।', ['cause', 'lead to']),
  lex('leap', 'noun', 'useful', 'a big jump or a sudden large improvement', 'লাফ / বড় অগ্রগতি', 'The new phone is a leap forward in design.', 'নতুন ফোনটা নকশায় বড় অগ্রগতি।', ['jump', 'advance']),
  lex('detect', 'verb', 'core', 'to notice or discover something that is difficult to see', 'শনাক্ত করা', 'The test can detect the virus early.', 'পরীক্ষাটা শুরুতেই ভাইরাস শনাক্ত করতে পারে।', ['discover', 'notice']),
  lex('precision', 'noun', 'useful', 'the quality of being exact', 'নির্ভুলতা / সূক্ষ্মতা', 'Surgery requires great precision.', 'অস্ত্রোপচারে অত্যন্ত সূক্ষ্মতা লাগে।', ['accuracy', 'exactness']),
  lex('eliminate', 'verb', 'core', 'to remove something completely', 'দূর করা / সম্পূর্ণ বাদ দেওয়া', 'We cannot eliminate every risk.', 'আমরা সব ঝুঁকি দূর করতে পারি না।', ['remove', 'get rid of']),
  lex('contaminate', 'verb', 'useful', 'to make something dirty or impure by adding something harmful', 'দূষিত করা', 'Waste from the factory contaminated the river.', 'কারখানার বর্জ্য নদীটা দূষিত করেছে।', ['pollute']),
  lex('stem from', 'phrasal verb', 'useful', 'to come from or be caused by something', 'উদ্ভূত হওয়া / কারণ থেকে আসা', 'Her interest in science stems from her childhood.', 'বিজ্ঞানে তাঁর আগ্রহ শৈশব থেকে এসেছে।', ['arise from', 'result from']),
  lex('disruption', 'noun', 'useful', 'a disturbance that stops something from continuing normally', 'বিঘ্ন / ব্যাঘাত', 'The strike caused disruption to train services.', 'ধর্মঘট ট্রেন চলাচলে বিঘ্ন ঘটিয়েছে।', ['disturbance', 'interruption']),
  lex('ban', 'verb', 'core', 'to officially say that something must not be done', 'নিষিদ্ধ করা', 'The city banned plastic bags.', 'শহরটা প্লাস্টিক ব্যাগ নিষিদ্ধ করেছে।', ['prohibit', 'forbid']),
  lex('marker', 'noun', 'useful', 'a sign or feature that shows something', 'চিহ্ন / নির্দেশক', 'The ash layer is a useful time marker.', 'ছাইয়ের স্তরটা সময়ের একটা কাজের চিহ্ন।', ['sign', 'indicator']),
  lex('enable', 'verb', 'core', 'to make it possible for someone to do something', 'সক্ষম করা', 'The scholarship enabled her to study abroad.', 'বৃত্তিটা তাঁকে বিদেশে পড়তে সক্ষম করেছে।', ['allow', 'make possible']),
  lex('forged', 'adjective', 'advanced', 'copied illegally so as to look real', 'জাল', 'The police found forged banknotes.', 'পুলিশ জাল নোট পেয়েছে।', ['fake', 'counterfeit']),
  lex('illegally', 'adverb', 'useful', 'in a way that is against the law', 'অবৈধভাবে', 'The trees were cut down illegally.', 'গাছগুলো অবৈধভাবে কাটা হয়েছিল।', ['unlawfully']),
  lex('occur', 'verb', 'core', 'to happen', 'ঘটা', 'The accident occurred at midnight.', 'দুর্ঘটনাটা মধ্যরাতে ঘটেছে।', ['happen', 'take place']),
];

export const PASSAGE: LibraryPassage = {
  id: 'rl-15-radiocarbon',
  title: 'The Clock in the Carbon',
  topic: 'Archaeology',
  level: 'advanced',
  minutes: 24,
  background: 'Well-established science and history: Willard Libby’s development of radiocarbon dating (Nobel Prize in Chemistry, 1960), the half-life of carbon-14 (about 5,730 years), tree-ring calibration, Colin Renfrew’s 1973 argument about European megaliths, accelerator mass spectrometry, the re-dating of European megalithic tombs, and the "bomb pulse" from nuclear tests.',
  paragraphs: [
    'Until the middle of the twentieth century, archaeologists who wanted to know the age of an object had few reliable tools. Where written records existed, as in ancient Egypt, sites could be dated by reference to lists of kings. Elsewhere, researchers relied on relative methods: a layer of soil lying beneath another was presumed to be older, and pottery styles could be arranged in a sequence. Such techniques could reveal the order of events, but rarely how long ago they had occurred. The development of radiocarbon dating changed this, giving archaeology something it had never possessed: a clock that worked almost everywhere.',
    'The method rests on a natural process high in the atmosphere. Cosmic rays striking the upper atmosphere produce particles that convert a small number of nitrogen atoms into a radioactive form of carbon, carbon-14. This carbon combines with oxygen and mixes through the atmosphere, where plants absorb it during photosynthesis; animals, in turn, take it in when they eat plants. As long as an organism is alive, the proportion of carbon-14 in its tissues remains roughly in balance with that of its environment. When it dies, however, it stops taking in new carbon, and the carbon-14 it contains begins to decay at a steady rate, with half of it disappearing roughly every 5,730 years. Measuring how much remains therefore indicates how long ago death occurred.',
    'The technique was developed in the late 1940s by the American chemist Willard Libby and his colleagues at the University of Chicago. To test it, they measured samples whose age was already known, including wood from ancient Egyptian tombs, and found that the results agreed closely with historical dates. The achievement earned Libby the Nobel Prize in Chemistry in 1960. Yet the method had built-in limits. Because so little carbon-14 survives after many half-lives, material older than about 50,000 years contains too little to measure reliably, and early laboratories needed relatively large samples, which meant destroying precious objects.',
    'More seriously, Libby’s method rested on an assumption that turned out to be false: that the amount of carbon-14 in the atmosphere had always been constant. In fact, it has varied over time, as changes in solar activity and the Earth’s magnetic field altered the rate at which it was produced. By the 1960s, researchers comparing radiocarbon dates with the annual growth rings of very long-lived trees had found discrepancies of several centuries. The solution was calibration. Using tree rings, and later lake sediments, cave formations and corals, scientists have built curves that convert a raw radiocarbon measurement into a calendar date, and these curves are revised periodically as new data emerge.',
    'Calibration had dramatic consequences. For decades, many archaeologists had assumed that major innovations, such as monumental stone architecture, had spread to Europe from the older civilisations of the Near East. Once radiocarbon dates were calibrated, however, some megalithic tombs in western Europe turned out to be older than the Egyptian pyramids, undermining the idea that their builders must have learned from distant civilisations and prompting a reconsideration of how such developments arise. The British archaeologist Colin Renfrew set out this argument in a 1973 book whose subtitle described the change as a radiocarbon revolution. The lesson reached well beyond Europe: a dating method that did not depend on written records allowed each region’s past to be measured on its own terms, rather than by comparison with its more famous neighbours.',
    'A second technical leap came in the late 1970s with accelerator mass spectrometry, which counts carbon-14 atoms directly rather than waiting to detect their decay. The approach requires samples of only a few milligrams, allowing scientists to date a single seed or a fragment of thread without destroying the object it came from. Still, precision does not eliminate error. Samples can be contaminated by younger carbon from groundwater or handling, and dating a piece of wood tells us when the tree died, not when the wood was used: a beam cut from an old tree and reused in a later building can make the building appear centuries older than it is.',
    'Curiously, one of the method’s newest applications stems from a human disruption of the carbon cycle. Nuclear weapons tests in the 1950s and early 1960s nearly doubled the amount of carbon-14 in the atmosphere of the Northern Hemisphere, and the level has been falling steadily since most such tests were banned. This "bomb pulse" provides an unusually precise marker for material formed in recent decades, enabling investigators to identify illegally traded ivory, expose forged wines and works of art, and even estimate how often cells in the human body are replaced.',
  ],
  vocab: [
    v('reliable', 'reliable', 'accurate and trustworthy', 'এখানে নির্ভুল ও বিশ্বাসযোগ্য উপায়।'),
    v('record', 'records', 'written documents about the past', 'এখানে অতীতের লিখিত নথি।', { en: 'a written account of past events', bn: 'লিখিত নথি / দলিল' }),
    v('by reference to', 'by reference to', 'by comparing with', 'এখানে রাজাদের তালিকার সাথে মিলিয়ে।'),
    v('rely on', 'relied on', 'had to use', 'এখানে এসব পদ্ধতির ওপর নির্ভর করতে হতো।'),
    v('relative', 'relative', 'giving order, not exact age', 'এখানে কোনটা আগে-পরে তা বলে, সঠিক বয়স নয় — আপেক্ষিক।', { en: 'compared with something else; not absolute', bn: 'আপেক্ষিক' }),
    v('layer', 'layer', 'a level of soil', 'এখানে মাটির একটা স্তর।'),
    v('presume', 'presumed', 'assumed', 'এখানে ধরে নেওয়া হতো।'),
    v('sequence', 'sequence', 'an order from earlier to later', 'এখানে আগে থেকে পরে সাজানো ক্রম।'),
    v('reveal', 'reveal', 'show', 'এখানে দেখাতে পারত।'),
    v('occur', 'occurred', 'happened', 'এখানে ঘটেছিল।'),
    v('develop', 'development', 'the invention of the method', 'এখানে পদ্ধতিটা উদ্ভাবন।', { en: 'the process of creating something new', bn: 'উদ্ভাবন / বিকাশ' }),
    v('possess', 'possessed', 'had', 'এখানে কখনো ছিল না এমন কিছু।'),
    v('rest on', ['rests on', 'rested on'], 'is based on', 'এখানে পদ্ধতিটা একটা প্রাকৃতিক প্রক্রিয়ার ওপর দাঁড়িয়ে।'),
    v('atmosphere', 'atmosphere', 'the layer of air around the Earth', 'এখানে পৃথিবীর বায়ুমণ্ডল।'),
    v('particle', 'particles', 'tiny pieces of matter', 'এখানে অতিক্ষুদ্র কণা।'),
    v('convert', ['convert'], 'change into', 'এখানে রূপান্তর করা।'),
    v('radioactive', 'radioactive', 'unstable and giving off energy', 'এখানে অস্থির, শক্তি নির্গত করে এমন।'),
    v('absorb', 'absorb', 'take in', 'এখানে গাছ শোষণ করে।'),
    v('photosynthesis', 'photosynthesis', 'how plants use sunlight to make food', 'এখানে গাছের সালোকসংশ্লেষণ।'),
    v('proportion', 'proportion', 'the share of carbon-14', 'এখানে carbon-14-এর অনুপাত।'),
    v('tissue', 'tissues', 'the material of the body', 'এখানে দেহের কলা।'),
    v('decay', ['decay'], 'change into another element over time', 'এখানে সময়ের সাথে অন্য উপাদানে পরিণত হওয়া।', { en: '(of radioactive atoms) to break down into another form', bn: '(তেজস্ক্রিয় পরমাণুর) ক্ষয় হওয়া' }),
    v('indicate', 'indicates', 'shows', 'এখানে নির্দেশ করে।'),
    v('colleague', 'colleagues', 'people he worked with', 'এখানে তাঁর সহকর্মীরা।'),
    v('sample', 'samples', 'pieces of material tested', 'এখানে পরীক্ষা করা নমুনা।'),
    v('built-in', 'built-in', 'part of the method itself', 'এখানে পদ্ধতিরই অন্তর্নিহিত সীমা।'),
    v('survive', 'survives', 'remains', 'এখানে অবশিষ্ট থাকে।'),
    v('reliably', 'reliably', 'accurately', 'এখানে নির্ভরযোগ্যভাবে।'),
    v('relatively', 'relatively', 'fairly', 'এখানে তুলনামূলক বড়।'),
    v('precious', 'precious', 'rare and valuable', 'এখানে দুর্লভ ও মূল্যবান।'),
    v('assumption', 'assumption', 'something believed without proof', 'এখানে প্রমাণ ছাড়া ধরে নেওয়া ধারণা।'),
    v('constant', 'constant', 'unchanging', 'এখানে কখনো বদলায়নি এমন।'),
    v('vary', 'varied', 'changed', 'এখানে সময়ের সাথে বদলেছে।'),
    v('alter', 'altered', 'changed', 'এখানে উৎপাদনের হার বদলে দিয়েছে।'),
    v('annual', 'annual', 'yearly', 'এখানে বার্ষিক বলয়।'),
    v('discrepancy', 'discrepancies', 'differences that should not exist', 'এখানে যে পার্থক্য থাকার কথা নয়।'),
    v('calibration', 'calibration', 'correcting measurements using known dates', 'এখানে জানা তারিখ দিয়ে মাপ সংশোধন করা।'),
    v('sediment', 'sediments', 'layers of mud at the bottom of lakes', 'এখানে হ্রদের তলার পলির স্তর।'),
    v('revise', 'revised', 'updated', 'এখানে হালনাগাদ করা।'),
    v('periodically', 'periodically', 'from time to time', 'এখানে মাঝে মাঝে।'),
    v('emerge', 'emerge', 'become available', 'এখানে নতুন তথ্য পাওয়া যায়।', { en: 'to become known', bn: 'প্রকাশ পাওয়া / জানা যাওয়া' }),
    v('dramatic', 'dramatic', 'very large and surprising', 'এখানে বড় ও চমকপ্রদ।'),
    v('consequence', 'consequences', 'results', 'এখানে ফলাফল।'),
    v('assume', 'assumed', 'believed', 'এখানে ধরে নিয়েছিলেন।'),
    v('innovation', 'innovations', 'new ideas and skills', 'এখানে নতুন ধারণা ও দক্ষতা।'),
    v('monumental', 'monumental', 'huge and long-lasting', 'এখানে বিশাল স্থাপত্য।'),
    v('spread', 'spread', 'moved from one region to another', 'এখানে এক অঞ্চল থেকে আরেক অঞ্চলে ছড়ানো।'),
    v('undermine', 'undermining', 'weakening', 'এখানে ধারণাটাকে দুর্বল করা।'),
    v('distant', 'distant', 'far away', 'এখানে দূরের সভ্যতা।'),
    v('prompt', 'prompting', 'causing', 'এখানে নতুন করে ভাবতে বাধ্য করা।'),
    v('leap', 'leap', 'a big step forward', 'এখানে বড় অগ্রগতি।'),
    v('detect', 'detect', 'notice', 'এখানে ক্ষয় টের পাওয়া।'),
    v('fragment', 'fragment', 'small piece', 'এখানে সুতার ছোট টুকরো।'),
    v('precision', 'precision', 'exactness', 'এখানে নির্ভুলতা।'),
    v('eliminate', 'eliminate', 'remove completely', 'এখানে ভুল সম্পূর্ণ দূর করা।'),
    v('contaminate', 'contaminated', 'mixed with unwanted material', 'এখানে অনাকাঙ্ক্ষিত কার্বন মিশে যাওয়া।'),
    v('stem from', 'stems from', 'comes from', 'এখানে কোনো কিছু থেকে উদ্ভূত।'),
    v('disruption', 'disruption', 'disturbance', 'এখানে প্রাকৃতিক চক্রে ব্যাঘাত।'),
    v('cycle', 'cycle', 'natural movement of carbon', 'এখানে কার্বনের প্রাকৃতিক চক্র।'),
    v('ban', 'banned', 'officially stopped', 'এখানে পরীক্ষা নিষিদ্ধ হওয়া।'),
    v('marker', 'marker', 'a sign that shows age', 'এখানে বয়স বোঝার চিহ্ন।'),
    v('enable', 'enabling', 'making it possible', 'এখানে সম্ভব করে তোলা।'),
    v('identify', 'identify', 'find', 'এখানে শনাক্ত করা।'),
    v('illegally', 'illegally', 'against the law', 'এখানে অবৈধভাবে।'),
    v('forged', 'forged', 'fake', 'এখানে জাল।'),
    v('estimate', 'estimate', 'calculate roughly', 'এখানে আনুমানিক হিসাব করা।'),
    v('replace', 'replaced', 'renewed with new cells', 'এখানে নতুন কোষ দিয়ে প্রতিস্থাপিত হওয়া।'),
  ],
  groups: [
    select('headings', HEAD_I, [
      q('rl15-q1', 'Paragraph B', 'iv', 'B explains how carbon-14 forms, is absorbed and decays.', 'Paragraph B-তে carbon-14 কীভাবে তৈরি, শোষিত ও ক্ষয় হয় — প্রাকৃতিক প্রক্রিয়া থেকে মাপযোগ্য সংকেত, তাই iv।', 'The method rests on a natural process high in the atmosphere'),
      q('rl15-q2', 'Paragraph C', 'i', 'C describes Libby’s tests and the method’s limits.', 'Paragraph C-তে Libby-র পরীক্ষা আর পদ্ধতির সীমাবদ্ধতা — তাই i।', 'Yet the method had built-in limits'),
      q('rl15-q3', 'Paragraph D', 'vii', 'D explains that carbon-14 levels varied and calibration fixed this.', 'Paragraph D-তে ভুল অনুমান আর calibration দিয়ে সংশোধন — তাই vii।', 'The solution was calibration'),
      q('rl15-q4', 'Paragraph E', 'ii', 'E shows how calibrated dates changed ideas about influence from the Near East.', 'Paragraph E-তে সংশোধিত তারিখ সংস্কৃতির প্রভাব নিয়ে পুরনো ধারণা বদলে দেয় — তাই ii।', 'undermining the idea that their builders must have learned from distant civilisations'),
      q('rl15-q5', 'Paragraph F', 'ix', 'F describes smaller samples and new sources of error.', 'Paragraph F-এ ছোট নমুনা সম্ভব হলেও নতুন ভুলের উৎস — তাই ix।', 'precision does not eliminate error'),
      q('rl15-q6', 'Paragraph G', 'v', 'G shows nuclear tests turning into a useful dating tool.', 'Paragraph G-তে মানুষের সৃষ্ট পরিবর্তন (পারমাণবিক পরীক্ষা) কাজের হাতিয়ারে পরিণত — তাই v।', 'stems from a human disruption of the carbon cycle'),
    ], headings(
      'Testing the method and recognising its limits',
      'Rewriting a story of cultural influence',
      'The rising cost of archaeological research',
      'How a natural process creates a measurable signal',
      'A human-made change becomes a useful tool',
      'Why ancient Egyptians recorded their kings',
      'Correcting for a mistaken belief',
      'Methods that have now replaced radiocarbon',
      'Smaller samples, but new sources of error',
    )),
    select('tfng', TFNG_I, [
      q('rl15-q7', 'Libby checked his method using objects whose age was already known.', 'TRUE', 'Paragraph C: "they measured samples whose age was already known".', 'Paragraph C: বয়স আগে থেকে জানা নমুনা দিয়ে পরীক্ষা — TRUE।', 'they measured samples whose age was already known'),
      q('rl15-q8', 'Calibration curves, once published, are never changed.', 'FALSE', 'Paragraph D: the curves "are revised periodically as new data emerge".', 'Paragraph D: curve-গুলো নিয়মিত সংশোধন করা হয় — FALSE।', 'these curves are revised periodically'),
      q('rl15-q9', 'Accelerator mass spectrometry costs less than earlier dating methods.', 'NOT GIVEN', 'Paragraph F describes smaller samples, not cost.', 'Paragraph F ছোট নমুনার কথা বলে, খরচের তুলনা নেই — NOT GIVEN।'),
    ]),
    gap('summary', 2, [
      gapItem('rl15-q10', ['carbon-14'], 'Paragraph B: particles "convert a small number of nitrogen atoms into a radioactive form of carbon, carbon-14".', 'Paragraph B: নাইট্রোজেন থেকে carbon-14 তৈরি হয় — hyphen-যুক্ত তাই একটা word।', 'a radioactive form of carbon, carbon-14'),
      gapItem('rl15-q11', ['photosynthesis'], 'Paragraph B: "plants absorb it during photosynthesis".', 'Paragraph B: "during photosynthesis" — উত্তর photosynthesis।', 'plants absorb it during photosynthesis'),
      gapItem('rl15-q12', ['5,730 years', '5730 years'], 'Paragraph B: half disappears "roughly every 5,730 years".', 'Paragraph B: "roughly every 5,730 years" — সংখ্যা আর years, দুটো word।', 'roughly every 5,730 years'),
    ], {
      numbers: true,
      title: 'How radiocarbon forms and disappears',
      lines: [
        'High in the atmosphere, cosmic rays turn some nitrogen into [[rl15-q10]]. Plants take it in through [[rl15-q11]], and animals take it in by eating plants. After death, no new carbon is absorbed, and half of the radioactive carbon disappears approximately every [[rl15-q12]].',
      ],
    }),
    multi('rl15-q13', TWO_I, 'According to paragraph F, which TWO things can make a radiocarbon date misleading?', abcd('younger carbon getting into the sample', 'using a sample of only a few milligrams', 'wood from an old tree being reused later', 'modern calibration curves', 'cosmic rays reaching the laboratory'), ['A', 'C'], 'Paragraph F: samples "can be contaminated by younger carbon", and "a beam cut from an old tree and reused" can make a building look older.', 'Paragraph F: নতুন কার্বনে দূষণ (A) আর পুরনো গাছের কাঠ পরে ব্যবহার (C)। ছোট নমুনা (B) বরং AMS-এর সুবিধা।', 'Samples can be contaminated by younger carbon'),
    gap('sentence', 1, [
      gapItem('rl15-q15', ['50,000', '50000'], 'Paragraph C: "material older than about 50,000 years contains too little to measure reliably".', 'Paragraph C: "older than about 50,000 years" — উত্তর 50,000।', 'material older than about 50,000 years', 'Radiocarbon dating cannot reliably measure material older than about ___ years.'),
      gapItem('rl15-q16', ['ivory'], 'Paragraph G: the bomb pulse helps "identify illegally traded ivory".', 'Paragraph G: "illegally traded ivory" — উত্তর ivory।', 'identify illegally traded ivory', 'The "bomb pulse" has helped investigators identify illegally traded ___.'),
    ], { numbers: true }),
  ],
};
