import { MCQ_I, NAMES_I, YNNG_I, abcd, gap, gapItem, lex, named, q, select, v } from '../kit';
import type { LexEntry, LibraryPassage } from '../types';

export const LEX: LexEntry[] = [
  lex('solitary', 'adjective', 'useful', 'done or living alone, without other people', 'একাকী / নিঃসঙ্গ', 'He enjoys solitary walks by the river.', 'তিনি নদীর ধারে একা হাঁটতে পছন্দ করেন।', ['lone', 'single']),
  lex('scepticism', 'noun', 'advanced', 'an attitude of doubting that something is true or useful', 'সংশয় / সন্দেহপ্রবণতা', 'The new plan was met with scepticism.', 'নতুন পরিকল্পনাটা সংশয়ের মুখে পড়ল।', ['doubt', 'disbelief']),
  lex('insight', 'noun', 'useful', 'a clear, sudden understanding of something', 'গভীর উপলব্ধি / অন্তর্দৃষ্টি', 'The book gives real insight into village life.', 'বইটা গ্রামীণ জীবন সম্পর্কে সত্যিকারের উপলব্ধি দেয়।', ['understanding', 'realisation']),
  lex('distortion', 'noun', 'advanced', 'a change that makes something false or misleading', 'বিকৃতি', 'The report was a distortion of the facts.', 'প্রতিবেদনটা ছিল তথ্যের বিকৃতি।', ['misrepresentation', 'twisting']),
  lex('assemble', 'verb', 'useful', 'to collect things or people together in one place', 'জড়ো করা / সংগ্রহ করা', 'She assembled a team of experts.', 'তিনি বিশেষজ্ঞদের একটা দল গড়ে তুললেন।', ['gather', 'collect']),
  lex('independently', 'adverb', 'core', 'separately, without help or contact from others', 'স্বাধীনভাবে / আলাদাভাবে', 'The two students solved the problem independently.', 'দুই শিক্ষার্থী আলাদাভাবে সমস্যাটার সমাধান করল।', ['separately', 'alone']),
  lex('inevitable', 'adjective', 'useful', 'certain to happen and impossible to avoid', 'অনিবার্য / অবশ্যম্ভাবী', 'Some delay was inevitable in such heavy rain.', 'এত ভারী বৃষ্টিতে কিছুটা দেরি অনিবার্য ছিল।', ['unavoidable', 'certain']),
  lex('coincidence', 'noun', 'useful', 'two things happening together by chance', 'কাকতালীয় ঘটনা', 'It was a coincidence that we met at the station.', 'স্টেশনে আমাদের দেখা হওয়াটা ছিল কাকতালীয়।', ['chance', 'accident']),
  lex('bound to', 'phrase', 'useful', 'very likely or certain to happen', 'ঘটবেই / নিশ্চিতভাবে', 'If you practise every day, you are bound to improve.', 'প্রতিদিন অনুশীলন করলে আপনার উন্নতি হবেই।', ['certain to', 'sure to']),
  lex('transmit', 'verb', 'core', 'to send a signal, message or information from one place to another', 'প্রেরণ করা / পাঠানো', 'The station transmits news every hour.', 'কেন্দ্রটা প্রতি ঘণ্টায় খবর প্রচার করে।', ['send', 'broadcast']),
  lex('submit', 'verb', 'core', 'to formally give a document to someone for a decision', 'জমা দেওয়া', 'Please submit your application by Friday.', 'অনুগ্রহ করে শুক্রবারের মধ্যে আপনার আবেদন জমা দিন।', ['hand in', 'present']),
  lex('comparable', 'adjective', 'useful', 'similar enough to be compared', 'তুলনীয় / প্রায় একই রকম', 'Prices in the two cities are comparable.', 'দুই শহরের দাম প্রায় একই রকম।', ['similar', 'equivalent']),
  lex('coin', 'verb', 'advanced', 'to invent a new word or phrase', 'নতুন শব্দ তৈরি করা', 'Who coined the word "podcast"?', '"podcast" শব্দটা কে তৈরি করেছিলেন?', ['invent', 'create']),
  lex('simultaneous', 'adjective', 'useful', 'happening at exactly the same time', 'একযোগে / একই সময়ে ঘটা', 'There were simultaneous protests in five cities.', 'পাঁচটা শহরে একই সময়ে বিক্ষোভ হয়েছিল।', ['concurrent', 'parallel']),
  lex('in disguise', 'phrase', 'advanced', 'looking like something else, so the true nature is hidden', 'ছদ্মবেশে / আসল রূপ লুকানো অবস্থায়', 'The delay was a blessing in disguise.', 'দেরিটা আসলে ছদ্মবেশে আশীর্বাদ ছিল।', ['hidden', 'disguised']),
  lex('priority', 'noun', 'useful', 'something that is more important than other things', 'অগ্রাধিকার', 'Safety is our first priority.', 'নিরাপত্তা আমাদের প্রথম অগ্রাধিকার।', ['precedence', 'first concern']),
  lex('dispute', 'noun / verb', 'core', 'a serious disagreement; to argue that something is not true or right', 'বিরোধ / বিবাদ; প্রশ্ন তোলা', 'The two families had a long dispute over land.', 'দুই পরিবারের মধ্যে জমি নিয়ে দীর্ঘ বিরোধ ছিল।', ['argument', 'disagreement']),
  lex('plagiarism', 'noun', 'advanced', 'copying someone else’s work or ideas and presenting them as your own', 'চৌর্যবৃত্তি / অন্যের লেখা নকল করা', 'The essay was rejected for plagiarism.', 'চৌর্যবৃত্তির কারণে প্রবন্ধটা বাতিল হলো।', ['copying', 'theft of ideas']),
  lex('credit', 'noun', 'core', 'praise or recognition for something someone has done', 'কৃতিত্ব / স্বীকৃতি', 'She deserves credit for the team’s success.', 'দলের সাফল্যের কৃতিত্ব তাঁর প্রাপ্য।', ['recognition', 'acknowledgement']),
  lex('misplaced', 'adjective', 'advanced', 'given to the wrong person or thing', 'ভুল জায়গায় দেওয়া / অনুচিত', 'His trust in the company was misplaced.', 'কোম্পানির ওপর তাঁর আস্থা ছিল ভুল জায়গায়।', ['mistaken', 'wrongly given']),
  lex('defensible', 'adjective', 'advanced', 'able to be supported with good reasons', 'যুক্তি দিয়ে সমর্থনযোগ্য', 'Her decision was difficult but defensible.', 'তাঁর সিদ্ধান্ত কঠিন হলেও যুক্তিসংগত ছিল।', ['justifiable', 'reasonable']),
  lex('modest', 'adjective', 'core', 'not large, extreme or ambitious', 'পরিমিত / সাদামাটা', 'They live in a modest house near the market.', 'তাঁরা বাজারের কাছে একটা সাদামাটা বাড়িতে থাকেন।', ['limited', 'moderate']),
  lex('collective', 'adjective', 'useful', 'done or shared by all members of a group', 'সম্মিলিত / যৌথ', 'Cleaning the park was a collective effort.', 'পার্ক পরিষ্কার করা ছিল সম্মিলিত প্রচেষ্টা।', ['shared', 'joint']),
  lex('circulate', 'verb', 'useful', 'to move or pass from person to person or place to place', 'ছড়িয়ে পড়া / প্রচলিত হওয়া', 'Rumours circulate quickly in a small town.', 'ছোট শহরে গুজব দ্রুত ছড়ায়।', ['spread', 'pass around']),
];

export const PASSAGE: LibraryPassage = {
  id: 'rl-16-lone-inventor',
  title: 'The Myth of the Lone Inventor',
  topic: 'Innovation',
  level: 'advanced',
  minutes: 24,
  background: 'Well-established history of science: Ogburn and Thomas’s 1922 paper "Are Inventions Inevitable?" (148 cases), Newton and Leibniz and calculus, Darwin and Wallace, Scheele and Priestley and oxygen, the Bell and Gray telephone filings of 14 February 1876, Antonio Meucci, Robert Merton’s 1961 work on "multiples", and Stigler’s law of eponymy (1980). The opinions are the writer’s own.',
  paragraphs: [
    'Popular histories of invention tend to follow a familiar pattern. A solitary genius, working against the scepticism of those around them, experiences a sudden flash of insight and changes the world. Thomas Edison and the light bulb, Alexander Graham Bell and the telephone, James Watt and the steam engine: the names are attached to the objects as though each could not have existed without the other. The story is appealing, partly because it is simple and partly because it flatters the belief that individual brilliance drives history. Yet a close look at the record suggests that it is, at best, a half-truth, and at worst a serious distortion of how new ideas actually come about.',
    'One of the most striking pieces of evidence against the lone-genius view was assembled a century ago. In 1922, the American sociologists William Ogburn and Dorothy Thomas published a paper entitled "Are Inventions Inevitable?", in which they listed 148 cases where the same discovery or invention had been made by two or more people working independently of one another. The list included calculus, developed by Isaac Newton in England and Gottfried Leibniz in Germany in the late seventeenth century; the theory of evolution by natural selection, reached separately by Charles Darwin and Alfred Russel Wallace; and the discovery of oxygen, achieved by Carl Wilhelm Scheele in Sweden and Joseph Priestley in England within a few years of each other. Ogburn and Thomas argued that such coincidences were far too common to be accidental. Once the necessary knowledge and tools existed in a culture, they suggested, certain inventions became almost bound to appear.',
    'The telephone offers perhaps the most dramatic example. On 14 February 1876, Bell’s lawyer submitted a patent application for a device to transmit speech electrically; on the very same day, the inventor Elisha Gray filed a document with the patent office describing a similar design. Which of the two had arrived first became the subject of years of legal argument, and Bell’s patent survived a large number of court challenges. What is rarely mentioned in popular accounts is that others, including the Italian-born Antonio Meucci, had been experimenting with comparable devices for years. The patent system, which grants rights to a single applicant, tends to turn what was really a crowded race into a story with only one winner.',
    'In 1961, the sociologist Robert Merton went further. He coined the term "multiples" for simultaneous discoveries and argued that they were not the exception in science but the rule. Discoveries that appear to have been made only once, which he called "singletons", were in his view often multiples in disguise: either rivals had been working on the same problem but abandoned it when someone else published first, or their work had simply been forgotten. Merton also pointed out that scientists themselves behave as though they know this. The intense disputes over priority that run through the history of science only make sense if researchers fear, often correctly, that someone else is close behind them. Newton and Leibniz, for instance, became involved in a bitter dispute in which each side accused the other of plagiarism.',
    'If credit is often disputed, it is also frequently misplaced. In 1980 the statistician Stephen Stigler proposed, with deliberate humour, that no scientific discovery is named after its original discoverer. He noted that the idea itself could be traced to earlier thinkers, including Merton, and so illustrated its own point. Stigler’s law is an exaggeration, but it captures something real: names tend to attach themselves to those who were already famous, who explained an idea most clearly, or who happened to be in the right country, rather than to those who came first.',
    'None of this means that individuals do not matter. Someone still has to do the difficult work of turning a possibility into a reality, and the skill, persistence and resources required are unevenly distributed. Darwin’s decades of careful observation gave his theory a depth that a short paper alone could not, which helps explain why his name, rather than Wallace’s, became attached to it. Nor does the evidence show that every invention was inevitable; historians still debate how long some discoveries might have been delayed without a particular person. The most defensible conclusion, it seems to me, is a modest one: individuals shape the timing and the form of an innovation, but the broader conditions of an age decide what is possible in the first place.',
    'This matters beyond the history books. Governments and funding bodies that believe in lone geniuses may concentrate resources on a few celebrated figures, whereas a more accurate picture would favour building the shared conditions from which many innovators can emerge: good education, open publication, well-equipped laboratories and the networks through which ideas circulate. Schools, too, might do better to present invention as a collective and cumulative achievement. Students who learn only the myth may conclude that creativity is a rare gift they do not possess, when history suggests that it is more often the product of being well prepared at the right moment.',
  ],
  vocab: [
    v('solitary', 'solitary', 'working alone', 'এখানে একা কাজ করা প্রতিভাবান মানুষ।'),
    v('scepticism', 'scepticism', 'doubt from other people', 'এখানে আশপাশের মানুষের সন্দেহ।'),
    v('insight', 'insight', 'a sudden clear idea', 'এখানে হঠাৎ আসা পরিষ্কার উপলব্ধি।'),
    v('individual', 'individual', 'belonging to one person', 'এখানে একজন মানুষের নিজস্ব প্রতিভা।', { en: 'relating to one single person', bn: 'ব্যক্তিগত / একক' }),
    v('distortion', 'distortion', 'a false picture', 'এখানে আসল ঘটনার বিকৃত ছবি।'),
    v('assemble', 'assembled', 'collected together', 'এখানে প্রমাণ জড়ো করা হয়েছিল।'),
    v('inevitable', 'inevitable', 'certain to happen', 'এখানে যা ঘটবেই, এড়ানো যায় না।'),
    v('independently', 'independently', 'without contact with each other', 'এখানে একে অপরের সাথে যোগাযোগ ছাড়া আলাদাভাবে।'),
    v('coincidence', 'coincidences', 'things happening together by chance', 'এখানে কাকতালীয়ভাবে একসাথে ঘটা।'),
    v('bound to', 'bound to', 'almost certain to', 'এখানে প্রায় নিশ্চিতভাবে আসবেই।'),
    v('submit', 'submitted', 'formally gave in', 'এখানে পেটেন্টের আবেদন জমা দিয়েছিলেন।'),
    v('transmit', 'transmit', 'send', 'এখানে কথা বিদ্যুতের মাধ্যমে পাঠানো।'),
    v('patent', 'patent', 'an official right to an invention', 'এখানে উদ্ভাবনের সরকারি স্বত্ব।'),
    v('comparable', 'comparable', 'similar', 'এখানে প্রায় একই রকম যন্ত্র।'),
    v('coin', 'coined', 'invented a new term', 'এখানে "multiples" শব্দটা প্রথম তৈরি করলেন।'),
    v('simultaneous', 'simultaneous', 'made at the same time', 'এখানে একই সময়ে হওয়া আবিষ্কার।'),
    v('in disguise', 'in disguise', 'hidden, not recognised', 'এখানে আসলে multiple, কিন্তু সেটা লুকিয়ে আছে।'),
    v('priority', 'priority', 'being the first', 'এখানে কে প্রথম আবিষ্কার করেছেন সেই দাবি।', { en: 'the right to be recognised as first', bn: 'প্রথম হওয়ার দাবি / অগ্রাধিকার' }),
    v('dispute', ['disputes', 'dispute', 'disputed'], 'argument; argued about', 'এখানে তীব্র বিবাদ / কৃতিত্ব নিয়ে প্রশ্ন।'),
    v('plagiarism', 'plagiarism', 'copying another’s work', 'এখানে অন্যের কাজ চুরি করার অভিযোগ।'),
    v('credit', 'credit', 'recognition for a discovery', 'এখানে আবিষ্কারের কৃতিত্ব।'),
    v('misplaced', 'misplaced', 'given to the wrong person', 'এখানে ভুল মানুষকে দেওয়া।'),
    v('trace to', 'traced to', 'shown to come from', 'এখানে ধারণার উৎস আগের চিন্তাবিদদের কাছে পাওয়া যায়।'),
    v('illustrate', 'illustrated', 'showed by example', 'এখানে নিজেই নিজের কথার উদাহরণ হলো।'),
    v('exaggerate', 'exaggeration', 'a claim that goes too far', 'এখানে অতিরঞ্জন — পুরোপুরি সত্য নয়।', { en: 'a statement that makes something seem bigger than it is', bn: 'অতিরঞ্জন' }),
    v('persistence', 'persistence', 'refusing to give up', 'এখানে হাল না ছেড়ে লেগে থাকা।', { en: 'continuing to try even when something is difficult', bn: 'অধ্যবসায় / লেগে থাকা' }),
    v('resource', 'resources', 'money, equipment and support', 'এখানে টাকা, যন্ত্রপাতি ও সুবিধা।'),
    v('defensible', 'defensible', 'supported by good reasons', 'এখানে যুক্তি দিয়ে সমর্থন করা যায় এমন।'),
    v('modest', 'modest', 'limited, not extreme', 'এখানে পরিমিত, বাড়াবাড়ি নয় এমন সিদ্ধান্ত।'),
    v('innovation', 'innovation', 'a new invention or idea', 'এখানে নতুন উদ্ভাবন।'),
    v('figure', 'figures', 'well-known people', 'এখানে বিখ্যাত ব্যক্তিরা।', { en: 'an important or well-known person', bn: 'বিশিষ্ট ব্যক্তি' }),
    v('emerge', 'emerge', 'appear and develop', 'এখানে নতুন উদ্ভাবক তৈরি হয়ে ওঠা।', { en: 'to appear or develop', bn: 'উঠে আসা / আবির্ভূত হওয়া' }),
    v('circulate', 'circulate', 'pass between people', 'এখানে ধারণা মানুষে মানুষে ছড়িয়ে পড়ে।'),
    v('collective', 'collective', 'shared by many people', 'এখানে অনেক মানুষের যৌথ অর্জন।'),
    v('cumulative', 'cumulative', 'built up step by step', 'এখানে ধাপে ধাপে জমে ওঠা অর্জন।'),
  ],
  groups: [
    select('ynng', YNNG_I, [
      q('rl16-q1', 'The popular story of the lone inventor is completely accurate.', 'NO', 'Paragraph A: the writer calls it "at best, a half-truth".', 'Paragraph A: লেখক একে "at best, a half-truth" (বড়জোর অর্ধসত্য) বলেছেন — তাই completely accurate নয়, NO।', 'at best, a half-truth'),
      q('rl16-q2', 'The patent system gives a misleading picture of how the telephone was developed.', 'YES', 'Paragraph C: the system turns "a crowded race into a story with only one winner".', 'Paragraph C: patent system ভিড়ে ভরা প্রতিযোগিতাকে এক বিজয়ীর গল্প বানিয়ে দেয় — লেখক একমত, YES।', 'turn what was really a crowded race into a story with only one winner'),
      q('rl16-q3', 'Stigler’s law should be understood as literally true.', 'NO', 'Paragraph E: "Stigler’s law is an exaggeration".', 'Paragraph E: লেখক বলেছেন এটা অতিরঞ্জন (exaggeration) — আক্ষরিক সত্য নয়, তাই NO।', 'is an exaggeration'),
      q('rl16-q4', 'Individual inventors have little effect on innovation.', 'NO', 'Paragraph F: "individuals shape the timing and the form of an innovation".', 'Paragraph F: ব্যক্তি উদ্ভাবনের সময় ও রূপ ঠিক করেন — "little effect" লেখকের মতের বিপরীত, NO।', 'individuals shape the timing and the form of an innovation'),
      q('rl16-q5', 'Governments today spend too little on scientific research overall.', 'NOT GIVEN', 'Paragraph G is about how resources are divided, not the total amount spent.', 'Paragraph G বলে সম্পদ কীভাবে ভাগ হয়, মোট খরচ কম না বেশি তা নিয়ে লেখকের মত নেই — NOT GIVEN।'),
      q('rl16-q6', 'Schools should present invention as a shared effort that builds up over time.', 'YES', 'Paragraph G: schools "might do better to present invention as a collective and cumulative achievement".', 'Paragraph G: collective (যৌথ) আর cumulative (ধাপে ধাপে জমা) — লেখকের মতের সাথে মেলে, YES।', 'present invention as a collective and cumulative achievement'),
    ]),
    select('names', NAMES_I, [
      q('rl16-q7', 'claimed, not entirely seriously, that discoveries are named after the wrong person', 'C', 'Paragraph E: Stigler proposed, "with deliberate humour", that no discovery is named after its original discoverer.', 'Paragraph E: Stigler মজা করে বলেছিলেন আবিষ্কারের নাম আসল আবিষ্কারকের নামে হয় না — C।', 'no scientific discovery is named after its original discoverer'),
      q('rl16-q8', 'produced a list of discoveries made separately by more than one person', 'A', 'Paragraph B: Ogburn and Thomas "listed 148 cases" of independent discovery.', 'Paragraph B: Ogburn আর Thomas ১৪৮টা ঘটনার তালিকা করেছিলেন — A।', 'they listed 148 cases'),
      q('rl16-q9', 'suggested that apparently unique discoveries may hide forgotten rivals', 'B', 'Paragraph D: Merton said "singletons" were often "multiples in disguise".', 'Paragraph D: Merton-এর মতে একবার হওয়া আবিষ্কারও প্রায়ই লুকানো multiple — B।', 'often multiples in disguise'),
      q('rl16-q10', 'described a similar device on the same day as a rival', 'D', 'Paragraph C: "on the very same day, the inventor Elisha Gray filed a document".', 'Paragraph C: একই দিনে Elisha Gray একটা নথি জমা দিয়েছিলেন — D।', 'on the very same day, the inventor Elisha Gray filed a document'),
    ], named('William Ogburn and Dorothy Thomas', 'Robert Merton', 'Stephen Stigler', 'Elisha Gray')),
    select('mcq', MCQ_I, [
      q('rl16-q11', 'Why does the writer mention the argument between Newton and Leibniz in paragraph D?', 'A', 'Paragraph D: priority disputes "only make sense if researchers fear … that someone else is close behind them"; Newton and Leibniz are the example.', 'Paragraph D: কৃতিত্ব নিয়ে বিবাদ দেখায় গবেষকেরা জানেন প্রতিযোগী কাছেই আছে — Newton-Leibniz তার উদাহরণ, তাই A। তাঁরা একসাথে কাজ করেননি, আদালতের কথাও নেই।', 'someone else is close behind them', abcd(
        'to show that scientists are aware of competition from others',
        'to show that the two men worked together on calculus',
        'to explain how a court settled a question of priority',
        'to suggest that Newton knew nothing of Leibniz’s work',
      )),
      q('rl16-q12', 'What is the writer’s main conclusion in paragraph F?', 'D', 'Paragraph F: "individuals shape the timing and the form of an innovation, but the broader conditions of an age decide what is possible".', 'Paragraph F: ব্যক্তি গুরুত্বপূর্ণ, কিন্তু যুগের পরিস্থিতি সীমা ঠিক করে — তাই D। Historians একমত নন (C ভুল), Darwin-এর কৃতিত্ব কমানোর কথা নেই (B ভুল)।', 'the broader conditions of an age decide what is possible', abcd(
        'Most inventions would have appeared at the same moment without their inventors.',
        'Darwin deserves less credit than he usually receives.',
        'Historians now agree that every invention was inevitable.',
        'Individuals matter, but within limits set by their time.',
      )),
    ]),
    gap('summary', 2, [
      gapItem('rl16-q13', ['148'], 'Paragraph B: "they listed 148 cases".', 'Paragraph B: "listed 148 cases" — উত্তর 148।', 'they listed 148 cases'),
      gapItem('rl16-q14', ['oxygen'], 'Paragraph B: "the discovery of oxygen" by Scheele and Priestley.', 'Paragraph B: Scheele আর Priestley — "the discovery of oxygen"। উত্তর oxygen।', 'the discovery of oxygen'),
      gapItem('rl16-q15', ['tools'], 'Paragraph B: "Once the necessary knowledge and tools existed".', 'Paragraph B: "knowledge and tools" — knowledge আগেই আছে, তাই উত্তর tools।', 'the necessary knowledge and tools existed'),
      gapItem('rl16-q16', ['court challenges'], 'Paragraph C: "Bell’s patent survived a large number of court challenges".', 'Paragraph C: "survived a large number of court challenges" — উত্তর court challenges।', 'court challenges'),
    ], {
      numbers: true,
      title: 'Discoveries made more than once',
      lines: [
        'In 1922, Ogburn and Thomas described [[rl16-q13]] cases in which the same discovery was made by people working separately. One of these was the discovery of [[rl16-q14]] in Sweden and England. The two sociologists concluded that once the necessary knowledge and [[rl16-q15]] were available, certain inventions were almost certain to appear. A similar race took place over the telephone, and Bell’s patent survived many [[rl16-q16]].',
      ],
    }),
  ],
};
