import { INFO_I, MCQ_I, TFNG_I, abcd, gap, gapItem, lex, q, select, v } from '../kit';
import type { LexEntry, LibraryPassage } from '../types';

export const LEX: LexEntry[] = [
  lex('wear away', 'phrasal verb', 'useful', 'to become thinner or disappear slowly through use or rubbing', 'ক্ষয়ে যাওয়া', 'The steps have worn away over the years.', 'বছরের পর বছর ব্যবহারে সিঁড়িগুলো ক্ষয়ে গেছে।', ['erode', 'rub away']),
  lex('inspect', 'verb', 'core', 'to look at something carefully to check its condition', 'পরিদর্শন করা / খুঁটিয়ে দেখা', 'Engineers inspect the bridge every year.', 'প্রকৌশলীরা প্রতি বছর সেতুটা পরিদর্শন করেন।', ['examine', 'check']),
  lex('defect', 'noun', 'useful', 'a fault or weakness in something', 'ত্রুটি', 'The phones were returned because of a defect.', 'একটা ত্রুটির কারণে ফোনগুলো ফেরত দেওয়া হলো।', ['fault', 'flaw']),
  lex('unnoticed', 'adjective', 'useful', 'not seen or noticed by anyone', 'কারও চোখে না পড়া', 'The mistake went unnoticed for weeks.', 'ভুলটা কয়েক সপ্তাহ কারও চোখে পড়েনি।', ['unseen', 'undetected']),
  lex('candidate', 'noun', 'useful', 'a person applying for a job or election; something suitable for a purpose', 'প্রার্থী / উপযুক্ত বিকল্প', 'Three candidates applied for the post.', 'পদটার জন্য তিনজন প্রার্থী আবেদন করেছিলেন।', ['applicant', 'possible choice']),
  lex('comparatively', 'adverb', 'advanced', 'when compared with something else', 'তুলনামূলকভাবে', 'The test was comparatively easy.', 'পরীক্ষাটা তুলনামূলকভাবে সহজ ছিল।', ['relatively', 'fairly']),
  lex('reinforce', 'verb', 'useful', 'to make something stronger by adding support or material', 'মজবুত করা / শক্তিশালী করা', 'The wall was reinforced with steel.', 'দেয়ালটা ইস্পাত দিয়ে মজবুত করা হয়েছিল।', ['strengthen', 'support']),
  lex('rust', 'verb / noun', 'core', 'to become covered with a red-brown layer when iron or steel reacts with water and air', 'মরিচা ধরা', 'The old gate has started to rust.', 'পুরোনো গেটটায় মরিচা ধরতে শুরু করেছে।', ['corrode']),
  lex('expand', 'verb', 'core', 'to become larger', 'প্রসারিত হওয়া / বড় হওয়া', 'Metal expands when it is heated.', 'তাপ দিলে ধাতু প্রসারিত হয়।', ['grow', 'swell']),
  lex('maintenance', 'noun', 'core', 'the work of keeping something in good condition', 'রক্ষণাবেক্ষণ', 'Old buildings need regular maintenance.', 'পুরোনো ভবনের নিয়মিত রক্ষণাবেক্ষণ দরকার।', ['upkeep', 'repair']),
  lex('seep', 'verb', 'advanced', 'to flow slowly through small holes or spaces', 'চুইয়ে ঢোকা', 'Rainwater seeped through the roof.', 'বৃষ্টির পানি ছাদ দিয়ে চুইয়ে ঢুকল।', ['leak', 'trickle']),
  lex('catalyst', 'noun', 'advanced', 'a substance that makes a chemical reaction happen faster', 'অনুঘটক', 'Heat acts as a catalyst in the reaction.', 'বিক্রিয়ায় তাপ অনুঘটকের কাজ করে।', ['trigger', 'accelerator']),
  lex('bond', 'verb', 'useful', 'to join two things firmly together', 'জোড়া লাগানো / আটকে যাওয়া', 'This glue bonds wood and metal.', 'এই আঠা কাঠ আর ধাতু জোড়া লাগায়।', ['join', 'stick']),
  lex('lifespan', 'noun', 'useful', 'the length of time something lives or lasts', 'আয়ুষ্কাল', 'A good battery has a long lifespan.', 'ভালো ব্যাটারির আয়ুষ্কাল দীর্ঘ।', ['life', 'duration']),
  lex('dismiss', 'verb', 'useful', 'to decide that something is not important or worth considering', 'গুরুত্ব না দিয়ে উড়িয়ে দেওয়া', 'At first, the idea was dismissed as foolish.', 'প্রথমে ধারণাটাকে বোকামি বলে উড়িয়ে দেওয়া হয়েছিল।', ['reject', 'disregard']),
  lex('dissolve', 'verb', 'core', 'to mix with a liquid and become part of it', 'দ্রবীভূত হওয়া / গলে মিশে যাওয়া', 'Sugar dissolves in hot tea.', 'গরম চায়ে চিনি গলে মিশে যায়।', ['melt', 'break down']),
  lex('accelerated', 'adjective', 'advanced', 'made to happen faster than normal', 'ত্বরান্বিত / দ্রুততর করা', 'The course follows an accelerated timetable.', 'কোর্সটা একটা দ্রুততর সময়সূচি মেনে চলে।', ['speeded-up', 'faster']),
];

export const PASSAGE: LibraryPassage = {
  id: 'rl-17-self-healing',
  title: 'Materials That Mend Themselves',
  topic: 'Science',
  level: 'advanced',
  minutes: 24,
  background: 'Well-established research: Henk Jonkers’s bacterial concrete at Delft University of Technology, the self-healing plastic described by Scott White’s team at the University of Illinois in 2001 and later vascular versions, induction-healing asphalt (Erik Schlangen, Delft), and the 2023 MIT-led study of lime lumps in Roman concrete. Cement’s share of global CO₂ emissions (roughly 8%) is a commonly cited estimate.',
  paragraphs: [
    'Every material eventually fails. Bridges crack, road surfaces break apart and the coatings that protect aircraft and ships wear away. For most of history, the response has been the same: inspect structures regularly, repair the damage by hand and, when repair is no longer possible, replace the whole thing. This approach is expensive, and it often comes too late, because small defects can grow unnoticed until they become serious. Over the past few decades, however, a different idea has attracted growing interest among engineers. Rather than waiting for people to fix damage, why not design materials that can repair themselves, much as a cut in human skin gradually closes?',
    'Concrete is the most obvious candidate. It is the most widely used manufactured material on Earth, and the production of cement, its key ingredient, is responsible for roughly eight per cent of global carbon dioxide emissions. Concrete is strong when squeezed but comparatively weak when stretched, so almost all concrete structures develop tiny cracks during their lifetime. These are not dangerous in themselves, but they allow water and dissolved chemicals to reach the steel bars that reinforce most concrete. Once the steel begins to rust, it expands, forcing the cracks wider and weakening the structure from within. Extending the life of concrete, therefore, would reduce not only maintenance costs but also the need to produce new cement.',
    'One of the best-known solutions was developed at Delft University of Technology in the Netherlands by the microbiologist Henk Jonkers. His approach relies on bacteria that can survive in extreme environments. Spores of these bacteria are mixed into the concrete together with a food source, calcium lactate. Inside dry concrete, the spores remain inactive, and they can stay that way for decades. When a crack forms and water seeps in, however, the spores become active, feed on the calcium lactate and produce limestone, which gradually fills the gap. In laboratory tests the method has sealed cracks less than a millimetre wide, and versions of it are now sold commercially for structures in which leaks are a particular concern.',
    'Concrete is not the only material to have been given this ability. In 2001, a team at the University of Illinois led by the engineer Scott White described a plastic that contained tiny capsules filled with a liquid healing agent. When a crack spread through the material, it broke open the capsules in its path, releasing the liquid, which then reacted with a catalyst scattered through the plastic and hardened, bonding the two sides of the crack together. Later versions replaced the capsules with networks of fine channels, inspired by blood vessels, which can deliver healing agent to the same spot more than once. Some coatings for cars and mobile phones now use related chemistry to make light scratches disappear, a process that is often faster in warm conditions.',
    'Roads present a different challenge. Asphalt, the mixture of stone and a sticky, oil-based binder used on most road surfaces, already has a limited ability to heal: in hot weather the binder softens and can flow into small cracks. Researchers in Delft, including the engineer Erik Schlangen, have built on this property by adding fine steel fibres to the mixture. A machine passing over the road generates a magnetic field that heats the steel, warming the surrounding binder so that it flows into cracks and seals them before they grow into potholes. Test sections of such roads have been laid in the Netherlands, and supporters claim that the technique could greatly extend the lifespan of a road surface.',
    'Interestingly, some ancient builders may have achieved something similar without knowing it. Many Roman structures, including harbour walls exposed to seawater, have survived for around two thousand years, far longer than much modern concrete. A 2023 study led by researchers at the Massachusetts Institute of Technology suggested that part of the explanation lies in small white lumps of lime found throughout Roman concrete, which had previously been dismissed as a sign of careless mixing. According to the study, when cracks form and water enters, these lumps can dissolve and then harden again as calcium carbonate, filling the cracks. If this is correct, the Roman technique may offer useful lessons for modern engineers.',
    'Despite these advances, self-healing materials remain far from universal. Bacterial concrete costs more than the conventional kind, and many clients, faced with tight budgets, are unwilling to pay extra at the start for savings that may only appear decades later. Most healing systems also have clear limits: they can deal with small cracks but not with major structural damage, and some can heal the same spot only once. Engineers also point out that proving a material will last for a century requires either waiting a century or trusting accelerated tests that may not reflect real conditions. Nevertheless, as the costs of maintenance and the environmental price of new construction continue to rise, materials that look after themselves are likely to become increasingly attractive.',
  ],
  vocab: [
    v('eventually', 'eventually', 'sooner or later', 'এখানে একসময় না একসময়।'),
    v('wear away', 'wear away', 'become thin and disappear', 'এখানে ব্যবহারে ক্ষয়ে যায়।'),
    v('inspect', 'inspect', 'check carefully', 'এখানে কাঠামো নিয়মিত খুঁটিয়ে পরীক্ষা করা।'),
    v('defect', 'defects', 'small faults', 'এখানে ছোট ছোট ত্রুটি।'),
    v('unnoticed', 'unnoticed', 'without anyone seeing', 'এখানে কারও চোখে না পড়ে।'),
    v('obvious', 'obvious', 'clearest', 'এখানে সবচেয়ে স্পষ্ট উদাহরণ।'),
    v('candidate', 'candidate', 'a suitable choice', 'এখানে এই প্রযুক্তির জন্য উপযুক্ত উপাদান।', { en: 'something suitable for a particular purpose', bn: 'উপযুক্ত বিকল্প' }),
    v('comparatively', 'comparatively', 'compared with its strength when squeezed', 'এখানে চাপের তুলনায় টানে তুলনামূলকভাবে দুর্বল।'),
    v('dissolve', 'dissolved', 'mixed into water', 'এখানে পানিতে মিশে থাকা রাসায়নিক।'),
    v('reinforce', 'reinforce', 'make stronger', 'এখানে ইস্পাতের রড কংক্রিটকে মজবুত করে।'),
    v('rust', 'rust', 'become damaged by water and air', 'এখানে ইস্পাতে মরিচা ধরে।'),
    v('expand', 'expands', 'gets bigger', 'এখানে মরিচা ধরা ইস্পাত আকারে বড় হয়।'),
    v('maintenance', 'maintenance', 'repair and upkeep', 'এখানে মেরামত ও রক্ষণাবেক্ষণ।'),
    v('survive', 'survive', 'stay alive', 'এখানে কঠিন পরিবেশে বেঁচে থাকা।'),
    v('inactive', 'inactive', 'not working, asleep', 'এখানে spore-গুলো ঘুমন্ত, কাজ করে না।', { en: 'not working or doing anything', bn: 'নিষ্ক্রিয়' }),
    v('seep', 'seeps', 'slowly gets in', 'এখানে পানি ফাটল দিয়ে চুইয়ে ঢোকে।'),
    v('gradually', 'gradually', 'slowly', 'এখানে ধীরে ধীরে।'),
    v('release', 'releasing', 'letting out', 'এখানে ক্যাপসুল থেকে তরল বেরিয়ে আসে।'),
    v('catalyst', 'catalyst', 'a substance that starts a reaction', 'এখানে যে রাসায়নিক তরলটাকে শক্ত হতে সাহায্য করে।'),
    v('scatter', 'scattered', 'spread through', 'এখানে প্লাস্টিকের ভেতরে ছড়িয়ে থাকা।'),
    v('bond', 'bonding', 'joining firmly', 'এখানে ফাটলের দুই পাশ জোড়া লাগিয়ে দেয়।'),
    v('inspired by', 'inspired by', 'copying an idea from', 'এখানে রক্তনালি দেখে ধারণা নেওয়া।'),
    v('generate', 'generates', 'produces', 'এখানে যন্ত্রটা চৌম্বক ক্ষেত্র তৈরি করে।'),
    v('lifespan', 'lifespan', 'how long it lasts', 'এখানে রাস্তা কত দিন টেকে।'),
    v('exposed to', 'exposed to', 'in contact with', 'এখানে সমুদ্রের পানির সংস্পর্শে থাকা।'),
    v('dismiss', 'dismissed', 'judged unimportant', 'এখানে অবহেলা করে ভুল মিশ্রণ বলে ধরে নেওয়া হয়েছিল।'),
    v('universal', 'universal', 'used everywhere', 'এখানে সব জায়গায় ব্যবহৃত নয়।'),
    v('conventional', 'conventional', 'ordinary', 'এখানে সাধারণ কংক্রিট।'),
    v('accelerated', 'accelerated', 'speeded-up', 'এখানে কম সময়ে দীর্ঘ ব্যবহারের অনুকরণ করা পরীক্ষা।'),
    v('reflect', 'reflect', 'show accurately', 'এখানে বাস্তব অবস্থা ঠিকভাবে তুলে ধরা।', { en: 'to show or be a sign of something accurately', bn: 'প্রতিফলন ঘটানো / সঠিকভাবে তুলে ধরা' }),
  ],
  groups: [
    select('info', INFO_I, [
      q('rl17-q1', 'a possible reason why some very old structures have lasted so long', 'F', 'Paragraph F: lumps of lime may explain why Roman structures "have survived for around two thousand years".', 'Paragraph F: রোমান কংক্রিটের চুনের দলা হয়তো দীর্ঘস্থায়িত্বের কারণ — F।', 'part of the explanation lies in small white lumps of lime'),
      q('rl17-q2', 'an explanation of how small cracks can lead to more serious damage', 'B', 'Paragraph B: rusting steel "expands, forcing the cracks wider and weakening the structure from within".', 'Paragraph B: মরিচা ধরা ইস্পাত বড় হয়ে ফাটল বাড়ায় — B।', 'forcing the cracks wider and weakening the structure from within'),
      q('rl17-q3', 'a comparison with the way the human body repairs itself', 'A', 'Paragraph A: "much as a cut in human skin gradually closes".', 'Paragraph A: মানুষের চামড়ার কাটা যেমন সেরে যায় — এই তুলনা A-তে।', 'much as a cut in human skin gradually closes'),
      q('rl17-q4', 'reasons why some people may not choose a new material', 'G', 'Paragraph G: clients "are unwilling to pay extra at the start for savings that may only appear decades later".', 'Paragraph G: শুরুতে বাড়তি খরচ দিতে গ্রাহকেরা রাজি নন — G।', 'are unwilling to pay extra at the start'),
    ]),
    select('tfng', TFNG_I, [
      q('rl17-q5', 'Concrete resists being pressed together better than being pulled apart.', 'TRUE', 'Paragraph B: "strong when squeezed but comparatively weak when stretched".', 'Paragraph B: চাপে শক্ত, টানে দুর্বল — বাক্যের সাথে মেলে, TRUE।', 'strong when squeezed but comparatively weak when stretched'),
      q('rl17-q6', 'The bacteria in Jonkers’s concrete are active all the time.', 'FALSE', 'Paragraph C: "Inside dry concrete, the spores remain inactive".', 'Paragraph C: শুকনো কংক্রিটে spore নিষ্ক্রিয় থাকে — "all the time active" বিপরীত, FALSE।', 'the spores remain inactive'),
      q('rl17-q7', 'Scott White’s team won an international prize for its self-healing plastic.', 'NOT GIVEN', 'Paragraph D describes the plastic but mentions no prize.', 'Paragraph D প্লাস্টিকটার বর্ণনা দেয়, কোনো পুরস্কারের কথা নেই — NOT GIVEN।'),
      q('rl17-q8', 'The lumps of lime in Roman concrete were once regarded as a mistake.', 'TRUE', 'Paragraph F: they "had previously been dismissed as a sign of careless mixing".', 'Paragraph F: আগে এগুলোকে অসাবধান মিশ্রণের চিহ্ন ভাবা হতো — TRUE।', 'dismissed as a sign of careless mixing'),
      q('rl17-q9', 'Most self-healing systems can repair serious structural damage.', 'FALSE', 'Paragraph G: they deal with small cracks "but not with major structural damage".', 'Paragraph G: বড় কাঠামোগত ক্ষতি সারাতে পারে না — FALSE।', 'but not with major structural damage'),
    ]),
    gap('table', 2, [
      gapItem('rl17-q10', ['limestone'], 'Paragraph C: the spores "produce limestone, which gradually fills the gap".', 'Paragraph C: "produce limestone" — উত্তর limestone।', 'produce limestone'),
      gapItem('rl17-q11', ['capsules'], 'Paragraph D: a crack "broke open the capsules in its path".', 'Paragraph D: ফাটল ক্যাপসুল ভেঙে দেয় — উত্তর capsules।', 'broke open the capsules'),
      gapItem('rl17-q12', ['magnetic field'], 'Paragraph E: a machine "generates a magnetic field that heats the steel".', 'Paragraph E: "a magnetic field that heats the steel" — উত্তর magnetic field।', 'generates a magnetic field'),
      gapItem('rl17-q13', ['calcium carbonate'], 'Paragraph F: the lumps "harden again as calcium carbonate".', 'Paragraph F: "harden again as calcium carbonate" — উত্তর calcium carbonate।', 'harden again as calcium carbonate'),
    ], {
      title: 'How different materials heal',
      table: {
        head: ['Material', 'What starts the healing', 'What fills the crack'],
        rows: [
          ['Bacterial concrete', 'water entering a crack', '[[rl17-q10]] made by bacteria'],
          ['Illinois plastic', 'a crack breaking open tiny [[rl17-q11]]', 'a liquid that hardens'],
          ['Asphalt with steel fibres', 'a [[rl17-q12]] that heats the steel', 'softened binder'],
          ['Roman concrete', 'water entering a crack', 'lime that becomes [[rl17-q13]]'],
        ],
      },
    }),
    select('mcq', MCQ_I, [
      q('rl17-q14', 'What is the main purpose of paragraph E?', 'A', 'Paragraph E: asphalt "already has a limited ability to heal", and researchers "have built on this property".', 'Paragraph E: asphalt-এর নিজস্ব সারার ক্ষমতাকে steel fibre দিয়ে উন্নত করা হয়েছে — তাই A। দাম, ইস্পাত দিয়ে asphalt বদলানো বা দেশের তুলনা নেই।', 'have built on this property', abcd(
        'to describe how a natural property of road surfaces has been improved',
        'to explain why asphalt is cheaper than concrete',
        'to argue that steel should replace asphalt on roads',
        'to compare roads in the Netherlands with those in other countries',
      )),
      q('rl17-q15', 'What does the writer suggest about the future of self-healing materials?', 'D', 'Paragraph G: "as the costs of maintenance and the environmental price of new construction continue to rise", these materials are "likely to become increasingly attractive".', 'Paragraph G: খরচ ও পরিবেশগত মূল্য বাড়ায় এগুলো আরও আকর্ষণীয় হবে — D। সব উপাদান বদলে যাবে (A) বা ১০০ বছর প্রমাণিত (C) — লেখা নেই।', 'likely to become increasingly attractive', abcd(
        'They will soon replace all conventional building materials.',
        'They will never be widely used because of their cost.',
        'Accelerated tests have already proved that they last a century.',
        'Rising costs and environmental concerns may make them more appealing.',
      )),
    ]),
  ],
};
