import { NAMES_I, TFNG_I, TWO_I, abcd, gap, gapItem, lex, multi, named, q, select, v } from '../kit';
import type { LexEntry, LibraryPassage } from '../types';

export const LEX: LexEntry[] = [
  lex('zone', 'noun', 'useful', 'an area with a particular purpose or feature', 'এলাকা / অঞ্চল', 'This part of the city is a no-parking zone.', 'শহরের এই অংশটা পার্কিং-নিষিদ্ধ এলাকা।', ['area', 'district']),
  lex('congested', 'adjective', 'useful', 'too full of traffic or people', 'যানজটপূর্ণ / ভিড়ে ঠাসা', 'Dhaka’s roads are congested every morning.', 'ঢাকার রাস্তাগুলো প্রতিদিন সকালে যানজটে ঠাসা থাকে।', ['crowded', 'jammed']),
  lex('vision', 'noun', 'useful', 'an idea or plan of what the future could be like', 'ভবিষ্যৎ-পরিকল্পনা / স্বপ্ন', 'The minister shared her vision for rural schools.', 'মন্ত্রী গ্রামীণ স্কুল নিয়ে তাঁর ভবিষ্যৎ-পরিকল্পনা জানালেন।', ['plan', 'dream']),
  lex('promote', 'verb', 'core', 'to support or encourage an idea, product or activity', 'প্রচার করা / উৎসাহ দেওয়া', 'The campaign promotes safe driving.', 'প্রচারণাটা নিরাপদ গাড়ি চালানোয় উৎসাহ দেয়।', ['support', 'advertise']),
  lex('essential', 'adjective', 'core', 'completely necessary', 'অপরিহার্য / অত্যাবশ্যক', 'Clean water is essential for good health.', 'সুস্বাস্থ্যের জন্য বিশুদ্ধ পানি অপরিহার্য।', ['necessary', 'vital']),
  lex('residential', 'adjective', 'useful', 'used for homes rather than offices or factories', 'আবাসিক', 'They live in a quiet residential area.', 'তাঁরা একটা শান্ত আবাসিক এলাকায় থাকেন।', ['housing', 'domestic']),
  lex('activist', 'noun', 'useful', 'a person who works to bring about social or political change', 'সমাজকর্মী / আন্দোলনকর্মী', 'Local activists campaigned for a new park.', 'স্থানীয় আন্দোলনকর্মীরা নতুন পার্কের দাবিতে প্রচারণা চালালেন।', ['campaigner', 'advocate']),
  lex('separation', 'noun', 'useful', 'the act of keeping things apart', 'পৃথকীকরণ / আলাদা রাখা', 'The separation of waste makes recycling easier.', 'বর্জ্য আলাদা করলে পুনর্ব্যবহার সহজ হয়।', ['division', 'split']),
  lex('contemporary', 'adjective', 'advanced', 'belonging to the present time', 'সমকালীন / আধুনিক', 'The museum shows contemporary art.', 'জাদুঘরটায় সমকালীন শিল্পকর্ম প্রদর্শিত হয়।', ['modern', 'current']),
  lex('walkable', 'adjective', 'advanced', 'easy or pleasant to walk around', 'হেঁটে চলাচলের উপযোগী', 'Old town centres are often very walkable.', 'পুরোনো শহরকেন্দ্রগুলো প্রায়ই হেঁটে চলার জন্য খুব উপযোগী।', ['pedestrian-friendly']),
  lex('policy', 'noun', 'core', 'a plan of action agreed by a government or organisation', 'নীতি', 'The new policy protects forests.', 'নতুন নীতিটা বন রক্ষা করে।', ['plan', 'strategy']),
  lex('administration', 'noun', 'useful', 'the people who manage a government or organisation during a period', 'প্রশাসন', 'The new administration promised cheaper transport.', 'নতুন প্রশাসন সস্তা পরিবহনের প্রতিশ্রুতি দিল।', ['government', 'management']),
  lex('momentum', 'noun', 'advanced', 'the force that keeps something developing or growing', 'গতি / জোর', 'The campaign gained momentum after the report.', 'প্রতিবেদনের পর প্রচারণাটা জোর পেল।', ['drive', 'impetus']),
  lex('dweller', 'noun', 'advanced', 'a person who lives in a particular place', 'বাসিন্দা', 'City dwellers often have little green space.', 'শহরের বাসিন্দাদের প্রায়ই সবুজ জায়গা কম থাকে।', ['resident', 'inhabitant']),
  lex('shortcoming', 'noun', 'advanced', 'a fault or weakness', 'ঘাটতি / দুর্বলতা', 'The plan has several shortcomings.', 'পরিকল্পনাটার কয়েকটা দুর্বলতা আছে।', ['weakness', 'flaw']),
  lex('immediate', 'adjective', 'useful', 'happening now; nearest in space or relationship', 'তাৎক্ষণিক; সবচেয়ে কাছের', 'We need an immediate answer.', 'আমাদের তাৎক্ষণিক উত্তর দরকার।', ['instant', 'nearest']),
  lex('pursue', 'verb', 'useful', 'to try to achieve something over a period of time', 'অনুসরণ করা / অর্জনের চেষ্টা করা', 'She wants to pursue a career in medicine.', 'তিনি চিকিৎসা পেশায় ক্যারিয়ার গড়তে চান।', ['seek', 'follow']),
  lex('strategy', 'noun', 'core', 'a long-term plan to achieve a goal', 'কৌশল / দীর্ঘমেয়াদি পরিকল্পনা', 'We need a clear strategy for the exam.', 'পরীক্ষার জন্য আমাদের একটা স্পষ্ট কৌশল দরকার।', ['plan', 'approach']),
  lex('emission', 'noun', 'useful', 'gas or other substance sent into the air', 'নির্গমন', 'Factories must reduce their emissions.', 'কারখানাগুলোকে তাদের নির্গমন কমাতে হবে।', ['discharge', 'release']),
  lex('sense of community', 'phrase', 'useful', 'the feeling of belonging to a group of people who live near each other', 'সামাজিক বন্ধনের অনুভূতি', 'The festival builds a sense of community.', 'উৎসবটা সামাজিক বন্ধনের অনুভূতি গড়ে তোলে।', ['belonging', 'togetherness']),
  lex('amenity', 'noun', 'advanced', 'a useful facility such as a park, shop or library', 'নাগরিক সুবিধা', 'The area has good amenities, including a hospital.', 'এলাকাটায় হাসপাতালসহ ভালো নাগরিক সুবিধা আছে।', ['facility', 'service']),
  lex('push up', 'phrasal verb', 'useful', 'to make a price or amount increase', 'দাম বাড়িয়ে দেওয়া', 'Bad weather pushed up vegetable prices.', 'খারাপ আবহাওয়া সবজির দাম বাড়িয়ে দিল।', ['raise', 'increase']),
  lex('sprawling', 'adjective', 'advanced', 'spreading over a large area in an untidy way', 'অপরিকল্পিতভাবে ছড়িয়ে পড়া', 'The city has grown into a sprawling mass of suburbs.', 'শহরটা অপরিকল্পিতভাবে ছড়িয়ে পড়া উপশহরে পরিণত হয়েছে।', ['spread-out', 'extensive']),
  lex('confine', 'verb', 'advanced', 'to keep someone or something within limits', 'আটকে রাখা / সীমাবদ্ধ রাখা', 'The patients were confined to their rooms.', 'রোগীদের তাঁদের ঘরে সীমাবদ্ধ রাখা হয়েছিল।', ['restrict', 'limit']),
  lex('well-intentioned', 'adjective', 'advanced', 'meant to help, even if the result is not good', 'সদিচ্ছাপ্রসূত', 'His advice was well-intentioned but unhelpful.', 'তাঁর পরামর্শ সদিচ্ছাপ্রসূত হলেও কাজে লাগেনি।', ['well-meaning', 'kindly meant']),
];

export const PASSAGE: LibraryPassage = {
  id: 'rl-18-fifteen-minute-city',
  title: 'The Fifteen-Minute City',
  topic: 'Urban development',
  level: 'advanced',
  minutes: 24,
  background: 'Well-established facts: Carlos Moreno (Sorbonne) and the fifteen-minute city concept (2016); Anne Hidalgo’s 2020 Paris re-election campaign; Clarence Perry’s neighbourhood unit (1929); Jane Jacobs (1961); Melbourne’s "20-minute neighbourhoods"; and the 2023 misinformation and protests linked to Oxford’s traffic filters. The final lesson is the writer’s view.',
  paragraphs: [
    'For much of the twentieth century, many cities were planned around the car. Homes were placed in one zone, offices in another and shopping in a third, on the assumption that residents would drive between them. The result, in many places, was long journeys, congested roads and neighbourhoods that emptied during the working day. In recent years, a very different vision has gained attention among planners and politicians: a city in which most of the things people need in daily life can be reached within a short walk or bicycle ride from home. Its best-known name is the "fifteen-minute city".',
    'The term is associated above all with Carlos Moreno, a scientist at the Sorbonne in Paris, who began to promote the concept in 2016. Moreno argued that urban life depends on six essential activities: living, working, obtaining supplies, caring for one’s health, learning and enjoying oneself. In a well-designed city, he suggested, all six should be accessible within a quarter of an hour, on foot or by bicycle. Rather than being a fixed rule, the figure of fifteen minutes was intended as a way of measuring how well a neighbourhood serves its residents, and of identifying what is missing. A neighbourhood with plenty of housing but no clinic or school, for instance, would fail the test, however attractive its streets might be, while one that offered all six functions could pass it without any new roads or major construction.',
    'The idea itself was not entirely new. In 1929, the American planner Clarence Perry proposed the "neighbourhood unit", a residential area organised around an elementary school that children could reach without crossing a major road. In 1961, the writer and activist Jane Jacobs attacked the separation of homes, shops and workplaces, arguing that lively streets depend on a mixture of uses that brings people outdoors at different times of day. What Moreno added was a new framing, one that linked the old idea of the walkable neighbourhood to contemporary concerns about climate change, public health and the quality of everyday life.',
    'The concept moved from theory to policy when the mayor of Paris, Anne Hidalgo, made it a central part of her campaign for re-election in 2020. Under her administration, the city has greatly expanded its network of cycle lanes, closed some streets outside schools to traffic, and encouraged schools to open their playgrounds to local residents outside teaching hours. The COVID-19 pandemic, which kept millions of people close to home, gave the idea further momentum, as many city dwellers discovered both the value and the shortcomings of their immediate surroundings. Other cities have pursued similar goals under different names; Melbourne’s long-term planning strategy, for example, aims to create "20-minute neighbourhoods".',
    'Supporters point to a range of potential benefits. Shorter journeys could reduce traffic and the emissions that come with it, while more walking and cycling would bring health gains. Local shops and services may find more customers among residents who no longer drive to distant shopping centres. Children, in particular, might gain more independence if schools, parks and friends’ homes were within safe walking distance. There are also social arguments: people who spend more time in their own neighbourhood are more likely to recognise their neighbours, which some researchers link to a stronger sense of community and to lower levels of loneliness.',
    'The model has also attracted serious criticism. Some urban economists point out that one of the main advantages of a large city is precisely that it gives people access to a vast range of jobs, and that few residents will find suitable work within fifteen minutes of home. Others warn that improving a neighbourhood’s amenities can push up property prices, eventually forcing out the lower-income residents the changes were meant to help. The concept is also far easier to apply in dense, older cities such as Paris than in sprawling suburbs built around motorways, where the distances involved are simply too great and public transport is often limited. Critics add that relabelling existing plans as fifteen-minute schemes does little to address these problems.',
    'In 2023 the debate took an unexpected turn. In the United Kingdom and elsewhere, false claims spread online that fifteen-minute cities were a plan to confine residents to their neighbourhoods and fine them for leaving. These claims often confused the concept with separate traffic schemes, such as the filters designed to reduce through-traffic in Oxford, and led to street protests; Moreno himself received threats. The episode showed how easily a planning idea can be misunderstood. It also suggests a lesson for its supporters: however well-intentioned, changes to the way people move around a city are more likely to succeed when residents are involved in designing them, rather than simply informed once decisions have been made.',
  ],
  vocab: [
    v('zone', 'zone', 'a separate area of the city', 'এখানে শহরের আলাদা একটা অংশ।'),
    v('assumption', 'assumption', 'something believed without checking', 'এখানে ধরে নেওয়া হয়েছিল মানুষ গাড়িতে যাতায়াত করবে।'),
    v('congested', 'congested', 'full of traffic', 'এখানে যানজটে ভরা রাস্তা।'),
    v('vision', 'vision', 'an idea of a better future', 'এখানে ভবিষ্যৎ শহরের নতুন ধারণা।'),
    v('promote', 'promote', 'spread and support', 'এখানে ধারণাটা প্রচার করা।'),
    v('essential', 'essential', 'basic and necessary', 'এখানে দৈনন্দিন জীবনের অপরিহার্য কাজ।'),
    v('obtain', 'obtaining', 'getting', 'এখানে প্রয়োজনীয় জিনিস সংগ্রহ করা।'),
    v('supplies', 'supplies', 'food and daily goods', 'এখানে খাবার ও দৈনন্দিন জিনিসপত্র।'),
    v('accessible', 'accessible', 'easy to reach', 'এখানে হেঁটে বা সাইকেলে সহজে পৌঁছানো যায়।'),
    v('quarter', 'quarter', 'one fourth', 'এখানে এক ঘণ্টার চার ভাগের এক ভাগ, মানে ১৫ মিনিট।'),
    v('residential', 'residential', 'for homes', 'এখানে বসবাসের এলাকা।'),
    v('activist', 'activist', 'a campaigner', 'এখানে সমাজ পরিবর্তনের জন্য কাজ করা মানুষ।'),
    v('separation', 'separation', 'keeping apart', 'এখানে বাসা, দোকান ও অফিস আলাদা রাখা।'),
    v('walkable', 'walkable', 'easy to walk around', 'এখানে হেঁটে চলাচলের উপযোগী।'),
    v('contemporary', 'contemporary', 'of today', 'এখানে বর্তমান সময়ের উদ্বেগ।'),
    v('policy', 'policy', 'official government action', 'এখানে সরকারি নীতি।'),
    v('administration', 'administration', 'her city government', 'এখানে মেয়রের প্রশাসন।'),
    v('momentum', 'momentum', 'extra force and speed', 'এখানে ধারণাটা আরও জোর পেল।'),
    v('dweller', 'dwellers', 'people who live in', 'এখানে শহরের বাসিন্দারা।'),
    v('shortcoming', 'shortcomings', 'weaknesses', 'এখানে নিজেদের এলাকার ঘাটতি।'),
    v('immediate', 'immediate', 'closest', 'এখানে একদম আশপাশের পরিবেশ।', { en: 'nearest to you in space', bn: 'সবচেয়ে কাছের / আশপাশের' }),
    v('pursue', 'pursued', 'tried to reach', 'এখানে একই লক্ষ্য অর্জনের চেষ্টা করেছে।'),
    v('strategy', 'strategy', 'a long-term plan', 'এখানে দীর্ঘমেয়াদি নগর পরিকল্পনা।'),
    v('emission', 'emissions', 'harmful gases', 'এখানে গাড়ি থেকে বের হওয়া ক্ষতিকর গ্যাস।'),
    v('sense of community', 'sense of community', 'feeling close to neighbours', 'এখানে প্রতিবেশীদের সাথে বন্ধনের অনুভূতি।'),
    v('precisely', 'precisely', 'exactly', 'এখানে ঠিক এটাই বড় শহরের সুবিধা।', { en: 'exactly; used to emphasise that something is completely true', bn: 'ঠিক এটাই / হুবহু' }),
    v('amenity', 'amenities', 'useful local facilities', 'এখানে পার্ক, দোকান, স্কুলের মতো নাগরিক সুবিধা।'),
    v('push up', 'push up', 'make higher', 'এখানে বাড়ির দাম বাড়িয়ে দেয়।'),
    v('sprawling', 'sprawling', 'spread over a large area', 'এখানে বিশাল এলাকা জুড়ে ছড়ানো উপশহর।'),
    v('confine', 'confine', 'keep inside limits', 'এখানে বাসিন্দাদের নিজের এলাকায় আটকে রাখা।'),
    v('misunderstand', 'misunderstood', 'understood wrongly', 'এখানে ধারণাটা ভুলভাবে বোঝা হয়েছে।'),
    v('well-intentioned', 'well-intentioned', 'meant to help', 'এখানে ভালো উদ্দেশ্যে করা হলেও।'),
  ],
  groups: [
    select('names', NAMES_I, [
      q('rl18-q1', 'identified a set of basic activities that a neighbourhood should support', 'C', 'Paragraph B: Moreno "argued that urban life depends on six essential activities".', 'Paragraph B: Moreno ছয়টা অপরিহার্য কাজের তালিকা দিয়েছিলেন — C।', 'six essential activities'),
      q('rl18-q2', 'argued that lively streets need a combination of different uses', 'B', 'Paragraph C: Jacobs argued "that lively streets depend on a mixture of uses".', 'Paragraph C: Jane Jacobs বলেছিলেন প্রাণবন্ত রাস্তার জন্য নানা ব্যবহারের মিশ্রণ দরকার — B।', 'lively streets depend on a mixture of uses'),
      q('rl18-q3', 'made the concept part of an election campaign', 'D', 'Paragraph D: Hidalgo "made it a central part of her campaign for re-election in 2020".', 'Paragraph D: Anne Hidalgo ২০২০ সালের নির্বাচনী প্রচারণায় এটা রেখেছিলেন — D।', 'her campaign for re-election in 2020'),
      q('rl18-q4', 'planned an area around a school that children could walk to safely', 'A', 'Paragraph C: Perry’s unit was "organised around an elementary school that children could reach without crossing a major road".', 'Paragraph C: Clarence Perry-র পরিকল্পনা স্কুলকে কেন্দ্র করে, বড় রাস্তা পার না হয়েই যাওয়া যায় — A।', 'organised around an elementary school'),
      q('rl18-q5', 'was personally threatened after false claims spread online', 'C', 'Paragraph G: "Moreno himself received threats".', 'Paragraph G: মিথ্যা দাবি ছড়ানোর পর Moreno নিজে হুমকি পেয়েছিলেন — C।', 'Moreno himself received threats'),
    ], named('Clarence Perry', 'Jane Jacobs', 'Carlos Moreno', 'Anne Hidalgo')),
    select('tfng', TFNG_I, [
      q('rl18-q6', 'Moreno intended fifteen minutes to be a strict limit that every city must meet.', 'FALSE', 'Paragraph B: "Rather than being a fixed rule, the figure of fifteen minutes was intended as a way of measuring".', 'Paragraph B: ১৫ মিনিট কোনো কঠোর নিয়ম নয়, মাপার একটা উপায় — FALSE।', 'Rather than being a fixed rule'),
      q('rl18-q7', 'The pandemic made some people more aware of the weaknesses of their local area.', 'TRUE', 'Paragraph D: city dwellers "discovered both the value and the shortcomings of their immediate surroundings".', 'Paragraph D: মানুষ নিজের এলাকার ভালো দিক আর ঘাটতি দুটোই টের পেয়েছে — TRUE।', 'the value and the shortcomings of their immediate surroundings'),
      q('rl18-q8', 'Melbourne’s plan was directly based on Moreno’s work in Paris.', 'NOT GIVEN', 'Paragraph D says Melbourne pursued similar goals under a different name, but not whether it was based on Moreno’s work.', 'Paragraph D বলে Melbourne একই রকম লক্ষ্য নিয়েছে, কিন্তু Moreno-র কাজ থেকে নেওয়া কিনা বলা নেই — NOT GIVEN।'),
      q('rl18-q9', 'The fifteen-minute model is equally easy to apply in all kinds of urban area.', 'FALSE', 'Paragraph F: it is "far easier to apply in dense, older cities such as Paris than in sprawling suburbs".', 'Paragraph F: ঘন পুরোনো শহরে সহজ, ছড়ানো উপশহরে কঠিন — "equally easy" বিপরীত, FALSE।', 'far easier to apply in dense, older cities'),
    ]),
    gap('short', 3, [
      gapItem('rl18-q10', ['playgrounds', 'their playgrounds'], 'Paragraph D: schools were encouraged "to open their playgrounds to local residents".', 'Paragraph D: স্কুলগুলোকে খেলার মাঠ খুলে দিতে বলা হয়েছিল — উত্তর playgrounds।', 'open their playgrounds', 'What did Paris encourage schools to open to local residents outside teaching hours?'),
      gapItem('rl18-q11', ['Oxford'], 'Paragraph G: the claims confused the concept with "filters designed to reduce through-traffic in Oxford".', 'Paragraph G: Oxford-এর traffic filter-এর সাথে ধারণাটা গুলিয়ে ফেলা হয়েছিল — উত্তর Oxford।', 'through-traffic in Oxford', 'In which city were traffic filters confused with the fifteen-minute city?'),
      gapItem('rl18-q12', ['20-minute neighbourhoods', 'twenty-minute neighbourhoods'], 'Paragraph D: Melbourne’s strategy "aims to create 20-minute neighbourhoods".', 'Paragraph D: Melbourne-এর নাম "20-minute neighbourhoods" — hyphen-যুক্ত শব্দ একটা word ধরা হয়।', '20-minute neighbourhoods', 'What does Melbourne’s long-term strategy aim to create?'),
    ], { numbers: true }),
    multi('rl18-q13', TWO_I, 'Which TWO criticisms of the fifteen-minute city are mentioned in paragraph F?', abcd(
      'Few people can find suitable jobs close to home.',
      'Local shops would lose their customers.',
      'Better local facilities may drive poorer residents out.',
      'Cycling is too dangerous in large cities.',
      'The idea is too expensive for most governments.',
    ), ['A', 'C'], 'Paragraph F: "few residents will find suitable work within fifteen minutes of home" (A) and improvements "can push up property prices, eventually forcing out the lower-income residents" (C). B contradicts paragraph E; D and E are not mentioned.', 'Paragraph F: কাছে উপযুক্ত চাকরি পাওয়া কঠিন (A), আর সুবিধা বাড়লে বাড়ির দাম বেড়ে দরিদ্র বাসিন্দারা সরে যেতে বাধ্য হন (C)। B paragraph E-এর উল্টো, D আর E নেই।', 'few residents will find suitable work within fifteen minutes of home'),
    gap('sentence', 1, [
      gapItem('rl18-q15', ['zone'], 'Paragraph A: "Homes were placed in one zone, offices in another".', 'Paragraph A: "placed in one zone" — উত্তর zone।', 'Homes were placed in one zone', 'In car-based planning, homes and offices were each placed in a different ___.'),
      gapItem('rl18-q16', ['quality'], 'Paragraph C: "concerns about climate change, public health and the quality of everyday life".', 'Paragraph C: "the quality of everyday life" — উত্তর quality।', 'the quality of everyday life', 'Moreno linked walkable neighbourhoods to concerns about climate change, public health and the ___ of everyday life.'),
    ]),
  ],
};
