import { HEAD_I, MCQ_I, TFNG_I, abcd, gap, gapItem, headings, lex, q, select, v } from '../kit';
import type { LexEntry, LibraryPassage } from '../types';

export const LEX: LexEntry[] = [
  lex('origin', 'noun', 'core', 'the place or situation where something begins', 'উৎস / উৎপত্তি', 'The origin of the river is in the hills.', 'নদীটার উৎস পাহাড়ে।', ['source', 'beginning']),
  lex('slaughter', 'verb / noun', 'useful', 'to kill animals for their meat; the killing of animals for food', 'জবাই করা / জবাই', 'The animals are slaughtered in a clean facility.', 'পশুগুলো একটা পরিষ্কার স্থাপনায় জবাই করা হয়।', ['kill', 'butcher']),
  lex('in effect', 'phrase', 'useful', 'in reality, though not officially described that way', 'কার্যত / বাস্তবে', 'The new rule is, in effect, a ban on cars.', 'নতুন নিয়মটা কার্যত গাড়ির ওপর নিষেধাজ্ঞা।', ['effectively', 'in practice']),
  lex('isolate', 'verb', 'useful', 'to separate something from other things', 'আলাদা করা / পৃথক করা', 'Scientists isolated the virus from a sample.', 'বিজ্ঞানীরা একটা নমুনা থেকে ভাইরাসটা আলাদা করলেন।', ['separate', 'extract']),
  lex('nutrient', 'noun', 'useful', 'a substance that living things need to grow and stay healthy', 'পুষ্টি উপাদান', 'Vegetables are full of nutrients.', 'সবজি পুষ্টি উপাদানে ভরপুর।', ['nourishment']),
  lex('multiply', 'verb', 'core', 'to increase greatly in number', 'সংখ্যায় বাড়া / বংশবৃদ্ধি করা', 'Bacteria multiply quickly in warm food.', 'গরম খাবারে ব্যাকটেরিয়া দ্রুত সংখ্যায় বাড়ে।', ['increase', 'grow']),
  lex('vast', 'adjective', 'core', 'extremely large in size or amount', 'বিশাল / বিপুল', 'The Sundarbans cover a vast area.', 'সুন্দরবন বিশাল এলাকা জুড়ে বিস্তৃত।', ['huge', 'immense']),
  lex('burden', 'noun', 'useful', 'a heavy load or a difficult responsibility', 'বোঝা / চাপ', 'Rising prices are a burden on poor families.', 'দাম বাড়া দরিদ্র পরিবারের ওপর বোঝা।', ['load', 'strain']),
  lex('impose', 'verb', 'advanced', 'to force something unpleasant on someone or something', 'চাপিয়ে দেওয়া', 'The government imposed a new tax.', 'সরকার একটা নতুন কর চাপিয়ে দিল।', ['force', 'place on']),
  lex('livestock', 'noun', 'core', 'animals such as cows, goats and chickens kept on a farm', 'গবাদি পশু', 'Floods killed many livestock in the village.', 'বন্যায় গ্রামের অনেক গবাদি পশু মারা গেল।', ['farm animals', 'cattle']),
  lex('graze', 'verb', 'useful', 'to eat grass in a field', 'চরানো / ঘাস খাওয়া', 'Cows were grazing by the river.', 'নদীর ধারে গরুগুলো ঘাস খাচ্ছিল।', ['feed', 'browse']),
  lex('driver', 'noun', 'core', 'a person who drives a vehicle', 'চালক', 'The bus driver stopped suddenly.', 'বাসচালক হঠাৎ থেমে গেলেন।', ['motorist', 'operator']),
  lex('deforestation', 'noun', 'useful', 'the cutting down of large areas of forest', 'বন উজাড়', 'Deforestation increases the risk of landslides.', 'বন উজাড় ভূমিধসের ঝুঁকি বাড়ায়।', ['forest clearance', 'logging']),
  lex('efficient', 'adjective', 'core', 'working well without wasting time, energy or money', 'দক্ষ / কার্যকর', 'LED bulbs are more efficient than old bulbs.', 'পুরোনো বাল্বের চেয়ে LED বাল্ব বেশি সাশ্রয়ী।', ['effective', 'economical']),
  lex('obstacle', 'noun', 'core', 'something that makes progress difficult', 'বাধা / প্রতিবন্ধকতা', 'Lack of money was the main obstacle.', 'টাকার অভাবই ছিল প্রধান বাধা।', ['barrier', 'difficulty']),
  lex('sterile', 'adjective', 'advanced', 'completely clean and free from bacteria', 'জীবাণুমুক্ত', 'Surgeons use sterile instruments.', 'সার্জনরা জীবাণুমুক্ত যন্ত্র ব্যবহার করেন।', ['germ-free', 'clean']),
  lex('pharmaceutical', 'adjective', 'advanced', 'connected with making medicines', 'ওষুধশিল্প-সংক্রান্ত', 'Bangladesh has a growing pharmaceutical industry.', 'বাংলাদেশের ওষুধশিল্প দ্রুত বাড়ছে।', ['medical', 'drug-making']),
  lex('formidable', 'adjective', 'advanced', 'very difficult to deal with; impressive and powerful', 'অত্যন্ত কঠিন / দুর্দম', 'The team faced a formidable opponent.', 'দলটা এক কঠিন প্রতিপক্ষের মুখোমুখি হলো।', ['daunting', 'tough']),
  lex('welfare', 'noun', 'useful', 'health, comfort and well-being', 'কল্যাণ / সুস্থতা', 'The charity cares for animal welfare.', 'দাতব্য সংস্থাটা পশু কল্যাণে কাজ করে।', ['well-being', 'care']),
  lex('confidential', 'adjective', 'useful', 'meant to be kept secret', 'গোপনীয়', 'Your medical records are confidential.', 'আপনার চিকিৎসা-নথি গোপনীয়।', ['secret', 'private']),
  lex('enthusiasm', 'noun', 'core', 'a strong feeling of interest and excitement', 'উৎসাহ / আগ্রহ', 'The students showed great enthusiasm for the project.', 'শিক্ষার্থীরা প্রকল্পটায় দারুণ উৎসাহ দেখাল।', ['eagerness', 'excitement']),
  lex('shrink', 'verb', 'core', 'to become smaller', 'ছোট হয়ে যাওয়া / কমে যাওয়া', 'Wool can shrink in hot water.', 'গরম পানিতে উল ছোট হয়ে যেতে পারে।', ['decrease', 'reduce']),
  lex('approval', 'noun', 'core', 'official permission; the feeling that something is good', 'অনুমোদন', 'The plan needs government approval.', 'পরিকল্পনাটার সরকারি অনুমোদন দরকার।', ['permission', 'consent']),
  lex('hesitant', 'adjective', 'useful', 'slow to act or decide because you are unsure', 'দ্বিধাগ্রস্ত', 'She was hesitant to speak in front of the class.', 'ক্লাসের সামনে কথা বলতে তিনি দ্বিধা করছিলেন।', ['unsure', 'reluctant']),
  lex('realistic', 'adjective', 'useful', 'sensible and based on what is actually possible', 'বাস্তবসম্মত', 'Set realistic goals for each week.', 'প্রতি সপ্তাহের জন্য বাস্তবসম্মত লক্ষ্য ঠিক করুন।', ['practical', 'sensible']),
  lex('appetite', 'noun', 'useful', 'the desire to eat; a strong wish for something', 'খিদে / চাহিদা', 'Exercise gives you a good appetite.', 'ব্যায়াম ভালো খিদে জাগায়।', ['hunger', 'desire']),
];

export const PASSAGE: LibraryPassage = {
  id: 'rl-19-cultured-meat',
  title: 'Meat Without the Animal',
  topic: 'Future technology',
  level: 'advanced',
  minutes: 24,
  background: 'Well-established facts: Mark Post’s cultured beef burger tasted in London on 5 August 2013 (about €250,000, funded by Sergey Brin); the FAO estimate that livestock account for about 14.5% of human-caused greenhouse gas emissions; foetal bovine serum in early growth media; Singapore’s approval of Eat Just’s cultured chicken (December 2020); US approvals (2023); Italy’s ban (2023); Florida and Alabama bans (2024).',
  paragraphs: [
    'On 5 August 2013, at a press event in London, two food critics sat down to taste a beef burger. It looked and cooked much like an ordinary burger, and the critics described it as close to meat in texture, though less juicy, since it contained no fat. What made the event remarkable was the origin of the meat. It had not come from a slaughtered cow but had been grown in a laboratory from cells taken from a living animal. The burger, developed by a team led by Mark Post of Maastricht University, had cost around €250,000 to produce, much of it funded by the Google co-founder Sergey Brin. It was, in effect, an expensive demonstration of a food that did not yet exist as a product.',
    'The basic principle is simpler than it sounds. A small sample of muscle is taken from an animal, usually through a procedure that does not harm it. From this sample, scientists isolate cells capable of dividing many times and place them in a nutrient-rich liquid known as a growth medium, which supplies the sugars, amino acids and other substances the cells need. Kept at body temperature in large steel vessels called bioreactors, the cells multiply and can then be encouraged to develop into muscle and fat tissue. In theory, a single sample could supply enough cells to produce vast quantities of meat.',
    'Supporters argue that the technology could ease some of the heaviest burdens imposed by conventional livestock farming. According to a widely cited estimate by the United Nations Food and Agriculture Organization, livestock account for around 14.5 per cent of human-caused greenhouse gas emissions. Raising animals also requires enormous areas of land for grazing and for growing feed, and it is a major driver of deforestation in some regions. In addition, the crowded conditions in which many animals are kept can encourage the spread of disease and contribute to the overuse of antibiotics. Growing only the parts of the animal that people actually eat, the argument goes, would be far more efficient.',
    'Turning this promise into a product on supermarket shelves has proved extremely difficult. The first obstacle is cost. Although prices have fallen dramatically since 2013, cultured meat remains far more expensive to produce than conventional meat, largely because of the growth medium, which must be kept sterile and contains costly ingredients. A second problem is scale: bioreactors large enough to compete with industrial farming would need to be far larger than those currently used in the pharmaceutical industry, and cells grown in such volumes are vulnerable to contamination. Third, most products so far consist of loose, minced tissue; reproducing the complex structure of a steak, with its fibres, fat and blood vessels, remains a formidable challenge.',
    'There have also been ethical difficulties. For years, the most effective growth media relied on foetal bovine serum, a substance obtained from the blood of unborn calves at slaughter, which is an awkward ingredient for a product promoted partly on grounds of animal welfare. Many companies now say they have developed serum-free alternatives, although the details are often kept confidential. The environmental benefits, meanwhile, are less certain than early enthusiasm suggested. Several analyses have concluded that the climate impact of cultured meat depends heavily on the energy used to run the bioreactors: if that energy comes from fossil fuels, the advantage over some kinds of conventional meat could shrink considerably, or even disappear.',
    'Regulators have taken very different approaches. In December 2020, Singapore became the first country to approve the sale of a cultured meat product, chicken pieces produced by the American company Eat Just. In 2023, the United States followed, giving approval to two companies to sell cultivated chicken. Other governments have moved in the opposite direction. Later that year, Italy passed a law banning the production and sale of cultured meat, with supporters of the ban arguing that it would protect traditional farming and food culture, and in 2024 the US states of Florida and Alabama introduced bans of their own.',
    'Ultimately, the future of cultured meat may depend less on laboratories than on consumers. Surveys suggest that many people are curious about it but hesitant to eat it regularly, with some describing it as unnatural. Price will matter too: few shoppers are likely to pay significantly more for a product that tastes the same as one they already buy. For the moment, therefore, the most realistic expectation is not that cultured meat will replace farming, but that it may take its place alongside plant-based alternatives as one of several ways of reducing the environmental cost of the human appetite for meat.',
  ],
  vocab: [
    v('origin', 'origin', 'where the meat came from', 'এখানে মাংসটা কোথা থেকে এসেছে — তার উৎস।'),
    v('slaughter', ['slaughtered', 'slaughter'], 'killed for meat', 'এখানে মাংসের জন্য জবাই করা পশু।'),
    v('in effect', 'in effect', 'really, in practice', 'এখানে কার্যত এটা ছিল একটা প্রদর্শনী।'),
    v('demonstrate', 'demonstration', 'an event showing that something works', 'এখানে প্রযুক্তিটা কাজ করে তা দেখানোর আয়োজন।', { en: 'an event that shows how something works', bn: 'প্রদর্শন / প্রদর্শনী' }),
    v('isolate', 'isolate', 'separate out', 'এখানে নমুনা থেকে বিশেষ কোষ আলাদা করা।'),
    v('nutrient', 'nutrient', 'food substances for cells', 'এখানে কোষের জন্য পুষ্টি উপাদান।'),
    v('multiply', 'multiply', 'increase in number', 'এখানে কোষগুলো বিভাজিত হয়ে সংখ্যায় বাড়ে।'),
    v('tissue', 'tissue', 'muscle and fat material', 'এখানে পেশি ও চর্বির টিস্যু।'),
    v('vast', 'vast', 'very large', 'এখানে বিপুল পরিমাণ।'),
    v('quantity', 'quantities', 'amounts', 'এখানে পরিমাণ।'),
    v('burden', 'burdens', 'heavy costs and problems', 'এখানে পরিবেশের ওপর বড় চাপ।'),
    v('impose', 'imposed', 'forced on others', 'এখানে পশুপালন পরিবেশের ওপর চাপিয়ে দেয়।'),
    v('livestock', 'livestock', 'farm animals', 'এখানে গবাদি পশু।'),
    v('enormous', 'enormous', 'very large', 'এখানে বিশাল পরিমাণ জমি।'),
    v('graze', 'grazing', 'animals eating grass', 'এখানে পশু চরানোর জন্য জমি।'),
    v('driver', 'driver', 'a main cause', 'এখানে বন উজাড়ের একটা প্রধান কারণ।', { en: 'something that causes or strongly influences something else', bn: 'প্রধান কারণ / চালিকাশক্তি' }),
    v('deforestation', 'deforestation', 'cutting down forests', 'এখানে বন উজাড়।'),
    v('overuse', 'overuse', 'using too much', 'এখানে অ্যান্টিবায়োটিকের অতিরিক্ত ব্যবহার।'),
    v('efficient', 'efficient', 'less wasteful', 'এখানে কম অপচয়ে বেশি কাজ।'),
    v('obstacle', 'obstacle', 'a problem in the way', 'এখানে পণ্য বানানোর পথে বাধা।'),
    v('sterile', 'sterile', 'free from germs', 'এখানে জীবাণুমুক্ত রাখতে হয়।'),
    v('pharmaceutical', 'pharmaceutical', 'medicine-making', 'এখানে ওষুধশিল্প।'),
    v('contaminate', 'contamination', 'becoming dirty or infected', 'এখানে জীবাণু ঢুকে নষ্ট হওয়া।', { en: 'the process of making something dirty or impure', bn: 'দূষণ / সংক্রমণ' }),
    v('formidable', 'formidable', 'very difficult', 'এখানে অত্যন্ত কঠিন চ্যালেঞ্জ।'),
    v('welfare', 'welfare', 'well-being of animals', 'এখানে পশুর কল্যাণ।'),
    v('confidential', 'confidential', 'kept secret', 'এখানে কোম্পানিগুলো বিস্তারিত গোপন রাখে।'),
    v('enthusiasm', 'enthusiasm', 'excitement', 'এখানে শুরুর দিকের উৎসাহ।'),
    v('shrink', 'shrink', 'become smaller', 'এখানে সুবিধাটা কমে যেতে পারে।'),
    v('regulator', 'Regulators', 'official bodies that control food', 'এখানে খাদ্য অনুমোদনকারী সরকারি সংস্থা।'),
    v('approval', 'approval', 'official permission', 'এখানে সরকারি অনুমোদন।'),
    v('ban', ['banning', 'bans', 'ban'], 'officially stopping', 'এখানে আইন করে নিষিদ্ধ করা।'),
    v('hesitant', 'hesitant', 'unsure', 'এখানে নিয়মিত খেতে দ্বিধা।'),
    v('realistic', 'realistic', 'sensible', 'এখানে বাস্তবসম্মত প্রত্যাশা।'),
    v('alongside', 'alongside', 'together with', 'এখানে উদ্ভিজ্জ বিকল্পের পাশাপাশি।'),
    v('appetite', 'appetite', 'strong desire', 'এখানে মাংসের প্রতি মানুষের চাহিদা।', { en: 'a strong desire for something', bn: 'চাহিদা / আকাঙ্ক্ষা' }),
  ],
  groups: [
    select('headings', HEAD_I, [
      q('rl19-q1', 'Paragraph B', 'ii', 'B explains how cells are taken, fed and grown in bioreactors.', 'Paragraph B-তে কোষ নেওয়া, খাওয়ানো আর bioreactor-এ বাড়ানোর প্রক্রিয়া — তাই ii।', 'place them in a nutrient-rich liquid'),
      q('rl19-q2', 'Paragraph C', 'i', 'C gives the environmental and health reasons supporters offer.', 'Paragraph C-তে সমর্থকেরা কেন পরিবর্তন চান — পরিবেশ ও রোগের কারণ। তাই i।', 'ease some of the heaviest burdens'),
      q('rl19-q3', 'Paragraph D', 'iv', 'D lists cost, scale and structure as obstacles.', 'Paragraph D-তে খরচ, আকার আর গঠন — তিনটা বাধা। তাই iv।', 'The first obstacle is cost'),
      q('rl19-q4', 'Paragraph E', 'v', 'E discusses serum in the growth medium and doubts about climate benefits.', 'Paragraph E-তে উপাদান (serum) আর জলবায়ু-সুবিধা নিয়ে প্রশ্ন — তাই v।', 'There have also been ethical difficulties'),
      q('rl19-q5', 'Paragraph F', 'iii', 'F contrasts countries that approved and countries that banned the product.', 'Paragraph F-এ কিছু দেশ অনুমোদন দিয়েছে, কিছু নিষিদ্ধ করেছে — তাই iii।', 'Regulators have taken very different approaches'),
      q('rl19-q6', 'Paragraph G', 'vii', 'G says the future "may depend less on laboratories than on consumers".', 'Paragraph G: ভবিষ্যৎ নির্ভর করবে ক্রেতাদের ওপর — তাই vii। vi ভুল, কারণ দাম এখনও বেশি।', 'may depend less on laboratories than on consumers'),
    ], headings(
      'Why supporters believe a change is needed',
      'How meat can be grown outside an animal',
      'Governments divided over a new food',
      'Technical and financial barriers to production',
      'Questions about ingredients and climate benefits',
      'Why cultured meat now costs less than beef',
      'Buyers may have the final say',
      'A new way of improving the health of farm animals',
      'How farmers have welcomed the technology',
    )),
    select('tfng', TFNG_I, [
      q('rl19-q7', 'The burger tasted in 2013 contained a small amount of fat.', 'FALSE', 'Paragraph A: it was less juicy "since it contained no fat".', 'Paragraph A: বার্গারে কোনো চর্বি ছিল না — "small amount of fat" বিপরীত, FALSE।', 'since it contained no fat'),
      q('rl19-q8', 'Taking the original sample of cells usually kills the animal.', 'FALSE', 'Paragraph B: the sample is taken "usually through a procedure that does not harm it".', 'Paragraph B: সাধারণত পশুর ক্ষতি হয় না — FALSE।', 'a procedure that does not harm it'),
      q('rl19-q9', 'Eat Just had sold plant-based foods before its cultured chicken was approved.', 'NOT GIVEN', 'Paragraph F names Eat Just but says nothing about its earlier products.', 'Paragraph F-এ Eat Just-এর নাম আছে, কিন্তু আগে কী বিক্রি করত তা নেই — NOT GIVEN।'),
      q('rl19-q10', 'Supporters of Italy’s ban presented it partly as a way of protecting food traditions.', 'TRUE', 'Paragraph F: supporters argued "that it would protect traditional farming and food culture".', 'Paragraph F: নিষেধাজ্ঞার পক্ষে যুক্তি ছিল ঐতিহ্যবাহী কৃষি ও খাদ্যসংস্কৃতি রক্ষা — TRUE।', 'protect traditional farming and food culture'),
    ]),
    gap('note', 3, [
      gapItem('rl19-q11', ['Sergey Brin', 'Brin'], 'Paragraph A: "much of it funded by the Google co-founder Sergey Brin".', 'Paragraph A: খরচের বড় অংশ দিয়েছিলেন Sergey Brin — উত্তর Sergey Brin।', 'Sergey Brin'),
      gapItem('rl19-q12', ['growth medium'], 'Paragraph B: "a nutrient-rich liquid known as a growth medium".', 'Paragraph B: পুষ্টিকর তরলটার নাম growth medium।', 'known as a growth medium'),
      gapItem('rl19-q13', ['bioreactors'], 'Paragraph B: "large steel vessels called bioreactors".', 'Paragraph B: "vessels called bioreactors" — উত্তর bioreactors।', 'called bioreactors'),
      gapItem('rl19-q14', ['14.5 per cent', '14.5%', '14.5 percent'], 'Paragraph C: livestock "account for around 14.5 per cent" of emissions.', 'Paragraph C: "around 14.5 per cent" — সংখ্যা আর per cent মিলে তিনটা word-এর মধ্যে।', 'around 14.5 per cent'),
      gapItem('rl19-q15', ['Singapore'], 'Paragraph F: "Singapore became the first country to approve the sale".', 'Paragraph F: প্রথম অনুমোদন দেয় Singapore।', 'Singapore became the first country'),
    ], {
      numbers: true,
      title: 'Cultured meat: key facts',
      lines: [
        'First public tasting: London, 2013; paid for largely by [[rl19-q11]]',
        'Cells are fed with a liquid called a [[rl19-q12]]',
        'Cells are grown in steel vessels known as [[rl19-q13]]',
        'Livestock share of human-caused greenhouse gas emissions: about [[rl19-q14]]',
        'First country to allow sales (2020): [[rl19-q15]]',
      ],
    }),
    select('mcq', MCQ_I, [
      q('rl19-q16', 'What point does the writer make about the 2013 burger?', 'A', 'Paragraph A: it was "an expensive demonstration of a food that did not yet exist as a product".', 'Paragraph A: বার্গারটা ছিল এমন খাবারের প্রদর্শনী যা তখনো পণ্য হিসেবে বাজারে ছিল না — A। স্বাদ ভালো ছিল (B) বা পুরো খরচ বিশ্ববিদ্যালয়ের (C) — লেখা নেই; মৃত গরু নয়, জীবিত পশুর কোষ (D ভুল)।', 'did not yet exist as a product', abcd(
        'It showed a food that could not yet be bought.',
        'It tasted better than an ordinary burger.',
        'It was paid for entirely by Maastricht University.',
        'It was made from the cells of a dead cow.',
      )),
      q('rl19-q17', 'What is the writer’s conclusion in paragraph G?', 'D', 'Paragraph G: cultured meat "may take its place alongside plant-based alternatives as one of several ways" to reduce the environmental cost.', 'Paragraph G: কালচার্ড মাংস কৃষি বদলে দেবে না, বরং কয়েকটা বিকল্পের একটা হবে — D।', 'one of several ways of reducing the environmental cost', abcd(
        'Cultured meat will soon replace livestock farming.',
        'Most consumers already eat cultured meat regularly.',
        'Plant-based alternatives will disappear from shops.',
        'Cultured meat is likely to become one option among several.',
      )),
    ]),
  ],
};
