import { INFO_I, MCQ_I, YNNG_I, abcd, gap, gapItem, lex, q, select, v } from '../kit';
import type { LexEntry, LibraryPassage } from '../types';

export const LEX: LexEntry[] = [
  lex('appoint', 'verb', 'useful', 'to choose someone officially for a job or position', 'নিয়োগ দেওয়া', 'The school appointed a new head teacher.', 'স্কুলটা একজন নতুন প্রধান শিক্ষক নিয়োগ দিল।', ['name', 'select']),
  lex('commission', 'noun', 'advanced', 'an official group given the job of studying a problem', 'কমিশন / তদন্ত-পরিষদ', 'A commission was set up to study road safety.', 'সড়ক নিরাপত্তা নিয়ে গবেষণার জন্য একটা কমিশন গঠন করা হলো।', ['committee', 'board']),
  lex('campaign', 'verb / noun', 'useful', 'to work in an organised way to achieve a social or political goal', 'প্রচারণা চালানো / আন্দোলন করা', 'Students campaigned for safer roads.', 'শিক্ষার্থীরা নিরাপদ সড়কের দাবিতে আন্দোলন করেছিল।', ['fight', 'push']),
  lex('issue', 'noun', 'core', 'an important topic or problem that people discuss', 'বিষয় / সমস্যা', 'Climate change is a global issue.', 'জলবায়ু পরিবর্তন একটা বৈশ্বিক সমস্যা।', ['matter', 'problem']),
  lex('observer', 'noun', 'useful', 'a person who watches and comments on events', 'পর্যবেক্ষক', 'Many observers expected the plan to fail.', 'অনেক পর্যবেক্ষক ভেবেছিলেন পরিকল্পনাটা ব্যর্থ হবে।', ['commentator', 'onlooker']),
  lex('significant', 'adjective', 'core', 'important or large enough to have an effect', 'উল্লেখযোগ্য / গুরুত্বপূর্ণ', 'There has been a significant rise in prices.', 'দামে উল্লেখযোগ্য বৃদ্ধি হয়েছে।', ['important', 'considerable']),
  lex('distinguish', 'verb', 'useful', 'to see or show the difference between things', 'পার্থক্য করা', 'Can you distinguish between the two sounds?', 'আপনি কি দুটো শব্দের পার্থক্য বুঝতে পারেন?', ['differentiate', 'tell apart']),
  lex('objective', 'adjective', 'advanced', 'based on facts, not on feelings or opinions', 'বস্তুনিষ্ঠ / বাস্তব তথ্যভিত্তিক', 'We need an objective measure of progress.', 'অগ্রগতির একটা বস্তুনিষ্ঠ মাপকাঠি দরকার।', ['factual', 'impartial']),
  lex('subjective', 'adjective', 'advanced', 'based on personal feelings or opinions', 'ব্যক্তিনিষ্ঠ / ব্যক্তিগত অনুভূতিনির্ভর', 'Taste in music is very subjective.', 'গানের রুচি খুবই ব্যক্তিগত।', ['personal', 'individual']),
  lex('coincide', 'verb', 'advanced', 'to happen at the same time or be the same', 'একই সময়ে ঘটা / মিলে যাওয়া', 'My holiday coincided with the festival.', 'আমার ছুটি উৎসবের সাথে মিলে গিয়েছিল।', ['match', 'overlap']),
  lex('evolve', 'verb', 'useful', 'to develop gradually over a long time', 'বিবর্তিত হওয়া / ধীরে ধীরে গড়ে ওঠা', 'Birds evolved from small dinosaurs.', 'পাখি ছোট ডাইনোসর থেকে বিবর্তিত হয়েছে।', ['develop', 'grow']),
  lex('seek out', 'phrasal verb', 'useful', 'to look for someone or something with effort', 'খুঁজে বের করা', 'She sought out the best teachers in the city.', 'তিনি শহরের সেরা শিক্ষকদের খুঁজে বের করলেন।', ['look for', 'search for']),
  lex('accumulate', 'verb', 'useful', 'to gradually increase in amount', 'জমা হওয়া / পুঞ্জীভূত হওয়া', 'Dust accumulated on the shelves.', 'তাকগুলোতে ধুলো জমেছিল।', ['build up', 'collect']),
  lex('likelihood', 'noun', 'useful', 'the chance that something will happen', 'সম্ভাবনা', 'Exercise reduces the likelihood of heart disease.', 'ব্যায়াম হৃদরোগের সম্ভাবনা কমায়।', ['probability', 'chance']),
  lex('epidemic', 'noun', 'advanced', 'a disease or problem that spreads quickly and affects many people', 'মহামারি', 'The city faced a dengue epidemic.', 'শহরটা ডেঙ্গু মহামারির মুখোমুখি হয়েছিল।', ['outbreak', 'plague']),
  lex('at risk', 'phrase', 'core', 'in a situation where something bad could happen', 'ঝুঁকিতে', 'Children near busy roads are at risk.', 'ব্যস্ত রাস্তার কাছের শিশুরা ঝুঁকিতে থাকে।', ['in danger', 'vulnerable']),
  lex('transition', 'noun', 'useful', 'a change from one state or stage to another', 'রূপান্তর / এক অবস্থা থেকে আরেক অবস্থায় যাওয়া', 'The transition from school to university can be hard.', 'স্কুল থেকে বিশ্ববিদ্যালয়ে যাওয়ার পরিবর্তনটা কঠিন হতে পারে।', ['change', 'shift']),
  lex('tempting', 'adjective', 'useful', 'attractive, making you want to do or believe it', 'লোভনীয় / প্রলুব্ধকর', 'It is tempting to skip breakfast when you are late.', 'দেরি হলে নাস্তা বাদ দেওয়াটা লোভনীয় মনে হয়।', ['attractive', 'appealing']),
  lex('straightforward', 'adjective', 'useful', 'simple and easy to understand', 'সোজাসাপ্টা / সহজ', 'The instructions were straightforward.', 'নির্দেশনাগুলো সহজ ছিল।', ['simple', 'clear']),
  lex('passively', 'adverb', 'advanced', 'without taking action or taking part', 'নিষ্ক্রিয়ভাবে', 'He sat passively while others argued.', 'অন্যরা তর্ক করার সময় তিনি নিষ্ক্রিয়ভাবে বসে ছিলেন।', ['inactively']),
  lex('exclude', 'verb', 'useful', 'to deliberately not include someone or something', 'বাদ দেওয়া / বাইরে রাখা', 'No child should feel excluded from the game.', 'কোনো শিশুর যেন খেলা থেকে বাদ পড়া মনে না হয়।', ['leave out', 'shut out']),
  lex('refer', 'verb', 'useful', 'to send someone to another person or place for help', 'পাঠানো / রেফার করা', 'The doctor referred her to a specialist.', 'ডাক্তার তাঁকে একজন বিশেষজ্ঞের কাছে পাঠালেন।', ['send', 'direct']),
  lex('volunteer', 'noun / verb', 'core', 'a person who works without being paid', 'স্বেচ্ছাসেবক', 'Volunteers helped clean the beach.', 'স্বেচ্ছাসেবকেরা সৈকত পরিষ্কারে সাহায্য করলেন।', ['helper', 'unpaid worker']),
  lex('in exchange for', 'phrase', 'useful', 'in return for something', 'বিনিময়ে', 'He tutors children in exchange for free meals.', 'বিনা মূল্যে খাবারের বিনিময়ে তিনি শিশুদের পড়ান।', ['in return for']),
  lex('evaluation', 'noun', 'useful', 'a careful judgement of how good or successful something is', 'মূল্যায়ন', 'The project will have an independent evaluation.', 'প্রকল্পটার একটা স্বাধীন মূল্যায়ন হবে।', ['assessment', 'review']),
  lex('substitute', 'noun', 'useful', 'something used instead of something else', 'বিকল্প', 'There is no substitute for hard work.', 'কঠোর পরিশ্রমের কোনো বিকল্প নেই।', ['replacement', 'alternative']),
  lex('misfortune', 'noun', 'advanced', 'bad luck, or an unlucky event', 'দুর্ভাগ্য', 'The family suffered one misfortune after another.', 'পরিবারটা একের পর এক দুর্ভাগ্যের শিকার হলো।', ['bad luck', 'hardship']),
  lex('to a considerable extent', 'phrase', 'advanced', 'to a large degree; very much', 'অনেকাংশে', 'Success depends to a considerable extent on practice.', 'সাফল্য অনেকাংশে অনুশীলনের ওপর নির্ভর করে।', ['largely', 'mostly']),
];

export const PASSAGE: LibraryPassage = {
  id: 'rl-20-loneliness',
  title: 'Alone in a Connected World',
  topic: 'Society',
  level: 'advanced',
  minutes: 24,
  background: 'Well-established facts: the UK minister for loneliness (January 2018) after the Jo Cox Commission on Loneliness; Japan’s equivalent post (2021); John Cacioppo’s hunger comparison; Holt-Lunstad and colleagues’ 2010 meta-analysis (148 studies, more than 300,000 people, about 50% greater likelihood of survival); the US Surgeon General’s 2023 advisory; the BBC Loneliness Experiment (2018, about 55,000 responses); social prescribing in the UK. The opinions are the writer’s own.',
  paragraphs: [
    'In January 2018, the British government did something that attracted attention around the world: it appointed a minister for loneliness. The decision followed the work of a commission set up in memory of Jo Cox, a member of parliament who had campaigned on the issue before she was killed in 2016. Three years later, Japan created a similar post. To some observers, the idea of a government minister responsible for something as personal as loneliness seemed strange. Yet the appointments reflected a growing body of research suggesting that loneliness is not merely an unpleasant feeling but a significant public health concern.',
    'Researchers are careful to distinguish loneliness from social isolation. Isolation is an objective condition: a person who lives alone and rarely meets others is isolated, whatever they feel about it. Loneliness, by contrast, is subjective. It is the painful gap between the relationships people have and those they would like to have. The two do not always coincide. Someone may live alone quite happily, while another person, surrounded by family and colleagues, may feel deeply lonely. The late neuroscientist John Cacioppo, of the University of Chicago, compared loneliness to hunger or thirst: an uncomfortable signal that evolved, he argued, to prompt people to seek out the company on which human survival once depended.',
    'The health evidence has accumulated steadily. In 2010, the psychologist Julianne Holt-Lunstad and her colleagues combined the results of 148 studies involving more than 300,000 people. They found that people with stronger social relationships had a roughly 50 per cent greater likelihood of survival over the study periods than those with weaker connections, an effect comparable in size to that of well-known risk factors such as smoking. Later work has linked loneliness and isolation to higher rates of heart disease, stroke and depression. In 2023, the Surgeon General of the United States, Vivek Murthy, published an official advisory describing loneliness and isolation as an epidemic.',
    'It is often assumed that loneliness is mainly a problem of old age, and older people who have lost partners and friends are certainly at risk. However, one of the largest surveys on the subject, the BBC Loneliness Experiment of 2018, which gathered responses from around 55,000 people, found that those aged 16 to 24 reported feeling lonely more often than any other age group. Researchers have offered several explanations. Young adulthood is a period of frequent transitions, such as leaving home, starting university or a first job, and moving to a new city, each of which can disrupt existing friendships. Young people may also expect more of their social lives, which widens the gap between hope and reality.',
    'Many commentators have blamed digital technology. It is tempting to conclude that time spent scrolling through social media replaces the face-to-face contact that genuinely satisfies the need for connection, and some studies have found associations between heavy social media use and loneliness. The evidence, however, is far from straightforward. An association does not show which comes first: lonely people may turn to their screens, rather than screens making people lonely. Other research suggests that the effect depends on how technology is used. Passively watching the lives of others may leave people feeling excluded, whereas using the same tools to arrange meetings or keep in touch with distant family can strengthen relationships. Treating technology as the single cause of loneliness, it seems to me, is as unhelpful as ignoring it altogether.',
    'Governments and health services have experimented with a range of responses. In the United Kingdom, doctors can refer patients to social prescribing schemes, which connect them with community activities such as walking groups, gardening projects and volunteering. Other programmes pair older residents with younger volunteers, or offer students rooms in homes for older people in exchange for spending time with the residents. Evaluations of such schemes are encouraging but mixed, partly because loneliness is difficult to measure and partly because an activity that suits one person may do nothing for another. Critics also warn that such programmes should not become a cheap substitute for properly funded health and social care.',
    'Perhaps the most important lesson is that loneliness is not simply a private misfortune. The design of cities, the reliability of public transport, the survival of libraries, cafés and community centres, and even the way workplaces are organised all influence how easily people can form and maintain relationships. Treating loneliness as a public issue does not mean that governments can make anyone feel less alone. It does mean recognising that the conditions in which friendships grow are, to a considerable extent, shaped by decisions that societies make together.',
  ],
  vocab: [
    v('appoint', 'appointed', 'officially gave the job to', 'এখানে সরকার একজন মন্ত্রী নিয়োগ দিল।'),
    v('commission', 'commission', 'an official study group', 'এখানে একাকীত্ব নিয়ে কাজ করা সরকারি দল।'),
    v('campaign', 'campaigned', 'worked publicly for a cause', 'এখানে বিষয়টা নিয়ে আন্দোলন করেছিলেন।'),
    v('issue', 'issue', 'a public problem or topic', 'এখানে একাকীত্ব — সমাজের একটা সমস্যা / বিষয়।'),
    v('observer', 'observers', 'people who watch and comment', 'এখানে যাঁরা ঘটনাটা দেখে মন্তব্য করেছেন।'),
    v('reflect', 'reflected', 'showed', 'এখানে গবেষণার প্রভাব প্রকাশ পেল।', { en: 'to show or be a result of something', bn: 'প্রকাশ করা / প্রতিফলিত করা' }),
    v('significant', 'significant', 'serious and important', 'এখানে গুরুত্বপূর্ণ জনস্বাস্থ্য-সমস্যা।'),
    v('distinguish', 'distinguish', 'tell the difference between', 'এখানে একাকীত্ব আর বিচ্ছিন্নতার পার্থক্য করা।'),
    v('objective', 'objective', 'based on facts you can see', 'এখানে বাইরে থেকে দেখা যায় এমন বাস্তব অবস্থা।'),
    v('subjective', 'subjective', 'based on personal feeling', 'এখানে মানুষ নিজে কেমন অনুভব করে তার ওপর নির্ভর।'),
    v('gap', 'gap', 'a difference between two things', 'এখানে যা আছে আর যা চাই তার মধ্যে ব্যবধান।', { en: 'a difference between two situations', bn: 'ব্যবধান / ফারাক' }),
    v('coincide', 'coincide', 'happen together', 'এখানে দুটো সবসময় একসাথে ঘটে না।'),
    v('evolve', 'evolved', 'developed over a long time', 'এখানে বিবর্তনের মাধ্যমে গড়ে উঠেছে।'),
    v('prompt', 'prompt', 'push someone to act', 'এখানে মানুষকে সঙ্গ খুঁজতে তাড়িত করা।'),
    v('seek out', 'seek out', 'look for', 'এখানে সঙ্গ খুঁজে নেওয়া।'),
    v('accumulate', 'accumulated', 'built up', 'এখানে প্রমাণ ধীরে ধীরে জমেছে।'),
    v('likelihood', 'likelihood', 'chance', 'এখানে বেঁচে থাকার সম্ভাবনা।'),
    v('comparable', 'comparable', 'about the same', 'এখানে ধূমপানের ঝুঁকির প্রায় সমান।'),
    v('epidemic', 'epidemic', 'a problem affecting very many people', 'এখানে বিপুল মানুষের সমস্যা — মহামারির মতো।'),
    v('at risk', 'at risk', 'in danger', 'এখানে একাকীত্বের ঝুঁকিতে।'),
    v('transition', 'transitions', 'big life changes', 'এখানে জীবনের বড় পরিবর্তন।'),
    v('disruption', 'disrupt', 'break or interrupt', 'এখানে পুরোনো বন্ধুত্বে ব্যাঘাত ঘটায়।', { en: 'to interrupt something so it cannot continue normally', bn: 'ব্যাঘাত ঘটানো' }),
    v('blame', 'blamed', 'said was responsible', 'এখানে প্রযুক্তিকে দায়ী করা।'),
    v('tempting', 'tempting', 'easy and attractive to believe', 'এখানে এমন সিদ্ধান্তে পৌঁছাতে মন চায়।'),
    v('straightforward', 'straightforward', 'simple', 'এখানে প্রমাণ মোটেও সোজাসাপ্টা নয়।'),
    v('passively', 'Passively', 'just watching, not taking part', 'এখানে শুধু দেখা, অংশ না নেওয়া।'),
    v('exclude', 'excluded', 'left out', 'এখানে বাদ পড়ে যাওয়ার অনুভূতি।'),
    v('refer', 'refer', 'send for help', 'এখানে ডাক্তার রোগীকে কর্মসূচিতে পাঠান।'),
    v('volunteer', ['volunteers', 'volunteering'], 'unpaid helpers; unpaid helping', 'এখানে স্বেচ্ছাসেবক / স্বেচ্ছাসেবা।'),
    v('in exchange for', 'in exchange for', 'in return for', 'এখানে সময় দেওয়ার বিনিময়ে থাকার ঘর।'),
    v('evaluation', 'Evaluations', 'studies of how well schemes work', 'এখানে কর্মসূচি কতটা কাজ করে তার মূল্যায়ন।'),
    v('mixed', 'mixed', 'partly good, partly not', 'এখানে ফলাফল মিশ্র।'),
    v('substitute', 'substitute', 'a replacement', 'এখানে যথাযথ স্বাস্থ্যসেবার সস্তা বিকল্প।'),
    v('misfortune', 'misfortune', 'bad luck', 'এখানে শুধু ব্যক্তিগত দুর্ভাগ্য নয়।'),
    v('maintain', 'maintain', 'keep going', 'এখানে সম্পর্ক বজায় রাখা।'),
    v('to a considerable extent', 'to a considerable extent', 'largely', 'এখানে অনেকাংশে।'),
  ],
  groups: [
    select('info', INFO_I, [
      q('rl20-q1', 'a comparison between loneliness and a basic physical need', 'B', 'Paragraph B: Cacioppo "compared loneliness to hunger or thirst".', 'Paragraph B: একাকীত্বকে খিদে বা তৃষ্ণার সাথে তুলনা — B।', 'compared loneliness to hunger or thirst'),
      q('rl20-q2', 'a reason why it is hard to judge whether a programme has worked', 'F', 'Paragraph F: evaluations are mixed "partly because loneliness is difficult to measure".', 'Paragraph F: একাকীত্ব মাপা কঠিন, তাই কর্মসূচির ফল বোঝা কঠিন — F।', 'loneliness is difficult to measure'),
      q('rl20-q3', 'a reference to a group that was set up to honour someone', 'A', 'Paragraph A: "a commission set up in memory of Jo Cox".', 'Paragraph A: Jo Cox-এর স্মরণে গঠিত কমিশন — A।', 'a commission set up in memory of Jo Cox'),
      q('rl20-q4', 'examples of life changes that can weaken friendships', 'D', 'Paragraph D: "leaving home, starting university or a first job, and moving to a new city".', 'Paragraph D: বাড়ি ছাড়া, বিশ্ববিদ্যালয় বা চাকরি শুরু, নতুন শহরে যাওয়া — D।', 'each of which can disrupt existing friendships'),
    ]),
    select('ynng', YNNG_I, [
      q('rl20-q5', 'Loneliness should be regarded as more than a personal problem.', 'YES', 'Paragraph G: "loneliness is not simply a private misfortune".', 'Paragraph G: লেখক বলছেন একাকীত্ব শুধু ব্যক্তিগত দুর্ভাগ্য নয় — YES।', 'loneliness is not simply a private misfortune'),
      q('rl20-q6', 'Technology is the main cause of loneliness today.', 'NO', 'Paragraph E: treating technology "as the single cause of loneliness … is as unhelpful as ignoring it".', 'Paragraph E: লেখকের মতে প্রযুক্তিকে একমাত্র কারণ ভাবা ভুল — NO।', 'as the single cause of loneliness'),
      q('rl20-q7', 'Japan’s minister for loneliness has achieved more than the British one.', 'NOT GIVEN', 'Paragraph A only says Japan created a similar post; nothing compares results.', 'Paragraph A শুধু বলে জাপানও একই পদ তৈরি করেছে; কার সাফল্য বেশি তা নেই — NOT GIVEN।'),
      q('rl20-q8', 'Studies of schemes to reduce loneliness have produced a varied picture.', 'YES', 'Paragraph F: "Evaluations of such schemes are encouraging but mixed".', 'Paragraph F: ফল আশাব্যঞ্জক কিন্তু মিশ্র — varied picture, YES।', 'encouraging but mixed'),
      q('rl20-q9', 'Governments are able to make people feel less alone directly.', 'NO', 'Paragraph G: it "does not mean that governments can make anyone feel less alone".', 'Paragraph G: সরকার সরাসরি কাউকে কম একা বোধ করাতে পারে না — NO।', 'does not mean that governments can make anyone feel less alone'),
    ]),
    gap('summary', 3, [
      gapItem('rl20-q10', ['300,000', '300000'], 'Paragraph C: "148 studies involving more than 300,000 people".', 'Paragraph C: "more than 300,000 people" — উত্তর 300,000।', 'more than 300,000 people'),
      gapItem('rl20-q11', ['50 per cent', '50%', '50 percent'], 'Paragraph C: "a roughly 50 per cent greater likelihood of survival".', 'Paragraph C: "roughly 50 per cent greater" — উত্তর 50 per cent।', 'roughly 50 per cent greater'),
      gapItem('rl20-q12', ['16 to 24', '16-24'], 'Paragraph D: "those aged 16 to 24 reported feeling lonely more often".', 'Paragraph D: "aged 16 to 24" — সবচেয়ে বেশি একাকীত্ব এই বয়সে।', 'those aged 16 to 24'),
      gapItem('rl20-q13', ['epidemic'], 'Paragraph C: an advisory "describing loneliness and isolation as an epidemic".', 'Paragraph C: "as an epidemic" — উত্তর epidemic।', 'as an epidemic'),
    ], {
      numbers: true,
      title: 'What the research shows',
      lines: [
        'A 2010 analysis combined studies of more than [[rl20-q10]] people and found that stronger social relationships were linked to a [[rl20-q11]] greater chance of survival. Loneliness is not only a problem of old age: in a 2018 survey, people aged [[rl20-q12]] reported feeling lonely most often. In 2023, an official US advisory described loneliness and isolation as an [[rl20-q13]].',
      ],
    }),
    select('mcq', MCQ_I, [
      q('rl20-q14', 'What is the writer’s main point in paragraph E?', 'B', 'Paragraph E: "the effect depends on how technology is used".', 'Paragraph E: প্রযুক্তি কীভাবে ব্যবহার হয় তার ওপর প্রভাব নির্ভর করে — B। সবাইকে একা করে (A) বা প্রমাণিত কারণ (D) — লেখক এমন বলেননি।', 'the effect depends on how technology is used', abcd(
        'Social media makes all its users lonely.',
        'The link between technology and loneliness depends on how it is used.',
        'Lonely people rarely use social media.',
        'Research has proved that screens cause loneliness.',
      )),
      q('rl20-q15', 'According to paragraph B, how is loneliness different from social isolation?', 'C', 'Paragraph B: "Loneliness, by contrast, is subjective" — the gap between the relationships people have and those they want.', 'Paragraph B: একাকীত্ব ব্যক্তিগত অনুভূতি, বিচ্ছিন্নতা বাস্তব অবস্থা — তাই C। "objective" হলো isolation (A ভুল)।', 'Loneliness, by contrast, is subjective', abcd(
        'Loneliness can be measured objectively.',
        'Social isolation affects only older people.',
        'Loneliness depends on how people feel about their relationships.',
        'Social isolation is always painful.',
      )),
    ]),
  ],
};
