import type { LicensedImage } from '@/lib/models';

/**
 * Country card photos, supplied by the Mino team (owner-provided images; the
 * team is responsible for the rights to use them). Each file is kept at its
 * original quality: the largest file is the original, never re-compressed or
 * enlarged, and smaller WebP versions are made only for smaller screens.
 * Files live in /public/abroad/countries/{code}-{width}.{ext}.
 *
 * Countries without a photo keep the flag placeholder. Only add a photo here
 * when it clearly shows that country.
 */
const SUPPLIED = 'Mino team';

export const COUNTRY_PHOTOS: Partial<Record<string, LicensedImage>> = {
  KR: {
    src: '/abroad/countries/kr-612.jpg',
    alt: { en: 'Gyeongbokgung Palace in Seoul with cherry blossoms', bn: 'সিউলের গিয়ংবকগুং প্রাসাদ, চেরি ফুলের সাথে' },
    credit: SUPPLIED,
    source: 'Mino team',
    sourceUrl: '',
    license: '',
    width: 612,
    height: 344,
    srcSet: [{ src: '/abroad/countries/kr-612.jpg', width: 612 }],
    position: 'center 45%',
  },
  IT: {
    src: '/abroad/countries/it-612.jpg',
    alt: { en: 'The Colosseum in Rome at sunrise', bn: 'সূর্যোদয়ে রোমের কলোসিয়াম' },
    credit: SUPPLIED,
    source: 'Mino team',
    sourceUrl: '',
    license: '',
    width: 612,
    height: 408,
    srcSet: [{ src: '/abroad/countries/it-612.jpg', width: 612 }],
    position: '60% 55%',
  },
  DE: {
    src: '/abroad/countries/de-1024.jpg',
    alt: { en: 'The Brandenburg Gate in Berlin at sunset', bn: 'সূর্যাস্তে বার্লিনের ব্র্যান্ডেনবুর্গ গেট' },
    credit: SUPPLIED,
    source: 'Mino team',
    sourceUrl: '',
    license: '',
    width: 1024,
    height: 576,
    srcSet: [{ src: '/abroad/countries/de-640.webp', width: 640 }, { src: '/abroad/countries/de-1024.jpg', width: 1024 }],
    position: 'center 45%',
  },
  AU: {
    src: '/abroad/countries/au-800.jpg',
    alt: { en: 'Sydney Harbour Bridge and the city skyline at dusk', bn: 'সন্ধ্যায় সিডনি হারবার ব্রিজ ও শহরের দৃশ্য' },
    credit: SUPPLIED,
    source: 'Mino team',
    sourceUrl: '',
    license: '',
    width: 800,
    height: 533,
    srcSet: [{ src: '/abroad/countries/au-640.webp', width: 640 }, { src: '/abroad/countries/au-800.jpg', width: 800 }],
    position: 'center 45%',
  },
  DK: {
    src: '/abroad/countries/dk-800.jpg',
    alt: { en: 'Colourful houses and boats in Nyhavn, Copenhagen, with the Danish flag', bn: 'কোপেনহেগেনের নাইহাভনে রঙিন বাড়ি ও নৌকা, ডেনমার্কের পতাকাসহ' },
    credit: SUPPLIED,
    source: 'Mino team',
    sourceUrl: '',
    license: '',
    width: 800,
    height: 534,
    srcSet: [{ src: '/abroad/countries/dk-640.webp', width: 640 }, { src: '/abroad/countries/dk-800.jpg', width: 800 }],
    position: 'center 45%',
  },
  GB: {
    src: '/abroad/countries/gb-612.jpg',
    alt: { en: 'Big Ben and Westminster Bridge in London', bn: 'লন্ডনের বিগ বেন ও ওয়েস্টমিনস্টার ব্রিজ' },
    credit: SUPPLIED,
    source: 'Mino team',
    sourceUrl: '',
    license: '',
    width: 612,
    height: 408,
    srcSet: [{ src: '/abroad/countries/gb-612.jpg', width: 612 }],
    position: '35% 40%',
  },
  NZ: {
    src: '/abroad/countries/nz-740.jpg',
    alt: { en: 'The New Zealand flag above green hills and mountains', bn: 'সবুজ পাহাড় ও পর্বতের সামনে নিউজিল্যান্ডের পতাকা' },
    credit: SUPPLIED,
    source: 'Mino team',
    sourceUrl: '',
    license: '',
    width: 740,
    height: 416,
    srcSet: [{ src: '/abroad/countries/nz-740.jpg', width: 740 }],
    position: '35% center',
  },
  US: {
    src: '/abroad/countries/us-1600.jpg',
    alt: { en: 'The Statue of Liberty and the New York skyline', bn: 'স্ট্যাচু অফ লিবার্টি ও নিউইয়র্কের স্কাইলাইন' },
    credit: SUPPLIED,
    source: 'Mino team',
    sourceUrl: '',
    license: '',
    width: 1600,
    height: 1000,
    srcSet: [{ src: '/abroad/countries/us-640.webp', width: 640 }, { src: '/abroad/countries/us-960.webp', width: 960 }, { src: '/abroad/countries/us-1280.webp', width: 1280 }, { src: '/abroad/countries/us-1600.jpg', width: 1600 }],
    position: 'center 60%',
  },
  CA: {
    src: '/abroad/countries/ca-1500.jpg',
    alt: { en: 'Quebec City at sunrise with the Canadian flag', bn: 'কানাডার পতাকাসহ সূর্যোদয়ে কুইবেক সিটি' },
    credit: SUPPLIED,
    source: 'Mino team',
    sourceUrl: '',
    license: '',
    width: 1500,
    height: 844,
    srcSet: [{ src: '/abroad/countries/ca-640.webp', width: 640 }, { src: '/abroad/countries/ca-960.webp', width: 960 }, { src: '/abroad/countries/ca-1500.jpg', width: 1500 }],
    position: '45% center',
  },
  FR: {
    src: '/abroad/countries/fr-1000.webp',
    alt: { en: 'The Eiffel Tower above Paris at sunset', bn: 'সূর্যাস্তে প্যারিসের আকাশে আইফেল টাওয়ার' },
    credit: SUPPLIED,
    source: 'Mino team',
    sourceUrl: '',
    license: '',
    width: 1000,
    height: 700,
    srcSet: [{ src: '/abroad/countries/fr-640.webp', width: 640 }, { src: '/abroad/countries/fr-1000.webp', width: 1000 }],
    position: '72% center',
  },
  SE: {
    src: '/abroad/countries/se-1200.jpg',
    alt: { en: 'Stockholm waterfront with the Swedish flag', bn: 'সুইডেনের পতাকাসহ স্টকহোমের জলতীর' },
    credit: SUPPLIED,
    source: 'Mino team',
    sourceUrl: '',
    license: '',
    width: 1200,
    height: 630,
    srcSet: [{ src: '/abroad/countries/se-640.webp', width: 640 }, { src: '/abroad/countries/se-960.webp', width: 960 }, { src: '/abroad/countries/se-1200.jpg', width: 1200 }],
    position: 'center 45%',
  },
};
