import type { LicensedImage } from '@/lib/models';

/**
 * Country card photos, supplied by the Mino team (owner-provided images; the
 * team is responsible for the rights to use them). Each file is kept at its
 * original quality: the largest file is the original, never re-compressed or
 * enlarged, and smaller WebP versions are made only for smaller screens.
 * Files live in /public/images/countries/{code}-{width}.{ext}.
 *
 * Countries without a photo keep the flag placeholder. Only add a photo here
 * when it clearly shows that country.
 */
const SUPPLIED = 'Mino team';

export const COUNTRY_PHOTOS: Partial<Record<string, LicensedImage>> = {
  KR: {
    src: '/images/countries/kr-612.jpg',
    alt: { en: 'Gyeongbokgung Palace in Seoul with cherry blossoms', bn: 'সিউলের গিয়ংবকগুং প্রাসাদ, চেরি ফুলের সাথে' },
    credit: SUPPLIED,
    source: 'Mino team',
    sourceUrl: '',
    license: '',
    width: 612,
    height: 344,
    srcSet: [{ src: '/images/countries/kr-612.jpg', width: 612 }],
    position: 'center 45%',
  },
  IT: {
    src: '/images/countries/it-612.jpg',
    alt: { en: 'The Colosseum in Rome at sunrise', bn: 'সূর্যোদয়ে রোমের কলোসিয়াম' },
    credit: SUPPLIED,
    source: 'Mino team',
    sourceUrl: '',
    license: '',
    width: 612,
    height: 408,
    srcSet: [{ src: '/images/countries/it-612.jpg', width: 612 }],
    position: '60% 55%',
  },
  DE: {
    src: '/images/countries/de-1024.jpg',
    alt: { en: 'The Brandenburg Gate in Berlin at sunset', bn: 'সূর্যাস্তে বার্লিনের ব্র্যান্ডেনবুর্গ গেট' },
    credit: SUPPLIED,
    source: 'Mino team',
    sourceUrl: '',
    license: '',
    width: 1024,
    height: 576,
    srcSet: [{ src: '/images/countries/de-640.webp', width: 640 }, { src: '/images/countries/de-1024.jpg', width: 1024 }],
    position: 'center 45%',
  },
  AU: {
    src: '/images/countries/au-800.jpg',
    alt: { en: 'Sydney Harbour Bridge and the city skyline at dusk', bn: 'সন্ধ্যায় সিডনি হারবার ব্রিজ ও শহরের দৃশ্য' },
    credit: SUPPLIED,
    source: 'Mino team',
    sourceUrl: '',
    license: '',
    width: 800,
    height: 533,
    srcSet: [{ src: '/images/countries/au-640.webp', width: 640 }, { src: '/images/countries/au-800.jpg', width: 800 }],
    position: 'center 45%',
  },
  DK: {
    src: '/images/countries/dk-800.jpg',
    alt: { en: 'Colourful houses and boats in Nyhavn, Copenhagen, with the Danish flag', bn: 'কোপেনহেগেনের নাইহাভনে রঙিন বাড়ি ও নৌকা, ডেনমার্কের পতাকাসহ' },
    credit: SUPPLIED,
    source: 'Mino team',
    sourceUrl: '',
    license: '',
    width: 800,
    height: 534,
    srcSet: [{ src: '/images/countries/dk-640.webp', width: 640 }, { src: '/images/countries/dk-800.jpg', width: 800 }],
    position: 'center 45%',
  },
  GB: {
    src: '/images/countries/gb-612.jpg',
    alt: { en: 'Big Ben and Westminster Bridge in London', bn: 'লন্ডনের বিগ বেন ও ওয়েস্টমিনস্টার ব্রিজ' },
    credit: SUPPLIED,
    source: 'Mino team',
    sourceUrl: '',
    license: '',
    width: 612,
    height: 408,
    srcSet: [{ src: '/images/countries/gb-612.jpg', width: 612 }],
    position: '35% 40%',
  },
  NZ: {
    src: '/images/countries/nz-740.jpg',
    alt: { en: 'The New Zealand flag above green hills and mountains', bn: 'সবুজ পাহাড় ও পর্বতের সামনে নিউজিল্যান্ডের পতাকা' },
    credit: SUPPLIED,
    source: 'Mino team',
    sourceUrl: '',
    license: '',
    width: 740,
    height: 416,
    srcSet: [{ src: '/images/countries/nz-740.jpg', width: 740 }],
    position: '35% center',
  },
  US: {
    src: '/images/countries/us-1600.jpg',
    alt: { en: 'The Statue of Liberty and the New York skyline', bn: 'স্ট্যাচু অফ লিবার্টি ও নিউইয়র্কের স্কাইলাইন' },
    credit: SUPPLIED,
    source: 'Mino team',
    sourceUrl: '',
    license: '',
    width: 1600,
    height: 1000,
    srcSet: [{ src: '/images/countries/us-640.webp', width: 640 }, { src: '/images/countries/us-960.webp', width: 960 }, { src: '/images/countries/us-1280.webp', width: 1280 }, { src: '/images/countries/us-1600.jpg', width: 1600 }],
    position: 'center 60%',
  },
  CA: {
    src: '/images/countries/ca-1500.jpg',
    alt: { en: 'Quebec City at sunrise with the Canadian flag', bn: 'কানাডার পতাকাসহ সূর্যোদয়ে কুইবেক সিটি' },
    credit: SUPPLIED,
    source: 'Mino team',
    sourceUrl: '',
    license: '',
    width: 1500,
    height: 844,
    srcSet: [{ src: '/images/countries/ca-640.webp', width: 640 }, { src: '/images/countries/ca-960.webp', width: 960 }, { src: '/images/countries/ca-1500.jpg', width: 1500 }],
    position: '45% center',
  },
  FR: {
    src: '/images/countries/fr-1000.webp',
    alt: { en: 'The Eiffel Tower above Paris at sunset', bn: 'সূর্যাস্তে প্যারিসের আকাশে আইফেল টাওয়ার' },
    credit: SUPPLIED,
    source: 'Mino team',
    sourceUrl: '',
    license: '',
    width: 1000,
    height: 700,
    srcSet: [{ src: '/images/countries/fr-640.webp', width: 640 }, { src: '/images/countries/fr-1000.webp', width: 1000 }],
    // The tower reaches almost to the top of the photo: anchor the crop at the top so it is never cut.
    position: '70% 4%',
  },
  SE: {
    src: '/images/countries/se-1200.jpg',
    alt: { en: 'Stockholm waterfront with the Swedish flag', bn: 'সুইডেনের পতাকাসহ স্টকহোমের জলতীর' },
    credit: SUPPLIED,
    source: 'Mino team',
    sourceUrl: '',
    license: '',
    width: 1200,
    height: 630,
    srcSet: [{ src: '/images/countries/se-640.webp', width: 640 }, { src: '/images/countries/se-960.webp', width: 960 }, { src: '/images/countries/se-1200.jpg', width: 1200 }],
    position: 'center 45%',
  },
  ES: {
    src: '/images/countries/es-1920.webp',
    alt: { en: 'Plaza de España in Seville with the Spanish flag', bn: 'স্পেনের পতাকাসহ সেভিয়ার প্লাজা দে এস্পানিয়া' },
    credit: SUPPLIED,
    source: 'Mino team',
    sourceUrl: '',
    license: '',
    width: 1920,
    height: 1212,
    srcSet: [{ src: '/images/countries/es-640.webp', width: 640 }, { src: '/images/countries/es-960.webp', width: 960 }, { src: '/images/countries/es-1280.webp', width: 1280 }, { src: '/images/countries/es-1920.webp', width: 1920 }],
    position: '55% center',
  },
  NL: {
    src: '/images/countries/nl-550.jpg',
    alt: { en: 'Windmills and tulip fields in the Netherlands', bn: 'নেদারল্যান্ডসের উইন্ডমিল ও টিউলিপের মাঠ' },
    credit: SUPPLIED,
    source: 'Mino team',
    sourceUrl: '',
    license: '',
    width: 550,
    height: 376,
    srcSet: [{ src: '/images/countries/nl-550.jpg', width: 550 }],
    position: 'center 40%',
  },
  MY: {
    src: '/images/countries/my-1366.jpg',
    alt: { en: 'The Petronas Twin Towers and Kuala Lumpur skyline at dusk', bn: 'সন্ধ্যায় পেট্রোনাস টুইন টাওয়ার ও কুয়ালালামপুর' },
    credit: SUPPLIED,
    source: 'Mino team',
    sourceUrl: '',
    license: '',
    width: 1366,
    height: 911,
    srcSet: [{ src: '/images/countries/my-640.webp', width: 640 }, { src: '/images/countries/my-960.webp', width: 960 }, { src: '/images/countries/my-1366.jpg', width: 1366 }],
    position: '40% 40%',
  },
  NO: {
    src: '/images/countries/no-1920.webp',
    alt: { en: 'The Norwegian flag above a fjord and green mountains', bn: 'ফিয়র্ড ও সবুজ পাহাড়ের সামনে নরওয়ের পতাকা' },
    credit: SUPPLIED,
    source: 'Mino team',
    sourceUrl: '',
    license: '',
    width: 1920,
    height: 960,
    srcSet: [{ src: '/images/countries/no-640.webp', width: 640 }, { src: '/images/countries/no-960.webp', width: 960 }, { src: '/images/countries/no-1280.webp', width: 1280 }, { src: '/images/countries/no-1920.webp', width: 1920 }],
    position: '40% center',
  },
  FI: {
    src: '/images/countries/fi-1920.webp',
    alt: { en: 'The Finnish flag above a lake and pine forest', bn: 'হ্রদ ও পাইন বনের সামনে ফিনল্যান্ডের পতাকা' },
    credit: SUPPLIED,
    source: 'Mino team',
    sourceUrl: '',
    license: '',
    width: 1920,
    height: 1280,
    srcSet: [{ src: '/images/countries/fi-640.webp', width: 640 }, { src: '/images/countries/fi-960.webp', width: 960 }, { src: '/images/countries/fi-1280.webp', width: 1280 }, { src: '/images/countries/fi-1920.webp', width: 1920 }],
    position: '60% 40%',
  },
  JP: {
    src: '/images/countries/jp-650.jpg',
    alt: { en: 'Mount Fuji, cherry blossoms and a pagoda in Japan', bn: 'জাপানের মাউন্ট ফুজি, চেরি ফুল ও প্যাগোডা' },
    credit: SUPPLIED,
    source: 'Mino team',
    sourceUrl: '',
    license: '',
    width: 650,
    height: 345,
    srcSet: [{ src: '/images/countries/jp-650.jpg', width: 650 }],
    position: 'center 40%',
  },
  CH: {
    src: '/images/countries/ch-1254.webp',
    alt: { en: 'A mountain train below snowy peaks in the Swiss Alps', bn: 'সুইস আল্পসে বরফঢাকা পাহাড়ের নিচে পাহাড়ি ট্রেন' },
    credit: SUPPLIED,
    source: 'Mino team',
    sourceUrl: '',
    license: '',
    width: 1254,
    height: 836,
    srcSet: [{ src: '/images/countries/ch-640.webp', width: 640 }, { src: '/images/countries/ch-960.webp', width: 960 }, { src: '/images/countries/ch-1254.webp', width: 1254 }],
    position: 'center 45%',
  },
  CN: {
    src: '/images/countries/cn-1920.webp',
    alt: { en: 'The Shanghai skyline reflected in the Huangpu River', bn: 'হুয়াংপু নদীতে সাংহাইয়ের স্কাইলাইনের প্রতিবিম্ব' },
    credit: SUPPLIED,
    source: 'Mino team',
    sourceUrl: '',
    license: '',
    width: 1920,
    height: 1080,
    srcSet: [{ src: '/images/countries/cn-640.webp', width: 640 }, { src: '/images/countries/cn-960.webp', width: 960 }, { src: '/images/countries/cn-1280.webp', width: 1280 }, { src: '/images/countries/cn-1920.webp', width: 1920 }],
    position: 'center 40%',
  },
  TR: {
    src: '/images/countries/tr-1920.webp',
    alt: { en: 'Istanbul’s Süleymaniye Mosque and ferries on the Golden Horn', bn: 'ইস্তাম্বুলের সুলেমানিয়ে মসজিদ ও গোল্ডেন হর্নে ফেরি' },
    credit: SUPPLIED,
    source: 'Mino team',
    sourceUrl: '',
    license: '',
    width: 1920,
    height: 1281,
    srcSet: [{ src: '/images/countries/tr-640.webp', width: 640 }, { src: '/images/countries/tr-960.webp', width: 960 }, { src: '/images/countries/tr-1280.webp', width: 1280 }, { src: '/images/countries/tr-1920.webp', width: 1920 }],
    position: 'center 40%',
  },
  // Ireland: the photo the owner chose for this card (Gothic cathedral towers). Alt text only describes what is shown.
  IE: {
    src: '/images/countries/ie-1300.jpg',
    alt: { en: 'Gothic cathedral towers at golden hour', bn: 'সোনালি আলোয় গথিক ক্যাথেড্রালের টাওয়ার' },
    credit: SUPPLIED,
    source: 'Mino team',
    sourceUrl: '',
    license: '',
    width: 1300,
    height: 1300,
    srcSet: [{ src: '/images/countries/ie-640.webp', width: 640 }, { src: '/images/countries/ie-960.webp', width: 960 }, { src: '/images/countries/ie-1300.jpg', width: 1300 }],
    position: 'center 35%',
  },
};
