import type { ReadingPassage } from '@/lib/models';

/**
 * Reading passages. All current passages are original Vocab Brain texts
 * written in an IELTS Academic style. Licensed content (e.g. Cambridge) can
 * be added later with `licenseStatus: 'licensed'` and its publisher as
 * `source`; the reader and Save to Brain work the same for any passage.
 */
export interface GlossaryEntry {
  word: string;
  partOfSpeech: string;
  meaning: string;
  meaningBn: string;
  synonyms: string[];
  antonyms?: string[];
  collocations: string[];
  example: string;
}

export interface Passage extends ReadingPassage {
  /** Paragraphs of the passage body. */
  paragraphs: string[];
  /** Key words with meanings, keyed by lowercase lemma. */
  glossary: Record<string, GlossaryEntry>;
}

export const PASSAGES: Passage[] = [
  {
    id: 'urban-heat',
    title: 'Why Cities Are Getting Hotter',
    topic: 'Environment',
    difficulty: 'band-6',
    estimatedMinutes: 6,
    source: 'Vocab Brain',
    sourceType: 'vocab-brain-original',
    licenseStatus: 'original',
    dateAdded: '2026-09-26',
    body: '',
    paragraphs: [
      'On a summer afternoon, the centre of a large city can be several degrees warmer than the countryside only a few kilometres away. Scientists call this the urban heat island effect, and it has become a substantial problem as cities continue to expand.',
      'The main cause is the materials that modern cities are built from. Concrete, asphalt and brick absorb heat during the day and release it slowly at night, so temperatures remain high long after sunset. In addition, tall buildings trap warm air, while air-conditioning units and traffic generate even more heat.',
      'The consequences are serious. Higher temperatures increase the demand for electricity, which in turn raises emissions from power stations. Heatwaves are also a threat to public health, particularly for elderly people and those who work outdoors. Some researchers argue that the problem will only intensify as the climate warms.',
      'Fortunately, there are practical ways to mitigate the effect. Many cities now encourage green roofs, where plants are grown on top of buildings to provide shade and cool the air. Others are replacing dark surfaces with lighter materials that reflect sunlight instead of absorbing it. Planting trees along streets is perhaps the simplest solution, although it requires long-term investment.',
      'Experts agree that no single measure is sufficient on its own. Instead, local governments need to allocate funding to a combination of approaches and involve residents in planning decisions. If they act now, the decline in quality of life that many urban residents fear may still be avoided.',
    ],
    glossary: {
      substantial: {
        word: 'substantial',
        partOfSpeech: 'adjective',
        meaning: 'large in size, amount or importance',
        meaningBn: 'উল্লেখযোগ্য / বড়',
        synonyms: ['considerable', 'significant'],
        antonyms: ['minor', 'small'],
        collocations: ['a substantial problem', 'a substantial increase', 'a substantial amount of'],
        example: 'The company made a substantial investment in renewable energy.',
      },
      absorb: {
        word: 'absorb',
        partOfSpeech: 'verb',
        meaning: 'to take in heat, liquid or information',
        meaningBn: 'শুষে নেওয়া / শোষণ করা',
        synonyms: ['soak up', 'take in'],
        antonyms: ['release', 'reflect'],
        collocations: ['absorb heat', 'absorb information', 'absorb water'],
        example: 'Dark clothes absorb more heat than light ones.',
      },
      generate: {
        word: 'generate',
        partOfSpeech: 'verb',
        meaning: 'to produce or create something',
        meaningBn: 'উৎপন্ন করা / তৈরি করা',
        synonyms: ['produce', 'create'],
        collocations: ['generate heat', 'generate income', 'generate electricity'],
        example: 'Tourism generates a large part of the country’s income.',
      },
      consequence: {
        word: 'consequence',
        partOfSpeech: 'noun',
        meaning: 'a result of an action or situation, often a bad one',
        meaningBn: 'ফলাফল / পরিণতি',
        synonyms: ['result', 'effect', 'outcome'],
        collocations: ['serious consequences', 'as a consequence', 'face the consequences'],
        example: 'Lack of sleep can have serious consequences for students.',
      },
      emission: {
        word: 'emission',
        partOfSpeech: 'noun',
        meaning: 'gas or other substance sent into the air',
        meaningBn: 'নির্গমন',
        synonyms: ['discharge', 'release'],
        collocations: ['carbon emissions', 'reduce emissions', 'emission levels'],
        example: 'Governments are trying to reduce carbon emissions from cars.',
      },
      intensify: {
        word: 'intensify',
        partOfSpeech: 'verb',
        meaning: 'to become or make stronger or more extreme',
        meaningBn: 'তীব্র হওয়া / বাড়া',
        synonyms: ['increase', 'strengthen', 'worsen'],
        antonyms: ['ease', 'lessen'],
        collocations: ['competition intensifies', 'intensify efforts', 'intensify pressure'],
        example: 'Competition for university places has intensified in recent years.',
      },
      mitigate: {
        word: 'mitigate',
        partOfSpeech: 'verb',
        meaning: 'to make something bad less serious or harmful',
        meaningBn: 'কমানো / প্রশমিত করা',
        synonyms: ['reduce', 'lessen', 'ease'],
        antonyms: ['worsen', 'aggravate'],
        collocations: ['mitigate the effects', 'mitigate risks', 'mitigate the impact'],
        example: 'Planting trees can help mitigate the effects of air pollution.',
      },
      sufficient: {
        word: 'sufficient',
        partOfSpeech: 'adjective',
        meaning: 'enough for a particular purpose',
        meaningBn: 'যথেষ্ট',
        synonyms: ['enough', 'adequate'],
        antonyms: ['insufficient', 'inadequate'],
        collocations: ['sufficient evidence', 'sufficient time', 'on its own is not sufficient'],
        example: 'Two hours a week is not sufficient to prepare for IELTS.',
      },
      allocate: {
        word: 'allocate',
        partOfSpeech: 'verb',
        meaning: 'to give money, time or resources for a particular purpose',
        meaningBn: 'বরাদ্দ করা',
        synonyms: ['assign', 'distribute', 'set aside'],
        collocations: ['allocate funding', 'allocate resources', 'allocate time to'],
        example: 'Students should allocate more time to Writing practice.',
      },
      decline: {
        word: 'decline',
        partOfSpeech: 'noun',
        meaning: 'a gradual decrease in amount, quality or importance',
        meaningBn: 'হ্রাস / অবনতি',
        synonyms: ['decrease', 'fall', 'deterioration'],
        antonyms: ['increase', 'rise', 'growth'],
        collocations: ['a sharp decline', 'a decline in', 'in decline'],
        example: 'There has been a steady decline in the number of bookshops.',
      },
    },
  },
  {
    id: 'online-learning',
    title: 'Can Online Learning Replace the Classroom?',
    topic: 'Education',
    difficulty: 'band-6',
    estimatedMinutes: 6,
    source: 'Vocab Brain',
    sourceType: 'vocab-brain-original',
    licenseStatus: 'original',
    dateAdded: '2026-09-26',
    body: '',
    paragraphs: [
      'In the past decade, online learning has moved from the margins of education to the mainstream. Millions of students now attend lectures, submit assignments and even sit exams without leaving their homes. Supporters claim that this shift will make education more accessible than ever before.',
      'The advantages are easy to see. Online courses allow learners to study at their own pace and to revisit difficult material as often as they need. They also remove the cost of travel and accommodation, which can be a significant barrier for students from rural areas or low-income families.',
      'However, critics point out that technology alone cannot guarantee success. Studying at home requires considerable self-discipline, and many learners find it difficult to stay motivated without the structure of a timetable. Research suggests that completion rates for fully online courses are often lower than for traditional ones.',
      'There is also the question of social interaction. In a classroom, students can collaborate on projects, ask questions immediately and learn from the reactions of their peers. These informal exchanges are hard to replicate on a screen, and some educators believe their absence has a detrimental effect on communication skills.',
      'For these reasons, many institutions are adopting a blended approach that combines online resources with regular face-to-face sessions. This model aims to retain the flexibility of digital learning while preserving the benefits of learning together.',
    ],
    glossary: {
      accessible: {
        word: 'accessible',
        partOfSpeech: 'adjective',
        meaning: 'easy to reach, get or use',
        meaningBn: 'সহজলভ্য / সহজে পাওয়া যায় এমন',
        synonyms: ['available', 'reachable'],
        antonyms: ['inaccessible'],
        collocations: ['easily accessible', 'accessible to everyone', 'make education accessible'],
        example: 'The library should be accessible to all students.',
      },
      revisit: {
        word: 'revisit',
        partOfSpeech: 'verb',
        meaning: 'to go back to something and look at it again',
        meaningBn: 'আবার দেখা / পুনরায় বিবেচনা করা',
        synonyms: ['review', 'return to', 'reconsider'],
        collocations: ['revisit a topic', 'revisit the idea', 'revisit old notes'],
        example: 'It helps to revisit difficult words a few days later.',
      },
      barrier: {
        word: 'barrier',
        partOfSpeech: 'noun',
        meaning: 'something that stops people from doing or getting something',
        meaningBn: 'বাধা',
        synonyms: ['obstacle', 'hurdle'],
        collocations: ['a major barrier', 'language barrier', 'remove barriers'],
        example: 'Cost is the main barrier to studying abroad for many students.',
      },
      guarantee: {
        word: 'guarantee',
        partOfSpeech: 'verb',
        meaning: 'to promise or make certain that something will happen',
        meaningBn: 'নিশ্চয়তা দেওয়া',
        synonyms: ['ensure', 'promise', 'secure'],
        collocations: ['guarantee success', 'cannot guarantee', 'guarantee a place'],
        example: 'Hard work does not guarantee a Band 8, but it helps a lot.',
      },
      considerable: {
        word: 'considerable',
        partOfSpeech: 'adjective',
        meaning: 'large or important enough to have an effect',
        meaningBn: 'যথেষ্ট / উল্লেখযোগ্য',
        synonyms: ['substantial', 'significant', 'great'],
        antonyms: ['negligible', 'slight'],
        collocations: ['considerable effort', 'considerable amount', 'to a considerable extent'],
        example: 'Learning a language takes considerable effort.',
      },
      motivated: {
        word: 'motivated',
        partOfSpeech: 'adjective',
        meaning: 'wanting to do something and willing to work hard at it',
        meaningBn: 'উৎসাহী / অনুপ্রাণিত',
        synonyms: ['driven', 'enthusiastic', 'determined'],
        antonyms: ['unmotivated'],
        collocations: ['highly motivated', 'stay motivated', 'motivated to learn'],
        example: 'Small daily goals help students stay motivated.',
      },
      collaborate: {
        word: 'collaborate',
        partOfSpeech: 'verb',
        meaning: 'to work together with others to achieve something',
        meaningBn: 'একসাথে কাজ করা / সহযোগিতা করা',
        synonyms: ['cooperate', 'work together', 'team up'],
        collocations: ['collaborate on a project', 'collaborate with', 'collaborate closely'],
        example: 'The two universities collaborate on climate research.',
      },
      replicate: {
        word: 'replicate',
        partOfSpeech: 'verb',
        meaning: 'to copy something exactly or do it again',
        meaningBn: 'হুবহু নকল করা / পুনরায় করা',
        synonyms: ['copy', 'reproduce', 'duplicate'],
        collocations: ['replicate results', 'hard to replicate', 'replicate the experience'],
        example: 'It is hard to replicate the atmosphere of a real exam at home.',
      },
      detrimental: {
        word: 'detrimental',
        partOfSpeech: 'adjective',
        meaning: 'causing harm or damage',
        meaningBn: 'ক্ষতিকর',
        synonyms: ['harmful', 'damaging'],
        antonyms: ['beneficial'],
        collocations: ['a detrimental effect on', 'detrimental to health', 'potentially detrimental'],
        example: 'Excessive screen time can be detrimental to children’s health.',
      },
      retain: {
        word: 'retain',
        partOfSpeech: 'verb',
        meaning: 'to keep or continue to have something',
        meaningBn: 'ধরে রাখা',
        synonyms: ['keep', 'preserve', 'maintain'],
        antonyms: ['lose'],
        collocations: ['retain information', 'retain staff', 'retain control'],
        example: 'Active recall helps you retain new vocabulary.',
      },
    },
  },
  {
    id: 'four-day-week',
    title: 'The Four-Day Working Week',
    topic: 'Work & Career',
    difficulty: 'band-7',
    estimatedMinutes: 7,
    source: 'Vocab Brain',
    sourceType: 'vocab-brain-original',
    licenseStatus: 'original',
    dateAdded: '2026-09-26',
    body: '',
    paragraphs: [
      'For most of the twentieth century, the five-day working week was regarded as a fixed feature of modern life. Recently, however, a growing number of companies have begun to experiment with a four-day week, in which employees work fewer hours without a reduction in pay.',
      'The idea is based on a simple observation: long hours do not necessarily lead to greater productivity. Tired workers make more mistakes, and a large proportion of the working day is often lost to unnecessary meetings. Advocates argue that a shorter week forces organisations to eliminate waste and concentrate on essential tasks.',
      'Early trials have produced encouraging results. In several countries, participating firms reported that output remained stable or even improved, while staff described lower levels of stress and a better balance between work and family life. Employers also noticed that it became easier to attract and retain skilled staff.',
      'Nevertheless, the model is not suitable for every sector. Hospitals, schools and shops must operate for a certain number of hours regardless of how employees are scheduled, so a shorter week may simply require hiring more people. Critics also warn that squeezing five days of work into four could increase pressure rather than reduce it.',
      'It remains to be seen whether the four-day week will become widespread. What the trials have demonstrated, though, is that the traditional structure of work is not inevitable, and that alternative arrangements deserve serious consideration.',
    ],
    glossary: {
      experiment: {
        word: 'experiment',
        partOfSpeech: 'verb',
        meaning: 'to try a new idea or method to see what happens',
        meaningBn: 'পরীক্ষা-নিরীক্ষা করা',
        synonyms: ['test', 'try out', 'trial'],
        collocations: ['experiment with', 'experiment on', 'freedom to experiment'],
        example: 'Many schools are experimenting with shorter lessons.',
      },
      productivity: {
        word: 'productivity',
        partOfSpeech: 'noun',
        meaning: 'how much work or output is produced in a given time',
        meaningBn: 'উৎপাদনশীলতা / কাজের দক্ষতা',
        synonyms: ['efficiency', 'output'],
        collocations: ['increase productivity', 'boost productivity', 'productivity levels'],
        example: 'Regular breaks can increase productivity.',
      },
      proportion: {
        word: 'proportion',
        partOfSpeech: 'noun',
        meaning: 'a part or share of a whole',
        meaningBn: 'অংশ / অনুপাত',
        synonyms: ['share', 'percentage', 'part'],
        collocations: ['a large proportion of', 'a small proportion', 'in proportion to'],
        example: 'A large proportion of students study abroad after their degree.',
      },
      eliminate: {
        word: 'eliminate',
        partOfSpeech: 'verb',
        meaning: 'to remove something completely',
        meaningBn: 'দূর করা / বাদ দেওয়া',
        synonyms: ['remove', 'get rid of', 'eradicate'],
        collocations: ['eliminate waste', 'eliminate the need for', 'eliminate errors'],
        example: 'Good planning can eliminate most last-minute stress.',
      },
      encouraging: {
        word: 'encouraging',
        partOfSpeech: 'adjective',
        meaning: 'giving hope that something will be successful',
        meaningBn: 'আশাব্যঞ্জক / উৎসাহজনক',
        synonyms: ['promising', 'hopeful', 'positive'],
        antonyms: ['discouraging'],
        collocations: ['encouraging results', 'encouraging signs', 'an encouraging start'],
        example: 'The first Mock Test result was very encouraging.',
      },
      stable: {
        word: 'stable',
        partOfSpeech: 'adjective',
        meaning: 'not changing much; steady',
        meaningBn: 'স্থিতিশীল',
        synonyms: ['steady', 'constant', 'secure'],
        antonyms: ['unstable', 'volatile'],
        collocations: ['remain stable', 'a stable job', 'stable income'],
        example: 'House prices remained stable last year.',
      },
      regardless: {
        word: 'regardless',
        partOfSpeech: 'adverb',
        meaning: 'without being affected by something',
        meaningBn: 'যাই হোক না কেন / বিবেচনা না করে',
        synonyms: ['irrespective', 'no matter'],
        collocations: ['regardless of', 'regardless of age', 'regardless of the cost'],
        example: 'Everyone should have access to education, regardless of income.',
      },
      widespread: {
        word: 'widespread',
        partOfSpeech: 'adjective',
        meaning: 'happening in many places or among many people',
        meaningBn: 'ব্যাপক / বহুল প্রচলিত',
        synonyms: ['common', 'extensive', 'prevalent'],
        antonyms: ['rare', 'limited'],
        collocations: ['widespread support', 'widespread use', 'become widespread'],
        example: 'Smartphone use is now widespread among teenagers.',
      },
      inevitable: {
        word: 'inevitable',
        partOfSpeech: 'adjective',
        meaning: 'certain to happen and impossible to avoid',
        meaningBn: 'অনিবার্য',
        synonyms: ['unavoidable', 'certain'],
        antonyms: ['avoidable', 'uncertain'],
        collocations: ['it is inevitable that', 'an inevitable result', 'seem inevitable'],
        example: 'Some mistakes are inevitable when you learn a new language.',
      },
      alternative: {
        word: 'alternative',
        partOfSpeech: 'adjective',
        meaning: 'different from the usual one; another possible choice',
        meaningBn: 'বিকল্প',
        synonyms: ['other', 'different', 'substitute'],
        collocations: ['an alternative approach', 'alternative energy', 'alternative arrangements'],
        example: 'Solar power is a clean alternative energy source.',
      },
    },
  },
];

export function getPassage(id: string): Passage | undefined {
  return PASSAGES.find((p) => p.id === id);
}
